### ISSUE TITLE
Rebase and merging instead of creating a merge commit

### ISSUE THREAD

**Issue by double-beep** [LeelaChessZero/lc0#100]
Hi all maintainers!
Sorry for spamming the issues but...
It is so much annoying that when you merge a pull request you select `Merge Pull Request` and create a merge commit which usually includes `Merge pull request 'number' from 'source'`! Why not selecting `Rebase and merge`? It would be nice.
Entirely yours.
@double-beep

**Comment by dubslow** [comment]
Even for fastforward merges, I prefer to leave an explicit merge commit to mark that I was the one who merged the otherwise-fastforward.

What is annoying about merge commits? The only thing that rebasing would offer is linear history, and I would argue that flattened history isn't any extra convenience in its own way.

**Comment by double-beep** [comment]
Hi @dubslow!
As you have said:

>  I prefer to leave an explicit merge commit to mark that **I was the one who merged** the otherwise-fastforward.

In rebase and merge you will see two people: the author and the 'merger' and in the commits menu you will see: `author's username` authored and (e.g.) dubslow commited. As you don't want it, I am closing the issue.

**Comment by dubslow** [comment]
The problem is you get that same issue with non-merges as well, e.g. cherry-picks. I do those relatively frequently.

**Comment by double-beep** [comment]
There's no way to commit a non-merge-commit without writing in the description 'Co-authored by "x" <x's email>'. If you want to see only the title and not the description, just squash and merge. You can edit the text there, and also you have a clearer history.

**Comment by mooskagh** [comment]
There are three "standard" options to choose, I don't really know the differences.
I tried "squash and merge" which is nice as LCZ repo will have only one commit per PR, but after that commits in local repo somehow don't disappear from "behind upstream" list.

**Comment by mooskagh** [comment]
I've read the "rebase commit" docs and it seems that it's something I'd like to avoid.
Many people like to develop using small commits, which sometimes break builds etc, and we don't really want to transfer all that commit spam to a base.
Also it makes bisect harder.
