### ISSUE TITLE
Chess960 "capture rook" moves shown in verbose (even with --no-chess960)

### ISSUE THREAD

**Issue by Mardak** [LeelaChessZero/lc0#1000]
I have various scripts that look for the `pgn-extract -Wuci` moves which use e1c1/e1g1 long algebraic notation.

@mooskagh Should the `--no-chess960` apply to `--verbose-move-stats` ?

E.g.,
```
./lc0 --no-chess960 -v
position startpos moves e2e4 e7e6 d2d4 d7d5 c1e3 d5e4 b1d2 g8f6 c2c3 f8e7 d1c2 f6d5 d2e4 f7f5 e4g3 f5f4 e3d2 f4g3 h2g3 g7g6
go nodes 1

info string e1a1  (97  ) N:       0 (+ 0) (P: 10.21%) (Q: -0.10354) (D:  0.000) (U: 0.30635) (Q+U:  0.20280) (V:  -.----) 
```

Whereas before #979, it would show up as:
```
info string e1c1  (97  ) N:       0 (+ 0) (P: 10.21%) (Q: -0.10354) (D:  0.000) (U: 0.30635) (Q+U:  0.20280) (V:  -.----) 
```

**Comment by mooskagh** [comment]
That's intended, or at least known.

`--verbose-move-stats` kind of shows internal debug info, and it makes sense to show internal representation.
But the main reason is that code in search.cc should not know about uci quirks and not know whether   UCI gui expects one move or another.

**Comment by Mardak** [comment]
I hacked my pgn-extract to always assume "chess 960":
```c++
current_game.tags[VARIANT_TAG] = copy_string("chess 960");
```
