### ISSUE TITLE
Crash when "go … searchmoves" for non FRC-style e1c1/e1g1 castling

### ISSUE THREAD

**Issue by Mardak** [LeelaChessZero/lc0#1001]
```
position startpos moves e2e4 e7e6 d2d4 d7d5 c1e3 d5e4 b1d2 g8f6 c2c3 f8e7 d1c2 f6d5 d2e4 f7f5 e4g3 f5f4 e3d2 f4g3 h2g3 g7g6

go nodes 1 searchmoves e1c1
…
bestmove a1a1

go nodes 1 searchmoves e1c1
Segmentation fault: 11
```

To be clear, using e1c1 as part of `position … moves … e1c1` works fine.

**Comment by mooskagh** [comment]
Thanks for finding the bug!
The intention is that both FRC-style and "traditional" castling moves are accepted in all contexts (if it's standard chess).
I didn't look into `searchmoves`, there must be something missing there.
