### ISSUE TITLE
Selfplay outputs chess960 "capture rook" moves

### ISSUE THREAD

**Issue by Mardak** [LeelaChessZero/lc0#1009]
lczero-client converts the `gameready` moves to pgn:
https://github.com/LeelaChessZero/lczero-client/blob/33e15f9ec6ce147de76802a0d173804845de219c/lc0_main.go#L403

A quick test:
```go
convertMovesToPGN(strings.Split("d2d4 g8f6 g1f3 b7b6 g2g3 c8b7 f1g2 c7c5 e1h1", " "), "")
```
errors with:
```
movstr: chess: invalid move e1h1
```

Perhaps either https://github.com/Tilps/chess needs to get updated or selfplay should output e1c1/e1g1:
https://github.com/LeelaChessZero/lc0/blob/58428e8c3fe0113c68390343f52d3fa6a1f92907/src/selfplay/loop.cc#L120

**Comment by mooskagh** [comment]
I didn't think about that, good catch. For now I think we should just convert moves in selfplay, or maybe introduce a chess960 flag in selfplay too.

**Comment by Tilps** [comment]
selfplay always starts from standard startpos so for now it makes sense to convert moves.
When we add support for starting from x-fen, we should make the output conditional on the x-fen being non standard.

**Comment by borg323** [comment]
Surely there must be a simpler way to do it than this:
```
diff --git a/src/selfplay/game.cc b/src/selfplay/game.cc
index f865a47..f0d725b 100644
--- a/src/selfplay/game.cc
+++ b/src/selfplay/game.cc
@@ -213,6 +213,18 @@ std::vector<Move> SelfPlayGame::GetMoves() const {
     flip = !flip;
   }
   std::reverse(moves.begin(), moves.end());
+  PositionHistory history = tree_[0]->GetPositionHistory();
+  for (size_t i = 0; i < moves.size(); i++) {
+    Position position = history.GetPositionAt(i);
+    ChessBoard board = position.GetBoard();
+    if (position.IsBlackToMove()) {
+      moves[i].Mirror();
+      moves[i] = board.GetLegacyMove(moves[i]);
+      moves[i].Mirror();
+    } else {
+      moves[i] = board.GetLegacyMove(moves[i]);
+    }
+  }
   return moves;
 }
 
```
