### ISSUE TITLE
Timer doesn't reset on `go` command when there's no `position command`

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#1012]
CrazyKing on discord reported a performance degradation in v0.23 (nps).

Relevant logs are attached.
[leelalog_T40_B260_lc0_23.0.txt](https://github.com/LeelaChessZero/lc0/files/3878726/leelalog_T40_B260_lc0_23.0.txt)
[leelalog_T40_B260_lc0_22.0.txt](https://github.com/LeelaChessZero/lc0/files/3878727/leelalog_T40_B260_lc0_22.0.txt)

[lc0.config.txt](https://github.com/LeelaChessZero/lc0/files/3878738/lc0.config.txt)

**Comment by mooskagh** [comment]
The issue is that with new time management code, if host types `go` uci command without any `ucinewgame` or `position` command, the timer is not reset and move time starts from the moment of engine start.

**Comment by borg323** [comment]
This is how it worked in the previous version as well - the difference is that the reported time is now the actual time since the reset instead of the time since the `go` command like it was before. I would argue that this is preferable to the old way (and have actually already done so). My suggestion is to only change the nps calculation to subtract the time between the reset and the go command.

**Comment by Mardak** [comment]
Looking at the output meaning:
```
	* time 
		the time searched in ms, this should be sent together with the pv.
	* nodes 
		x nodes searched, the engine should send this info regularly
```
… in the context of `go` commands:
```
	* nodes 
	   search x nodes only,
	* mate 
		search for a mate in x moves
	* movetime 
		search exactly x mseconds
```

If I "go nodes 100" then "go nodes 1000" the info line prints out nodes ~100 then nodes ~1000 with the second "go" doing ~900 more nodes.

If I "go movetime 1000" then "go movetime 10000", should the first search do 1 second worth of searching then 9 more seconds of searching independent of how long I waited between doing the two "go" (i.e., should time between commands count towards the movetime)?

**Comment by borg323** [comment]
The main issue is that some guis start counting time when sending the initial `ucinewgame` or `position` command, assuming they will be instantaneous. So we reset the time counter only for those commands and assume any time given in the `go` command is relative to the last reset.

**Comment by mooskagh** [comment]
So the intended behavior is:
- For time budget, reset timer on `ucinewgame` and on `position`, and if timer is still not started by the time `go` comes, reset on `go`.
- For `time` uci info value, show the same time as for budget (right?)
- For `nps` uci info, start timer after the first search batch is completed.

Sounds good?
