### ISSUE TITLE
Have "auto" backend.

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#1014]
We can have "auto" backend which would probe system for GPUs and picks appropriate configuration (cudnn, cudnn-fp16, multiplexing etc) based on what it found.

It doesn't even have to be a separate class forwarding requests, it should just create backend it needs directly in factory function.

**Comment by mooskagh** [comment]
As a simpler version of it, we can have `cudnn-auto`, residing in `network_cudnn.cc`

**Comment by borg323** [comment]
See #1026 for a take at the simple version.

**Comment by mooskagh** [comment]
Looks good. For the less simple version, probably it makes sense to keep that issue open for now, but I don't think it's high priority as we have per-backend compiled binaries anyway.

It makes sense to think about multi-GPU configurations though.

**Comment by Naphthalin** [comment]
#1026 was merged, and discussion should probably continue in #1038
