### ISSUE TITLE
Possible regression in lc0

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lc0#102]
Reported by MTGOStark on discord.  Seeing 40 elo drop in testing between the 0604 experimental and 0619 with default parameters using net test1_27. (Also mainline 315 - but the position below was with test1_27)
Still trying to find a great example of where the two differ, but the following position does at least seem to be converging on different results.

position startpos moves e2e4 c7c5 g1f3 d7d6 f1b5 c8d7 b5d7 d8d7 e1g1 g8f6 f1e1 b8c6 c2c3 e7e6 h2h3 f8e7 d2d4 c5d4 c3d4 d6d5 e4e5 f6e4 a2a3 e8g8 b1d2 e4d2 d1d2 a7a5 d2f4 a5a4 f4g4 g8h8 c1e3 b7b5 g4h5 b5b4 a3b4 c6b4 e1e2 h8g8 f3g5 h7h6 g5f3 d7b5 e2d2 f8c8 e3h6 g7h6 h5h6 b4c2

**Comment by mooskagh** [comment]
No, didn't reproduce.
(I accidentally synced to 4 June commit which didn't yet have ASilver's settings).

What are moves reported differently by those two binaries, and after how many nodes that happens?

**Comment by mooskagh** [comment]
Ok, so there are no differences between 0604 and 0619, but there are differences between multiple runs of the same position with the same version (with 2 threads).

Example on master:
```
position fen r1r3k1/4bp2/4p2Q/1q1pP3/p2P4/5N1P/1PnR1PP1/R5K1 w - - 1 26
go nodes 5000000

info string a1a2  (7   ) N:    1017 (+ 0) (V:   5.39%) (P:  7.68%) (Q: -0.40903) (U: 0.40662) (Q+U: -0.00241) 
info string a1b1  (0   ) N:    1198 (+ 0) (V:  20.55%) (P:  8.92%) (Q: -0.40283) (U: 0.40107) (Q+U: -0.00176) 
info string a1f1  (4   ) N:    6874 (+ 0) (V:  10.34%) (P:  1.49%) (Q: -0.10037) (U: 0.01166) (Q+U: -0.08871) 
info string a1d1  (2   ) N: 2495250 (+256) (V:  16.51%) (P:  4.30%) (Q: -0.00203) (U: 0.00009) (Q+U: -0.00194) 
bestmove a1d1

info string a1a2  (7   ) N:    1047 (+ 0) (V:   5.39%) (P:  7.68%) (Q: -0.41146) (U: 0.39799) (Q+U: -0.01347) 
info string a1b1  (0   ) N:    1238 (+ 0) (V:  20.55%) (P:  8.92%) (Q: -0.40488) (U: 0.39108) (Q+U: -0.01379) 
info string a1d1  (2   ) N:   45280 (+ 0) (V:  16.51%) (P:  4.30%) (Q: -0.02977) (U: 0.00516) (Q+U: -0.02462) 
info string a1f1  (4   ) N: 2495029 (+196) (V:  10.34%) (P:  1.49%) (Q: -0.01503) (U: 0.00003) (Q+U: -0.01500) 
bestmove a1f1
```

Same on 0406:
```
info string a1b1  (0   ) N:    1200 (+ 0) (V:  20.55%) (P:  8.92%) (Q: -0.40211) (U: 0.40054) (Q+U: -0.00157) 
info string a1f1  (4   ) N:    8677 (+ 0) (V:  10.34%) (P:  1.49%) (Q: -0.09449) (U: 0.00924) (Q+U: -0.08525) 
info string a1d1  (2   ) N: 2495198 (+117) (V:  16.51%) (P:  4.30%) (Q: -0.00145) (U: 0.00009) (Q+U: -0.00135) 
bestmove a1d1

info string a1b1  (0   ) N:    1296 (+ 0) (V:  20.55%) (P:  8.92%) (Q: -0.40088) (U: 0.42729) (Q+U:  0.02641) 
info string a1f1  (4   ) N:  830976 (+ 0) (V:  10.34%) (P:  1.49%) (Q: -0.01777) (U: 0.00011) (Q+U: -0.01766) 
info string a1d1  (2   ) N: 2494933 (+256) (V:  16.51%) (P:  4.30%) (Q: -0.00097) (U: 0.00011) (Q+U: -0.00086) 
bestmove a1d1

info string a1b1  (0   ) N:    1207 (+ 0) (V:  20.55%) (P:  8.92%) (Q: -0.40527) (U: 0.40853) (Q+U:  0.00326) 
info string a1d1  (2   ) N:  140535 (+ 0) (V:  16.51%) (P:  4.30%) (Q: -0.00634) (U: 0.00169) (Q+U: -0.00465) 
info string a1f1  (4   ) N: 2495113 (+256) (V:  10.34%) (P:  1.49%) (Q: -0.00175) (U: 0.00003) (Q+U: -0.00172) 
bestmove a1f1
```

What happens is that engine initially thinks that it's loosing but then suddenly finds threefold repetition draw (with either of positions), and sticks to it.
Move that was found first (more or less), wins in the end.

**Comment by mooskagh** [comment]
Closing for now, as it doesn't seem to be 0604 vs 0619 difference.

**Comment by mooskagh** [comment]
(note for myself)
Interesting example:
```
position startpos moves d2d4 g8f6 g1f3 d7d5 c2c4 e7e6 g2g3 f8b4 c1d2 b4e7 f1g2 e8g8 e1g1 d5c4 d1a4 c7c6 a4c4 b7b6 b1c3 c8a6 c4b3 b8d7 f1d1 f6d5 e2e4 d5c3 b3c3 a6b7 d2f4 d8c8 a1c1 f8d8 c3e1 e7f8 f3d2 d7f6
```
at 10000 nodes.
