### ISSUE TITLE
Wiki link not landing on target, the technical overview pic

### ISSUE THREAD

**Issue by Dboingue** [LeelaChessZero/lc0#1028]
https://applied-data.science/static/main/res/alpha_go_zero_cheat_sheet.png
it lands on a generic page.  Given it position on top of the wiki page that interests me most, it seems promising in terms of getting some overall picture of the lc zero project.  please provide us with the picture.

Edit: the link has been fixed.

**Comment by Dboingue** [comment]
I am going to add all links that are dead in this issue, centralizing in one place, scattered information.
http://oldmain.lczero.org/networks  is dead
it seems since the whole design of experiment is spread over time, getting access to early documents, might help me or any newcomer getting a global view of this set of experiments, and why lc0 is coordinating such and such distributed instance with contributor.  what is the objective and intent of this design.  Not just give a taste of the kind of parameters that are considered.  but the plan must be somewhere.  I am willing to help by the way. if that is not a dev. cup of tea.

**Comment by mooskagh** [comment]
I'm not sure whether you refer to github wiki or lczero.org, but if it's about github wiki, note that anyone can edit it, so if you consider fixing your findings yourself, it would be much appreciated!

**Comment by Dboingue** [comment]
> I'm not sure whether you refer to github wiki or lczero.org, but if it's about github wiki, note that anyone can edit it, so if you consider fixing your findings yourself, it would be much appreciated!

Should I make a pull request for the wiki, or it does not  work that way.
I noticed that the wiki was missing from my fork of lc0, for studying and inferring DOE and corresponding training data.  So, I see that code and wiki don't follow same rules of collaboration.

I can clone it directly from here, though, to my gitub desktop.  Should i create a branch of the wiki, or a pull request, or directly work on my local copy of the master branch of the wiki.  For me pull request look like branches at a smaller scale.  The articulation of collaboration tools is still not clear to me, and depending on where you read, terminology seems to be overloaded right and left, and not consciously.

My current focus, is filtering the blog, finding the archived blog, and combing the wiki for any information relevant to the DOE and the corresponding data.  As I find dead links, i will work on fixing them if i can.  But i might have to get back to you, in doing so, with questions. Is that ok?

lczero.org: 3 or 5 dead links, in one page, i have not been there again, and since they were iin a list of links without any accompanying text, i have no clue what i was missing, contrary to the wiki.  When i'm done with the wiki, i can go scrutinize all the pages, there.

Also there seems to be widgets that are not actually linked to any event or action, right, it is not my browser or anything. not yet implemented, or never.

last point: I had mentioned that i thought your slides were well made for explaining the theory behind lc0.  I forgot where i found the link, i know not in the wiki.  Would you mind if i put a link to it there (toward having one self-contained set of documentation, in terms of links and or content, no need to duplicate content.  Also, do you have a static versions of your slides, perhaps a pdf? So i could have more precise targets than the whole thing. Verification: your policy explanation was adapted to chess, right.   because the wiki was still using the go overview, and so does the link i found that has the same filename.  Also, you should know that i have a slow pace at any task, given the dispersal.  Otherwise, i am happy, to help where i can, just wary of blundering the wiki.

**Comment by mooskagh** [comment]
I'm no longer sure on which exactly page the link was wrong, so closing the bug as obsolete.

**Comment by Dboingue** [comment]
I was about the go  picture explaining the RL for alpha-zero.  I was going to a web page on some page, but not the figure. this had been fixed, a while ago. I did not check recently, but assume that since the lczero.org moving of all documentation, it would not.
agree with closing.
