### ISSUE TITLE
UCI stop does not reset an infinite search

### ISSUE THREAD

**Issue by CaryKnoop** [LeelaChessZero/lc0#1035]
To reproduce:
------------------------
uci
isready
ucinewgame
go infinite
< let it run for a while>
stop
go infinite

The search depth continues at right before the previous stop instead of restarting.  

This is a problem when you need to change an option after the first stop, for instance, to compare various searches for different NN's or with or without options such as LogitQ.

Stockfish resets the depth to 1 after a stop.

**Comment by mooskagh** [comment]
It is intended, if tree can be reused, it's reused.
To reset the tree, use `ucinewgame`.

**Comment by CaryKnoop** [comment]
Check with using `ucinewgame`, and that works!
