### ISSUE TITLE
Crashes under chessbase GUIs - memory overflow?

### ISSUE THREAD

**Issue by maelic13** [LeelaChessZero/lc0#1039]
If let run for a very long time (hours), lc0 0.23.1 crashes as shown in the picture. Maybe memory overflow or something?
![scr](https://user-images.githubusercontent.com/30387931/70563916-724acf00-1b8f-11ea-869f-ae8621fc1a1b.png)

**Comment by stengoes** [comment]
I am experiencing the same on Ubuntu 18.04 and Lc0 0.23.2. 

It seems to me that either 0.23.2 has a memory leak or that it is very hungry for memory. I am on a machine with 92GB ram. If I monitor the ram usage it just keeps growing even after changing the position.

**Comment by SG7** [comment]
Yes, it could be! But similar/same? problem exists on 0.24.1.
See:
https://github.com/LeelaChessZero/lc0/issues/1152

**Comment by mooskagh** [comment]
This is working as intended. Unlike A/B engines, Lc0 has to keep entire tree in memory.
I suggest checking [our troubleshoot page](http://lczero.org/play/troubleshoot/) to find what possible options you have.
