### ISSUE TITLE
Support Polyglot Opening Book

### ISSUE THREAD

**Issue by jjoshua2** [LeelaChessZero/lc0#104]
Can maybe use code from brainfish/cfish which both support polyglot (and feature 2). 

ASMFish actually has the best implementation of this support following three features:

1. Ponders while in book, especially helpful if opponent gets out of book before you.
2. Has option to specify get out of book after at most X moves (default 20 or so)
3. Option to say get out of book when X moves deep remaining (say moves are calculated to depth 28 and this TC allows reaching depth 30, then you would want to clip the last 2 moves of the book)

**Comment by mooskagh** [comment]
Not really planned.
