### ISSUE TITLE
Tactical position where lc0 is blinded

### ISSUE THREAD

**Issue by aochoam** [LeelaChessZero/lc0#1042]
1r1q1rk1/p2b1p2/1pn1p1pQ/2p1P3/4BB1b/2PP4/P1N4P/1R3RK1 w - - 1 20 

Bxg6!

I tried several networks, but none of them seems to find out that move.

Please, can anybody validate?

**Comment by mooskagh** [comment]
Which losing/drawing move Lc0 is playing instead?

**Comment by PowerMove72** [comment]
![nibbler](https://user-images.githubusercontent.com/45057484/71608184-8dea3980-2b7f-11ea-94cb-f6cf25e0c766.PNG)

**Comment by PowerMove72** [comment]
![nibbler2](https://user-images.githubusercontent.com/45057484/71608357-f554b900-2b80-11ea-9121-df09dafe0349.PNG)
net J13-410 (Terminator)

**Comment by Corniel** [comment]
> I tried several networks, but none of them seems to find out that move.

It finds the move (20.Rf3) with a score 98.5%. As this move is obviously also winning (without any risk) given how Lc0 works, that move is preferable over the tactical 20.Bxg6. That is the logical outcome of a NN that prefers no counter-play, and lacks the human desire to finish a game with a nice (tactical) attack.

**Comment by Naphthalin** [comment]
Known and expected behavior in general. However, this specific position isn't even an issue in itself, as Leela simply favors another way of converting the game via `Rf3`. Closing now.
