### ISSUE TITLE
Have a separate timewatch thread

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#105]
Currently Search checks whether time is up at every iteration.
But as ComputeBlocking may be long, search may take significant time overhead with that approach.

Instead of that, we need a separate thread which would watch the time and output `bestmove` as soon as time is up.

**Comment by dubslow** [comment]
Is the answer to everything :morethreads: ?

**Comment by mooskagh** [comment]
Fixed in #309
