### ISSUE TITLE
OpenCL SGEMM tuner fails to find a valid configuration

### ISSUE THREAD

**Issue by Tobias-Thomas** [LeelaChessZero/lc0#1061]
I had a working version of lc0 on my AMD RX 580 with the amd-gpu-pro driver and the OpenCL 2.1 backend. Then I installed the rocm drivers for my graphics-card because tensorflow requires this driver.
I still have OpenCL installed and lc0 is able to find it but in the end the SGEM tuner is uable to find a valid configuration. 

```
|   _ | |
|_ |_ |_| v0.24.0-dev+git.f83f81d built Jan  7 2020
id name Lc0 v0.24.0-dev+git.f83f81d
id author The LCZero Authors.
Found pb network file: ./weights
Creating backend [multiplexing]...
Creating backend [opencl]...
OpenCL, maximum batch size set to 16.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 2.1 AMD-APP (3052.0)
Platform profile: FULL_PROFILE
Platform name:    AMD Accelerated Parallel Processing
Platform vendor:  Advanced Micro Devices, Inc.
Device ID:      0
Device name:    gfx803
Device type:    GPU
Device vendor:  Advanced Micro Devices, Inc.
Device driver:  3052.0 (HSA1.1,LC)
Device speed:   1350 MHZ
Device cores:   36 CU
Device score:   1121
Selected platform: AMD Accelerated Parallel Processing
Selected device: gfx803
with OpenCL 2.1 capability.
Started OpenCL SGEMM tuner with batch size 16.
Will try 578 valid configurations.
Failed to find a working configuration.
Check your OpenCL drivers.
Unhandled exception: Tuner failed to find working configuration.
Aborted (core dumped) 
```
Is the output when i try to start the selfplay. 
The output of uname -a: ``
> Linux tobias-MS-7C52 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

Really appreciate any help. 
Thanks in advance!
Tobias

**Comment by Naphthalin** [comment]
Is Windows 10 an option for you? The OpenCL drivers for newer AMD cards seem to have several issues (see #1057), and with Win10 you could make use of the dx12 backend which gives a significant performance increase for AMD cards.

**Comment by mooskagh** [comment]
I think it's really a driver problem, so there's nothing we can do.
So closing this for now, feel free to reopen if you have any more thoughts.
