### ISSUE TITLE
LC0 Windows doesn't use endgame tablebases despite finding them

### ISSUE THREAD

**Issue by ipostr08x** [LeelaChessZero/lc0#1064]
<img width="350" alt="Capture4" src="https://user-images.githubusercontent.com/59011913/73727558-bc6baf00-46ff-11ea-9310-c9a9132cae54.PNG">

`
C:\lc0>lc0 --logfile=c:\lc0\log.txt --backend=cudnn-fp16 --backend-opts=(gpu=0,backend=cudnn-fp16),(gpu=1,backend=cudnn-fp16),(gpu=2,backend=cudnn-fp16),(gpu=3,backend=cudnn-fp16) --nncache=100000000 --threads=5 --backend=roundrobin --syzygy-paths=c:\syzygy\
       _
|   _ | |
|_ |_ |_| v0.23.2+git.c8d9095 built Dec 31 2019
isready
readyok
ucinewgame
Loading Syzygy tablebases from c:\syzygy\
Found 510WDL, 0 DTM and 145 DTZ tablebase files.
Found pb network file: ./weights_run1_62204.pb.gz
Creating backend [roundrobin]...
Creating backend [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 10.1.0
GPU: Tesla V100-SXM2-16GB
GPU memory: 16 Gb
GPU clock frequency: 1530 MHz
GPU compute capability: 7.0
Creating backend [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 10.1.0
GPU: Tesla V100-SXM2-16GB
GPU memory: 16 Gb
GPU clock frequency: 1530 MHz
GPU compute capability: 7.0
Creating backend [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 10.1.0
GPU: Tesla V100-SXM2-16GB
GPU memory: 16 Gb
GPU clock frequency: 1530 MHz
GPU compute capability: 7.0
Creating backend [cudnn-fp16]...
CUDA Runtime version: 10.0.0
Cudnn version: 7.4.2
Latest version of CUDA supported by the driver: 10.1.0
GPU: Tesla V100-SXM2-16GB
GPU memory: 16 Gb
GPU clock frequency: 1530 MHz
GPU compute capability: 7.0
position fen r3k2r/3n4/8/8/8/8/3Q4/4K3 w kq - 0 1
go infinite
info depth 1 seldepth 2 time 18382 nodes 3 score cp -187 hashfull 0 nps 187 tbhits 0 pv d2e3 e8f7 e3a7
info depth 2 seldepth 3 time 18404 nodes 4 score cp -161 hashfull 0 nps 105 tbhits 0 pv d2e3 e8f8 e3f3
info depth 2 seldepth 4 time 18416 nodes 9 score cp -151 hashfull 0 nps 180 tbhits 0 pv d2e3 e8f8 e3f4 f8e7
info depth 3 seldepth 4 time 18424 nodes 13 score cp -177 hashfull 0 nps 220 tbhits 0 pv d2e3 e8f8 e3f4 f8e7
info depth 3 seldepth 5 time 18432 nodes 14 score cp -173 hashfull 0 nps 212 tbhits 0 pv d2e3 e8f8 e3f3 f8e7 f3e4

C:\syzygy>dir c:\syzygy\krrnvkq.rtbw
 Volume in drive C has no label.
 Volume Serial Number is 083C-9DFA

 Directory of c:\syzygy

01/31/2020  09:46 AM       200,234,128 KRRNvKQ.rtbw
               1 File(s)    200,234,128 bytes
               0 Dir(s)  418,432,872,448 bytes free
`

Stockfish uses the tablebases correctly. They are verified.

Likely the same issue as https://github.com/LeelaChessZero/lc0/issues/668

**Comment by joergoster** [comment]
The problem here is that castling for Black is still possible. Syzygy bases don't hold information for positions with castling still possible.

See https://syzygy-tables.info/?fen=r3k2r/3n4/8/8/8/8/3Q4/4K3_w_kq_-_0_1
And Stockfish doesn't probe this position at root, either.

```
 +---+---+---+---+---+---+---+---+
 | r |   |   |   | k |   |   | r |
 +---+---+---+---+---+---+---+---+
 |   |   |   | n |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   | Q |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   | K |   |   |   |
 +---+---+---+---+---+---+---+---+

Fen: r3k2r/3n4/8/8/8/8/3Q4/4K3 w kq - 0 1
Key: AF2FD6E81C95B4C0
Checkers: 
```
Without the castling rights set:
```
 +---+---+---+---+---+---+---+---+
 | r |   |   |   | k |   |   | r |
 +---+---+---+---+---+---+---+---+
 |   |   |   | n |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   | Q |   |   |   |   |
 +---+---+---+---+---+---+---+---+
 |   |   |   |   | K |   |   |   |
 +---+---+---+---+---+---+---+---+

Fen: r3k2r/3n4/8/8/8/8/3Q4/4K3 w - - 0 1
Key: 13C7B08AB8E143B7
Checkers: 
Tablebases WDL: Draw (Success)
Tablebases DTZ:    0 (Success)
```

**Comment by ipostr08x** [comment]
Thank you for the explanation. This issue can be closed.
