### ISSUE TITLE
An issue with multithreading in search

### ISSUE THREAD

**Issue by punter11235** [LeelaChessZero/lc0#1067]
Here are two famous test positions:
1)rn3r1k/pn1p1ppq/bpp4p/7P/4N1Q1/6P1/PP3PB1/R1B1R1K1 w - - 3 21
2)r7/5p1p/pR2rnp1/1p1q4/kP6/P1Q2PP1/2P4P/1K3B2 w - - 0 33

The first one is from AlphaZero match, the second one is a variation from immortal Kasparov-Topalov game. Setup:
1)Infinite analysis
2)one 2080ti
3)Current (62271) T60 net and current dev build as of 2020-02-09 (b69b90a)
4)default parameters (with the exception of number of threads and NN Cache Size which I increased)
5)Syzygy 6man TBs (shouldn't matter as it barely get hits from those positions but I am just mentioning it for completeness)

Lc0 running with one thread finds 21.Bg5 in less than 3 minutes and quickly after that it gives almost 80% score, significantly better than inferior 21.b4.
In the second position it finds 33.Rxe6 instantly and needs around 12-15 seconds to give it huge winning score (85%+).

Now the problem: when running using 2 threads the behavior becomes completely unpredictable. It either finds the solutions quickly or it never finds them depending on the run and initial luck. By "never" I mean that I've run it for more than an hour for the first position and 15 minutes for the second one and it still didn't find it.

As suggested on Discord I tried reducing MaxCollisionEvents as well as MinibatchSzie but it doesn't fix the problem.
I think it's a very serious problem as any kind of testing or long analysis is now very unpredictable with more than 1 thread. Lc0 now blunders randomly when using 2 threads and then when people try to reproduce it they will see completely unpredictable results or won't be able to reproduce the blunder at all (if they run it with 1 thread). I think the issue is very serious. I understand that there is some unavoidable non-deterministic behavior with many threads but it seems the influence of initial luck in search is far too great right now.

EDIT: it seems it depends on the net a lot as well 62271 gets it every time in a few seconds 62272 doesn't get it at all. Is it possible that it changed that much from net to net or maybe the search is too sensitive to very small value changes?

**Comment by Naphthalin** [comment]
I checked the 2nd position, also with 62271 and default parameters, but with the dx backend.

I got the very interesting result, that `-t 2` finds the move instantly sometimes (ran it 10 times for 100k nodes; 5x instantly winning, 3x best move, but drawish/slightly negative, 2x Qb2 instead).

`-t 3` and `-t 4` don't find it at all, and surprisingly `-t 1` also doesn't find it at 1M nodes (nps is nearly identical at 1 and 2 threads):

```
lc0.exe -v -w weights\62271 -t 1
position fen r7/5p1p/pR2rnp1/1p1q4/kP6/P1Q2PP1/2P4P/1K3B2 w - - 0 33

info string f1b5  (141 ) N:    1187 (+ 0) (P:  8.56%) (Q: -0.81908) (D:  0.053) (U: 0.83036) (Q+U:  0.01129) (V:  -.----)
info string b6e6  (1182) N:    3999 (+ 0) (P: 10.32%) (Q: -0.28694) (D:  0.298) (U: 0.29744) (Q+U:  0.01050) (V:  -.----)
info string b1b2  (31  ) N: 1068934 (+ 0) (P:  6.93%) (Q:  0.00965) (D:  0.668) (U: 0.00075) (Q+U:  0.01040) (V:  -.----)``` 

I ran it 10x for 100k nodes as well with `-t 1`, and it never finds the move.

**Comment by Naphthalin** [comment]
Checked it with kiudee bonus parameters for reference, again 100k nodes.

At `-t 1` the move is never found.
At `-t 2` the move was found 5/10 times
At `-t 3` the move was found 4/5 times, but more slowly.

**Comment by MelleKoning** [comment]
Just as a reference, you can 'broaden' the search of the MCTS searchtree by setting the cpUCT settings.
As an example when starting lc0 from command line:

`lc0 --verbose-move-stats -t 2 --minibatch-size=256 --weights=.\nets\62275  --multipv=5 --cpuct=100 --cpuct-factor=1000 --cpuct-base=1
`

will buildup the searchtree very broadly, and in this scenario sticks with the Rb6xe6 move a little longer. Notice the number of nodes of the other moves are now much closer to the number of nodes of the bestmove:
```

info string b6b7  (1187) N:    4869 (+ 0) (P:  5.03%) (Q: -0.15568) (D:  0.070) (U: 37.38742) (Q+U: 37.23174) (V: -0.9723)
info string f1d3  (134 ) N:    5165 (+ 0) (P:  5.36%) (Q: -0.29027) (D:  0.092) (U: 37.53150) (Q+U: 37.24123) (V: -0.9701)
info string b1b2  (31  ) N:    6787 (+ 0) (P:  6.48%) (Q:  0.54571) (D:  0.040) (U: 34.50688) (Q+U: 35.05259) (V: -0.9719)
info string f1b5  (141 ) N:   10940 (+191) (P:  9.35%) (Q: -0.03571) (D:  0.049) (U: 30.38210) (Q+U: 30.34638) (V: -0.5779)
info string b6e6  (1182) N:   12942 (+229) (P: 10.98%) (Q:  0.18581) (D:  0.074) (U: 30.16007) (Q+U: 30.34587) (V: -0.8630)
bestmove b6e6 ponder d5e6
```

**Comment by Tilps** [comment]
Seems like the kind of scenario that mcts will struggle with.
Interesting that some people have it do better with threading, and other people have it do worse. I guess it depends a lot on how those initial visits go as to how deep the Qb2 rabbit hole opens up.

Lets just blame Q values, the early Q values in search tree are clearly very very wrong for both moves.
