### ISSUE TITLE
Leela accepts draw when winning

### ISSUE THREAD

**Issue by chara1ampos** [LeelaChessZero/lc0#1068]
I was playing on playchess.com. Leela was clearly winning by >120 points, eventually reporting mate in 27 moves using 6-man sygygy tablebases. Yet, the game ended up in a draw. It appears the opponent offered a draw and Leela accepted it. This appears to be a serious bug.
[Christopher50_YURK78_2020_BLUNDER.zip](https://github.com/LeelaChessZero/lc0/files/4177147/Christopher50_YURK78_2020_BLUNDER.zip)

Hardware: Nvidia Quadro GV100, Intel XEON 8173M, 384 GB ECC RAM.
Neural network: 256x20-t40-1541.pb, 2020-01-01, by [sergio-v](https://www.comp.nus.edu.sg/~sergio-v/t40/256x20/)

**Comment by Tilps** [comment]
Looking at your pgn I don't see any mate in x reporting - which is not surprising as there isn't any released version of lc0 that supports mate in x reporting.  Leela did manage to determine with certainty that it could convert to a TB win endgame, but having converted to that won endgame leela failed to win.
It is possible for leela to determine that there exists a path to certain victory and then fail to to convert if you only provide WDL tablebases and not DTZ - or potentially if you provide 6 piece tablebases without the 5 piece and smaller as well.
Please verify that you have the DTZ tables installed correctly.
(That being said, something seems strange about returning identical evals for all the moves prior to the draw. So there could be something else lurking here.)

**Comment by chara1ampos** [comment]
Thanks for looking into it. I checked that all 6, 5, 4 and 3 man DTZ and WTZ tablebases are included (about 150GB). Maybe something else is lurking indeed.

**Comment by Tilps** [comment]
I played through with T59 with 5 piece WDL/DTZ and it wouldn't have done the blunder, and immediately recognizes draw as the game outcome after playing the blunder.
I would suggest you check your tablebases for corruption. And verify that your syzygy-paths property is set correctly by checking the leela logs for the number of WDL and DTZ tablebases loaded during the start up initialization.

**Comment by Tilps** [comment]
Also to be sure I did a verbose-move-stats on a search at the blunder - 0 visits to anything other than a7h7 and a7g7 - indicating that the DTZ filtering is working fine to ensure that only minimal-dtz moves are played in this position. (despite the blunder move having a moderately high policy value).

**Comment by Tilps** [comment]
Game in uci format in case someone wants to position startpos moves manually like I did.
e2e4 e7e5 g1f3 b8c6 f1b5 g8f6 e1g1 f6e4 f1e1 e4d6 f3e5 f8e7 b5d3 c6e5 e1e5 e8g8 d1f3 c7c6 c2c3 d6e8 d3c2 d7d5 d2d4 e7d6 e5e3 d8h4 h2h3 g7g5 f3e2 e8g7 b2b3 h4f4 g2g3 f4f6 e2f3 f6h6 c1a3 d6a3 b1a3 f7f5 e3e5 h6h3 a1e1 f8f6 f3g2 h3h6 g2h2 h6h2 g1h2 g5g4 e5e7 a8b8 c2d3 f5f4 e1e5 f4g3 f2g3 c8f5 e7g7 g8g7 d3f5 b8f8 f5g4 f6f2 h2h3 f2a2 a3b5 c6b5 e5d5 a7a6 c3c4 b5c4 b3c4 a2d2 d5g5 g7h6 g5d5 b7b6 c4c5 b6c5 d5c5 d2d4 c5a5 d4d6 g4e2 f8a8 e2c4 h6g7 c4f1 a8a7 g3g4 h7h6 h3h4 g7f8 f1e2 f8e7 g4g5 h6g5 h4g5 e7d8 g5f4 d8c7 f4f5 c7b6 a5a1 d6d2 e2h5 d2d5 f5g6 d5h5 g6h5 a6a5 h5g4 a5a4 g4f3 a4a3 f3e2 b6c5 e2d3 c5b4 a1b1 b4a4 b1a1 a4b3 a1b1 b3a4 b1a1 a4b3 a1b1 b3a4

**Comment by chara1ampos** [comment]
> 
> 
> I played through with T59 with 5 piece WDL/DTZ and it wouldn't have done the blunder, and immediately recognizes draw as the game outcome after playing the blunder.
> I would suggest you check your tablebases for corruption. And verify that your syzygy-paths property is set correctly by checking the leela logs for the number of WDL and DTZ tablebases loaded during the start up initialization.

I used a checksum utility by Massimiliano Goi, it reports all 5-man tablebases are OK. I cannot see any log files for Leela. Do I need to enable logging before play?

**Comment by Tilps** [comment]
yes turn on the logfile parameter to a path you'll be able to find.
(It will be in the standard UCI output as well, but that would assume that your uci host keeps that somewhere for you to see - logfile doesn't make any such assumption.)

**Comment by Naphthalin** [comment]
@chara1ampos could you ever reproduce the issue? As Leela "winning by >120 points" means that she found a definite TB win, and won't ever report a mate in 27 as the functionality to report mates was added only recently.

**Comment by mooskagh** [comment]
Closing as the issue author didn't respond with more information for quite a while.

Feel free to reopen if you have new data.
