### ISSUE TITLE
It's not possible to specify absolute path to config

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#1071]
Because of
https://github.com/LeelaChessZero/lc0/blob/3ac7e7e2e08f29a4b2864701d3e9e9e949d5b671/src/utils/configfile.cc#L90

**Comment by Naphthalin** [comment]
Was there any attempted fix to this so far, given it is marked as a release blocker?

**Comment by mooskagh** [comment]
It's not a release blocker as everyone forgot. It would be nice to have it fixed eventually.
