### ISSUE TITLE
Add a mode to force more visits to inferior moves at root when multipv is on

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#1072]
When chess players use chess engines for analyze, they often use MultiPV mode to looks at few moves from the given position.
It often happens that the tree is very biased towards the best move, so 2nd and especially tail moves get orders of magnitude less visits.

To make MultiPV more useful for people, have a mode (and maybe make it default on) to force more visits to weaker moves.

E.g. 
* (N+1)th best move should get at least ((N)th best move - 100) visits.
* or (N+1)th best move should get at least ((N)th best move * 0.9) visits.

**Comment by Naphthalin** [comment]
Would the option of setting a separate cpuct value at root help with this? This would be a functionality we would like to have anyway for experiments with increasing the number of playouts during a training run, as we then would have a comparable problem of too sharp policies.

That solution would also be in line with the bandit literature on `best arm identification` which basically says that root should be treated differently then.

**Comment by mooskagh** [comment]
I'd prefer it to be more explicit than tuning unrelated constants and hoping that it helps, and also I think it makes sense to do that only for moves observed by multiPV.

E.g. if MultiPV=3, 4th best move should not receive any additional visits (although in reality they will receive quite a lot of visits as I expect 3rd and 4th best moves switch quite frequently as search runs).

**Comment by mooskagh** [comment]
https://discordapp.com/channels/425419482568196106/425419999096733706/677612189288235028 for some more info

**Comment by Naphthalin** [comment]
#1173 is an attempt at doing so regardless of multi-PV; it would probably nice to know the use case scenario where this is relevant, especially in situations where move alternatives are obviously inferior.

**Comment by mooskagh** [comment]
I think --cpuct-at-root setting may be already good enough and we don't need anything else (I know I said it opposite but now that we have it, it seems that it may be a good idea).
However it would be nice for someone to test it and come with recommended settings for position analysis.
