### ISSUE TITLE
[dx] Search stops at ~4M nodes

### ISSUE THREAD

**Issue by Naphthalin** [LeelaChessZero/lc0#1078]
Win10 build 18363
AMD RX Vega 56

When running the `dx` backend for enough nodes, search seems to stop around 4M nodes (one time 3.6M nodes, on time 4M nodes). No crashes, `lc0` keeps running, but number of nodes doesn't increase anymore:
```
info depth 15 seldepth 43 time 97432 nodes 3548028 score cp 36 hashfull 1000 nps 36650 tbhits 0 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 g2g3 f8e7 f1g2 e8g8 e1g1 d5c4 d1c2 a7a6 a2a4 c8d7 c2c4 d7c6 c1f4 e7d6 f4g5 b8d7 b1c3 h7h6 g5f6 d7f6 f1e1 f6e4 f3e5 d6e5 d4e5 e4c3 g2c6
info depth 15 seldepth 43 time 102439 nodes 3594953 score cp 36 hashfull 1000 nps 35308 tbhits 0 pv d2d4 g8f6 c2c4 e7e6 g2g3 d7d5 f1g2 d5c4 g1f3 f8b4 c1d2 c7c5 e1g1 e8g8 d1c1 b4d2 b1d2 c5d4 d2c4 b8c6 f1d1 f8e8 f3e5 c6e5 c4e5 d8d6 c1f4 e8d8 a1c1 d6b6 e5c4
info depth 15 seldepth 43 time 107442 nodes 3594953 score cp 36 hashfull 1000 nps 33654 tbhits 0 pv d2d4 g8f6 c2c4 e7e6 g2g3 d7d5 f1g2 d5c4 g1f3 f8b4 c1d2 c7c5 e1g1 e8g8 d1c1 b4d2 b1d2 c5d4 d2c4 b8c6 f1d1 f8e8 f3e5 c6e5 c4e5 d8d6 c1f4 e8d8 a1c1 d6b6 e5c4
```
log file doesn't show anything additional to this.

I so far only tried net 58613 and `--minibatch-size=256`, rerunning the test with a T60 net now.

EDIT: stopped T60 at 5.6M nodes, as it kept going.

**Comment by mooskagh** [comment]
If you built it yourself, could you try attaching visual studio when it's in that state and looking at stack traces?

**Comment by Naphthalin** [comment]
I didn't build that binary myself, I think this is a AppVeyor build
```
v0.24.0-dev+git.a6f286b built Jan 25 2020
```
I will try if I can reproduce the behavior with a self compiled master.

**Comment by mooskagh** [comment]
If you used appveyour build, then we can open the process dump as we store .pdb files.
Could you run the following when the Lc0 is hanging in that state?
```
procdump64.exe -mm lc0.exe
```
https://docs.microsoft.com/en-us/sysinternals/downloads/procdump <- download procdump here.

**Comment by Naphthalin** [comment]
Couldn't reproduce the hanging with a local compile yet.

`procdump64 -mm lc0.exe` produces
[lc0.exe_200216_004810.zip](https://github.com/LeelaChessZero/lc0/files/4209115/lc0.exe_200216_004810.zip)

**Comment by mooskagh** [comment]
Also if there are not very many nodes yet when it hangs, `-ma` instead of `-mm` would dump even more data.
Which may bring some additional information, but the resulting file may be huge.

**Comment by ankan-ban** [comment]
@Naphthalin , could be the same issue that was fixed in https://github.com/LeelaChessZero/lc0/pull/1063. Can you try appveyour from that PR ?

**Comment by Naphthalin** [comment]
Running the binary from #1063 neither hangs nor produces the stuttering mentioned above at 10M nodes. I therefore assume this was actually the bug I encountered, and while I'm happy that it is already fixed I am a bit sorry that I didn't think of looking whether there were any fixes during the last weeks first.

I therefore consider this closed, if you think it should stay open please reopen the issue.
