### ISSUE TITLE
CudNN library not found

### ISSUE THREAD

**Issue by CalKK8** [LeelaChessZero/lc0#1086]
I am using an nVIDIA GeForce GPU, and want to use CUDA AND cudNN to build and run lc0. I run on linux, and downloaded both the Runtime and Developer library for CUDA 10.2 (I downloaded 10.2). I ran ./build.sh, but library cudnn wasn't found. Can somebody help?

**Comment by ddobbelaere** [comment]
This is the issues and bug tracker of the engine lc0.

For installation questions, please join our responsive Discord https://discord.gg/pKujYxD and ask in #help channel.

**Comment by ddobbelaere** [comment]
Maybe just to quickly exclude a possible issue with the build scripts themselves: where (in which directory) did you install the CUDA libraries? Thanks!

**Comment by borg323** [comment]
Did you also install cuDNN? It is a separate download from <https://developer.nvidia.com/cudnn>.

If you did, build.sh should report something like:
```
Library cublas found: YES
Library cudnn found: YES
Library cudart found: YES
Program nvcc found: YES (/usr/local/cuda/bin/nvcc)
```

**Comment by Naphthalin** [comment]
Author never responded, and this isn't a Lc0 issue. Closing now.
