### ISSUE TITLE
Remove the BLAS dependency from OpenCL backend.

### ISSUE THREAD

**Issue by frpays** [LeelaChessZero/lc0#109]
This is to be investigated as it would make the build easier for AMD users.

There are 2 BLAS dependencies:

- sgemm reference timing in the OpenCL tuning.  Can it be removed ?

- sgemv at the end of the inference. It can definitely be replaced by a for loop that the compiler will happily vectorize. This implementation will be marginally slower than the blas one, and is not critical for overall backend performance.

**Comment by Ttl** [comment]
sgemm in tuning shouldn't be removed as it is needed to check that the output of the GPU is correct. Some parameters can give incorrect output with certain GPUs. It is possible to replace it with any other sgemm though. It's performance doesn't matter at all, it is only run once at the start of tuning.

Last sgemv of the value head is very small (128 multiplications). Loop would work here just fine without having any measurable effect on performance.

**Comment by oscardssmith** [comment]
@frpays should this be closed then?
