### ISSUE TITLE
Proposal to add Transposition Difference Value

### ISSUE THREAD

**Issue by TesseractA** [LeelaChessZero/lc0#1091]
**_EDIT: I've revised this pseudo-code to make more slightly more sense. I realize the actual code will somewhat different (and maybe fewer lines), but the principles should be the same._**

I made 2 functions allowing 50-move-rule transpositions in with NNCache;

```
function makeTD(board.plyPlayed(original_position))
    cutoff = 20 #tunable; also is a somewhat arbitrary number
    distance_factor = 8 #tunable; linearly increases the TD value.
    ply_until_100 = ply_played - 100
    if ply_until_100>cutoff: #prevents the log function being 0 or lower
        return TD=abs(int(distance_factor*log(ply_until_100-cutoff))) #This function does not have to be a log function, but it probably works better that way.
#Two numbers in this function are tunable. Notably, odd number outputs should be rounded to even numbers because transpositions do not happen with a difference of 1 in ply, as it is then the other side's turn.
#Another option is just to divide 100 by 2 beforehand and count moves instead of ply.

#NNCache search code
#invoked when comparing boards/FENs to see whether a new position was already searched or not
#first compare boards, then compare 50-MRs using TD
function comparePositions_withTD(original_position, new_position)
    if board.position(new_position) == board.position(original_position): #comparing old and new positions without 50MR
        TD=makeTD(board.plyPlayed(original_position))
        OP=board.plyPlayed(original_position) #original position's ply count
        NP=board.plyPlayed(original_position) #new position's ply count
        if OP+TD>NP and NP>OP-TD: #comparing 50MRs with bounds TD
            return True #means the search code treats the old position as if it were the new position
        else:
            return False #means the search code treats the old position as if it wasn't the original position
   else:
       continue
````

I only expect TD to fail in certain conditions, which I believe the distance of 10 moves from the 50MR as (x-10); x>10 accounts for. If functional errors are accounted for and TD fails, it is because:
-X is small
-Somehow, repetitions are encouraged and expands search unnecessarily on multiple fronts
-Descending evaluations due to approaching the 50MR are delayed and hampered by a single visit
-Evaluations don't descend enough and serve as an ineffective or proactive draw avoidance mechanism
-Being practically useless? (Which I do not expect at all if implemented correctly)
-Could need to be paired with a policy boosting/subtracting mechanism that increases/decreases priority to searching transpositions in NNcache (maybe causing a small but noticeable slowdown?)
-could also need to be paired with an additional visit beyond the transposition (for worst-case 50MR faults)
-conflicts with moves-left head when the moves-left head's prediction approaches -> 50MR only because the transposition is closer to the 50MR, therefore necessitating that transpositions should only be allowed as equal or less distance to root.
-Extremely high depth searches requiring precise and stable evaluations may spike and increase expected time needed for moves during games
-Multivariable tunes could be required, possibly including the function I've defined above

As for training:
-training could not like it (for various unknown outerspace reasons)
-positive feedback loops in training due to high Q insensitivity, wildly differing evaluations between places in the 50 MR, and preference to positions with/without transpositions could cause overfitting of some kind
-everything needs retuning? (heavy rocks to be lifted?)

A possible remedy to the encouragement of high-depth related repetitions (which would unnecessarily allow for expansion of the search tree along already explored paths) would be to reconsider implementing 2-fold draw scoring, but perhaps only for already searched positions.

**Comment by TesseractA** [comment]
I'm going to take a crack at this in the next 2 weeks, and hopefully before May I'll have something on Github.

**Comment by TesseractA** [comment]
https://github.com/LeelaChessZero/lc0/blob/master/src/mcts/search.cc
https://github.com/LeelaChessZero/lc0/blob/master/src/mcts/search.h
https://github.com/LeelaChessZero/lc0/search?q=nncache&unscoped_q=nncache
https://github.com/LeelaChessZero/lc0/search?q=node&unscoped_q=node
https://github.com/LeelaChessZero/lc0/blob/e0b6ef380c8ac6bfa381d14883435941aef0c982/src/engine.cc
https://github.com/LeelaChessZero/lc0/blob/afd087551bb2523e171bd42f80a49db8cc119aa4/src/engine.h
Just to give myself some links for reference

**Comment by Naphthalin** [comment]
I don't fully understand what you are trying to do here; but I'm also not the person to grasp things from reading pseudocode. Can you explain the high-level idea?

**Comment by TesseractA** [comment]
Unfortunately, the 50 move rule prevents certain positions from the cache to be used in other circumstances. With TD, you allow the engine to treat positions similar 50-move rule counts as transpositions, minimally slowing down search at the cost of lengthening code.

**Comment by Naphthalin** [comment]
Ah ok, thanks.
If I remember correctly, @mooskagh posted something related in Discord basically stating that nearly all identical positions (in training (?)) have the same 50 move rule counter as well, so ignoring the counter in special cases wouldn't really allow any speed up. The true benefit of this however probably lies in the correct representation in DAGs where this behavior is crucial for 2-fold draw scoring -- we will see how that turns out, if we ever do :)

Additionally, I don't know how the MLH coming influences this and makes it either more or less desirable; in theory more, but in practice there could be strange side effects.

**Comment by Mardak** [comment]
https://github.com/LeelaChessZero/lc0/wiki/Transposition-tests

**Comment by TesseractA** [comment]
Thanks Mardak! I acknowledge that there may not be an extremely significant gain in strength from search, however I do think there will be some degree of speedup in certain middle-endgame positions due to the fact that certain positions consistently get repeat-searched. Also, the NNCache size may be reduced in a way different than tested in those conditions since there are fewer repeats of the same position in the cache.

Also Naphthalin, the 'patch' that I'm associating with this issue is more along the lines of speeding up analysis rather than speeding up training games, as these types of transpositions are more likely to happen in longer and deeper search. Also, you make an interesting point about the MLH side effects. But I don't think it'll be a huge issue since the NN typically doesn't change its preferences until things start becoming ~40-30 ply from the 50 move rule.

Also, I had another idea a while ago about policy boosting positions in the NN cache. But that will have weird side effects probably, since moves with more transpositions would get searched more.

I'm closing this issue as it was just a toss-up idea that I wanted people to know it existed if they had any ideas associated with it, and I'm actually currently still working on this issue myself. By closing it, I'll reduce clutter, and I'll be coming up with a PR before ~May 30 (after I finish classes).
