### ISSUE TITLE
[dx] error Unknown backend

### ISSUE THREAD

**Issue by Mbr18** [LeelaChessZero/lc0#1092]
lc0-v0.24.0-rc1-windows-gpu-dx1 quits with "Unknown backend: dx" error. See attachment.
Tried it on two different UpToDate Windows10 machines (i7-4790/GTX1060 and Q9400/HD 7770).

[Error LC0.txt](https://github.com/LeelaChessZero/lc0/files/4242306/Error.LC0.txt)

**Comment by mooskagh** [comment]
We renamed `dx` backend to `dx12` and that causes some problems.
Most likely in the next version (v0.24.0 release or v0.24.0-rc2) it will be renamed back to `dx`.

**Comment by borg323** [comment]
This is now fixed in v0.24.0-rc2 - we fixed both the client and the check_dx script to use the dx12 backend name.

**Comment by Mbr18** [comment]
Seems to be working! 
My UpToDate Windows10 PC’s passes the check_dx.bat and check_opencl.bat.
Ps. There is no check_cuda.bat so that is excluded for the NVIDIA GPU’s.

The results of my PC’s are attached.
PC i7-4790/NVIDIA GTX1060 6GB
PC q9400/AMD HD 7770 (R7 200) 1GB
PC Pentium G645 /NVIDIA GeForce GTX 750 Ti 2GB

[Lc0 Benchmark.txt](https://github.com/LeelaChessZero/lc0/files/4278253/Lc0.Benchmark.txt)

**Comment by borg323** [comment]
> Ps. There is no check_cuda.bat so that is excluded for the NVIDIA GPU’s.

Due to a license incompatibility, we cannot distribute an lc0 compiled with the backends needed for a check_cuda script. Moreover, we haven't received any reports of driver issues regarding cuda/cudnn.
