### ISSUE TITLE
When using ChessOK Aquarium GUI LC0 v0.24.0-rc1 doesn't work BUG

### ISSUE THREAD

**Issue by Chess321** [LeelaChessZero/lc0#1094]
v0.23.3 works fine.

v0.24.0-rc1 freezes GUI and some seconds later the PC too!
Happens with infinite analysis and also happens with IDeA.
There is really a terrible BUG.

**Comment by mooskagh** [comment]
Could you record a Lc0 logfile and attach to this issue?

**How to write a log file:**
Suppose you want log file to be at **D:\\logfile.txt**, then:

Set the following UCI option:
**Logfile:** D:\\logfile.txt

OR

pass this as a command line argument:
`--logfile=D:\logfile.txt`

OR

Create **lc0.config** file in the same directory as your **lc0.exe** is located, with the following contents:
```ini
logfile=D:\logfile.txt
```

After running Lc0, **D:\\logfile.txt** should appear.

**Comment by Naphthalin** [comment]
@Chess321 could you please respond and provide a logfile?

**Comment by mooskagh** [comment]
Closing as not reproducible. Feel free to reopen if you have more data.
