### ISSUE TITLE
Document build instructions for visual studio 2017 more completely.

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lc0#11]
Current instructions for visual studio 2017 based build appear to miss a few details that need changing in the build_cuda.cmd.

The following is my build_cuda.cmd. (Having installed visual studio 2017 community edition with the 14.11 compiler version option installed and using Cuda 9.1 since I don't have 9.2 installed yet and having installed cudnn into the same directory as cuda 9.1. I hear cuda 9.2 supports newer compiler versions, so it might be a bit simpler.)

rd /s build

call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" amd64 -vcvars_ver=14.11
python "C:\Users\<UsernameHere>\AppData\Local\Programs\Python\Python36\Scripts\meson.py" build --backend vs2017 --buildtype release ^
-Dcudnn_libdirs="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\lib\x64" ^
-Dcudnn_include="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1\include" ^
-Ddefault_library=static

pause

cd build

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" ^
/p:Configuration=Release ^
/p:Platform=x64 ^
/p:PreferredToolArchitecture=x64 subprojects\zlib-1.2.11\subprojects@zlib-1.2.11@@z@sta.vcxproj ^
/filelogger

"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe" ^
/p:Configuration=Release ^
/p:Platform=x64 ^
/p:PreferredToolArchitecture=x64 lc0@exe.vcxproj ^
/filelogger

**Comment by mooskagh** [comment]
It would be easiest to have separate .cmd file for VS 2017 and 2015.
Or if noone uses VS 2015, update the build-cuda.cmd.  I build with 2015 currently, but I'm happy to change.

Alternatively it may make sense to probe several directories in .cmd file and pick one automatically.

**Comment by mooskagh** [comment]
I think this is outdated. Although I didn't build for windows for ages.
