### ISSUE TITLE
Assertion failed: !edges_,

### ISSUE THREAD

**Issue by Naphthalin** [LeelaChessZero/lc0#1106]
BUG REPORT

**Describe the bug**

Using lc0 on command line, see below. It was reproducible for me with that exact version, but neither with v0.24-rc1 nor an older version from January. If this is already fixed this is good, but then I'm unaware of the fix.

**Steps to Reproduce**

```
lc0 -v --policy-softmax-temp=1.0 -w weights\700275
       _
|   _ | |
|_ |_ |_| v0.24.0-dev+git.f5d2c10 built Feb 19 2020
position startpos moves g1f3
go nodes 800
Loading weights file from: weights\700275
Creating backend [dx]...
--verbose omitted--
info string d7d5  (293 ) N:     363 (+111) (P: 33.35%) (WL: -0.09099) (D:  0.298) (Q: -0.09099) (U: 0.06163) (Q+U: -0.02936) (V: -0.1051)
bestmove d7d5 ponder d2d4
position startpos moves d2d4
go nodes 800
Assertion failed: !edges_, file c:\users\Naphthalin\documents\schach\lc0-master\src\mcts\node.cc, line 185
```

**Hardware**
* Win10, dx backend, AMD RX Vega 56

logfile doesn't say anything, lc0 just crashes.

**Comment by Tilps** [comment]
Maybe test latest with max-concurrent-searchers=0? Possibly max-concurrent-searchers=1 is hiding a threading race?

**Comment by Naphthalin** [comment]
I tried to reproduce it with latest and max-concurrent-searchers=0, but didn't run into the same error. I randomly hit the above error for multiple combinations where it would crash consistently (and independent of the net which was used!), always at a specific tree reset. As this seems to be a local VS build, I probably can access a debugging, but wouldn't know what to look for.

**Comment by borg323** [comment]
Can you do a `git bisect`?

**Comment by Naphthalin** [comment]
Started the bisect. Current master has the exact same problem:
```
lc0 -v --policy-softmax-temp=1.0 -w weights\700275
       _
|   _ | |
|_ |_ |_| v0.25.0-dev+git.787d5de built Mar  4 2020
position startpos moves g1f3
go nodes 800
Loading weights file from: weights\700275
Creating backend [dx12]...
bestmove d7d5 ponder d2d4
position startpos moves d2d4
go nodes 800
Assertion failed: !edges_, file c:\users\Naphthalin\documents\schach\lc0-master\src\mcts\node.cc, line 185
```
All binaries are built with the `build-cl.cmd` script, stating
`meson build --backend vs2017 --buildtype release -Dblas=false ^`
so these definitely are release builds.

**Comment by mooskagh** [comment]
We need to fix that the code that assert is not triggered (it will work of you simply remove it, but it's better to clear `edges_` when killing subtree).
And possibly it makes sense to investigate why asserts are not compiled out in release build (or why the build is not the release one).

**Comment by Mardak** [comment]
Pretty sure the `assert(!edges_)` has failed ever since it was added in c7e15bcaa584729507dc6b8707e25d4a71ea791c

After `position startpos moves …` then another `position startpos moves …`, startpos node is reused and already has the previous 1 edge created in the previous `CreateSingleChildNode`.

**Comment by mooskagh** [comment]
Yeah I mean `ReleaseChildrenExceptOne` probably has to clear edges() too. Or something like this.
