### ISSUE TITLE
Meson: handle better headers include directories.

### ISSUE THREAD

**Issue by frpays** [LeelaChessZero/lc0#112]
Right now, for tensor_flow, openblas, mkl, cudnn, a unique include path is specified in `meson_options` If it's different from the platform, the build fails and the user has to edit `meson_options`.

But honestly we should do better here.

For all include headers, we could have a list of possible directories, and add the first one that exists, or the first one that exists and contains the header. If someone knows how to code that in meson. That would be a few options less, or some options that you almost never have to change.

And I point out that when you found the library, the include path is most often derived from it.

**Comment by frpays** [comment]
This PR addresses https://github.com/LeelaChessZero/lc0/issues/112 I guess.

**Comment by mooskagh** [comment]
Do we kind of have that now?

**Comment by ddobbelaere** [comment]
Although it's a bit hacky, #113 does the trick for openblas (add first found include dir out of list of options).
