### ISSUE TITLE
LC0 crashes when it threatens mate

### ISSUE THREAD

**Issue by v11580** [LeelaChessZero/lc0#1127]
BUG REPORT

**Describe the bug**
LC0 hangs when it analyzes a position where there is a mate threat. See move 19 below.
This happens when it is playing or doing UCI analysis.

**Steps to Reproduce**

[Event "[04] Lc0 v0.24  vs oHoudini 3 (14/03/2020)"]
[Site "Local computer"]
[Date "2020.03.14"]
[White "Lc0 v0.24"]
[Black "Houdini 3"]
[Result "0-1"]
[ECO "C79"]
1. e4 e5 2. Nf3 Nc6 3. Bb5 a6 4. Ba4 Nf6 5. O-O d6 6. c3 b5 7. Bc2 Be7 8. d4
O-O 9. h3 Bb7 10. Nbd2 exd4 11. cxd4 Nb4 12. Bb1 c5 13. Re1 c4 14. Nf1 Rc8 15.
Ng3 d5 16. e5 Ne4 17. a3 Nxg3 18. fxg3 Nc6 19. Qc2 {threatening mate in one} g6  {White loses on time} 0-1

Expected behavior: finish game or continue analyzing
Observed behavior: hangs

**Lc0 version**
Include Lc0 version/operating system/backend type.

LC0 24.0 cpu dnnl version; blas backend
This crash has been occurring with other versions as well  (23 series)

**Lc0 parameters**
All default settings

**Hardware**
* one cpu
* 12 gigs of RAM
Using Aquarium interface

**Comment by mooskagh** [comment]
Could you record a Lc0 log file?


Here is how to do it:

Suppose you want log file to be at **D:\\logfile.txt**, then:

Set the following UCI option:
**Logfile:** D:\\logfile.txt

OR

pass this as a command line argument:
`--logfile=D:\logfile.txt`

OR

Create **lc0.config** file in the same directory as your **lc0.exe** is located, with the following contents:
```ini
logfile=D:\logfile.txt
```

After running Lc0, **D:\\logfile.txt** should appear.

**Comment by Naphthalin** [comment]
@v11580 can you please respond and provide a log file? Apparently you could reproduce this behavior in the past.

**Comment by mooskagh** [comment]
I'm closing this for now as not reproducible.
If you can reproduce it, please reopen and attach the log.
