### ISSUE TITLE
Lc0 v0.24.1 caused an exception

### ISSUE THREAD

**Issue by SG7** [LeelaChessZero/lc0#1152]
This is second crash in a row. All parameters are at default. It happens after approximately 4 hours at depth 27.  (Infinite analyses) 

Nividia also reported a problem.  The GUI is Fritz17 . 

Captured crash messages:
https://ibb.co/F8CSwMS

Card is GEForce RTX 2080 with the latest driver version 445.7
Driver Type DCH
Direct3D APU version 12
feature level 12_1
OS Win 10 latest version 1903-OS Build 18362.752 and 1909-OS Build 18363.752

**Comment by mooskagh** [comment]
This is working as intended. Unlike A/B engines, Lc0 has to keep entire tree in memory.
I suggest checking [our troubleshoot page](http://lczero.org/play/troubleshoot/) to find what possible options you have.
