### ISSUE TITLE
On powerful gpu how does this compare to Deep Blue?

### ISSUE THREAD

**Issue by hydrogenpi** [LeelaChessZero/lc0#116]
is it stronger or weaker if say using 8xV100 (rentable on aws p3.16xlarge instance) compared to the "pentium genius" of 20+ years ago aka deep blue....

**Comment by mooskagh** [comment]
Github issues is not really a discussion board (use [forum](https://groups.google.com/forum/#!forum/lczero) instead).

But I believe that on average single consumer-level GPU Lc0 is already stronger than any chess engine older than 10 years (probably even less than 10).

I believe https://www.twitch.tv/ccls (or was it another twitch channel?) runs matches between Lc0 and best chess engines of past years, and last match I remember was against year 2012 winner.
