### ISSUE TITLE
"bestmove" printed mixed with other output

### ISSUE THREAD

**Issue by borg323** [LeelaChessZero/lc0#117]
Specifically, the client printed: 
`
2018/06/25 19:11:18 lc0_main.go:174: movstr: chess: failed to decode long algebraic notation text "d4e5bestmove" for position 8/7P/8/1p2q1P1/3K4/P7/1Pk5/8 w - - 1 64
`
This looks like a lc0 issue and not a client issue.

This was reported by joel on discord: https://discordapp.com/channels/425419482568196106/427066771627966466/460907387860287488

**Comment by Tilps** [comment]
I think this should have been fixed by #111
