### ISSUE TITLE
Wrong documentation in utils/cache.h?

### ISSUE THREAD

**Issue by farmersrice** [LeelaChessZero/lc0#1199]
https://github.com/LeelaChessZero/lc0/blob/master/src/utils/cache.h#L97-L115

`BringToFront` is commented out here, but the comment says `If found, brings the element to the head of the queue`. This seems contradictory, I assume the comment is wrong? Or is there some other mechanism to bring it to the front?

**Comment by mooskagh** [comment]
Indeed it's outdated. Bringing it to front slowed down cache a bit without bringing much benefit (entries become stale roughly at the order they were added).

**Comment by mooskagh** [comment]
The comment is not longer there in cache.h
