### ISSUE TITLE
When MLH enabled, verbose move stats is not so useful.

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lc0#1200]
We only output Q+U and raw M - no Q+U+(calculated M effect), so its hard to know the actual current active ordering.

**Comment by mooskagh** [comment]
Would be nice to fix that for v0.25.

**Comment by Naphthalin** [comment]
I agree, the `M` term should be included in the verbose `Q+U`.

**Comment by AlexisOlson** [comment]
I've started an attempt at resolving this.

https://github.com/LeelaChessZero/lc0/compare/master...AlexisOlson:issue-1200

**Comment by mooskagh** [comment]
Fixed via #1230
