### ISSUE TITLE
CPU usage high even for positions with zero moves

### ISSUE THREAD

**Issue by fohristiwhirl** [LeelaChessZero/lc0#1209]
When Lc0 is asked to analyse a position with zero legal moves, it enters a useless loop of some sort and consumes CPU resources.

```
position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves f2f3 e7e5 g2g4 d8h4
go infinite
```

If at all possible, it shouldn't. Still, I suppose the UCI specs don't allow you to instantly send `bestmove` in this situation; but if Lc0 could wait for the `stop` command in a less CPU-intensive manner...

**Comment by mooskagh** [comment]
UCI hosts should not send malformed UCI commands to the engine. In this case, as well as in lots of other cases (illegal moves etc), engine's behaviour is undefined.
If you see any UCI host sending such requests, I suggest filing a bug to that UCI host.

**Comment by fohristiwhirl** [comment]
:)
