### ISSUE TITLE
cache.cc assert error.

### ISSUE THREAD

**Issue by leedavid** [LeelaChessZero/lc0#1215]
in function below which in files  cache.cc

 float CachingComputation::GetPVal(int sample, int move_id) const {
  auto& item = batch_[sample];
  if (item.idx_in_parent >= 0)
    return parent_->GetPVal(item.idx_in_parent, move_id);
  const auto& moves = item.lock->p;

  int total_count = 0;
  while (total_count < moves.size()) {
    // Optimization: usually moves are stored in the same order as queried.
    const auto& move = moves[item.last_idx++];
    if (item.last_idx == moves.size()) item.last_idx = 0;
    if (move.first == move_id) return move.second;
    ++total_count;
  }
  assert(false);  // Move not found.
  return 0;
}

if open the assert without NDEBUG,  some times will trigger assert error show that the Move not found error.

**Comment by mooskagh** [comment]
Thanks for the bug report.

Which version did you use?
Is it stably reproducible or was it one off?
Roughly how many nodes did the search have when this failure occurred?

**Comment by leedavid** [comment]
I test by run training, it is very rarely, only about train more than 20 games will happen one times.

**Comment by leedavid** [comment]
if test only by go nodes XXX, it will not happen.

**Comment by leedavid** [comment]
and I test a few verion, will happen this error.

**Comment by mooskagh** [comment]
1. Which version exactly do you run?
2. Why do you run a debug version for training?
3. Could you send some log with examples?

Thanks!

**Comment by leedavid** [comment]
sorry, maybe I make a mistake test.
