### ISSUE TITLE
Help, Windows 10 Build Error

### ISSUE THREAD

**Issue by jimi-pz** [LeelaChessZero/lc0#1218]
Following the instructions for Windows 10 fails at the build step; giving "**LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj**" error.

Only 7 projects fails, others are ok. Could not make much sense to me, any idea ? 
I'm using visual studio 2019, fyi.

Error: 

"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\lc0.sln" (default target) (1) ->
"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\lc0@exe.vcxproj" (default target) (30) ->
(Link target) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b
8acff\build\lc0@exe.vcxproj]

"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\lc0.sln" (default target) (1) ->
"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\chessboard_test@exe.vcxproj" (default target) (32) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b
8acff\build\chessboard_test@exe.vcxproj]

"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\lc0.sln" (default target) (1) ->
"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\hashcat_test@exe.vcxproj" (default target) (33) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b
8acff\build\hashcat_test@exe.vcxproj]

"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\lc0.sln" (default target) (1) ->
"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\position_test@exe.vcxproj" (default target) (34) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b
8acff\build\position_test@exe.vcxproj]

"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\lc0.sln" (default target) (1) ->
"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\optionsparser_test@exe.vcxproj" (default target) (35) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b
8acff\build\optionsparser_test@exe.vcxproj]

"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\lc0.sln" (default target) (1) ->
"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\syzygy_test@exe.vcxproj" (default target) (36) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b
8acff\build\syzygy_test@exe.vcxproj]

"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\lc0.sln" (default target) (1) ->
"C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b8acff\build\encoder_test@exe.vcxproj" (default target) (37) ->
  LINK : fatal error LNK1181: cannot open input file 'C:\Program.obj' [C:\Users\jimi\Leela Chess\LeelaChessZero-lc0-4b
8acff\build\encoder_test@exe.vcxproj]

    699 Warning(s)
    7 Error(s)

**Comment by Naphthalin** [comment]
Just to be sure, can you try again with a fresh clone of `master`? There recently was a fix merged for some Windows 10 compiler problems.

**Comment by mooskagh** [comment]
I recommend joining our Discord chat at http://lc0.org/chat and asking there in #help. There are often lots of helpful people and that way it will be resolved quicker.

**Comment by jimi-pz** [comment]
@Naphthalin: Thanks; it builds with master; @mooskagh, thanks for the info.
