### ISSUE TITLE
Feature Request: Allow for training data output folder configuration

### ISSUE THREAD

**Issue by cn4750** [LeelaChessZero/lc0#1222]
When training is enabled in selfplay, the training data is generated in a local, randomly named folder. Make an option to allow for a folder path to be specified.

**Comment by mooskagh** [comment]
Probably should be done together with the rest of https://github.com/LeelaChessZero/lc0/issues/976

**Comment by mooskagh** [comment]
Duplicate of #839 and fixed in #1338.
