### ISSUE TITLE
Policy favors shuffling instead of progress until necessary

### ISSUE THREAD

**Issue by Mardak** [LeelaChessZero/lc0#1229]
Here's some test positions and the raw policy for the expected progressing move, e.g., the one played at TCEC17 SuFi.

From game 84, there was 80 ply before lc0 decided to move the pawn https://www.tcec-chess.com/archive.html?season=17&div=sf&game=84:
![c3 move](https://user-images.githubusercontent.com/438537/80036642-ff3f5680-84a6-11ea-9dd6-e36169639b1d.png)
![c3 policy vs rule50ply](https://user-images.githubusercontent.com/438537/80036647-01091a00-84a7-11ea-8716-8a6fecee2e81.png)

From game 26, this 8-piece KRNPPvKRB endgame waited 91 ply before lc0 made some progress https://www.tcec-chess.com/archive.html?season=17&div=sf&game=26:
![f4 move](https://user-images.githubusercontent.com/438537/80036927-8b517e00-84a7-11ea-93ee-da028b50ad17.png)
![f4 policy vs rule50ply](https://user-images.githubusercontent.com/438537/80036937-8db3d800-84a7-11ea-978b-b978534b27f1.png)

And a test 3-piece KRvK endgame shows policies some runs peaking at 87 ply before 88 ply would result in a cursed win for white:
![Ka2 move](https://user-images.githubusercontent.com/438537/80037056-c5228480-84a7-11ea-9e43-6686d82dd6aa.png)
![Ka2 policy vs rule50ply](https://user-images.githubusercontent.com/438537/80037064-c784de80-84a7-11ea-9e8a-df043d6bc8d1.png)

**Comment by Naphthalin** [comment]
This is sadly to be expected, as policies reflect the estimations of values in training games; whenever the path to conversion has too many possibilites of going wrong, the eval at low nodes will be worse than for staying in the same situation for longer, and only when shuffling isn't an option anymore, the slight eval loss of the correct conversion seems acceptable to the net. This will only be solved by giving any incentive for progress as MLH does for example.

**Comment by mooskagh** [comment]
I don't think it's expected, we should watch and think about a fix. MLH will likely help in endgames, but for midgame fortresses some debugging is needed.
As you can see for earlier nets it was less of a problem, and also a0 seemingly didn't have this problem at all.

**Comment by mooskagh** [comment]
Actually, I think it makes sense to split this into two issues:
- Shuffling in midgame fortresses.
- Taking long to convert won games.

It seems they have the same root cause (poor policy), but many people consider them different.

**Comment by Mardak** [comment]
Looking more closely at the search behavior when changing the rule50ply for various positions, the network policies do reflect the network's position WDL value. E.g., using ttl-mlh-added 384x30-2-swa-30000.pb and looking at the highest prior move and the pawn move from the first position above:
![c3 move](https://user-images.githubusercontent.com/438537/80036642-ff3f5680-84a6-11ea-9dd6-e36169639b1d.png)
```
go nodes 1000 searchmoves f5e3
go nodes 2000 searchmoves c3c4

position fen 8/3k3p/1rrp1p1P/3RpNp1/p3P1P1/PnP2P2/KP6/3R4 w - - 0
info c3c4 N:    1000 (P:  3.02%) (WL:  0.59994) (D: 0.238) (M: 85.3)
info f5e3 N:    1000 (P: 23.24%) (WL:  0.87349) (D: 0.074) (M: 79.3)

position fen 8/3k3p/1rrp1p1P/3RpNp1/p3P1P1/PnP2P2/KP6/3R4 w - - 50
info c3c4 N:    1000 (P:  4.80%) (WL:  0.60310) (D: 0.237) (M: 85.0)
info f5e3 N:    1000 (P: 20.00%) (WL:  0.79350) (D: 0.129) (M: 84.9)

position fen 8/3k3p/1rrp1p1P/3RpNp1/p3P1P1/PnP2P2/KP6/3R4 w - - 95
info c3c4 N:    1000 (P: 11.13%) (WL:  0.59668) (D: 0.242) (M: 85.9)
info f5e3 N:    1000 (P: 13.24%) (WL:  0.37139) (D: 0.540) (M: 66.6)
```
Notice how the c4 pawn move policy increases from 3% to 11% while WDL is pretty consistent (as it's a zeroing move). And the highest prior move keeps decreasing reflecting the network's more drawish WDL value.

I suppose is the problem more that the WDL head is too optimistic and only decides to push the pawn when the zeroing move looks less drawish than shuffling into rule50 draw?

**Comment by Naphthalin** [comment]
As there haven't been reported similar issues with more recent networks, I'm closing this as stale.
