### ISSUE TITLE
Newest version of Nibbler doesn't work with newest version of Leela - OUT of SYNC

### ISSUE THREAD

**Issue by MadMike1234** [LeelaChessZero/lc0#1249]
V0.25 with Nibbler v1.2.4
Nibbler working fine with Stockfish but with any leela doesnt work anymore. I used CUDA version.

It was working 0.25 rc1 with nibbler 1.1.7 but I deleted because I wannted newest version and after that no any combination working.. I tried lot of different leelas nibblers but all the time the same "OUT of SYNC"
I have Nvidia 750 .. i7 16GB.. Windows 7 x64

And yes, leela benchmark working well...

Many thanks in advance!

**Comment by fohristiwhirl** [comment]
Hi - can you make an issue on the Nibbler repo, which is here:

https://github.com/fohristiwhirl/nibbler

**Comment by MadMike1234** [comment]
Hmm I am not sure where is problem because Nibbler work with Stockfish and on the other hand Leela benchmark working well. Also, I cant add Leela under Fritz, maybe that is connected. But Ill put question there as well. Thanks!

**Comment by fohristiwhirl** [comment]
Hi - I opened an issue for you at https://github.com/fohristiwhirl/nibbler/issues/87

If possible can you provide a screenshot there? Thanks.

**Comment by MadMike1234** [comment]
![Leela 2 -Nibbler](https://user-images.githubusercontent.com/64505251/80608886-bf90e580-8a37-11ea-9a1b-45780e431da8.png)
![Leela 1 Nibbler](https://user-images.githubusercontent.com/64505251/80608890-c0c21280-8a37-11ea-809f-2261700c6fc5.png)
![Stockfish_22-Nibbler](https://user-images.githubusercontent.com/64505251/80608894-c15aa900-8a37-11ea-8c8c-4364bf790027.png)

**Comment by MadMike1234** [comment]
Bottom one is with Stockfish, in the middle Leela just loaded and top one "OUT of SYNC". And here is also from Fritz 
![FRITZ UCI](https://user-images.githubusercontent.com/64505251/80609222-231b1300-8a38-11ea-9492-f9f26825bc70.png)

**Comment by Naphthalin** [comment]
I get this behavior basically whenever I start an analysis, halt it, and switch engines. Going a move back or forth, starting an analysis, and then going back to the original position sometimes increases the `Out of Sync` counter, but starts working soon.

Anyway, this isn't a Lc0 issue, but a Nibbler one, so closing here.
