### ISSUE TITLE
Lc0 aborts while searching. [MacOS, OpenCL]

### ISSUE THREAD

**Issue by Rejwana** [LeelaChessZero/lc0#1253]
I am trying to run lc0 on MacBook Air 2020. 
But the search aborts after certain depth:

>|   _ | |
|_ |_ |_| v0.24.1+git.dirty built Apr 20 2020
go nodes 100
Found pb network file: /Users/rejwanahaque/Downloads/Chess_Engins/Lc0/Lc0_negative/20ef76987442ff4e25cb456987ddb827e6561393d377ae931f7352cdfdf31d60
Creating backend [opencl]...
OpenCL, maximum batch size set to 16.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 (Feb 29 2020 00:40:07)
Platform profile: FULL_PROFILE
Platform name:    Apple
Platform vendor:  Apple
Device ID:      0
Device name:    Intel(R) Core(TM) i7-1060NG7 CPU @ 1.20GHz
Device type:    CPU
Device vendor:  Intel
Device driver:  1.1
Device speed:   1200 MHZ
Device cores:   8 CU
Device score:   512
Device ID:      1
Device name:    Intel(R) Iris(TM) Plus Graphics
Device type:    GPU
Device vendor:  Intel Inc.
Device driver:  1.2(Mar 15 2020 21:29:52)
Device speed:   1100 MHZ
Device cores:   64 CU
Device score:   612
Selected platform: Apple
Selected device: Intel(R) Iris(TM) Plus Graphics
with OpenCL 1.2 capability.
Started OpenCL SGEMM tuner with batch size 16.
Will try 578 valid configurations.
(1/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 29761.2 us (28.2 GFLOPS)
(2/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 13259.5 us (63.3 GFLOPS)
(4/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 11032.5 us (76.0 GFLOPS)
(5/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 7937.9 us (105.7 GFLOPS)
(8/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 6588.7 us (127.3 GFLOPS)
(15/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 6134.9 us (136.7 GFLOPS)
(18/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 4737.9 us (177.1 GFLOPS)
(32/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=16 NDIMC=16 NWG=64 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 4287.6 us (195.7 GFLOPS)
(72/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 3481.3 us (241.0 GFLOPS)
(294/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=1 VWN=1 3165.1 us (265.0 GFLOPS)
(295/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=64 NDIMB=8 NDIMC=8 NWG=32 SA=1 SB=1 STRM=0 STRN=0 VWM=1 VWN=1 2826.9 us (296.7 GFLOPS)
(297/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=1 VWN=1 2731.3 us (307.1 GFLOPS)
(307/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=1 VWN=1 2413.1 us (347.6 GFLOPS)
(518/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=64 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 2354.9 us (356.2 GFLOPS)
Wavefront/Warp size: 8
Max workgroup size: 256
Max workgroup dimensions: 256 256 256
info depth 1 seldepth 2 time 152370 nodes 21 score cp 1 nps 101 tbhits 0 pv a2a3 a7a6
info depth 2 seldepth 3 time 152629 nodes 22 score cp 146 nps 47 tbhits 0 pv b1c3 c7c5 a2a3
info depth 2 seldepth 3 time 157630 nodes 22 score cp 146 nps 4 tbhits 0 pv b1c3 c7c5 a2a3 c5c4
zsh: abort      

The problem seems to be solved by #516 
Still I get this error.

**Comment by Naphthalin** [comment]
I'm not familiar with the behavior on mac in general; did you try other backends, especially the CPU backends? You will see all possible ones when displaying `lc0 --help` and look for the `--backend` option. You might need to adapt the build script to build the backends relevant for you.

**Comment by Rejwana** [comment]
I have tested on two different machines both having same version of OS (macOS Catalina): Mackbook pro(2012), Macbook Air(2020) . It worked with  `--backend=blas` on newer Macbook Air(2020) while `opencl` works for older Mackbook pro(2012). I am not sure is it OS issue or not.

Thanks @Naphthalin for you response.

**Comment by borg323** [comment]
This is just a guess, but can you do the following change and recompile - it won't fix it but may provide some insight on what goes wrong. In file `src/neural/opencl/OpenCL.cc`, right after line 360 (`m_program.build(args.c_str());`) insert the following line:
```
CERR << m_program.getBuildInfo<CL_PROGRAM_BUILD_LOG>(m_device);
```

**Comment by Mardak** [comment]
I've found OpenCL 1.2 drivers on macOS with Intel GPUs have been quite buggy (sometimes requiring a hard reboot…), e.g., https://github.com/leela-zero/leela-zero/issues/1677
```
./lc0 --backend-opts=gpu=1

Device ID:      1
Device name:    Intel(R) UHD Graphics 630
Device type:    GPU
Device vendor:  Intel Inc.
Device driver:  1.2(Jan 17 2020 22:29:16)
Device speed:   1200 MHZ
Device cores:   24 CU
Device score:   612

go infinite
info depth 3 seldepth 6 time 189142 nodes 360 score cp 35 nps 21 tbhits 0 pv c2c4 h7h5 d1b3 h5h4 g2g4
Abort trap: 6
```
Another run with `CERR << m_program.getBuildInfo<CL_PROGRAM_BUILD_LOG>(m_device);`:
```
<program source>:129:6: warning: no previous prototype for function '__in_transform_eq'
void __in_transform_eq(float x[4][4], __global float * restrict V, int offset, int CPpad) {
     ^
<program source>:215:6: warning: no previous prototype for function '__out_transform_eq'
void __out_transform_eq(__global const float * restrict M, float o[4],
     ^
<program source>:219:13: warning: unused variable 'H'
  const int H = 8;
            ^
<program source>:589:19: warning: no previous prototype for function 'GetGroupID1'
  INLINE_FUNC int GetGroupID1() { return get_group_id(1); }
                  ^
<program source>:590:19: warning: no previous prototype for function 'GetGroupID0'
  INLINE_FUNC int GetGroupID0() { return get_group_id(0); }
                  ^
<program source>:694:19: warning: no previous prototype for function 'InitAccRegisters'
INLINE_FUNC realM InitAccRegisters() {
                  ^
<program source>:741:18: warning: no previous prototype for function 'GlobalToLocalA'
INLINE_FUNC void GlobalToLocalA(const __global realM* restrict agm, LOCAL_PTR realM* alm,
                 ^
<program source>:771:18: warning: no previous prototype for function 'GlobalToLocalB'
INLINE_FUNC void GlobalToLocalB(const __global realN* restrict bgm, LOCAL_PTR realN* blm,
                 ^
<program source>:845:19: warning: no previous prototype for function 'LocalToPrivateA'
INLINE_FUNC realM LocalToPrivateA(LOCAL_PTR realM* alm, const int _mi, const int kg) {
                  ^
<program source>:857:19: warning: no previous prototype for function 'LocalToPrivateB'
INLINE_FUNC realN LocalToPrivateB(LOCAL_PTR realN* blm, const int _ni, const int kg) {
                  ^
<program source>:875:19: warning: no previous prototype for function 'MultiplyAddVector'
INLINE_FUNC realM MultiplyAddVector(realM cvec, const realM avec, const real bval) {
                  ^
<program source>:923:18: warning: no previous prototype for function 'StoreResults'
INLINE_FUNC void StoreResults(__global realM* cgm, realM cpm[NWI*MWI/VWM], const int kSizeM) {
                 ^
<program source>:956:18: warning: no previous prototype for function 'XgemmBody'
INLINE_FUNC void XgemmBody(const int kSizeM, const int kSizeN, const int kSizeK,
                 ^
<program source>:1168:18: warning: no previous prototype for function 'LoadMatrixA'
INLINE_FUNC real LoadMatrixA(const __global real* restrict agm, const int x, const int y,
                 ^
<program source>:1185:18: warning: initializing '__global real *' (aka '__global float *') with an expression of type 'const __global real *' (aka 'const __global float *') discards qualifiers
  __global real* xgm=x + batch*n;
                 ^   ~~~~~~~~~~~

…
info depth 3 seldepth 7 time 2072 nodes 263 score cp -17 nps 151 tbhits 0 pv f2f3 d7d5 e2e3 c7c6 d2d4
Segmentation fault: 11
```

**Comment by Mardak** [comment]
And just testing with updating to macOS 10.15.4 (with updated drivers from `1.2(Jan 17 2020 22:29:16)` to `1.2(Mar 15 2020 21:29:48)`):

```
Device ID:      1
Device name:    Intel(R) UHD Graphics 630
Device type:    GPU
Device vendor:  Intel Inc.
Device driver:  1.2(Mar 15 2020 21:29:48)
Device speed:   1200 MHZ
Device cores:   24 CU
Device score:   612

info depth 4 seldepth 6 time 1571 nodes 84 score cp 32 nps 108 tbhits 0 pv e2e4 e7e5 b1c3 d7d5 a2a3
info depth 4 seldepth 6 time 6624 nodes 97 score cp 29 nps 16 tbhits 0 pv e2e4 e7e5 b1c3 d7d5 a2a3
info depth 4 seldepth 6 time 11642 nodes 97 score cp 29 nps 8 tbhits 0 pv e2e4 e7e5 b1c3 d7d5 a2a3
info depth 4 seldepth 6 time 16685 nodes 97 score cp 29 nps 6 tbhits 0 pv e2e4 e7e5 b1c3 d7d5 a2a3
Abort trap: 6


info depth 5 seldepth 9 time 2328 nodes 244 score cp -33 nps 118 tbhits 0 pv e2e4 c7c6 b1c3 d7d5 a1b1 d8c7 f2f3
info depth 5 seldepth 9 time 7353 nodes 247 score cp -33 nps 34 tbhits 0 pv e2e4 c7c6 b1c3 d7d5 a1b1 d8c7 f2f3
info depth 5 seldepth 9 time 12443 nodes 247 score cp -33 nps 20 tbhits 0 pv e2e4 c7c6 b1c3 d7d5 a1b1 d8c7 f2f3
info depth 5 seldepth 9 time 17522 nodes 247 score cp -33 nps 14 tbhits 0 pv e2e4 c7c6 b1c3 d7d5 a1b1 d8c7 f2f3
Abort trap: 6
```
