### ISSUE TITLE
Leela's end game

### ISSUE THREAD

**Issue by khuttur** [LeelaChessZero/lc0#1254]
Hi,
It seems that lc0 has a bug in endgame playing on android device. Lc0 plays very poorly endgame. It seems that she has no knowledge of endgame!
Please solve this bug.
See this,
http://s000.tinyupload.com/?file_id=74172443691161865248

**Comment by fohristiwhirl** [comment]
The problem is not that Leela doesn't know how to win, but that Leela has nothing making her prefer short victories over long ones.

**Comment by Naphthalin** [comment]
Marking this as a duplicate of the more elaborate #1229.
