### ISSUE TITLE
lc0-v0.25.1: Dx12 backend cannot be validated

### ISSUE THREAD

**Issue by Mbr18** [LeelaChessZero/lc0#1257]
lc0-v0.25.1-windows10-gpu-dx12
HD7770(R7 200)/Q9400
Uptodate Windows 10 with latest AMD Adrenalin 20.4.2 driver

-Client.exe quits with the following error:
2020/04/30 22:40:22 lc0_main.go:319: Dx12 backend cannot be validated
-Same PC passes the check_dx.bat
See attachment for the log file.

[Logfile 300420.txt](https://github.com/LeelaChessZero/lc0/files/4561380/Logfile.300420.txt)

**Comment by borg323** [comment]
Can you replace client.exe with <https://ci.appveyor.com/api/buildjobs/x6sq7hs8lrj23dly/artifacts/client.exe> and try again?

**Comment by Naphthalin** [comment]
Can you please run Win+R, `dxdiag` and tell us the exact windows version? Should be something like 10.0.18363 or so; if the windows version is too old, the dx12 backend won't work despite newest AMD drivers.

**Comment by Mbr18** [comment]
> Can you replace client.exe with https://ci.appveyor.com/api/buildjobs/x6sq7hs8lrj23dly/artifacts/client.exe and try again?

This client.exe works stable for the selfplay games. See attachment for logfile.
But compared with OpenCL version (v0.25.1) the DX12 version slows the whole PC down which make Windows almost unusable. See attachment for the PC details. 

> Can you please run Win+R, `dxdiag` and tell us the exact windows version? Should be something like 10.0.18363 or so; if the windows version is too old, the dx12 backend won't work despite newest AMD drivers.

Windows 10 Pro 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
I consider this issue as solved!

[Dxdiag 020520.txt](https://github.com/LeelaChessZero/lc0/files/4566477/Dxdiag.020520.txt)
[Logfile new client 020520.txt](https://github.com/LeelaChessZero/lc0/files/4566478/Logfile.new.client.020520.txt)

**Comment by Naphthalin** [comment]
I just wanted to report that I get the same `Dx12 backend cannot be validated` error when contributing, and that AppVeyor client version works for me as well.

Windows 10 Pro 10.0.18363, latest AMD driver (26.20.15029.27016), AMD RX Vega 56

**Comment by CalKK8** [comment]
> But compared with OpenCL version (v0.25.1) the DX12 version slows the whole PC down which make Windows almost unusable. See attachment for the PC details.
**Is there a way to use Lc0 with DX12 without making the PC slow down?**

**Comment by borg323** [comment]
> Is there a way to use Lc0 with DX12 without making the PC slow down?

Not exactly, but you can try <https://ci.appveyor.com/api/buildjobs/8cut4qxitct4lug5/artifacts/build%2Flc0.exe>. This is not usable with the client (development version) but includes the `-nps-limit` option that allows you to specify an upper limit for the nodes calculated per second. Setting this at a value lower than the peak will keep the gpu idle for some portion of the time.

**Comment by CalKK8** [comment]
@borg323 Thank you. With future versions of Lc0 to come, will DX12 lag become less?

**Comment by Naphthalin** [comment]
This heavily depends on your hardware and is not a problem with the dx12 backend. In your case, an AMD RX 560X in a laptop will inevitably produce too much heat at full load, so the hardware throttling is inevitable.
