### ISSUE TITLE
Lc0 v0.25.0 DX12 uses integrated instead of dedicated mobile GPU

### ISSUE THREAD

**Issue by CalKK8** [LeelaChessZero/lc0#1264]
Computer slows down and lags when using Lc0 v0.25.0 DX12

I'm running Lc0 on lichess.org, and when it plays, my computer is very slow and glitchy.

AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 2.00 GHz
* 2 GPUs. 1. AMD Radeon (TM) Vega 8 Graphics (4.5 GB) 2. Radeon RX 560X Series (7.5 GB)
* 8 GB RAM, 6.90 GB usable
Other info for GPUs:
```

GPU 0

	Radeon RX 560X Series

	Driver version:	26.20.15019.19000
	Driver date:	2/28/2020
	DirectX version:	12 (FL 12.0)
	Physical location:	PCI bus 1, device 0, function 0

	Utilization	0%
	Dedicated GPU memory	0.0/4.0 GB
	Shared GPU memory	0.0/3.5 GB
	GPU Memory	0.0/7.5 GB

```
```
GPU 1

	AMD Radeon(TM) Vega 8 Graphics

	Driver version:	26.20.15019.19000
	Driver date:	2/28/2020
	DirectX version:	12 (FL 12.1)
	Physical location:	PCI bus 4, device 0, function 0

	Utilization	5%
	Dedicated GPU memory	0.3/1.0 GB
	Shared GPU memory	0.1/3.5 GB
	GPU Memory	0.3/4.5 GB
```

**Comment by Naphthalin** [comment]
As I already explained to you in https://github.com/LeelaChessZero/lc0/issues/1257#issuecomment-623112386, this is to be somehow expected for notebook hardware, which can only deal with so much heat.

First thing to check would be that Lc0 is actually using the dedicated GPU and not the (surprisingly powerful) integrated GPU. Can you please start Lc0 and provide a screenshot of the Task manager under Performance/GPU?

Also please note that the issues are intended for problems with the binary; for getting help on your setup, please join the discord and ask in #help.

**Comment by CalKK8** [comment]
@Naphthalin Do you want a screenshot of Lc0 using RX 560X or Radeon Vega 8 Graphics. I assume that Vega 8 is integrated because I once tried uninstalling it but it wouldn't budge.

**Comment by Naphthalin** [comment]
A screenshot where we could see whether it uses the integrated or the dedicated GPU would be helpful -- so start Lc0 search, and make a screenshot of both GPU's tabs in the task manager.

**Comment by CalKK8** [comment]
Should I do `UCI`, `Selfplay`, `Benchmark`, or `Backendbench`?

**Comment by CalKK8** [comment]
![AMD Radeon(TM) Vega 8 Graphics](https://user-images.githubusercontent.com/54694286/81236072-64786900-8fca-11ea-83b5-81f0121553c9.png)
![Radeon RX 560X Series](https://user-images.githubusercontent.com/54694286/81236083-69d5b380-8fca-11ea-98cb-b362150290c4.png)

**Comment by CalKK8** [comment]
When I use Vega 8, my computer glitches.

**Comment by Naphthalin** [comment]
Yeah, that's what I expected. 1) it overheats the CPU and 2) the integrated GPU seems to fill your RAM
Can you try `lc0 --backend-opts=(gpu=1)` with different numbers 0, 1, 2 for GPU and see whether one of them uses your dedicated GPU?

Also, once #685 is merged this could be a viable solution for your problem; but we definitely should figure out how to use the dedicated GPU by default.

**Comment by borg323** [comment]
The order of the gpus depends on what is returned by windows' [IDXGIFactory::EnumAdapters](https://docs.microsoft.com/en-gb/windows/win32/api/dxgi/nf-dxgi-idxgifactory-enumadapters) which "first returns the adapter with the output on which the desktop primary is displayed. This adapter corresponds with an index of zero."

**Comment by mooskagh** [comment]
It should be `--backend-opts=gpu=1` not `--backend-opts=(gpu=1)`, i know it's confusing. :)

**Comment by CalKK8** [comment]
When I run `./lc0.exe backendbench --backend-opts=gpu=0`, Lc0 uses the **integrated** GPU.
When I run `./lc0.exe backendbench --backend-opts=gpu=1`, Lc0 uses the **dedicated** GPU.

**Comment by Naphthalin** [comment]
Exactly the same, just leave out the `backendbench`. Best is probably to create a `lc0.config` which contains the `--backend-opts=gpu=1`.

**Comment by CalKK8** [comment]
@Naphthalin No, my computer does not lag at all when using the dedicated GPU. To create a config file, I just create a text document, type `backend-opts=gpu=1`, and rename it to `lc0.config.txt`?

**Comment by mooskagh** [comment]
Not `lc0.config.txt` but just `lc0.config`.

**Comment by CalKK8** [comment]
Ok.

**Comment by mooskagh** [comment]
yes

**Comment by CalKK8** [comment]
Ok, thanks. It worked!
