### ISSUE TITLE
Enhancement: Show Draw as 0.00

### ISSUE THREAD

**Issue by SquarishRectangle** [LeelaChessZero/lc0#1269]
Most other engines will show a drawn or mostly drawn position as 0.00 but Lc0 doesn't. Maybe when converting WDL to CP if the Draw rate is above a threshold like 90% show CP as 0.00?

**Comment by mooskagh** [comment]
Lc0 does show 0.0 when it's a draw, if it doesn't show 0.0, that means that it's not that sure that it's a draw.

It's true that it would be nice to improve detection of a draw, but outputting 0.00 in "likely draw" situations brings no benefit.

Lc0 was actually praised by several top GMs for not showing 0.00 in situations where SF shows 0.00 ("it may end up in a draw in the end of all variants, but we still want to know which side has more chances").

I'm closing this issue for not as not actionable, but feel free to reopen if you disagree.
If you still think it's a good feature, I'd suggest to join our Discord chat at http://lc0.org/chat, and starting a discussion there to see whether it has some support.
