### ISSUE TITLE
Crash report on Discord

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#1270]
Crash dump: http://www.alex-h.de/lc0-crashdump.zip
Discussion: https://discord.com/channels/425419482568196106/427066771627966466/707579948214517792

Cudnn version v0.25.1, Windows.

**Comment by mooskagh** [comment]
From the crash dump it's clear that it's `lczero::Exception` in the worker thread, but the text of the exception is in the memory region not stored in the dump.

![image](https://user-images.githubusercontent.com/11266455/81204269-4d854700-8fc9-11ea-9549-af28b0b9f35e.png)

Most likely it's CUDA error, at least it's not something like segmentation fault.

**Comment by Mardak** [comment]
https://discord.com/channels/425419482568196106/427066771627966466/707659373387972638
> i got that leela crash again i mentioned earlier today
> it shows in the log file, leela ran out of memory

**Comment by mooskagh** [comment]
Btw he uses `custom_winograd=false`, without it it doesn't even start.
He has 2GB VRAM, and this only happens on larger nets.

Unless @ankan-ban has other ideas, I think we can close it as working as intended.

**Comment by ankan-ban** [comment]
setting max_batch parameter to some smaller value (like 256) can probably help so save some memory. 
Do we know what net they are using? I think 384x30 without custom_winograd optimization should likely fit in 2 GB (unless they are also running other apps/games in background). 512x40 would be stretching it too far.

**Comment by mooskagh** [comment]
As per Discord message (https://discord.com/channels/425419482568196106/427066771627966466/708627196415049749),
he ran two copies of Lc0, with 384x30-t60-3010 and with T40.

**Comment by mooskagh** [comment]
Most likely was caused by running out of VRAM, but happened too long ago to do something about it now.
