### ISSUE TITLE
go movetime is wrong

### ISSUE THREAD

**Issue by fohristiwhirl** [LeelaChessZero/lc0#1271]
```
position startpos
go infinite
stop

(wait a minute)

go movetime 60000
```

You'll find that the search stops instantly. `go movetime` seems to think the search began when the position was entered, but this isn't so. The timer should be from when `go` was sent.

(There might be an implicit assumption here that the controller is a match runner, but normal GUIs may well send `go movetime` commands as well. I was thinking of adding such. In the GUI case, there's no particular reason to expect the `go` to come immediately after a `position` command.)

**Comment by fohristiwhirl** [comment]
Actually, maybe I've not understood the UCI specs correctly, I guess they say:

`Before the engine is asked to search on a position, there will always be a position command to tell the engine about the current position.`

So Lc0 may be right after all.

**Comment by mooskagh** [comment]
Since v0.25, we have `--strict-uci-timing` flag which makes timer start from `go` command.
It was originally done from `position` command because some GUIs (e.g. arena) do it that way, making Lc0 lose on time.
