### ISSUE TITLE
T60: Serious tactical blunder in CCC ECO megamatch games 1566, 1562, 1769

### ISSUE THREAD

**Issue by Naphthalin** [LeelaChessZero/lc0#1296]
<https://www.chess.com/computer-chess-championship#event=eco-megamatch&game=1566>

The serious tactical blunder happens at move 22, where taking the knight on `a5` is a poisoned sacrifice, leading to a (semi-?) forced mate. T60 (roughly 63491 judging from the time) keeps a positive eval for 4 more moves, and only starts to realize the loss after `26. ... Rd4` where SF already displays `-M20`.

Analyzing the position at home shows:

- the policy head thinks the continuation there is `26. ... Rgd4 27. a5 R8d5 28. axb6 Ba4+ 29. Rxa4`. After 330k nodes searched in that position the evaluation becomes slightly negative, and only after 630k nodes it finds the deciding move `27. ... R4d5`. None of these moves have a policy lower than 10%
- backwards analysis until evaluation becomes negative: 700k nodes before `26. a4`, 800k nodes before `25. Ne5`, (`24. Kc6` is forced), (`23. Ka6` is a proven mate at 100k nodes)
- it doesn't explore `23. ... Bd3+` (`44.25%`!!) enough and expects `23. ... Bd7+` (`7.12%`). I stopped the search at 5M nodes because `23. ... Bd3+ only gets to 260k nodes despite being only 0.09cp behind the move favored by the policy head; forcing `23. ... Bd3+` shows that it would have needed 650k nodes to become the move with best eval, so ~25M nodes.
- running the position before `22. Kxa5`, around 1.4M nodes the correct `22. Ka3` gets first place, and starts to pull away at 2M nodes. So it seems that with some luck and 3x the nodes, Leela wouldn't have played `22. Kxa5`.

Repeating the same analysis with 702180 shows: 450k nodes to find `26. ... Rgd4`, 350k nodes to display a negative eval after `26. a4`, 400k nodes to neg `25. ... Bc2`, 1.2M nodes to neg `25. Ne5`, 300k nodes to neg `24. ... O-O-O`, 530k nodes to neg `24. Kc6`, 6M nodes to find `23. ... Bd3+`, 10.5M nodes to neg on `23. Kb5`, and finally 3.7M nodes to play `22. Ka3` instead of the losing `22. Kxa5` as the evals fall below 0.00 (it obviously never displays a strong negative eval for `22. Kxa5`, as the search doesn't focus exploring it, keeping it at 1.9M nodes)

Note that the number of nodes sometimes decreases; I blame history-dependent luck on evals and policies. 

PGN of the game:
```
[Event "ECO MegaMatch! (1|1)"]
[Site "?"]
[Date "2020.05.13"]
[Round "1"]
[White "Lc0-dev"]
[Black "Stockfish"]
[Result "0-1"]
[ECO "C15"]
[GameDuration "00:02:53"]
[GameEndTime "2020-05-13T06:48:11.299 PDT"]
[GameStartTime "2020-05-13T06:45:18.129 PDT"]
[Opening "French"]
[PlyCount "88"]
[TimeControl "60+1"]
[Variation "Winawer, Kondratiyev Variation"]

1. e4 e6 2. d4 d5 3. Nc3 Bb4 4. Bd3 c5 5. exd5 Qxd5 6. Bd2 Bxc3 7. Bxc3 cxd4 8.
Bxd4 e5 9. Bc3 Nf6 10. Nf3 e4 11. Bxf6 exd3 12. Bxg7 Rg8 13. Be5 Qe4+ 14. Kd2
dxc2 15. Qxc2 Qxc2+ 16. Kxc2 Nc6 17. Bg3 Bf5+ 18. Kb3 Na5+ 19. Ka3 Nc4+ 20. Kb3
Na5+ 21. Kb4 Rg4+ 22. Kxa5 b6+ 23. Kb5 Bd3+ 24. Kc6 O-O-O 25. Ne5 Bc2 26. a4
Rgd4 27. a5 R4d5 28. Nd7 R8xd7 29. axb6 Be4 30. Rhe1 R5d6+ 31. Kc5 Rc6+ 32. Kb4
Rxb6+ 33. Ka5 Rd5+ 34. Ka4 Rd4+ 35. Ka5 Bd3 36. Rec1+ Kd7 37. Rc7+ Kd8 38. Rc4
Bxc4 39. Ra3 Bf1 40. Bc7+ Kxc7 41. Rc3+ Kd7 42. Rc4 Bxc4 43. f3 Bd3 44. b3 Ra6#
0-1
```

**Comment by Mardak** [comment]
Looks like the network was confused about the position value thinking it was really good for white then really bad for white then thinking it's drawn before finally realizing it's really bad for white. Search was probably also getting confusing signals considering both move 29 the net thinks each side is losing after high prior moves.

Here's the prior for the played move as well as the Q of the position (not V of the played move).
```
63494  26.0 a2a4  (P:  6.25%) (Q:  0.45590)       g4d4  (P: 18.73%) (Q: -0.33685) 
63494  27.0 a4a5  (P:  3.77%) (Q:  0.70015)       d4d5  (P: 10.42%) (Q:  0.16046) 
63494  28.0 e5d7  (P: 18.59%) (Q: -0.31897)       d8d7  (P: 33.30%) (Q: -0.14475) 
63494  29.0 a5b6  (P: 68.26%) (Q: -0.64807)       c2e4  (P: 40.72%) (Q: -0.66353) 
63494  30.0 h1e1  (P:  5.90%) (Q: -0.80411)       d5d6  (P:  1.53%) (Q:  0.30786) 
63494  31.0 c6c5  (P: 66.46%) (Q:  0.77734)       d6c6  (P: 40.36%) (Q: -0.05111) 
63494  32.0 c5b4  (P: 81.15%) (Q: -0.00146)       c6b6  (P: 88.31%) (Q:  0.21205) 
63494  33.0 b4a5  (P: 13.79%) (Q:  0.02131)       d7d5  (P: 54.42%) (Q:  0.23504) 
63494  34.0 a5a4  (P:100.00%) (Q: -0.63033)       d5d4  (P: 19.50%) (Q:  0.56942) 
63494  35.0 a4a5  (P: 54.98%) (Q: -0.29549)       e4d3  (P:  7.67%) (Q:  0.37524) 
63494  36.0 e1c1  (P: 25.84%) (Q: -0.80320)       c8d7  (P: 37.13%) (Q:  0.03791) 

702180  26.0 a2a4  (P:  0.63%) (Q:  0.58207)       g4d4  (P: 13.56%) (Q: -0.51628) 
702180  27.0 a4a5  (P:  3.41%) (Q:  0.22856)       d4d5  (P:  4.67%) (Q:  0.66589) 
702180  28.0 e5d7  (P: 10.87%) (Q:  0.07398)       d8d7  (P: 21.20%) (Q: -0.09903) 
702180  29.0 a5b6  (P: 59.20%) (Q: -0.15118)       c2e4  (P: 63.84%) (Q: -0.48465) 
702180  30.0 h1e1  (P: 11.59%) (Q: -0.03004)       d5d6  (P:  2.76%) (Q:  0.10165) 
702180  31.0 c6c5  (P: 45.58%) (Q:  0.32566)       d6c6  (P: 36.12%) (Q: -0.09878) 
702180  32.0 c5b4  (P: 79.66%) (Q: -0.07858)       c6b6  (P: 70.58%) (Q: -0.02926) 
702180  33.0 b4a5  (P: 10.29%) (Q:  0.03063)       d7d5  (P: 56.13%) (Q:  0.10529) 
702180  34.0 a5a4  (P:100.00%) (Q: -0.31674)       d5d4  (P: 24.90%) (Q:  0.34058) 
702180  35.0 a4a5  (P: 58.57%) (Q: -0.12916)       e4d3  (P:  7.67%) (Q:  0.38896) 
702180  36.0 e1c1  (P: 38.67%) (Q: -0.70860)       c8d7  (P: 16.06%) (Q:  0.15901) 
```

**Comment by Naphthalin** [comment]
Game 1562 had a similar issue; `26. Ka1` lost the game, as the T60 network failed to realize how good `26. ... b3` was as a continuation in time. I will post a more detailed analysis tomorrow.

**Comment by Naphthalin** [comment]
Game 1769 is a particularly bad case of misevaluation; T60 misses `21. Qd1` and still displays -0.07 before that while SF is already above +5.

In the position before `21. Qd1`, it takes the latest T60 net 63500 
This means that despite getting the correct PV for moves 17-20, it takes 35k nodes on `21. Qd1` to realize that this is the much better variation than `21. Qa5` which unfortunately for our search slowly starts with climbing evals to +0.5 at 300k nodes, making `21. Qd1` stuck at 1.3k nodes for a very long time. At 1M nodes, `21. Qd1` is still at 1.3k nodes, while `21. Qa5` is at +1.2. However, this apparently is the same general idea, except for a black pawn at b6 instead of b7, freeing the black bishop. It needs approx. 70k nodes for `21. Qd1` to display +1.3, 100k for +1.5, 190k for +2.0.

This leads to a low eval from farer away: Before `18. ... c6`, it takes 200k nodes to even display +0.05, where SF already is at +2.8, and the correct line isn't found for the reasons above. Someone with SF would have to check this, but this basically leads to T60 missing nearly everything about the position; however, the nodes per move are extremely low (around 170k max), so this might more be a timing issue (?)

Meanwhile, checking with 702180 shows that it nearly instantly finds the right line from `18. Qb5+` and therefore plays `18 ... Kf7` instead of `18 ... c6` (even though it's probably too late at this point anyway). The played `18. ... c6` is evaluated as +1.0 at 80k nodes, +1.5 at 300k nodes, +2.0 at 790k nodes, and the correct PV is given, despite T60 having double (!) the policy on `21. Qd1`. So this is once more an example of T70 having superior evals even at the same number of nodes.

PGN: 
```
[Event "ECO MegaMatch! (1|1)"]
[Site "?"]
[Date "2020.05.14"]
[Round "1"]
[White "Stockfish"]
[Black "Lc0-dev"]
[Result "1-0"]

1. e4 e5 2. f4 Qh4+ 3. g3 Qe7 4. Nc3 exf4 5. Qe2 fxg3 6. hxg3 d6 7. d4 Nc6
8. Nd5 Qd8 9. Be3 Nce7 10. Nc3 Nf6 11. O-O-O d5 12. Bg5 Nxe4 13. Nxe4 dxe4
14. d5 f6 15. Bf4 g5 16. d6 gxf4 17. dxe7 Qxe7 18. Qb5+ c6 19. Qh5+ Qf7 20. Rd8+
Ke7 21. Qd1 Qe6 22. Ne2 f5 23. Nxf4 Qf6 24. c3 h5 25. Kb1 h4 26. Bc4 h3 27. Qd2
e3 28. Re1 Be6 29. Qd6+ Kf7 30. Qd7+ Qe7 31. Bxe6+ Kf6 32. Qd4+ Kg5 33. Qxh8 Bh6
34. Rxa8 Kg4 35. Rg8+ Qg5 36. Qxh6 Qxg8 37. Qxh3+ Kf3 38. Rf1+ Ke4 39. Qxf5# 1-0
```

**Comment by Naphthalin** [comment]
Game 1793 again a single move blunder, `61. ... Rc4` loses the game instantly.

`61. ... Rc4` was played at 76k nodes (so slightly lower than the moves before it) with an eval of -0.27; ~~however I can't reproduce this eval with 63500~~ when playing through the game, `61. ... Rc4` has 16.64% policy (highest policy move), and maybe due to the higher batch size than I am using it takes a bit longer. However, it still never is the top move, but instead the correct `61. ... Rd8`. After playing the wrong `61. ... Rc4`, it takes 33k nodes to have `62. Qd6` at +0.01, and at 70k nodes the eval starts to rise from +0.6; this means that we very likely had some bad luck with smart pruning here.
(at 100k nodes it crosses +1.0, at 170k nodes +1.5, at 280k +2.0)

702180 never prefers `61. ... Rc4` and takes ~2x the nodes to come to the same evals as 63500; 190k for +1.0, 460k for +1.5, but doesn't rise as high after that.

**Comment by Naphthalin** [comment]
Game 1799 again a single move blunder; `41. ... Qe6` loses due to missing the `42. Re2 Rh5 43. Bh2!!`, but it takes 63500 220k nodes in the position to see `43. Bh2` as favorable for white despite favoring the line for a brief moment at ~10k nodes. It takes 280k nodes before `42. Re2` starts to climb above +0.1; 550k for +0.5 and not rising further until 800k nodes where it switches to the variant `42. ... Nd5` also preferred by SF (but still evaluated as +1.7).

Before `43. ... Qe6` it initially prefers the holding `Qf1+` which is also the highest policy move, but switches to `43. ... Qe6` with some bad luck, evaluating both at 0.00 even at 1M nodes (800k to `Qf1+`, 200k to `Qe6`).

702180 recognizes `43. ... Qe6` as favorable for white immediately, giving the correct continuation and an eval of +0.20 at 4k nodes, and then "forgetting" the correct line again. as well, though always giving a positive eval for `Qe6` so never considering playing it. It takes 702180 approx. 3.2M nodes until `43. Bh2` is found as favorable for white (where it spent 40k nodes on the move) despite it being the highest policy move (which is in fact the same for 63500).

**Comment by Naphthalin** [comment]
Game 1829, single move blunder `43. ... Rxf5`. Leela's eval only changed to be in white's favor after `46. h4`.

I can't reproduce 63500 playing that move at the 170k nodes searched in CCC; for me, it switches to `43. ... Rf6` after 100k nodes, as the evaluation for `43. ... Rxf5` start to slowly rise in white's favor. However, T60 doesn't find `46. h4` but thinks that `46. Re1` also is favorable for white, giving it +1.0 at 500k nodes searched. It needs to spend 30k nodes on `h4` to evaluate it as +0.5, 130k for +1.0, 460k for +1.5 but it never reaches them due to `Re1` slowly climbing.

702180 recognizes `43. ... Rxf5` as favorable for white instantly, has it as equal for a very brief moment at 500k nodes, and then rises again, giving the correct continuation including `46. h4`. It instead wants to play `43. ... a5`, the move which is also recommended by SF. Policies for `h4` are comparable between the T60 and T70 nets while slightly in favor of 63500 (7.2% vs 5.7%).

**Comment by leedavid** [comment]
Is it necessary to add the checking extended treatment process?

**Comment by wakamex** [comment]
all 3 games can be found here http://s000.tinyupload.com/index.php?file_id=03577054094109394527

**Comment by Naphthalin** [comment]
Doesn't need to be an open issue, as there are no new T60 games. Still useful in archive.
