### ISSUE TITLE
Apk for android missing support of x86 cpu

### ISSUE THREAD

**Issue by spasski** [LeelaChessZero/lc0#1299]
The apk for android didn't run with Droidfish under my old Lenovo Tab S8.
Please compile Lc0 for x86 cpu and make it run under Android 4.4
You would make my day.

**Comment by lealgo** [comment]
Hi. I've just made a build for x86 but I don't have a device to test it. Maybe you could give it a try?

[lc0.zip](https://github.com/LeelaChessZero/lc0/files/4624326/lc0.zip)

1. Unzip this and copy the file `lc0` into the folder: `/DroidFish/uci` on your device. 
2. Copy the weighs file `591200` to the folder `/DroidFish/`
3. Select the new engine on Droidfish
4. Go to Engne Options and set the WeightsFile with this path: `/storage/emulated/0/DroidFish/591200`.

**Comment by spasski** [comment]
Wow, it runs.
This is the perfect day.

Thx soo much and all the best.

**Comment by lealgo** [comment]
> Wow, it runs.
> This is the perfect day.
> 
> Thx soo much and all the best.

I'm really glad it worked for you. We'll continue working on it and try to include it in future releases.
Cheers.

**Comment by lealgo** [comment]
@spasski 

Hi,
we've created an optimized build for x86 that should be much faster. I'll link it here just in case you want to try it out:

[lc0-i686-blas.zip](https://github.com/LeelaChessZero/lc0/files/4636848/lc0-i686-blas.zip)

Regards

**Comment by spasski** [comment]
This "little" gift doubled the speed from 36 kn/sec to 78 kn for me.

Thx a lot friends of the sun.

**Comment by venkat623** [comment]
Dear team kindly support my need..
How can I install lc0 application in my Android phone... please reply valuable comments...

**Comment by lealgo** [comment]
> Dear team kindly support my need..
> How can I install lc0 application in my Android phone... please reply valuable comments...

Hi,
Please visit our #help channel on Discord:
https://discord.gg/ESrTWs
I'm sure someone will be ready to help you there.
Regards

**Comment by CalKK8** [comment]
Hi, speaking of missing support, I was wondering if someone could compile a linux x64 lc0 engine that works with [Salesforce Heroku](https://dashboard.heroku.com/). Lc0 does not work if I compile it by myself on my own linux computer. I have no idea what kind of architecture its dynos have
