### ISSUE TITLE
Reduce memory footprint (Node structure is too large)

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#13]
_From @mooskagh on April 16, 2018 9:33_

Plan is:
- Remove ChessBoard from Node structure
- Make leaves take less space
- Consider swtiching to stockfish movegen, if result of two previous steps is slow.

_Copied from original issue: glinscott/leela-chess#331_

**Comment by mooskagh** [comment]
I removed chessboards from nodes, size went from 112 to 56. Others ideas to do:
* Make move 2 bytes, not 4  (-2 bytes)
* Don't store Q, as it's W/N (-4 bytes)
* Don't store V, it's only needed right after NN eval (-4 bytes)
* Make N-in-flight 2 bytes instead of 4 (-2 bytes)
* Make depth and full-depth 1 bytes each instead of 2, or possibly don't store them at all (-2..-4 bytes)
* Don't store parent (-8 bytes)
* Store is_terminal not as a separate bool, but e.g. as highest bit of N. (-1 byte)
* Instead of 64-bit pointer to child, use 32-bit and resolve through node-pool (-4 bytes)
* Store siblings in array rather than linked list (-7 bytes)

All in all, it will give 56->20 size reduce per node if all is implemented. Not everything from the list is feasible as it can slow things down.

Also leaves only really need 6 bytes (move+P), it may be worthwhile to explore using separate structs for leaves vs internal node. Although some bookkeeping to distinguish between them will require at least one additional byte.
Probably there's no feasible solution with replacing linked list with an array in that case, but we still can have node translation optimization, so it will be ~10 bytes per leaf, and 24 bytes per internal node.

**Comment by dubslow** [comment]
One million nodes times 100 bytes is... 100MB. That's not much on modern systems. That's less than a modern webbrowser. And removing the chess board is probably good enough, down to 50MB. And a million nodes is a *really* large tree, like 60-120 minute time controls on a very good GPU.

**Comment by mooskagh** [comment]
Actually it's not that good.

I on my old GTX 970 have 8800 nps, it takes less than 2 minutes to get 1000000 visits.

More importantly, tree contains not only visits (which are counted for user) but also unvisited leaf nodes (but they do contain some useful information, namely P value and move itself). Unvisited nodes increase number of nodes by factor of 35 (from startpos at least).

That means that even on my GTX 970, memory growth is
```
8800 * 35 * 60 * 56 = 1GB per minute
```
which is not that negligible at all.

**Comment by dubslow** [comment]
> Unvisited nodes increase number of nodes by factor of 35

:O

Man, 1GB per minute is definitely a problem! And it definitely sounds like leaf nodes are the problem...

**Comment by mooskagh** [comment]
`Node` is growing again, and we'll probably have to have another round of memory optimizations. But from what was originally planned, most is done.
