### ISSUE TITLE
CUDA error: no kernel image available (in winograd_helper)

### ISSUE THREAD

**Issue by aiorla** [LeelaChessZero/lc0#1315]
**DESCRIPTION**

`Exception: CUDA error: no kernel image is available for execution on the device (../../src/neural/cuda/winograd_helper.inc:363)` when analyzing a position in a Colab Pro notebook with a GPU runtime (Tesla P100 16GB & CUDA 10.1.243).

It happens in 0.25 and in master and **does not happen in 0.24**. (#1228?)
It happens with main run networks (e.g. 63601) and big SV networks (e.g. 384x30-t60-3010),

**REPRODUCE**

Using Colab Pro with GPU runtime usually gives you a Tesla P100 with 16GB RAM.
Clone repo + download dependencies + compile + upload network weights + "go nodes X".

**DETAILS**

GPU: Tesla P100 16GB
CUDA: 10.1 (10.1.243)
LOGFILE: https://pastebin.com/Mxcdhkzh

EDIT: **works with "--backend-opts=custom_winograd=false"**. Is this the intended behaviour?

**Comment by cn4750** [comment]
Your edit is currently intended behavior, but if you need more assistance come over to our Discord's #help channel: [https://discord.gg/pKujYxD](https://discord.gg/pKujYxD)
