### ISSUE TITLE
Consistent cudnn crashes with specific arguments

### ISSUE THREAD

**Issue by Cyanogenoid** [LeelaChessZero/lc0#134]
I'm consistently getting strange crashes when running lc0, cudnn backend, with the arguments `--no-smart-pruning --minibatch-size=1024` and go nodes 1000000 (that's 10^6). Full output: https://gist.github.com/Cyanogenoid/2703d32b4072cb9482aab87f23fe27c0

- Weights are test10 10020
- Crashes almost always seems to happen at > 500 000 nodes. I can reproduce this every single run at the moment.
- I haven't had it happen when smart pruning is on or when I halve the batch size to 512
- Changing backend to cudnn-fp16 also doesn't crash
- cudnn version 7.1.4, one V100 GPU
- Sample size of 1 for these runs: Crashes at batch size 1023 at about the usual point, 999 perhaps a bit later (around 650k nodes), batch size 950 crashes at 1.2 million nodes, 900 at 1 million and 1.3 million in two runs, batch size 800 was fine for 20 million nodes without crash.

**Comment by mooskagh** [comment]
Cudnn backend has a hardcoded batch limit of 1024.
https://github.com/mooskagh/lc0/blob/master/src/neural/network_cudnn.cu#L97

Maybe it's actually not 1024.. Or maybe GPU doesn't have enough VRAM or something.

**Comment by mooskagh** [comment]
I cannot find in github UI how to add people to a project. If I could, I'd assign that to @ankan-ban. :)

**Comment by ankan-ban** [comment]
looking into it.. likely some out of bound access (seems to happen when batch size is > 800)

**Comment by ankan-ban** [comment]
The problem turned out to be this hard coded limit that I thought would be enough:

```
// 256 MB fixed scratch memory size (hardcoded for now)
static constexpr int kCudaScratchSize = 256 * 1024 * 1024;

```
For 20x256 network and large batches it's not enough. Will fix it by querying required size correctly.

**Comment by ankan-ban** [comment]
fix here: https://github.com/LeelaChessZero/lc0/pull/136

**Comment by dubslow** [comment]
@Cyanogenoid can you confirm the fix and close please?

**Comment by Cyanogenoid** [comment]
Fix confirmed. I ran it for 10 million nodes (~20 times more than when it usually crashed) without issues.
