### ISSUE TITLE
Need a way to limit memory use

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#135]
There is no way to limit memory use of lc0. Most of the memory is from the nodes in the tree, so a quick solution is to implement a max_tree_size. 

For TCEC I hear the memory limit is 16GB. 
16GB / 56 bytes per node / 30 nodes allocated per node reported to user = ~10M nodes reported to user.
I think we might go over that at TCEC time controls.

**Comment by mooskagh** [comment]
Duplicate of https://github.com/LeelaChessZero/lc0/issues/298
