### ISSUE TITLE
WDL displays negative values

### ISSUE THREAD

**Issue by masterkni666** [LeelaChessZero/lc0#1350]
As it says in the title, W in WDL gives negative values for certain positions. My current machine uses a 1080 Max-Q. Using latest binary with sv4175 net using cudaNN backend. 

8/8/8/2p5/1pp5/brpp4/qpprpK1P/1nkbn3 w - - 0 1
![bug](https://user-images.githubusercontent.com/19353314/85183442-907d4000-b240-11ea-8d32-a2e8de266a8a.PNG)

![negW](https://user-images.githubusercontent.com/19353314/85183444-92470380-b240-11ea-923d-c3b854f6fe0f.PNG)

**Comment by fohristiwhirl** [comment]
What network was this?

**Comment by masterkni666** [comment]
Using latest binary with sv4175 net using cudaNN backend.

**Comment by fohristiwhirl** [comment]
OK I have reproduced this in all of cudnn, cudnn-fp16, and dx12. Need to wait for 1.9M nodes for it to show up.
