### ISSUE TITLE
No output when running

### ISSUE THREAD

**Issue by DylwinTFTW** [LeelaChessZero/lc0#1359]
When I run Lc0 in Scid, it says there's 0 depth and 0 nodes. Whenever I try to get it to make a move, nothing happens.

**Comment by Naphthalin** [comment]
Can you give some specifics on: Hardware, OS, which Lc0 version you use, which net, etc?

**Comment by cn4750** [comment]
You are more likely to get effective help at our Discord's #help channel: [https://discord.gg/pKujYxD](https://discord.gg/pKujYxD)
