### ISSUE TITLE
Limit of 64 search threads on Windows

### ISSUE THREAD

**Issue by cn4750** [LeelaChessZero/lc0#1382]
Due to [processor group](https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups) limitations in Windows, we can't use more than 64 search threads.
Can we possibly leverage [Stockfish's code](https://github.com/official-stockfish/Stockfish/blob/ab5cd8340f2f7f8730aa7c77476edf4a98a166e4/src/misc.cpp#L423-L527) for this?

**Comment by Tilps** [comment]
The limit can in practice be between 32 and 64 since windows attempts to balance the processor groups to reduce splitting of a socket across multiple groups.

**Comment by borg323** [comment]
I think #1383 is ready for review - seems to work OK.

**Comment by borg323** [comment]
Yes, but there is an issue with Alder Lake (or other hybrid core) systems. However this is not related to this, so closing.
