### ISSUE TITLE
Lc0 0.26 misses stunning bishop sac in android (droidfish) 

### ISSUE THREAD

**Issue by Adiyen1** [LeelaChessZero/lc0#1386]
In a match against stockfish 11 Lc0 played the stunning bishop sacrifice line and won the game which I came to know after seeing https://youtu.be/A-vNq61KfLs.

First of all congratulations to the entire Lc0 team for your hard work. If not you the world would have not known that there exists a line like that following 8.d5 in the charousek variation. 

I'm a school boy. When I tried Lc0 0.26 / 0.25 even till depth=12 it did not show me the move. Even when I let the computer vs computer mode a go it played to save the bishop. Can you do something so that the move d5 happens in my android (POCO)? or what should i do so that that happens. Thank you.

**Comment by Adiyen1** [comment]
![Screenshot_2020-07-05-00-08-32-930_org petero droidfish](https://user-images.githubusercontent.com/67839289/86519041-92581d80-be54-11ea-8872-9e1d1647570d.png)

**Comment by cn4750** [comment]
You are more likely to get effective help at our Discord's #help channel: [https://discord.gg/pKujYxD](https://discord.gg/pKujYxD)
