### ISSUE TITLE
How to enable true for other backend-options

### ISSUE THREAD

**Issue by CalKK8** [LeelaChessZero/lc0#1388]
When I run `./lc0.exe --help`, I see backend-options such as
`--[no-]ponder`

How am I supposed to enable these kinds of options? I have tried `--[yes-]ponder`, etc. but none of my tries worked.

**Comment by cn4750** [comment]
The `no-` is optional. `--ponder` or `--no-ponder` are allowed options. Feel free to join our Discord if you have any more questions.
