### ISSUE TITLE
ninja: build stopped: subcommand failed.

### ISSUE THREAD

**Issue by Adajone** [LeelaChessZero/lc0#1395]
I get the feeling this is something horribly simple that I simply cannot see despite being right in front of me. I'm using the mendel OS on a google coral dev board.

mendel@jumbo-xylophone:~/lc0$ ./build.sh
~/lc0 ~/lc0
[0/1] Regenerating build files.
The Meson build system
Version: 0.52.0
Source dir: /home/mendel/lc0
Build dir: /home/mendel/lc0/build/release
Build type: native build
Project name: lc0
Project version: undefined
C++ compiler for the host machine: c++ (gcc 8.3.0 "c++ (Debian 8.3.0-6) 8.3.0")
C++ linker for the host machine: GNU ld.bfd 2.31.1
Host machine cpu family: aarch64
Host machine cpu: aarch64
Has header "optional" : YES (cached)
Has header "string_view" : YES (cached)
Has header "charconv" : YES (cached)
Compiler for C++ supports arguments -march=native: YES (cached)
Program scripts/compile_proto.py found: YES (/home/mendel/lc0/scripts/compile_proto.py)
Program git found: YES (/usr/bin/git)
meson.build:107: WARNING: Cannot extract valid git short revision from dirty working directory.
Message: Using build identifier "git.dirty".
Dependency threads found: YES (cached)
Library dl found: YES
Found pkg-config: /usr/bin/pkg-config (0.29)
Found CMake: /usr/bin/cmake (3.13.4)
Run-time dependency tensorflow_cc found: NO (tried pkgconfig and cmake)
Run-time dependency accelerate found: NO (tried pkgconfig and cmake)
Library mkl_rt found: NO
Library mklml found: NO
Library dnnl found: NO
Library openblas.dll found: NO
Library openblas found: NO
Dependency eigen3 found: YES (cached)
Program ispc found: NO
Library OpenCL found: YES
Run-time dependency opencl found: NO
Has header "CL/opencl.h" : YES (cached)
Library cublas found: NO
Library cudnn found: NO
Library cudart found: NO
Program nvcc found: NO
Program /usr/local/cuda/bin/nvcc found: NO
Program /opt/cuda/bin/nvcc found: NO
Run-time dependency zlib found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency zlib

|Executing subproject zlib method meson
|
|Project name: zlib
|Project version: 1.2.11
|C compiler for the host machine: cc (gcc 8.3.0 "cc (Debian 8.3.0-6) 8.3.0")
|C linker for the host machine: GNU ld.bfd 2.31.1
|Compiler for C supports arguments -Wno-implicit-fallthrough -Wimplicit-fallthrough: YES (cached)
|Compiler for C supports arguments -Wno-implicit-function-declaration -Wimplicit-function-declaration: YES (cached)
|Build targets in project: 1
|Subproject zlib finished.

Dependency zlib from subproject subprojects/zlib found: YES
Dependency gtest found: YES (cached)
Build targets in project: 9
Option b_lto is: false [default: true]
Found ninja-1.8.2 at /usr/bin/ninja
[4/134] Compiling C++ object 'lc0_lib@sha/src_mcts_search.cc.o'.
FAILED: lc0_lib@sha/src_mcts_search.cc.o
c++ -Ilc0_lib@sha -I. -I../.. -I../../src -I/usr/include/ -Isubprojects/zlib-1.2.11 -I../../subprojects/zlib-1.2.11 -I/usr/include/eigen3 -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -march=native '-DBUILD_IDENTIFIER="git.dirty"' -DNO_PEXT -fPIC -pthread -isystem../../third_party -MD -MQ 'lc0_lib@sha/src_mcts_search.cc.o' -MF 'lc0_lib@sha/src_mcts_search.cc.o.d' -o 'lc0_lib@sha/src_mcts_search.cc.o' -c ../../src/mcts/search.cc
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[5/134] Compiling C++ object 'lc0_lib@sha/src_mcts_stoppers_common.cc.o'.
FAILED: lc0_lib@sha/src_mcts_stoppers_common.cc.o
c++ -Ilc0_lib@sha -I. -I../.. -I../../src -I/usr/include/ -Isubprojects/zlib-1.2.11 -I../../subprojects/zlib-1.2.11 -I/usr/include/eigen3 -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -march=native '-DBUILD_IDENTIFIER="git.dirty"' -DNO_PEXT -fPIC -pthread -isystem../../third_party -MD -MQ 'lc0_lib@sha/src_mcts_stoppers_common.cc.o' -MF 'lc0_lib@sha/src_mcts_stoppers_common.cc.o.d' -o 'lc0_lib@sha/src_mcts_stoppers_common.cc.o' -c ../../src/mcts/stoppers/common.cc
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[8/134] Compiling C++ object 'lc0_lib@sha/src_mcts_stoppers_legacy.cc.o'.
In file included from ../../src/mcts/stoppers/timemgr.h:36,
                 from ../../src/mcts/stoppers/legacy.h:30,
                 from ../../src/mcts/stoppers/legacy.cc:28:
../../src/mcts/node.h:334:29: warning: ‘lczero::Node::terminal_type_’ is too small to hold all values of ‘enum class lczero::Node::Terminal’
   Terminal terminal_type_ : 2;
                             ^
../../src/mcts/node.h:336:29: warning: ‘lczero::Node::lower_bound_’ is too small to hold all values of ‘enum class lczero::GameResult’
   GameResult lower_bound_ : 2;
                             ^
../../src/mcts/node.h:337:29: warning: ‘lczero::Node::upper_bound_’ is too small to hold all values of ‘enum class lczero::GameResult’
   GameResult upper_bound_ : 2;
                             ^
[9/134] Compiling C++ object 'lc0_lib@sha/src_mcts_stoppers_factory.cc.o'.
In file included from ../../src/mcts/stoppers/stoppers.h:33,
                 from ../../src/mcts/stoppers/common.h:30,
                 from ../../src/mcts/stoppers/factory.h:30,
                 from ../../src/mcts/stoppers/factory.cc:28:
../../src/mcts/node.h:334:29: warning: ‘lczero::Node::terminal_type_’ is too small to hold all values of ‘enum class lczero::Node::Terminal’
   Terminal terminal_type_ : 2;
                             ^
../../src/mcts/node.h:336:29: warning: ‘lczero::Node::lower_bound_’ is too small to hold all values of ‘enum class lczero::GameResult’
   GameResult lower_bound_ : 2;
                             ^
../../src/mcts/node.h:337:29: warning: ‘lczero::Node::upper_bound_’ is too small to hold all values of ‘enum class lczero::GameResult’
   GameResult upper_bound_ : 2;
                             ^
ninja: build stopped: subcommand failed.

**Comment by borg323** [comment]
The real problem is reported earlier: ` c++: fatal error: Killed signal terminated program cc1plus`.
I guess you run out of memory, in which case you can try to run `cd build/release && ninja -j 1` to see if it helps.

**Comment by Adajone** [comment]
I tried your suggestion and got a lot further, but encountered another error:

[22/127] Compiling C++ object 'lc0@exe/src_neural_encoder.cc.o'.
FAILED: lc0@exe/src_neural_encoder.cc.o
c++ -Ilc0@exe -I. -I../.. -I../../src -I/usr/include/ -Isubprojects/zlib-1.2.11 -I../../subprojects/zlib-1.2.11 -I/usr/include/eigen3 -fdiagnostics-color=always -DNDEBUG -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -march=native '-DBUILD_IDENTIFIER="git.dirty"' -DNO_PEXT -pthread -isystem../../third_party -MD -MQ 'lc0@exe/src_neural_encoder.cc.o' -MF 'lc0@exe/src_neural_encoder.cc.o.d' -o 'lc0@exe/src_neural_encoder.cc.o' -c ../../src/neural/encoder.cc
../../src/neural/encoder.cc: In function ‘bool lczero::IsCanonicalArmageddonFormat(pblczero::NetworkFormat::InputFormat)’:
../../src/neural/encoder.cc:116:14: error: ‘INPUT_112_WITH_CANONICALIZATION_HECTOPLIES_ARMAGEDDON’ is not a member of ‘pblczero::NetworkFormat’
              INPUT_112_WITH_CANONICALIZATION_HECTOPLIES_ARMAGEDDON;
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/neural/encoder.cc: In function ‘bool lczero::IsHectopliesFormat(pblczero::NetworkFormat::InputFormat)’:
../../src/neural/encoder.cc:120:35: error: ‘INPUT_112_WITH_CANONICALIZATION_HECTOPLIES’ is not a member of ‘pblczero::NetworkFormat’
          pblczero::NetworkFormat::INPUT_112_WITH_CANONICALIZATION_HECTOPLIES;
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/neural/encoder.cc: In function ‘lczero::InputPlanes lczero::EncodePositionForNN(pblczero::NetworkFormat::InputFormat, const lczero::PositionHistory&, int, lczero::FillEmptyHistory, int*)’:
../../src/neural/encoder.cc:173:37: error: ‘INPUT_112_WITH_CANONICALIZATION_HECTOPLIES’ is not a member of ‘pblczero::NetworkFormat’
       case pblczero::NetworkFormat::INPUT_112_WITH_CANONICALIZATION_HECTOPLIES:
                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../src/neural/encoder.cc:175:11: error: ‘INPUT_112_WITH_CANONICALIZATION_HECTOPLIES_ARMAGEDDON’ is not a member of ‘pblczero::NetworkFormat’
           INPUT_112_WITH_CANONICALIZATION_HECTOPLIES_ARMAGEDDON: {
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
ninja: build stopped: subcommand failed.

So I ran `git submodule update` and tried again, which looks to have worked. Thank you!
