### ISSUE TITLE
Make parameter parsers validate input

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#14]
_From @mooskagh on April 29, 2018 20:6_

(pretty straightforward, so if someone wants an easy task to start contributing, that's a good candidate)

Currently while command line / uci parameters have restrictions (min/max for numeric, list of choices for choice params), they are not checked. Validate them.

_Copied from original issue: glinscott/leela-chess#470_

**Comment by Synthetica9** [comment]
This should be closed, right?
