### ISSUE TITLE
"Compiler or library does not have full C++17 support"

### ISSUE THREAD

**Issue by CalKK8** [LeelaChessZero/lc0#1405]
While running `./build.sh`, an error came up saying:

`meson.build:30: WARNING: Your compiler or library does not have full C++17 support. See the README for compilers that are known to be working. This will become an error in the future.
`

- Meson Version: 0.55.0
- G++ Version: 7.5.0
- Clang Version: 6.0.0
- Zlib is not installed
- Do not know what "C++17 stdlib" is.

**Comment by borg323** [comment]
This is a warning, not an error. The c++ library of g++-7 is known to miss some c++17 features, but we have workarounds to support it, so you should be fine. If the build failed, we need more details.

**Comment by CalKK8** [comment]
Will this warning effect the strength of lc0?

**Comment by borg323** [comment]
No, this specific workaround gives slightly less informative error messages for string parameter validation.

**Comment by CalKK8** [comment]
Ok, thanks!
