### ISSUE TITLE
Infinite loop if uses go with depth option

### ISSUE THREAD

**Issue by ConradoCps** [LeelaChessZero/lc0#1406]
If you execute the command go depth 4 and the checkmate is in less movements, Lc0 enters an infinite loop and never shows bestmove 

I'm trying create a script that runs Lc0 focused on depth and not on time, but near checkmate if depth is higher, comes a infinite loop.

**Comment by borg323** [comment]
Our standard recommendation is to use `go nodes` instead of `go depth`, I'll take a look to see if we can change this, but strictly speaking in this case it is equivalent to `go infinite` which should only exit when a `stop` command is sent.

**Comment by ConradoCps** [comment]
> Our standard recommendation is to use `go nodes` instead of `go depth`, I'll take a look to see if we can change this, but strictly speaking in this case it is equivalent to `go infinite` which should only exit when a `stop` command is sent.

Hi borg23...I try this method because my hardware it's weak, and in this way a match against stockfish, for example it's more equilibrated. Others engines return some move with option depth, in this case when depth is higher than mate.
See below ... Using depth, all engines return bestmove except Lc0


see:
in stockfish 8-->

stockfish
Stockfish 8 by T. Romstad, M. Costalba, J. Kiiski, G. Linscott
ucinewgame
position fen 3rr1k1/5pp1/p4P1p/P7/8/6bP/6P1/7K w - - 0 37
go depth 4
info depth 1 seldepth 1 multipv 1 score mate -1 nodes 11 nps 3666 tbhits 0 time 3 pv h3h4 d8d1
info depth 2 seldepth 3 multipv 1 score mate -1 nodes 17 nps 5666 tbhits 0 time 3 pv h3h4 d8d1
info depth 3 seldepth 3 multipv 1 score mate -1 nodes 23 nps 7666 tbhits 0 time 3 pv h3h4 d8d1
info depth 4 seldepth 3 multipv 1 score mate -1 nodes 29 nps 7250 tbhits 0 time 4 pv h3h4 d8d1
bestmove h3h4 ponder d8d1

in RubiChess -->

$ ./RubiChess 
ucinewgame
position fen 3rr1k1/5pp1/p4P1p/P7/8/6bP/6P1/7K w - - 0 37
go depth 4
info depth 1 seldepth 2 multipv 1 time 0 score cp -1767  nodes 4 nps 0 tbhits 0 hashfull 0 pv f6g7  g8g7  
info depth 2 seldepth 3 multipv 1 time 0 score cp -1767  nodes 14 nps 0 tbhits 0 hashfull 0 pv f6g7  g8g7  
info depth 3 seldepth 4 multipv 1 time 0 score cp -1784  nodes 29 nps 0 tbhits 0 hashfull 0 pv f6g7  g8g7  h1g1  
info depth 4 seldepth 5 multipv 1 time 0 score cp -1742  nodes 53 nps 0 tbhits 0 hashfull 0 pv f6g7  g8g7  h1g1  h6h5  
bestmove f6g7  ponder g8g7 


in Lc0 -->

./lc0
       _
|   _ | |
|_ |_ |_| v0.26.0+git.unknown built Jul 19 2020
Found configuration file: ./lc0.config
ucinewgame
Loading weights file from: /home/conrado/Xadrez/Programas/lc0-0.26.0/build/release/Networks-alternative/atual-128x10-2-swa-2990000.pb
Creating backend [blas]...
BLAS vendor: OpenBLAS.
OpenBLAS [NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Barcelona].
OpenBLAS found 2 Barcelona core(s).
BLAS max batch size is 256.
position fen 3rr1k1/5pp1/p4P1p/P7/8/6bP/6P1/7K w - - 0 37
go depth 4
info depth 1 seldepth 2 time 7883 nodes 4 score cp -7671 nps 42 tbhits 0 pv f6g7 d8d1
info depth 2 seldepth 3 time 7884 nodes 260 score mate -1 nps 2736 tbhits 0 pv f6g7 d8d1
info depth 2 seldepth 3 time 12885 nodes 5873582 score mate -1 nps 1152586 tbhits 0 pv f6g7 d8d1
info depth 2 seldepth 3 time 17886 nodes 11576518 score mate -1 nps 1146416 tbhits 0 pv f6g7 d8d1
info depth 2 seldepth 3 time 22887 nodes 17268464 score mate -1 nps 1143758 tbhits 0 pv f6g7 d8d1
info depth 2 seldepth 3 time 27888 nodes 22585078 score mate -1 nps 1123691 tbhits 0 pv f6g7 d8d1
info depth 2 seldepth 3 time 32894 nodes 27754721 score mate -1 nps 1105501 tbhits 0 pv f6g7 d8d1

**Comment by OfekShochat** [comment]
If you compile lc0 yourself, the issue doesn't appear anymore
