### ISSUE TITLE
LC0 speedup absent on multiplexing with 2 RTX cards

### ISSUE THREAD

**Issue by magicianofriga** [LeelaChessZero/lc0#1414]
Hi,
I am using the latest Lc0 T60 nets with my dual graphics cards. I notice that when I choose the cudnn fp-16 backend I get around 15Kn/s, but when I choose multiplexing I get around 8-9KN/s. What is the issue? What backend should be used for multiple GPUs? How many threads should I use for the same? I have an older 2nd Gen Threadripper. Thanks a lot.

**Comment by Naphthalin** [comment]
Can you please give a bit more details? Especially: OS, cudnn/CUDA, which Lc0 version are you using, what command line arguments.

**Comment by magicianofriga** [comment]
Hi,
I use Windows 10. Lc0 26.0, Sergio Vieri's latest T60 Net and two RTX 2080 Cards. No command line arguments - I use it from Chessbase 15.

**Comment by Naphthalin** [comment]
Could you please update to v0.26.1 and check whether that's the same behavior? Also, can you check the dx12-backend as well for your part?
As for the multiple GPUs, you want `--backend=multiplexing --backend-opts=(backend=cudnn-fp16,gpu=0),(backend=cudnn-fp16,gpu=1)` as it only uses 1 GPU per default. If you need more help, please join the Discord, as the GitHub issues are only for issues, not technical support.

**Comment by magicianofriga** [comment]
Hi, 
Since I use a GUI, it is not possible for me to specify such options. I have asked on the Discord but there are no responses till now. Any other suggestions?

**Comment by magicianofriga** [comment]
Hi,
Since I found the solution, I am closing this now. Thank you!
