### ISSUE TITLE
Exploring an illegal move from a solid tree node crashes Lc0

### ISSUE THREAD

**Issue by Naphthalin** [LeelaChessZero/lc0#1416]
Version: 0.26.2-rc1 (same with 0.26.1)

Steps to reproduce: 
```
lc0 -v --solid-tree-threshold=1
go nodes 1
position startpos moves a8a7
go nodes 1
```
crashes the engine, while doing the same with `--solid-tree-threshold=1000` doesn't crash, and instead outputs moves for the side to play (though having a rubbish position).

**Comment by OfekShochat** [comment]
so its because of tree reuse?

**Comment by OfekShochat** [comment]
this is interesting, seems like its crashing with any illegal move.
