### ISSUE TITLE
How to make Lc0 use more GPU Memory

### ISSUE THREAD

**Issue by CalKK8** [LeelaChessZero/lc0#1417]
Lc0 is not using as much GPU memory as I expected. It uses 1 GB, but 14 GB is left. How can I make Lc0 use more GPU memory? 

Other information
- Lc0 v0.26.2
- CUDA + cuDNN
- Tesla T4 16GB

**Comment by cn4750** [comment]
lc0 doesn't use more VRAM than it needs. It does not affect performance.
