### ISSUE TITLE
Build Fail on Raspberry Pi 3

### ISSUE THREAD

**Issue by UHaider** [LeelaChessZero/lc0#1419]
**Details**
I am following the install/build step but the build.sh fails  Below is the error 

```
/usr/bin/ld: /tmp/cc9mixq3.ltrans5.ltrans.o: in function `std::thread::_State_impl<std::thread::_Invoker<std::tuple<lczero::(anonymous namespace)::DemuxingNetwork::AddBackend(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::optional<pblczero::Net> const&, lczero::OptionsDict const&)::{lambda()#1}> > >::_M_run()':
<artificial>:(.text+0x22a8): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: /tmp/cc9mixq3.ltrans4.ltrans.o: in function `lczero::(anonymous namespace)::RoundRobinNetwork::NewComputation()':
<artificial>:(.text+0x830): undefined reference to `__atomic_fetch_add_8'
/usr/bin/ld: /tmp/cc9mixq3.ltrans4.ltrans.o: in function `lczero::(anonymous namespace)::RecordReplayNetwork::NewComputation()':
<artificial>:(.text+0x8e4): undefined reference to `__atomic_fetch_add_8'
collect2: error: ld returned 1 exit status
[125/131] Linking target position_test
```

Complete log [https://pastebin.pl/view/0999918b](Fail log)
**Steps to Reproduce**
Steps mentioned here [https://github.com/LeelaChessZero/lc0#raspberry-pi](steps)

**Comment by UHaider** [comment]
Hi @borg323 ,

**That did it.** Now, I am getting only the warnings, a lot of these
_/tmp/ccsALbsQ.s:1035: This coprocessor register access is deprecated in ARMv8_

But I think these can be ignored. 

So, how should we close this issue? Maybe add that line conditionally in meson.build for raspberry pi?

**Comment by borg323** [comment]
I believe the line can be added unconditionally - at least my test on x86 Linux worked fine. Can you make a pull request?

**Comment by UHaider** [comment]
Created a pull request.
