### ISSUE TITLE
Crash in older mac opencl 0.26.0 similar to #88

### ISSUE THREAD

**Issue by freeeve** [LeelaChessZero/lc0#1429]
BUG REPORT

**Describe the bug**
Version 0.26.0 (and current master branch) crashes with low end macbook. I tried various models as well--smaller ones like from https://github.com/dkappe/leela-chess-weights/wiki/Bad-Gyal also crash (after getting farther, sometimes up to depth 11). Works if I switch to blas backend, but I figured I would report this since this is the default behavior.

**Steps to Reproduce**
1. ucinewgame
2. go
Expected behavior: doesn't crash
Observed behavior: crashes

**Lc0 version**
current brew install: v0.26.2+git.dirty built Sep  3 2020

**Lc0 parameters**
./lc0

**Hardware**
OpenCL, maximum batch size set to 16.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 (Sep  5 2019 21:59:08)
Platform profile: FULL_PROFILE
Platform name:    Apple
Platform vendor:  Apple
Device ID:      0
Device name:    Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
Device type:    CPU
Device vendor:  Intel
Device driver:  1.1
Device speed:   3100 MHZ
Device cores:   4 CU
Device score:   512
Device ID:      1
Device name:    Intel(R) Iris(TM) Graphics 6100
Device type:    GPU
Device vendor:  Intel Inc.
Device driver:  1.2(Sep 25 2019 21:33:24)
Device speed:   1100 MHZ
Device cores:   48 CU
Device score:   612
Selected platform: Apple
Selected device: Intel(R) Iris(TM) Graphics 6100
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning for batch size 16.
Wavefront/Warp size: 8

Max workgroup size: 256
Max workgroup dimensions: 256 256 256

**Lc0 logs**
============= Log started. =============
0925 10:18:38.130207 0x108079d40 ../../src/main.cc:41] Lc0 started.
0925 10:18:38.130994 0x108079d40 ../../src/main.cc:42]        _
0925 10:18:38.131037 0x108079d40 ../../src/main.cc:43] |   _ | |
0925 10:18:38.131406 0x108079d40 ../../src/main.cc:44] |_ |_ |_| v0.26.2+git.dirty built Sep  3 2020
0925 10:18:38.135744 0x108079d40 ../../src/utils/commandline.cc:56] Command line: /usr/local/Cellar/lc0/0.26.2/libexec/lc0 --logfile=/Users/wfreeman/lc0log.txt
0925 10:18:41.075710 0x108079d40 ../../src/chess/uciloop.cc:135] >> ucinewgame
0925 10:18:41.076355 0x108079d40 ../../src/neural/loader.cc:238] Found pb network file: /usr/local/Cellar/lc0/0.26.2/libexec/00af53b081e80147172e6f281c01daf5ca19ada173321438914c730370aa4267
0925 10:18:41.694089 0x108079d40 ../../src/neural/factory.cc:91] Creating backend [opencl]...
0925 10:18:41.801159 0x108079d40 ../../src/neural/opencl/network_opencl.cc:272] OpenCL, maximum batch size set to 16.
0925 10:18:41.801246 0x108079d40 ../../src/neural/opencl/OpenCL.cc:233] Initializing OpenCL.
0925 10:18:41.801284 0x108079d40 ../../src/neural/opencl/OpenCL.cc:250] Detected 1 OpenCL platforms.
0925 10:18:41.801322 0x108079d40 ../../src/neural/opencl/OpenCL.cc:257] Platform version: OpenCL 1.2 (Sep  5 2019 21:59:08)
0925 10:18:41.801351 0x108079d40 ../../src/neural/opencl/OpenCL.cc:258] Platform profile: FULL_PROFILE
0925 10:18:41.801378 0x108079d40 ../../src/neural/opencl/OpenCL.cc:259] Platform name:    Apple
0925 10:18:41.801402 0x108079d40 ../../src/neural/opencl/OpenCL.cc:260] Platform vendor:  Apple
0925 10:18:41.829304 0x108079d40 ../../src/neural/opencl/OpenCL.cc:276] Device ID:      0
0925 10:18:41.829403 0x108079d40 ../../src/neural/opencl/OpenCL.cc:277] Device name:    Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
0925 10:18:41.829433 0x108079d40 ../../src/neural/opencl/OpenCL.cc:279] Device type:    CPU
0925 10:18:41.829587 0x108079d40 ../../src/neural/opencl/OpenCL.cc:281] Device vendor:  Intel
0925 10:18:41.829648 0x108079d40 ../../src/neural/opencl/OpenCL.cc:282] Device driver:  1.1
0925 10:18:41.829674 0x108079d40 ../../src/neural/opencl/OpenCL.cc:283] Device speed:   3100 MHZ
0925 10:18:41.829704 0x108079d40 ../../src/neural/opencl/OpenCL.cc:285] Device cores:   4 CU
0925 10:18:41.829735 0x108079d40 ../../src/neural/opencl/OpenCL.cc:300] Device score:   512
0925 10:18:41.829758 0x108079d40 ../../src/neural/opencl/OpenCL.cc:276] Device ID:      1
0925 10:18:41.829777 0x108079d40 ../../src/neural/opencl/OpenCL.cc:277] Device name:    Intel(R) Iris(TM) Graphics 6100
0925 10:18:41.829808 0x108079d40 ../../src/neural/opencl/OpenCL.cc:279] Device type:    GPU
0925 10:18:41.829830 0x108079d40 ../../src/neural/opencl/OpenCL.cc:281] Device vendor:  Intel Inc.
0925 10:18:41.829859 0x108079d40 ../../src/neural/opencl/OpenCL.cc:282] Device driver:  1.2(Sep 25 2019 21:33:24)
0925 10:18:41.829884 0x108079d40 ../../src/neural/opencl/OpenCL.cc:283] Device speed:   1100 MHZ
0925 10:18:41.829910 0x108079d40 ../../src/neural/opencl/OpenCL.cc:285] Device cores:   48 CU
0925 10:18:41.829937 0x108079d40 ../../src/neural/opencl/OpenCL.cc:300] Device score:   612
0925 10:18:41.829963 0x108079d40 ../../src/neural/opencl/OpenCL.cc:324] Selected platform: Apple
0925 10:18:41.830000 0x108079d40 ../../src/neural/opencl/OpenCL.cc:325] Selected device: Intel(R) Iris(TM) Graphics 6100
0925 10:18:41.830026 0x108079d40 ../../src/neural/opencl/OpenCL.cc:327] with OpenCL 1.2 capability.
0925 10:18:41.831032 0x108079d40 ../../src/neural/opencl/OpenCLTuner.cc:468] Loaded existing SGEMM tuning for batch size 16.
0925 10:18:41.833987 0x108079d40 ../../src/neural/opencl/OpenCL.cc:375] Wavefront/Warp size: 8

0925 10:18:41.834114 0x108079d40 ../../src/neural/opencl/OpenCL.cc:380] Max workgroup size: 256
0925 10:18:41.834169 0x108079d40 ../../src/neural/opencl/OpenCL.cc:383] Max workgroup dimensions: 256 256 256
0925 10:18:44.258163 0x108079d40 ../../src/chess/uciloop.cc:135] >> go
0925 10:18:44.258266 0x108079d40 ../../src/engine.cc:285] Timer started at 0925 10:18:41.075922
0925 10:18:44.258355 0x700008bf6000 ../../src/mcts/search.cc:845] Start a watchdog thread.
0925 10:18:44.258384 0x700008cfc000 ../../src/mcts/search.h:216] Started search thread.
0925 10:18:44.258368 0x108079d40 ../../src/mcts/search.cc:782] Search started. 3182ms already passed.
0925 10:18:44.258369 0x700008c79000 ../../src/mcts/search.h:216] Started search thread.

**Chess GUI logs**
lc0
       _
|   _ | |
|_ |_ |_| v0.26.2+git.dirty built Sep  3 2020
ucinewgame
Found pb network file: /usr/local/Cellar/lc0/0.26.2/libexec/00af53b081e80147172e6f281c01daf5ca19ada173321438914c730370aa4267
Creating backend [opencl]...
OpenCL, maximum batch size set to 16.
Initializing OpenCL.
Detected 1 OpenCL platforms.
Platform version: OpenCL 1.2 (Sep  5 2019 21:59:08)
Platform profile: FULL_PROFILE
Platform name:    Apple
Platform vendor:  Apple
Device ID:      0
Device name:    Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
Device type:    CPU
Device vendor:  Intel
Device driver:  1.1
Device speed:   3100 MHZ
Device cores:   4 CU
Device score:   512
Device ID:      1
Device name:    Intel(R) Iris(TM) Graphics 6100
Device type:    GPU
Device vendor:  Intel Inc.
Device driver:  1.2(Sep 25 2019 21:33:24)
Device speed:   1100 MHZ
Device cores:   48 CU
Device score:   612
Selected platform: Apple
Selected device: Intel(R) Iris(TM) Graphics 6100
with OpenCL 1.2 capability.
Loaded existing SGEMM tuning for batch size 16.
Wavefront/Warp size: 8

Max workgroup size: 256
Max workgroup dimensions: 256 256 256
go
Abort trap: 6

**Comment by Ttl** [comment]
Apple OpenCL drivers for some Intel GPUs are known to be broken. There's nothing that really can be done in lc0 and it's Apple/Intel that should fix the drivers. However Apple has deprecated OpenCL so it's unlikely for them to be ever fixed. You should use blas backend instead to compute on CPU.
