### ISSUE TITLE
On Mac, the ./build.sh doesn't finish and ends with 1 error generated.

### ISSUE THREAD

**Issue by shyamalschandra** [LeelaChessZero/lc0#1433]
Could you please change the installation instructions for Mac because of this error?

```
#include <gtest/gtest.h>
         ^~~~~~~~~~~~~~~
1 error generated.
[106/134] Compiling C++ ob.../src_chess_board_test.cc.
FAILED: chessboard_test.p/src_chess_board_test.cc.o 
c++ -Ichessboard_test.p -I. -I../.. -I../../src -flto -Xclang -fcolor-diagnostics -DNDEBUG -pipe -Wall -Winvalid-pch -Wnon-virtual-dtor -Wextra -Wpedantic -std=c++17 -O3 -Wthread-safety -march=native '-DBUILD_IDENTIFIER="git.unknown"' -DUSE_BLAS -DNO_PEXT -isystem../../third_party -MD -MQ chessboard_test.p/src_chess_board_test.cc.o -MF chessboard_test.p/src_chess_board_test.cc.o.d -o chessboard_test.p/src_chess_board_test.cc.o -c ../../src/chess/board_test.cc
../../src/chess/board_test.cc:21:10: fatal error: 'gtest/gtest.h' file not found
#include <gtest/gtest.h>
         ^~~~~~~~~~~~~~~
1 error generated.
[121/134] Linking target lc0
```

Thanks in advance!

**Comment by lealgo** [comment]
@shyamalschandra 

try disabling tests with:

```
./build.sh -Dgtest=false
```

**Comment by borg323** [comment]
Can you show more output from the build, in particular there should be a line earlier about gtest being detected. I want to see if gtest is detected in your system (and the include file is missing) or if  there is an issue with the alternative that is used if gtest is not installed.

**Comment by gsobala** [comment]
I get this too. Meson detects a test:

`Run-time dependency GTest found: YES (prebuilt)`

**Comment by ZeepXanflorp** [comment]
On Raspberry pi - is this the same issue?:

**Comment by ZeepXanflorp** [comment]
On Raspberry Pi: Is this the same issue? 

> 
> |Executing subproject gtest method meson 
> |
> |Project name: gtest
> |Project version: 1.10.0
> |C++ compiler for the host machine: clang++-6.0 (clang 6.0.1-10 "clang version 6.0.1-10+rpi1 (tags/RELEASE_601/final)")
> |C++ linker for the host machine: clang++-6.0 ld.bfd 2.31.1
> |Dependency threads found: YES unknown (cached)
> |Dependency threads found: YES unknown (cached)
> |Dependency threads found: YES unknown (cached)
> |Dependency threads found: YES unknown (cached)
> |Build targets in project: 1
> |Subproject gtest finished.
> 
> Dependency gtest from subproject subprojects/googletest-release-1.10.0 found: YES 1.10.0
> Build targets in project: 8
> 
> lc0 undefined
> 
>   Subprojects
>     eigen: YES
>     gtest: YES
> 
> Found ninja-1.10.0.git.kitware.jobserver-1 at /home/muffin/.local/bin/ninja
> [17/30] Linking target chessboard_test
> FAILED: chessboard_test 
> clang++-6.0  -o chessboard_test chessboard_test.p/src_chess_board_test.cc.o chessboard_test.p/subprojects_googletest-release-1.10.0_googletest_src_gtest-all.cc.o -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,--start-group liblc0_lib.a -pthread /usr/lib/libopenblas.so /usr/lib/arm-linux-gnueabihf/libz.so -Wl,--end-group
> /usr/bin/ld: liblc0_lib.a: error adding symbols: archive has no index; run ranlib to add one
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by borg323** [comment]
It is not the same issue, but the workaround in https://github.com/LeelaChessZero/lc0/issues/1433#issuecomment-699642821 should work for you as well.
