### ISSUE TITLE
Failed compiling on Raspbian 

### ISSUE THREAD

**Issue by salsan** [LeelaChessZero/lc0#1445]
My Operating System

```
pi@raspberrypi:~/lc0 $ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

My Hardware Raspberry Pi 4 Model B 4GB RAM

I follow  the [README.md ](https://github.com/LeelaChessZero/lc0/blob/master/README.md#raspberry-pi) for Raspberry Pi, but when compile the code result these **[errors](https://pastebin.com/raw/eMJudarV)** 

```
clang: error: unable to execute command: Segmentation fault
clang: error: linker command failed due to signal (use -v to see invocation)
```

**Comment by mooskagh** [comment]
I'm pretty sure linker runs out of memory, possibly due to enabled lto.

Could you try to delete `build` directory and retry with the following command:
```
CC=clang-6.0 CXX=clang++-6.0 ./build.sh -Ddefault_library=static -Dlto=false
```
?

**Comment by salsan** [comment]
```
pi@raspberrypi:~/Desktop/lc0 $ rm build -rf
pi@raspberrypi:~/Desktop/lc0 $ CC=clang-6.0 CXX=clang++-6.0 ./build.sh -Ddefault_library=static -Dlto=false
```

but I read from console that

> **WARNING: Unknown options: "lto"**
> The value of new options can be set with:
> meson setup <builddir> --reconfigure -Dnew_option=new_value ...

I tried later also

`meson setup build/release/ --reconfigure -Dlto=false`

but again

> **WARNING: Unknown options: "lto"**
> The value of new options can be set with:
> meson setup <builddir> --reconfigure -Dnew_option=new_value ...

My **mesion** version is **0.55.3**

**Comment by salsan** [comment]
I solved with this

`CC=clang-6.0 CXX=clang++-6.0 ./build.sh -Ddefault_library=static -Db_lto=false`

Thank you so much 😃

**Comment by ScallyBag** [comment]
Lc0 has always compiled fine on gcc-8.3.0 & gcc-9.1.0 on my RPi4.

I also have clang-9.0.0 which also compiles on my RPi4.

Al.

**Comment by salsan** [comment]
@ScallyBag also with GCC require **b_lto** flag set to false

 `CC=gcc-8 CXX=g++-8 ./build.sh -Ddefault_library=static `

> This coprocessor register access is deprecated in ARMv8 ❌ 

 `CC=gcc-8 CXX=g++-8 ./build.sh -Ddefault_library=static -Db_lto=false` 

> [130/130] Linking target encoder_test ✔️ 

🖥️ This is my [CPU](https://pastebin.com/raw/9n5zSzT7)
> ARMv7 Processor rev 3 (v7l)
> Hardware	: [BCM2711](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2711/README.md)
> Revision	: c03112
> Serial	: 10000000cf4e375b
> Model	: Raspberry Pi 4 Model B Rev 1.2

**Comment by ScallyBag** [comment]
Yes, I got a similar problem with gcc-10.1.0 But had not tried -Db_lto=false on gcc.

CC=gcc-8.3.0 CXX=g++-8.3.0 ./build.sh -Ddefault_library=static  Works for me.

This is my CPU (I don’t know how to attach it like you):
processor       : 0
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 118.02
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 118.02
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 118.02
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
model name      : ARMv7 Processor rev 3 (v7l)
BogoMIPS        : 118.02
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

Hardware        : BCM2711
Revision        : d03114
Serial          : 10000000c1338a62
Model           : Raspberry Pi 4 Model B Rev 1.4]

Cheers,

Al.

**Comment by gsobala** [comment]
I have no problem at all compiling current master on Raspberry 4 running 64-bit Gentoo using gcc 10.2 with just the command `./build.sh`. clang is no longer required.

On a Raspberry Pi 3B running 32-bit Raspbian Buster with gcc 8.30 one needs to change meson.build according to PR #1423 and then there are no problems compiling with gcc just with `./build.sh`

However the Eigen backend benefits from being compiled with the neon option set: on 32-bit systems this can be set with
`CXXFLAGS="-mfpu=neon" ./build.sh`. On 64-bit systems neon is enabled by default and the flag is not required - indeed it will throw a compiler error.

Hopefully #1423 will get merged soon and then we can update README.md to reflect this.

**Comment by Naphthalin** [comment]
As #1423 was merged, this can be closed.
