### ISSUE TITLE
Lc0 keeps searching node with lower S.

### ISSUE THREAD

**Issue by Rejwana** [LeelaChessZero/lc0#1456]
As we see from AlphaZero: “Each simulation traverses the tree by selecting the edge that maximizes Q(s,a) + U(s,a)” in the MCTS search phase. It seems Lc0 is not selecting the move with highest S=Q+U in the simulation stage.

> `/lc0/build/release# ./lc0 --weights=/weights/weights_run1_10970.pb --verbose-move-stats=true
       _
|   _ | |
|_ |_ |_| v0.27.0-dev+git.dirty built Oct 12 2020
position fen 8/7Q/8/k1K5/8/8/4q3/8 w - - 0 1
go nodes 100
Loading weights file from: /weights/weights_run1_10970.pb
Creating backend [cudnn-auto]...
Switching to [cudnn-fp16]...
CUDA Runtime version: 10.2.0
Cudnn version: 7.6.5
Latest version of CUDA supported by the driver: 11.0.0
GPU: GeForce RTX 2080 Ti
GPU memory: 10.7612 GiB
GPU clock frequency: 1545 MHz
GPU compute capability: 7.5
info depth 1 seldepth 2 time 11144 nodes 3 score cp 7 nps 272 tbhits 0 pv h7a7 e2a6
info depth 2 seldepth 3 time 11147 nodes 6 score cp 14 nps 428 tbhits 0 pv h7c7 a5a4 c7d7
info depth 3 seldepth 4 time 11150 nodes 23 score cp 18 nps 1277 tbhits 0 pv h7c7 a5a4 c7a7 a4b3
info depth 3 seldepth 5 time 11154 nodes 86 score cp 6 nps 4095 tbhits 0 pv h7c7 a5a4 c5d5 a4b4 c7e5
info depth 3 seldepth 6 time 11157 nodes 110 score cp 4 nps 4400 tbhits 0 pv h7c7 a5a4 c7f4 a4a5 f4c7
info string h7h2  (1577) N:       0 (+ 0) (P:  0.68%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.15448) (S: -0.21453) (V: -0.7881) 
info string h7d3  (1578) N:       0 (+ 0) (P:  0.69%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.15526) (S: -0.21376) (V: -0.9126) 
info string h7e4  (1580) N:       0 (+ 0) (P:  0.70%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.15715) (S: -0.21186) (V: -0.8188) 
info string h7c2  (1576) N:       0 (+ 0) (P:  0.75%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.16942) (S: -0.19959) (V: -0.9634) 
info string h7h5  (1584) N:       0 (+ 0) (P:  1.16%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.26245) (S: -0.10656) (V: -0.9424) 
info string h7e7  (1592) N:       0 (+ 0) (P:  1.42%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.32119) (S: -0.04782) (V: -0.9268) 
info string h7h6  (1587) N:       0 (+ 0) (P:  3.40%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.76796) (S:  0.39895) (V:  0.0179) 
info string h7f5  (1582) N:       0 (+ 0) (P:  3.43%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.77520) (S:  0.40619) (V: -0.1742) 
info string h7h1  (1575) N:       0 (+ 0) (P:  3.50%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.79001) (S:  0.42100) (V:  0.0240) 
info string c5d4  (962 ) N:       0 (+ 0) (P:  3.63%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.82068) (S:  0.45167) (V:  0.0241) 
info string h7h4  (1581) N:       2 (+ 0) (P:  3.72%) (WL: -0.12177) (D: 0.000) (M:  0.5) (Q: -0.12177) (U: 0.28022) (S:  0.15845) (V: -0.0159) 
info string c5d6  (974 ) N:       2 (+ 0) (P:  4.23%) (WL:  0.00953) (D: 0.000) (M:  0.5) (Q:  0.00953) (U: 0.31823) (S:  0.32776) (V:  0.0241) 
info string c5d5  (966 ) N:       3 (+ 0) (P:  3.65%) (WL:  0.00223) (D: 0.000) (M:  0.7) (Q:  0.00223) (U: 0.20612) (S:  0.20834) (V:  0.0182) 
info string h7g6  (1586) N:       3 (+ 0) (P:  3.67%) (WL:  0.00297) (D: 0.000) (M:  0.7) (Q:  0.00297) (U: 0.20715) (S:  0.21012) (V: -0.0035) 
info string c5c6  (973 ) N:       3 (+ 0) (P:  3.72%) (WL:  0.00101) (D: 0.000) (M:  0.7) (Q:  0.00101) (U: 0.21017) (S:  0.21117) (V:  0.0155) 
info string h7h3  (1579) N:       3 (+ 0) (P:  3.67%) (WL:  0.00524) (D: 0.000) (M:  0.7) (Q:  0.00524) (U: 0.20715) (S:  0.21239) (V: -0.0004) 
info string h7h8  (1597) N:       3 (+ 0) (P:  3.72%) (WL:  0.01978) (D: 0.000) (M:  0.7) (Q:  0.01978) (U: 0.21017) (S:  0.22994) (V:  0.0060) 
info string h7g8  (1596) N:       3 (+ 0) (P:  3.76%) (WL:  0.02119) (D: 0.000) (M:  0.7) (Q:  0.02119) (U: 0.21223) (S:  0.23343) (V:  0.0178) 
info string h7g7  (1594) N:       3 (+ 0) (P:  4.79%) (WL:  0.02266) (D: 0.000) (M:  0.7) (Q:  0.02266) (U: 0.27020) (S:  0.29286) (V:  0.0157) 
info string h7d7  (1591) N:       3 (+ 0) (P:  4.91%) (WL:  0.02125) (D: 0.000) (M:  0.7) (Q:  0.02125) (U: 0.27692) (S:  0.29817) (V:  0.0297) 
info string h7b1  (1574) N:       3 (+ 0) (P:  5.58%) (WL:  0.03121) (D: 0.000) (M:  0.7) (Q:  0.03121) (U: 0.31473) (S:  0.34595) (V:  0.0486) 
info string h7f7  (1593) N:       4 (+ 0) (P:  5.39%) (WL:  0.02097) (D: 0.000) (M:  0.8) (Q:  0.02097) (U: 0.24331) (S:  0.26428) (V:  0.0218) 
info string h7b7  (1589) N:       5 (+ 0) (P:  3.99%) (WL:  0.03552) (D: 0.000) (M:  0.8) (Q:  0.03552) (U: 0.14999) (S:  0.18551) (V:  0.0500) 
info string h7a7  (1588) N:       6 (+ 0) (P: 13.47%) (WL:  0.07445) (D: 0.000) (M:  1.7) (Q:  0.07445) (U: 0.43451) (S:  0.50895) (V:  0.0527) 
info string h7c7  (1590) N:      63 (+113) (P: 12.37%) (WL:  0.03542) (D: 0.063) (M:  3.0) (Q:  0.03542) (U: 0.01578) (S:  0.05120) (V:  0.0237) 
info string node  (  25) N:     110 (+113) (P: 80.63%) (WL:  0.02878) (D: 0.036) (M:  3.0) (Q:  0.02878) (V:  0.0673) 
bestmove h7c7 ponder a5a4
go nodes 10
info depth 2 seldepth 2 time 46800 nodes 227 score cp 3 tbhits 0 pv h7c7 a5a4 c7f4 a4b3 f4d4 e2e7
info string h7h2  (1577) N:       0 (+ 0) (P:  0.68%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.22415) (S: -0.18501) (V: -0.7881) 
info string h7d3  (1578) N:       0 (+ 0) (P:  0.69%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.22528) (S: -0.18389) (V: -0.9126) 
info string h7e4  (1580) N:       0 (+ 0) (P:  0.70%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.22803) (S: -0.18114) (V: -0.8188) 
info string h7c2  (1576) N:       0 (+ 0) (P:  0.75%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.24584) (S: -0.16333) (V: -0.9634) 
info string h7h5  (1584) N:       0 (+ 0) (P:  1.16%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.38082) (S: -0.02835) (V: -0.9424) 
info string h7e7  (1592) N:       0 (+ 0) (P:  1.42%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.46605) (S:  0.05689) (V: -0.9268) 
info string h7f5  (1582) N:       1 (+ 0) (P:  3.43%) (WL: -0.17419) (D: 0.000) (M:  0.0) (Q: -0.17419) (U: 0.56241) (S:  0.38822) (V: -0.1742) 
info string h7h6  (1587) N:       1 (+ 0) (P:  3.40%) (WL:  0.01790) (D: 0.000) (M:  0.0) (Q:  0.01790) (U: 0.55717) (S:  0.57506) (V:  0.0179) 
info string h7h1  (1575) N:       1 (+ 0) (P:  3.50%) (WL:  0.02397) (D: 0.000) (M:  0.0) (Q:  0.02397) (U: 0.57316) (S:  0.59713) (V:  0.0240) 
info string c5d4  (962 ) N:       1 (+ 0) (P:  3.63%) (WL:  0.02406) (D: 0.000) (M:  0.0) (Q:  0.02406) (U: 0.59541) (S:  0.61947) (V:  0.0241) 
info string h7h4  (1581) N:       2 (+ 0) (P:  3.72%) (WL: -0.12177) (D: 0.000) (M:  0.5) (Q: -0.12177) (U: 0.40660) (S:  0.28483) (V: -0.0159) 
info string c5d6  (974 ) N:       2 (+ 0) (P:  4.23%) (WL:  0.00953) (D: 0.000) (M:  0.5) (Q:  0.00953) (U: 0.46176) (S:  0.47129) (V:  0.0241) 
info string c5d5  (966 ) N:       3 (+ 0) (P:  3.65%) (WL:  0.00223) (D: 0.000) (M:  0.7) (Q:  0.00223) (U: 0.29908) (S:  0.30131) (V:  0.0182) 
info string h7g6  (1586) N:       3 (+ 0) (P:  3.67%) (WL:  0.00297) (D: 0.000) (M:  0.7) (Q:  0.00297) (U: 0.30058) (S:  0.30355) (V: -0.0035) 
info string h7h3  (1579) N:       3 (+ 0) (P:  3.67%) (WL:  0.00524) (D: 0.000) (M:  0.7) (Q:  0.00524) (U: 0.30058) (S:  0.30581) (V: -0.0004) 
info string c5c6  (973 ) N:       3 (+ 0) (P:  3.72%) (WL:  0.00101) (D: 0.000) (M:  0.7) (Q:  0.00101) (U: 0.30495) (S:  0.30596) (V:  0.0155) 
info string h7h8  (1597) N:       3 (+ 0) (P:  3.72%) (WL:  0.01978) (D: 0.000) (M:  0.7) (Q:  0.01978) (U: 0.30495) (S:  0.32473) (V:  0.0060) 
info string h7g8  (1596) N:       3 (+ 0) (P:  3.76%) (WL:  0.02119) (D: 0.000) (M:  0.7) (Q:  0.02119) (U: 0.30795) (S:  0.32915) (V:  0.0178) 
info string h7g7  (1594) N:       3 (+ 0) (P:  4.79%) (WL:  0.02266) (D: 0.000) (M:  0.7) (Q:  0.02266) (U: 0.39207) (S:  0.41472) (V:  0.0157) 
info string h7d7  (1591) N:       3 (+ 0) (P:  4.91%) (WL:  0.02125) (D: 0.000) (M:  0.7) (Q:  0.02125) (U: 0.40181) (S:  0.42306) (V:  0.0297) 
info string h7b1  (1574) N:       3 (+ 0) (P:  5.58%) (WL:  0.03121) (D: 0.000) (M:  0.7) (Q:  0.03121) (U: 0.45668) (S:  0.48789) (V:  0.0486) 
info string h7f7  (1593) N:       4 (+ 0) (P:  5.39%) (WL:  0.02097) (D: 0.000) (M:  0.8) (Q:  0.02097) (U: 0.35305) (S:  0.37402) (V:  0.0218) 
info string h7b7  (1589) N:       5 (+ 0) (P:  3.99%) (WL:  0.03552) (D: 0.000) (M:  0.8) (Q:  0.03552) (U: 0.21763) (S:  0.25315) (V:  0.0500) 
info string h7a7  (1588) N:       6 (+ 1) (P: 13.47%) (WL:  0.07445) (D: 0.000) (M:  1.7) (Q:  0.07445) (U: 0.55167) (S:  0.62611) (V:  0.0527) 
info string h7c7  (1590) N:     176 (+ 0) (P: 12.37%) (WL:  0.02330) (D: 0.023) (M:  3.5) (Q:  0.02330) (U: 0.02289) (S:  0.04620) (V:  0.0237) 
info string node  (  25) N:     227 (+ 1) (P: 94.60%) (WL:  0.02170) (D: 0.018) (M:  3.9) (Q:  0.02170) (V:  0.0673) 
bestmove h7c7 ponder a5a4

`

Though the S of ‘h7a7’ is much higher than the S of ‘h7c7’, Lc0 keeps selecting ‘h7c7’ for further searches. Also Lc0 is visiting a much higher number of nodes than the number in the go nodes command.

**Comment by Naphthalin** [comment]
There are a few deviations from the general "explore highest S" rule. Among that

- to fill batches and make sure that multiple threads don't end up choosing the same leaf node, some deviations are intended
- even with a low node number, 1 batch will be evaluated; that's what you are seeing here
- smart pruning will prevent not so well explored moves from getting more visits. That's what you're seeing here as well; deactivate with `--smart-pruning-factor=0.0`
- we cache the highest S move to avoid recomputing U too often, but that estimation can be off under certain circumstances, likely happening here as well

Also, why are you using a T10 net?

**Comment by Rejwana** [comment]
@Naphthalin would you please elaborate

> we cache the highest S move to avoid recomputing U too often, but that estimation can be off under certain circumstances, likely happening here as well


I am using this net from a while ago as it had a very ELO rating. Do you suggest any other updated net?
Also does using T10 net has any impact on search exploration?

**Comment by Naphthalin** [comment]
> @Naphthalin would you please elaborate
> 
> > we cache the highest S move to avoid recomputing U too often, but that estimation can be off under certain circumstances, likely happening here as well
 
It's actually difficult to go into a bit more detail without entering TMI territory. The basic idea is that under the assumption of stable Q values, the U values change in a predictable fashion, and we estimate how many visits on the top node are needed until another node will be explored again. However, at these low numbers this isn't that relevant, and the most relevant aspect in your case is smart pruning.

> I am using this net from a while ago as it had a very ELO rating. Do you suggest any other updated net?
> Also does using T10 net has any impact on search exploration?

T10 is outdated for multiple reasons. It is much, much weaker than recent nets, significantly weaker in tactical positions, worse opening exploration, and no trained moves left head yet -- I recommend either the 703810 shipped with the recent release, or the big J92-330 which is playing in TCEC/CCC tournaments right now.

**Comment by Rejwana** [comment]
I kinda understand the basic idea. What I still can't figure out: the score printed in the verbose output is actual score after search or not?
According to your suggestion I deactivated smart pruning and got the output:
`

./lc0 --smart-pruning-factor=0.0 --backend=blas --verbose-move-stats=true
       _
|   _ | |
|_ |_ |_| v0.27.0-dev+git.unknown built Oct 24 2020
position fen 8/7Q/8/k1K5/8/8/4q3/8 w - - 0 1
go nodes 400
Found pb network file: ./weights_run1_10970.pb
Creating backend [blas]...
BLAS vendor: Apple vecLib.
BLAS max batch size is 256.
info depth 1 seldepth 2 time 767 nodes 3 score cp 7 nps 9 tbhits 0 pv h7a7 e2a6
info depth 2 seldepth 3 time 816 nodes 6 score cp 14 nps 17 tbhits 0 pv h7c7 a5a4 c7d7
info depth 2 seldepth 4 time 819 nodes 7 score cp 91 nps 19 tbhits 0 pv h7c7 a5a4 c7d7 a4a5
info depth 3 seldepth 4 time 1124 nodes 24 score cp 17 nps 36 tbhits 0 pv h7c7 a5a4 c7a7 a4b3
info depth 3 seldepth 5 time 1597 nodes 59 score cp 9 nps 52 tbhits 0 pv h7c7 a5a4 c5d4 e2d2 d4e4
info depth 3 seldepth 6 time 2531 nodes 184 score cp 5 nps 89 tbhits 0 pv h7c7 a5a4 c5d4 e2d2 d4e4
info depth 4 seldepth 7 time 3927 nodes 363 score cp 4 nps 104 tbhits 0 pv h7c7 a5a4 c7f4 a4b3 f4d4 e2e7
info depth 4 seldepth 7 time 4515 nodes 416 score cp 4 nps 102 tbhits 0 pv h7c7 a5a4 c7f4 a4b3 f4d4 e2e7
info string h7d3  (1578) N:       0 (+ 0) (P:  0.68%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.30586) (S: -0.11604) (V: -0.9125) 
info string h7h2  (1577) N:       0 (+ 0) (P:  0.69%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.30997) (S: -0.11193) (V: -0.7858) 
info string h7e4  (1580) N:       0 (+ 0) (P:  0.70%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.31280) (S: -0.10910) (V: -0.8173) 
info string h7c2  (1576) N:       0 (+ 0) (P:  0.75%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.33894) (S: -0.08295) (V: -0.9635) 
info string h7h5  (1584) N:       0 (+ 0) (P:  1.16%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.52342) (S:  0.10152) (V: -0.9423) 
info string h7e7  (1592) N:       1 (+ 0) (P:  1.42%) (WL: -0.92740) (D: 0.000) (M:  0.0) (Q: -0.92740) (U: 0.31803) (S: -0.60938) (V: -0.9274) 
info string h7f5  (1582) N:       2 (+ 0) (P:  3.42%) (WL: -0.56936) (D: 0.000) (M:  0.5) (Q: -0.56936) (U: 0.51227) (S: -0.05708) (V: -0.1723) 
info string h7h4  (1581) N:      12 (+ 0) (P:  3.67%) (WL: -0.01294) (D: 0.000) (M:  2.0) (Q: -0.01294) (U: 0.12682) (S:  0.11388) (V: -0.0174) 
info string h7h6  (1587) N:      14 (+ 1) (P:  3.38%) (WL:  0.00881) (D: 0.000) (M:  1.9) (Q:  0.00881) (U: 0.09502) (S:  0.10384) (V:  0.0167) 
info string c5d5  (966 ) N:      15 (+ 0) (P:  3.65%) (WL:  0.00432) (D: 0.067) (M:  2.0) (Q:  0.00432) (U: 0.10244) (S:  0.10676) (V:  0.0182) 
info string h7h1  (1575) N:      16 (+ 0) (P:  3.52%) (WL:  0.01144) (D: 0.000) (M:  1.8) (Q:  0.01144) (U: 0.09306) (S:  0.10450) (V:  0.0237) 
info string c5d4  (962 ) N:      16 (+ 0) (P:  3.63%) (WL:  0.00911) (D: 0.000) (M:  1.6) (Q:  0.00911) (U: 0.09593) (S:  0.10504) (V:  0.0242) 
info string c5c6  (973 ) N:      16 (+ 0) (P:  3.78%) (WL:  0.00692) (D: 0.000) (M:  1.7) (Q:  0.00692) (U: 0.09996) (S:  0.10688) (V:  0.0156) 
info string h7h3  (1579) N:      16 (+ 0) (P:  3.64%) (WL:  0.01150) (D: 0.000) (M:  1.9) (Q:  0.01150) (U: 0.09621) (S:  0.10771) (V: -0.0010) 
info string h7g6  (1586) N:      16 (+ 0) (P:  3.66%) (WL:  0.01178) (D: 0.000) (M:  2.0) (Q:  0.01178) (U: 0.09677) (S:  0.10856) (V: -0.0053) 
info string h7g8  (1596) N:      17 (+ 0) (P:  3.81%) (WL:  0.01126) (D: 0.000) (M:  1.9) (Q:  0.01126) (U: 0.09506) (S:  0.10631) (V:  0.0177) 
info string h7h8  (1597) N:      18 (+ 0) (P:  3.71%) (WL:  0.01314) (D: 0.000) (M:  2.2) (Q:  0.01314) (U: 0.08767) (S:  0.10082) (V:  0.0057) 
info string c5d6  (974 ) N:      18 (+ 1) (P:  4.27%) (WL:  0.00806) (D: 0.000) (M:  1.8) (Q:  0.00806) (U: 0.09591) (S:  0.10396) (V:  0.0239) 
info string h7b7  (1589) N:      20 (+ 0) (P:  4.05%) (WL:  0.01935) (D: 0.000) (M:  2.1) (Q:  0.01935) (U: 0.08660) (S:  0.10595) (V:  0.0500) 
info string h7g7  (1594) N:      22 (+ 0) (P:  4.79%) (WL:  0.01123) (D: 0.000) (M:  2.1) (Q:  0.01123) (U: 0.09356) (S:  0.10479) (V:  0.0149) 
info string h7d7  (1591) N:      23 (+ 0) (P:  4.90%) (WL:  0.01479) (D: 0.000) (M:  2.1) (Q:  0.01479) (U: 0.09178) (S:  0.10657) (V:  0.0291) 
info string h7f7  (1593) N:      24 (+ 1) (P:  5.31%) (WL:  0.01179) (D: 0.000) (M:  2.1) (Q:  0.01179) (U: 0.09174) (S:  0.10352) (V:  0.0223) 
info string h7b1  (1574) N:      28 (+ 0) (P:  5.52%) (WL:  0.01948) (D: 0.000) (M:  2.1) (Q:  0.01948) (U: 0.08560) (S:  0.10508) (V:  0.0489) 
info string h7a7  (1588) N:      45 (+ 0) (P: 13.62%) (WL:  0.03032) (D: 0.178) (M:  3.3) (Q:  0.03032) (U: 0.13304) (S:  0.16336) (V:  0.0528) (W) 
info string h7c7  (1590) N:      76 (+ 0) (P: 12.29%) (WL:  0.03266) (D: 0.000) (M:  2.9) (Q:  0.03266) (U: 0.07171) (S:  0.10437) (V:  0.0240) 
info string node  (  25) N:     416 (+ 3) (P: 96.01%) (WL:  0.01219) (D: 0.022) (M:  3.3) (Q:  0.01219) (V:  0.0687) 
bestmove h7c7 ponder a5a4
go nodes 500
info depth 5 seldepth 6 time 27754 nodes 433 score cp 4 tbhits 0 pv h7c7 a5a4 c7f4 a4b3 f4d4 e2e7
info depth 5 seldepth 7 time 28582 nodes 446 score cp 4 nps 32 tbhits 0 pv h7c7 a5a4 c7f4 a4b3 f4d4 e2e7
info depth 5 seldepth 8 time 28587 nodes 449 score cp 4 nps 36 tbhits 0 pv h7c7 a5a4 c7f4 a4b3 f4d4 e2e7
info depth 5 seldepth 8 time 28703 nodes 450 score cp 72 nps 32 tbhits 0 pv h7a7 e2a6 a7b8 a6c4 c5c4 a5a6
info depth 6 seldepth 9 time 29096 nodes 455 score cp 81 nps 26 tbhits 0 pv h7a7 e2a6 a7b8 a6c4 c5c4 a5a6 c4c5 a6a5 b8b5
info depth 6 seldepth 10 time 29097 nodes 459 score cp 85 nps 29 tbhits 0 pv h7a7 e2a6 a7b8 a6c6 c5c6 a5a6
info depth 6 seldepth 10 time 30622 nodes 500 score cp 150 nps 28 tbhits 0 pv h7a7 e2a6 a7b8 a6b6 b8b6 a5a4 b6b4
info string h7d3  (1578) N:       0 (+ 0) (P:  0.68%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.33719) (S:  0.07657) (V: -0.9125) 
info string h7h2  (1577) N:       0 (+ 0) (P:  0.69%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.34172) (S:  0.08111) (V: -0.7858) 
info string h7e4  (1580) N:       0 (+ 0) (P:  0.70%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.34484) (S:  0.08423) (V: -0.8173) 
info string h7c2  (1576) N:       0 (+ 0) (P:  0.75%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.37367) (S:  0.11305) (V: -0.9635) 
info string h7h5  (1584) N:       0 (+ 0) (P:  1.16%) (WL:  0.00000) (D: 0.000) (M:  0.0) (Q:  0.00000) (U: 0.57704) (S:  0.31642) (V: -0.9423) 
info string h7e7  (1592) N:       1 (+ 0) (P:  1.42%) (WL: -0.92740) (D: 0.000) (M:  0.0) (Q: -0.92740) (U: 0.35061) (S: -0.57680) (V: -0.9274) 
info string h7f5  (1582) N:       2 (+ 0) (P:  3.42%) (WL: -0.56936) (D: 0.000) (M:  0.5) (Q: -0.56936) (U: 0.56475) (S: -0.00461) (V: -0.1723) 
info string h7h4  (1581) N:      12 (+ 0) (P:  3.67%) (WL: -0.01294) (D: 0.000) (M:  2.0) (Q: -0.01294) (U: 0.13981) (S:  0.12687) (V: -0.0174) 
info string h7h6  (1587) N:      15 (+ 0) (P:  3.38%) (WL:  0.00800) (D: 0.000) (M:  1.9) (Q:  0.00800) (U: 0.10476) (S:  0.11275) (V:  0.0167) 
info string c5d5  (966 ) N:      15 (+ 0) (P:  3.65%) (WL:  0.00432) (D: 0.067) (M:  2.0) (Q:  0.00432) (U: 0.11293) (S:  0.11725) (V:  0.0182) 
info string h7h1  (1575) N:      16 (+ 0) (P:  3.52%) (WL:  0.01144) (D: 0.000) (M:  1.8) (Q:  0.01144) (U: 0.10260) (S:  0.11404) (V:  0.0237) 
info string c5d4  (962 ) N:      16 (+ 0) (P:  3.63%) (WL:  0.00911) (D: 0.000) (M:  1.6) (Q:  0.00911) (U: 0.10575) (S:  0.11487) (V:  0.0242) 
info string c5c6  (973 ) N:      16 (+ 0) (P:  3.78%) (WL:  0.00692) (D: 0.000) (M:  1.7) (Q:  0.00692) (U: 0.11020) (S:  0.11712) (V:  0.0156) 
info string h7h3  (1579) N:      16 (+ 0) (P:  3.64%) (WL:  0.01150) (D: 0.000) (M:  1.9) (Q:  0.01150) (U: 0.10607) (S:  0.11756) (V: -0.0010) 
info string h7g6  (1586) N:      16 (+ 0) (P:  3.66%) (WL:  0.01178) (D: 0.000) (M:  2.0) (Q:  0.01178) (U: 0.10669) (S:  0.11847) (V: -0.0053) 
info string h7g8  (1596) N:      17 (+ 0) (P:  3.81%) (WL:  0.01126) (D: 0.000) (M:  1.9) (Q:  0.01126) (U: 0.10479) (S:  0.11605) (V:  0.0177) 
info string h7h8  (1597) N:      18 (+ 0) (P:  3.71%) (WL:  0.01314) (D: 0.000) (M:  2.2) (Q:  0.01314) (U: 0.09665) (S:  0.10980) (V:  0.0057) 
info string c5d6  (974 ) N:      19 (+ 0) (P:  4.27%) (WL:  0.00700) (D: 0.000) (M:  1.8) (Q:  0.00700) (U: 0.10573) (S:  0.11273) (V:  0.0239) 
info string h7b7  (1589) N:      20 (+ 0) (P:  4.05%) (WL:  0.01935) (D: 0.000) (M:  2.1) (Q:  0.01935) (U: 0.09548) (S:  0.11483) (V:  0.0500) 
info string h7g7  (1594) N:      22 (+ 0) (P:  4.79%) (WL:  0.01123) (D: 0.000) (M:  2.1) (Q:  0.01123) (U: 0.10315) (S:  0.11438) (V:  0.0149) 
info string h7d7  (1591) N:      23 (+ 0) (P:  4.90%) (WL:  0.01479) (D: 0.000) (M:  2.1) (Q:  0.01479) (U: 0.10118) (S:  0.11597) (V:  0.0291) 
info string h7f7  (1593) N:      25 (+ 0) (P:  5.31%) (WL:  0.01107) (D: 0.000) (M:  2.2) (Q:  0.01107) (U: 0.10113) (S:  0.11220) (V:  0.0223) 
info string h7b1  (1574) N:      28 (+ 0) (P:  5.52%) (WL:  0.01948) (D: 0.000) (M:  2.1) (Q:  0.01948) (U: 0.09437) (S:  0.11385) (V:  0.0489) 
info string h7c7  (1590) N:      76 (+ 0) (P: 12.29%) (WL:  0.03266) (D: 0.000) (M:  2.9) (Q:  0.03266) (U: 0.07906) (S:  0.11171) (V:  0.0240) 
info string h7a7  (1588) N:     126 (+ 0) (P: 13.62%) (WL:  0.65912) (D: 0.063) (M:  5.3) (Q:  0.65912) (U: 0.05312) (S:  0.71224) (V:  0.0528) (W) 
info string node  (  25) N:     500 (+ 0) (P: 96.01%) (WL:  0.17346) (D: 0.018) (M:  3.9) (Q:  0.17346) (V:  0.0687) 
bestmove h7a7 ponder e2a6`

Here when I search 400 nodes the score of h7a7 is S:  0.16336  while searching only 100 nodes more changes it to S:  0.71224. It's a bit interesting to see that how the score drastically changes with only 100 more nodes searched.

**Comment by Naphthalin** [comment]
> What I still can't figure out: the score printed in the verbose output is actual score after search or not?

Yes.

> Here when I search 400 nodes the score of h7a7 is S: 0.16336 while searching only 100 nodes more changes it to S: 0.71224. It's a bit interesting to see that how the score drastically changes with only 100 more nodes searched.

As you see, at first the net evaluates `h7a7` as `Q=0.03`, same as the move `h7c7` and then discovers that it is totally winning. Meanwhile the `U` value goes down significantly (as it should), and the big `Q` increase causes the `S` increase.

**Comment by Rejwana** [comment]
It's now understandable. Thanks @Naphthalin
