### ISSUE TITLE
Building Lc0 on Ubuntu 18.04

### ISSUE THREAD

**Issue by ulliit** [LeelaChessZero/lc0#1463]
build works only with meson version 0.55.3! otherwise compiling breaks with

"TypeError: cannot deepcopy this pattern object"

this is probably caused by commit c20ef4b2d2518c7aaca14f95ac08ac493dcb37a4 "use meson 0.55.3 on appveyor since 0.56.0 is broken".

if meson was installed before with

$ pip3 install meson --user

reinstall with

$ pip3 install --force-reinstall meson==0.55.3

otherwise choose

$ pip3 install --user meson==0.55.3

check version with

$ meson --version

if the version command shows nothing, try adjusting the PATH with

$ export PATH=$PATH:/home/us/.local/bin

**Comment by dombrno** [comment]
Thanks, you saved my life! :)
