### ISSUE TITLE
Unhandled exception in worker thread: clSetKernelArg

### ISSUE THREAD

**Issue by nguyencongminh090** [LeelaChessZero/lc0#1464]
How can I fix this probelm? Can you help me?

**Comment by borg323** [comment]
The opencl backend has exposed issues with several drivers. Can you give us details of your gpu, cpu and operating system so we can offer the appropriate suggestions?

**Comment by nguyencongminh090** [comment]
I use Windows 7 64 bit.
GPU: Radeon (TM)  6490M HD
CPU: Intel(R) Core(TM) i7-2670QM CPU @2.20GHz
Thanks

**Comment by borg323** [comment]
Unfortunately your only alternative option is to use the cpu, the dnnl version will probably be the best for you.

**Comment by borg323** [comment]
OpenCL is not working for you, so DNNL is most likely the best.
