### ISSUE TITLE
Same number of nodes search on same position leads to different moves.

### ISSUE THREAD

**Issue by Rejwana** [LeelaChessZero/lc0#1467]
Searching same amount of nodes for same position using same hardware and same parameters leads to two different moves in two different runs. As all the parameters along with the same weightfile, it doesn't make any sense to get two different moves in different runs. Here is to log of two different runs.

> ./lc0 --smart-pruning-factor=0.0 --verbose-move-stats=true --weights=/weights/J92-330 --logfile=test_psn_log
       _
|   _ | |
|_ |_ |_| v0.27.0-dev+git.dirty built Nov 24 2020
position fen q7/1k6/8/Q1K5/8/8/8/8 w - - 0 1
go nodes 1200
Loading weights file from: /weights/J92-330
Creating backend [cudnn-auto]...
Switching to [cudnn-fp16]...
CUDA Runtime version: 10.2.0
Cudnn version: 7.6.5
Latest version of CUDA supported by the driver: 11.0.0
GPU: TITAN RTX
GPU memory: 23.6526 GiB
GPU clock frequency: 1770 MHz
GPU compute capability: 7.5
info depth 1 seldepth 2 time 10653 nodes 5 score cp 1 nps 357 tbhits 0 pv a5b5 b7c7
info depth 2 seldepth 3 time 10661 nodes 54 score cp 0 nps 2454 tbhits 0 pv a5a8 b7a8
info depth 3 seldepth 4 time 10676 nodes 98 score cp 0 nps 2578 tbhits 0 pv a5a8 b7a8
info depth 3 seldepth 5 time 10691 nodes 108 score cp 0 nps 2076 tbhits 0 pv a5a8 b7a8
info depth 4 seldepth 6 time 10704 nodes 173 score cp 5 nps 2621 tbhits 0 pv a5b5 b7c7 b5b6 c7c8 b6e6 c8c7
info depth 4 seldepth 7 time 10726 nodes 319 score cp 8 nps 3625 tbhits 0 pv a5b4 b7c8 b4g4 c8b8 g4g8 b8a7 g8a2
info depth 4 seldepth 8 time 10741 nodes 349 score cp 18 nps 3388 tbhits 0 pv a5b6 b7c8 b6e6 c8b8 e6e5 b8a7 e5a1 a7b7
info depth 5 seldepth 10 time 10756 nodes 485 score cp 13 nps 4145 tbhits 0 pv a5b6 b7c8 b6e6 c8b8 e6d6 b8c8 d6c6 a8c6 c5c6
info depth 5 seldepth 11 time 10842 nodes 1265 score cp 13 nps 6231 tbhits 0 pv a5b4 b7c8 b4g4 c8b8 g4g3 b8c8 g3g8 c8b7 g8g7 b7c8 g7f8
info string a5c7  (918 ) N:       1 (+ 0) (P:  0.91%) (WL: -0.99902) (D: 0.001) (M: 11.5) (Q: -0.99902) (U: 0.37677) (S: -0.62225) (V: -0.9990) 
info string a5a6  (913 ) N:       1 (+ 0) (P:  0.92%) (WL: -1.00000) (D: 0.000) (M: 16.7) (Q: -1.00000) (U: 0.38087) (S: -0.61913) (V: -1.0000) 
info string a5a7  (916 ) N:       1 (+ 0) (P:  1.00%) (WL: -1.00000) (D: 0.000) (M: 21.2) (Q: -1.00000) (U: 0.41382) (S: -0.58618) (V: -1.0000) 
info string a5a2  (898 ) N:       1 (+ 0) (P:  1.02%) (WL: -0.99951) (D: 0.001) (M: 13.9) (Q: -0.99951) (U: 0.42060) (S: -0.57891) (V: -0.9995) 
info string a5a4  (903 ) N:       1 (+ 0) (P:  1.00%) (WL: -0.99267) (D: 0.007) (M: 11.2) (Q: -0.99267) (U: 0.41429) (S: -0.57838) (V: -0.9927) 
info string a5d8  (920 ) N:       1 (+ 0) (P:  1.12%) (WL: -1.00000) (D: 0.000) (M:  8.9) (Q: -1.00000) (U: 0.46269) (S: -0.53731) (V: -1.0000) 
info string a5a3  (900 ) N:       1 (+ 0) (P:  1.16%) (WL: -1.00000) (D: 0.000) (M: 10.6) (Q: -1.00000) (U: 0.47829) (S: -0.52171) (V: -1.0000) 
info string a5a1  (896 ) N:       1 (+ 0) (P:  1.32%) (WL: -0.99951) (D: 0.001) (M: 14.2) (Q: -0.99951) (U: 0.54372) (S: -0.45579) (V: -0.9995) 
info string c5d4  (962 ) N:       1 (+ 0) (P:  1.43%) (WL: -1.00000) (D: 0.000) (M: 14.1) (Q: -1.00000) (U: 0.58928) (S: -0.41072) (V: -1.0000) 
info string c5d5  (966 ) N:       1 (+ 0) (P:  1.52%) (WL: -1.00000) (D: 0.000) (M: 13.7) (Q: -1.00000) (U: 0.62758) (S: -0.37242) (V: -1.0000) 
info string c5d6  (974 ) N:       1 (+ 0) (P:  1.56%) (WL: -0.99609) (D: 0.004) (M: 12.2) (Q: -0.99609) (U: 0.64634) (S: -0.34975) (V: -0.9961) 
info string c5c4  (961 ) N:       1 (+ 0) (P:  1.98%) (WL: -1.00000) (D: 0.000) (M: 13.3) (Q: -1.00000) (U: 0.81818) (S: -0.18182) (V: -1.0000) 
info string c5b5  (965 ) N:      29 (+ 0) (P:  4.93%) (WL:  0.00027) (D: 0.998) (M: 44.9) (Q:  0.00027) (U: 0.13574) (S:  0.13601) (V: -0.0002) 
info string c5b4  (960 ) N:      38 (+ 0) (P:  6.51%) (WL:  0.00013) (D: 1.000) (M: 52.4) (Q:  0.00013) (U: 0.13795) (S:  0.13808) (V: -0.0002) 
info string a5d2  (899 ) N:      45 (+ 0) (P:  7.36%) (WL:  0.00409) (D: 0.996) (M: 64.2) (Q:  0.00409) (U: 0.13226) (S:  0.13634) (V: -0.0001) 
info string a5c3  (902 ) N:      50 (+ 0) (P:  7.93%) (WL:  0.01015) (D: 0.990) (M: 65.8) (Q:  0.01015) (U: 0.12849) (S:  0.13864) (V: -0.0003) 
info string a5e1  (897 ) N:      54 (+ 0) (P:  7.70%) (WL:  0.01838) (D: 0.982) (M: 62.3) (Q:  0.01838) (U: 0.11566) (S:  0.13404) (V: -0.0003) 
info string a5a8  (919 ) N:      71 (+ 0) (P: 10.54%) (WL:  0.01408) (D: 0.986) (M:  1.1) (Q:  0.01408) (U: 0.12104) (S:  0.13512) (V:  0.0000) (L) 
info string a5b5  (906 ) N:     159 (+ 0) (P: 11.95%) (WL:  0.06157) (D: 0.938) (M: 62.7) (Q:  0.06157) (U: 0.06173) (S:  0.12331) (V:  0.0099) 
info string a5b6  (914 ) N:     345 (+ 0) (P: 15.92%) (WL:  0.08260) (D: 0.917) (M: 53.0) (Q:  0.08260) (U: 0.03804) (S:  0.12064) (V:  0.0038) 
info string a5b4  (904 ) N:     461 (+ 1) (P: 12.22%) (WL:  0.09259) (D: 0.899) (M: 58.5) (Q:  0.09259) (U: 0.02181) (S:  0.11440) (V:  0.0011) 
info string node  (  21) N:    1265 (+ 1) (P: 100.0%) (WL:  0.05670) (D: 0.921) (M: 55.0) (Q:  0.05670) (V:  0.0402) 
bestmove a5b4 ponder b7c8

For the second run:

> ./lc0 --smart-pruning-factor=0.0 --verbose-move-stats=true --weights=/weights/J92-330 --logfile=test_psn_log
       _
|   _ | |
|_ |_ |_| v0.27.0-dev+git.dirty built Nov 24 2020
position fen q7/1k6/8/Q1K5/8/8/8/8 w - - 0 1
go nodes 1200
Loading weights file from: /weights/J92-330
Creating backend [cudnn-auto]...
Switching to [cudnn-fp16]...
CUDA Runtime version: 10.2.0
Cudnn version: 7.6.5
Latest version of CUDA supported by the driver: 11.0.0
GPU: TITAN RTX
GPU memory: 23.6526 GiB
GPU clock frequency: 1770 MHz
GPU compute capability: 7.5
info depth 1 seldepth 2 time 21289 nodes 5 score cp 1 nps 384 tbhits 0 pv a5b5 b7c7
info depth 2 seldepth 3 time 21297 nodes 54 score cp 0 nps 2571 tbhits 0 pv a5a8 b7a8
info depth 3 seldepth 4 time 21312 nodes 98 score cp 0 nps 2648 tbhits 0 pv a5a8 b7a8
info depth 3 seldepth 5 time 21319 nodes 106 score cp 0 nps 2409 tbhits 0 pv a5a8 b7a8
info depth 4 seldepth 6 time 21340 nodes 175 score cp 5 nps 2692 tbhits 0 pv a5b5 b7c7 b5b6 c7c8 b6e6 c8c7
info depth 4 seldepth 7 time 21362 nodes 294 score cp 11 nps 3379 tbhits 0 pv a5b4 b7c8 b4g4 c8b8 g4g8 b8a7 g8a2
info depth 4 seldepth 8 time 21377 nodes 319 score cp 18 nps 3127 tbhits 0 pv a5b6 b7c8 b6e6 c8b8 e6e5 b8a7 e5a1 a7b7
info depth 5 seldepth 10 time 21399 nodes 492 score cp 13 nps 3967 tbhits 0 pv a5b6 b7c8 b6e6 c8b8 e6d6 b8c8 d6c6 a8c6 c5c6
info depth 5 seldepth 11 time 21446 nodes 977 score cp 11 nps 5713 tbhits 0 pv a5b6 b7c8 b6e6 c8b8 e6e8 b8a7 e8e7 a8b7 e7b7 a7b7
info depth 5 seldepth 11 time 21472 nodes 1326 score cp 11 nps 6730 tbhits 0 pv a5b6 b7c8 b6e6 c8b8 e6e8 b8a7 e8e7 a8b7 e7b7 a7b7
info string a5c7  (918 ) N:       1 (+ 0) (P:  0.91%) (WL: -0.99902) (D: 0.001) (M: 11.5) (Q: -0.99902) (U: 0.38715) (S: -0.61187) (V: -0.9990) 
info string a5a6  (913 ) N:       1 (+ 0) (P:  0.92%) (WL: -1.00000) (D: 0.000) (M: 16.7) (Q: -1.00000) (U: 0.39136) (S: -0.60864) (V: -1.0000) 
info string a5a7  (916 ) N:       1 (+ 0) (P:  1.00%) (WL: -1.00000) (D: 0.000) (M: 21.2) (Q: -1.00000) (U: 0.42522) (S: -0.57478) (V: -1.0000) 
info string a5a2  (898 ) N:       1 (+ 0) (P:  1.02%) (WL: -0.99951) (D: 0.001) (M: 13.9) (Q: -0.99951) (U: 0.43218) (S: -0.56733) (V: -0.9995) 
info string a5a4  (903 ) N:       1 (+ 0) (P:  1.00%) (WL: -0.99267) (D: 0.007) (M: 11.2) (Q: -0.99267) (U: 0.42570) (S: -0.56696) (V: -0.9927) 
info string a5d8  (920 ) N:       1 (+ 0) (P:  1.12%) (WL: -1.00000) (D: 0.000) (M:  8.9) (Q: -1.00000) (U: 0.47543) (S: -0.52457) (V: -1.0000) 
info string a5a3  (900 ) N:       1 (+ 0) (P:  1.16%) (WL: -1.00000) (D: 0.000) (M: 10.6) (Q: -1.00000) (U: 0.49147) (S: -0.50853) (V: -1.0000) 
info string a5a1  (896 ) N:       1 (+ 0) (P:  1.32%) (WL: -0.99951) (D: 0.001) (M: 14.2) (Q: -0.99951) (U: 0.55870) (S: -0.44081) (V: -0.9995) 
info string c5d4  (962 ) N:       1 (+ 0) (P:  1.43%) (WL: -1.00000) (D: 0.000) (M: 14.1) (Q: -1.00000) (U: 0.60551) (S: -0.39449) (V: -1.0000) 
info string c5d5  (966 ) N:       1 (+ 0) (P:  1.52%) (WL: -1.00000) (D: 0.000) (M: 13.7) (Q: -1.00000) (U: 0.64487) (S: -0.35513) (V: -1.0000) 
info string c5d6  (974 ) N:       1 (+ 0) (P:  1.56%) (WL: -0.99609) (D: 0.004) (M: 12.2) (Q: -0.99609) (U: 0.66415) (S: -0.33194) (V: -0.9961) 
info string c5c4  (961 ) N:       1 (+ 0) (P:  1.98%) (WL: -1.00000) (D: 0.000) (M: 13.3) (Q: -1.00000) (U: 0.84072) (S: -0.15928) (V: -1.0000) 
info string c5b5  (965 ) N:      32 (+ 6) (P:  4.93%) (WL:  0.00026) (D: 0.998) (M: 44.9) (Q:  0.00026) (U: 0.10729) (S:  0.10755) (V: -0.0002) 
info string c5b4  (960 ) N:      43 (+ 7) (P:  6.51%) (WL:  0.00017) (D: 1.000) (M: 52.4) (Q:  0.00017) (U: 0.10840) (S:  0.10857) (V: -0.0002) 
info string a5d2  (899 ) N:      48 (+10) (P:  7.36%) (WL:  0.00383) (D: 0.996) (M: 63.3) (Q:  0.00383) (U: 0.10596) (S:  0.10978) (V: -0.0001) 
info string a5c3  (902 ) N:      54 (+13) (P:  7.93%) (WL:  0.00941) (D: 0.991) (M: 66.2) (Q:  0.00941) (U: 0.09902) (S:  0.10844) (V: -0.0003) 
info string a5e1  (897 ) N:      61 (+10) (P:  7.70%) (WL:  0.01807) (D: 0.982) (M: 61.4) (Q:  0.01807) (U: 0.09079) (S:  0.10886) (V: -0.0003) 
info string a5a8  (919 ) N:      90 (+ 0) (P: 10.54%) (WL:  0.01111) (D: 0.989) (M:  1.1) (Q:  0.01111) (U: 0.09840) (S:  0.10951) (V:  0.0000) (L) 
info string a5b5  (906 ) N:     181 (+36) (P: 11.95%) (WL:  0.06049) (D: 0.939) (M: 62.8) (Q:  0.06049) (U: 0.04656) (S:  0.10705) (V:  0.0099) 
info string a5b4  (904 ) N:     388 (+117) (P: 12.22%) (WL:  0.08811) (D: 0.902) (M: 58.7) (Q:  0.08811) (U: 0.02051) (S:  0.10862) (V:  0.0011) 
info string a5b6  (914 ) N:     416 (+57) (P: 15.92%) (WL:  0.08318) (D: 0.917) (M: 53.0) (Q:  0.08318) (U: 0.02853) (S:  0.11171) (V:  0.0038) 
info string node  (  21) N:    1326 (+256) (P: 100.0%) (WL:  0.05324) (D: 0.926) (M: 54.2) (Q:  0.05324) (V:  0.0402) 
bestmove a5b6 ponder b7c8

The number of visit count of nodes a5b4 and a5b6 are very different in the two runs. Also the search suggest a5b4 to be the best move in one run while a5b6 in another.

**Comment by Naphthalin** [comment]
Thanks for your report. Please note that the search of Lc0 is non-deterministic through multithreading and batching. You can retry the same search with including the `-t 1` option which will make the search deterministic (assuming a fixed batch size), but a bit slower.

This is expected and intended behavior.

**Comment by borg323** [comment]
There are ways to make multi-threaded tree search deterministic but have considerable overhead. Given that we are already limited by search speed on fast gpus, this isn't something we are likely to consider implementing.
