### ISSUE TITLE
LC0 on arena not working 

### ISSUE THREAD

**Issue by AlexWithYou** [LeelaChessZero/lc0#1469]
I use the guide to setting up leela on chess GUI to setting up leela zero on Arena

Here is the process I follow
`Command Line : C:\Games\Chess\Arena\Engines\LC0\lc0.exe`
`Command Line Parameters: --weights=703810.pb.gz`
`Type: UCI`
I was using newest leela zero version V0.26.3 [https://lczero.org/play/download/](url)
I unzip all the file into the folder. I didn't change the neural network.
When I clicked 'Start this engine right now!' The GUI seems not reponding at all. Because no calculation steps showing like stockfish. Anything I can do?

**Comment by Naphthalin** [comment]
For technical support, please use the Lc0 Discord at https://lc0.org/chat
The GitHub issues are for issues directly concerning the engine.
