### ISSUE TITLE
Cannot use cudnn-fp16 backend on P100 (and similar)

### ISSUE THREAD

**Issue by cn4750** [LeelaChessZero/lc0#148]
Tesla P100, Quadro GP100, and Jetson TX1/TX2 cards support full-speed fp16 math, but cannot use the backend:
```
terminate called after throwing an instance of 'lczero::Exception'
  what():  Your GPU doesn't support FP16
```
Is it due to this?
https://github.com/LeelaChessZero/lc0/blob/e4d0123b5223879f435713ae5ddd0fe971570dd3/src/neural/network_cudnn.cu#L980-L985

**Comment by TollerTyp** [comment]
I'm using --backend-opts="x(backend=cudnn-fp16,gpu=0)" at V100 GPU and it's working fine.

**Comment by cn4750** [comment]
@TollerTyp, V100 works fine. The above mentioned cards do not due to their lack of tensor cores.

**Comment by mooskagh** [comment]
Is this still an issue?
Closing for now. If it's an issue, please reopen.
