### ISSUE TITLE
TSAN found issues (2021-01-10).

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lc0#1486]
1) GetBestChildrenNoTemperature doesn't check GetN() > 0 before accessing Edges() for input, or similarly before accessing IsTerminal for edges.
2) PopulateCommonIterationStats similarly doesn't check GetN() > 0.
3) GetTwoFoldDraws isn't cached at SearchParams construction time, but is accessed from multiple threads during search (and options dict is not technically thread safe).
4) std::localtime is used in FormatTime called from the logger, which can be called from arbitrary threads - but std::localtime is non-threadsafe.
5) FetchSingleNodeResult doesn't check node_to_process.IsCollision - which means it falls through to nn_requested and accesses the node despite it being a collision target.
6) PopulateCommonIterationStats writes 'now' to nps_start_time_, potentially from multiple threads simultaneously. (tsan registered two writes one of 8 bytes and one of 1 byte - but this is the only written shared state I can see, I thought a time_point was only 8 bytes...)
7) Selfplay game performs make move before destroying the search instance. (Thus pending shared collisions can be run against a deleted tree.)

**Comment by mooskagh** [comment]
Can be closed?

**Comment by Tilps** [comment]
yes.
