### ISSUE TITLE
Optimize windows build

### ISSUE THREAD

**Issue by SunnyWar** [LeelaChessZero/lc0#149]
The windows project files do not have optimal compiler/linker settings to produce the fastest possible code. For example, these are the times for chessboard_test.exe

default | optimizations on | optimization plus pogo
50150 | 36851 | 35495
41961 | 36680 | 36380
42125 | 37126 | 37142
42928 | 36372 | 35982
45452 | 36763 | 35956
42281 | 37037 | 35829
42747 | 36424 | 37074
42358 | 36275 | 36207
42497 | 37329 | 36612
41587 | 36592 | 37084
average
43408.6 | 36744.9 | 36376.1

Change the project setting produces over 15% faster code. Specifically these additional flags

compiler: /Oi /GL /Gy
linker: /OPT:REF /OPT:ICF

Doing an additional Profile Guided Optimization produced only an additional 1% performance.

Finally, I noticed the the /fp:precise flag is set.  I don't understand the need precise floating point math. Is it really necessary to have the all operations exact down to the last digit? There are parts of the code would be more fully optimized if the projects used: fp:/fast.

**Comment by SunnyWar** [comment]
Just to get a feel for the possible benefit, I ran chessboard_test.exe before profile guided optimization and after on my laptop.

Before: 40146 ms 
After: 36804 ms

I don't know if this represents a body of code that needs to be optimized for speed or not. I'd be happy to run a test on anything else (now that I can build leela) and report the numbers.

**Comment by mooskagh** [comment]
@borg323 do you know if that's already implemented?

**Comment by borg323** [comment]
On appveyor we use VS default "Release" flags, and only do "whole program optimization" for release builds. So for the compiler /Oi is included (with /O2), /Gy is always set and /GL is set for release builds. For the linker /OPT:REF is always used, which does some of the /OPT:ICF work. I don't know whether /OPT:ICF would bring any additional benefit in our case, but I suppose it wouldn't hurt. The same for /fp:fast. The speed gains are marginal for actual game play, the gains reported here are for the tests.

I have a medium term plan to consolidate the windows build scripts, where I can add these as defaults.

**Comment by SunnyWar** [comment]
This work was done on chessboard_test.exe therefore closing this.
