### ISSUE TITLE
Implement benchmarks in lc0

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#15]
_From @mooskagh on May 4, 2018 11:38_

Implement the following benchmarks in "new" `lc0`:

- Perft (already implemented in tests)
- Running backend computation in loop without MCTS
- "nodes 130000" from starting position
- Something which evaluates precision of NN evaluation by backend, but I don't know where to get ground truth from.

_Copied from original issue: glinscott/leela-chess#527_

**Comment by mooskagh** [comment]
_From @cn4750 on May 22, 2018 14:33_

For a benchmark command, something that tests a variety of positions from the early, middle, and late game would be best. Ideally, something like what Stockfish uses [here](https://github.com/official-stockfish/Stockfish/blob/master/src/benchmark.cpp).

**Comment by mooskagh** [comment]
_From @CMCanavessi on May 22, 2018 15:48_

A nice option too would be to run the benchmark routine the 1st time it's launched and create a config file with the best parameters? Or maybe optional, similar to --tuner

**Comment by jjoshua2** [comment]
It should be easy to try several values of maxprefetch. And see if 512 batchsize is more than say 1% faster to use that...

**Comment by mooskagh** [comment]
I think this one is kind of done, which positions to use can be discussed in #215.
