### ISSUE TITLE
Can't download the trainingdata-tool binary

### ISSUE THREAD

**Issue by lzanini** [LeelaChessZero/lc0#1506]
It is currently impossible to download the binary to generate training data from PGN's, from the [link](https://ci.appveyor.com/api/buildjobs/wd7cagmgvd7dknal/artifacts/build%2FRelease%2Ftrainingdata-tool.exe) in [this guide](https://docs.google.com/document/d/1pB2MtqVVgYC2BwJbIrVvP2xWe5KIFFVteEqZroMf20E/edit#).

Error message:

`{"message":"Artifact not found or access denied."}`

**Comment by cn4750** [comment]
That guide is written by a member of the community but is not an official guide by the LCZero project and is not maintained by us.
