### ISSUE TITLE
Invalid move

### ISSUE THREAD

**Issue by fohristiwhirl** [LeelaChessZero/lc0#1517]
Found on lc0-cuda:

```
uci
ucinewgame
position fen rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1 moves e2e4 e7e5
go infinite

error Invalid move!
```

**Comment by Tilps** [comment]
Fixed this case by #1518 -  but #1518 itself didn't fix all possible cases.

**Comment by Naphthalin** [comment]
Did #1519 solve this issue?

**Comment by Tilps** [comment]
If it doesn't its magic - since the line of code that raises Invalid move! no longer exists ;)

**Comment by fohristiwhirl** [comment]
Fixed afaik. I'll close this.
