### ISSUE TITLE
MacOS, brew install issues

### ISSUE THREAD

**Issue by nguyenpham** [LeelaChessZero/lc0#1549]
I have tried installing Lc0 0.27 as the guide from lczero.org as the following image:

<img width="511" alt="Screen Shot 2021-03-20 at 9 20 56 pm" src="https://user-images.githubusercontent.com/1370755/111866625-f14dca80-89c2-11eb-8148-0b86d32fdf56.png">

The installation was quick without any error message, Lc0 can start. However, there are some issues:
- it can't compute since missing the network. I have checked, there is not the network 42850 in the installed folder (/usr/local/bin)
- I have tried to download 703810.pb.gz to that folder (the same folder as Lc0), but Lc0 can't auto-detect it. I must specify it (via setoption) and Lc0 can compute after that
- Lc0 prints its version as "v0.27.0+git.dirty built Feb 21 2021". It is not a big deal but look like an unofficial one

**Comment by pvaibhav** [comment]
Same issue.. how to fix it? Any instructions? I'm a complete beginner.

**Comment by nguyenpham** [comment]
> Same issue.. how to fix it? Any instructions? I'm a complete beginner.

You may watch my tutorial video for beginners: https://www.youtube.com/watch?v=TIn5kM3Eta0&t=6s&ab_channel=BanksiaGUI

**Comment by pvaibhav** [comment]
Thanks. I copied the network, and also added the setoption. But lc0 still doesn't make any moves.

**Comment by neongreen** [comment]
> The homebrew package includes ... network 42850

Can confirm, there doesn't seem to be a network anywhere so at least this part of the manual is wrong.

**Comment by neongreen** [comment]
FWIW it's not obvious how to get a network at all. The two networks recommended at https://lczero.org/play/networks/bestnets/ are more than a year old.
