### ISSUE TITLE
Tree reuse is not saving TB hit nodes

### ISSUE THREAD

**Issue by AndrewTCEC** [LeelaChessZero/lc0#1557]
When Leela uses tree reuse feature after a move, somehow all the TB Hit nodes are lost. Is it intended or not?

**Comment by Naphthalin** [comment]
With tree reuse, depth, average depth and other stats like TB hits only refer to the new nodes searched. This is more or less unavoidable, as there is no way to know whether old TB hits happened in the subtree of the actual game, or whether it happened when searching alternative moves.

**Comment by AndrewTCEC** [comment]
Thanks for explanation @Naphthalin. Closing this issue.
