### ISSUE TITLE
Improve performance on Apple M1 chip

### ISSUE THREAD

**Issue by lex312** [LeelaChessZero/lc0#1562]
Run LC0 on the NPU / neural engine 16 cores.

Apple is using tensor flow. We should see the same performance as one RTX 2080 Ti.

**Comment by oscardssmith** [comment]
That is an unrealistic performance expectation. The M1 has about 1.2 TFLOPS compared to about 27 TFLOPS for a 2080ti.

**Comment by lex312** [comment]
@oscardssmith,

It looks like LC0 need some improvements: 
https://forums.macrumors.com/threads/apple-m1-cpu-gpu-speed-is-very-disappointing.2293062/page-18

Someone would need to do a code review to give an in-depth explanation, but the initial observation is that LC0 is not developed or tested for M1 (or for Mac for what matters), does not use the correct APIs and most likely does not use the GPU at all.

**Comment by oscardssmith** [comment]
It's not worth writing special code for m1, when the performance will suck anyway. The m1 gpu (like all igp) is not powerful. Writing special code for m1 gpu would probably make it 2 to 5x faster, but it will still be slow compared to a real gpu.

**Comment by fahadrahman** [comment]
> It's not worth writing special code for m1, when the performance will suck anyway. The m1 gpu (like all igp) is not powerful. Writing special code for m1 gpu would probably make it 2 to 5x faster, but it will still be slow compared to a real gpu.

even if it's improve 1% we should consider it. 5x is no joke. Also there will be future apple chips like M2 which most likely coming with 32 core GPU compare to 8 now.

**Comment by oscardssmith** [comment]
If you want to write the custom NN inference code for Lc0 on M1 GPU, go right ahead. All I'm saying is so long as there isn't an ARM based mac with a good enough GPU (2060 level or so), this will be an extremely low priority.

**Comment by lex312** [comment]
@fahadrahman 
@oscardssmith 

LC0 is reaching 0.3K now.
5x faster = 1.5K with 8 GPU cores
But the Apple M1X/ will use 32 GPU cores.

1.5K x 4 = 6K !!

Okay it’s still slower than a RTX 2060 with 17.5K but other improvements can be found later too.
Or everybody can analyse 3 seconds in every position instead of only 1 second and he/she will reach the same performance.

Don’t forget that the next chip which will be at the end of 2022/ beginning of 2023 will have 64 GPU cores.
This will change the 6K into 12K :)

**Comment by oscardssmith** [comment]
You're assuming that it will have enough thermal headroom to run it at the same speed. More importantly,  32 gpu cores is still a rumor. Once the M2 is released and there are other GPU benchmarks for it, you might get more interest. Also the 5x estimate I gave isn't an exact number. It is a very rough estimate. The other problem is that developing a Lc0 backend without having the computer is hard. If you want to write the special code, go ahead, but don't be surprised if it doesn't happen quickly.

**Comment by ankan-ban** [comment]
I played around with M1 recently and tested performance of Apple's veclib (colas and bnns). 

I have some very small directed tests here:
https://github.com/ankan-ban/AppleMatmulTest

With FP32 datatype, I was able to achieve about 1.3TFlops peak performance for 512x512x512 gemm and similar performance for a big convolution. I tried fp16 datatype, but it didn't work for the gem (I get error code of -1, without any hint of what's wrong!). For convolutions, it ran slower than FP32. Maybe I am not passing the data in the right layout?
Again this is the first time I am using a Mac so progress has been very slow and I would appreciate any help to improve the performance of my directed tests.

Once I am confident that I am using the fastest available libraries with the right data-type and layout, I plan to attempt making a new backend for Mac/M1 which which hopefully would run much faster than current version.

For the Winograd convolution we use in other backends, we need a batched GEMM where M=4*minibatch-size, N=384, K=384 (filter count), and batch-size of 36 for the GEMM. For this particular problem size (assuming minibatch-size of 256) I get ~900 Gflops using BNNS library with fp32 datatype.

Another thing to try would be using the M1's GPU - which is supposed to have 2.6Tflops of peak FP32 performance (and same fp16 performance) as discussed here:
https://www.realworldtech.com/forum/?threadid=197759&curpostid=197759

**Comment by ankan-ban** [comment]
Also, I am not sure if my test is making any use of the Apple Neural Engine (That they advertise to have 11 Tops of peak performance). 
From what I could gather BNNS and CBLAS libraries don't use the neural engine, but 1.3TFlops of regular floating point performance seems a bit unlikely from such a small chip so it's possible that they are somehow making use of them.

It seems the only way to make use of the neural engine is to use high level CoreML APIs and I couldn't find any example or documentation on how to use them with C++. I only need support  for batched GEMM. Any help or pointers would be greatly appreciated. Really want to see my thin and light M1 Macbook air hit 11 Tops (or ~5+ FP16 TFlops).

**Comment by ValZapod** [comment]
> Apple Neural Engine

No, those are in special instruction set that is propriteray to ARMv8. See: https://gist.github.com/dougallj/7a75a3be1ec69ca550e7c36dc75e0d6f

> such a small chip

You do understand it is 5 nm?? It is not small.

**Comment by oscardssmith** [comment]
It's 16 billion transistors for cpu+gpu+memory (compared to 19 billion for an and 5600x CPU or 13 billion for an rtx 3060 not counting memory)

**Comment by lex312** [comment]
Can we expect any changes or improvements now that Apple MacBook Pro 16-inch with M1 MAX chip and 32 GPU cores has arrived?
Take a look at macrumors too. They have a lot of very interesting chess engine discussions.

**Comment by AviKav** [comment]
> > Apple Neural Engine
> 
> No, those are in special instruction set that is propriteray to ARMv8. See: https://gist.github.com/dougallj/7a75a3be1ec69ca550e7c36dc75e0d6f
> 

Note that this gist is about AMX which is completely separate from the Neural Engine

**Comment by Playerrrrr** [comment]
now that we have m3, which back-end should we be using to improve the performance?
