### ISSUE TITLE
Smooth time manager should use piggybank then the eval for the current bestmove rapidly drops

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#1582]
In TCEC 2021 DivP game 10 (vs Stockfish), Lc0 found the move 27.Bxf8 which initially had a very high eval. Later during the search, Lc0 found a tactical refutation so the eval started to drop rapidly. 

However, Lc0 still made the move before Q dropped low enough for this move not to be the best, making possibly blunder move.

In such cases, it makes sense to trigger piggybank time usage.

Similar behaviour may be useful when some of the moves that are currently not the best, start to rapidly raise eval.

**Comment by borg323** [comment]
I tried something similar (but with smart pruning) in #1534.

**Comment by Naphthalin** [comment]
As smooth time manager isn't maintained actively, can this be closed?
