### ISSUE TITLE
Neural net training

### ISSUE THREAD

**Issue by vibranium21** [LeelaChessZero/lc0#1589]
in the training wiki for  training an nn it says python 3.9 might not be compatible, has it been resolved if  yes or no, because one command went wrong and i thin it could be that

**Comment by mooskagh** [comment]
With questions like that, I'd suggest to join our Discord chat at http://lc0.org/chat and ask there in the #help channel.

**Comment by vibranium21** [comment]
link not working

**Comment by mooskagh** [comment]
Works for me, but here is the direct link without redirect: https://discord.gg/pKujYxD
