### ISSUE TITLE
meson.build:398:6: ERROR: Include dir /usr/include/ does not exist.

### ISSUE THREAD

**Issue by Saikatsaha1996** [LeelaChessZero/lc0#1602]
Got error android termux
What is OpenCL run-time dependency?
OpenCL found but OpenCL runtime dependency not found why?
![Screenshot_2021-07-12-22-02-06-118_com termux](https://user-images.githubusercontent.com/72664192/125325302-65d7bb00-e35e-11eb-9a7c-7023948b35a7.jpg)

**Comment by mooskagh** [comment]
Do you know where the "main" include directory is located in android?
What happens actually is it tries to find dnnl libs there.

**Comment by borg323** [comment]
The issue here is with OpenCL. You should set the `opencl_include` build variable to the correct directory (the one containing the `CL` directory with the header files. The alternative is to disable the opencl backend.

**Comment by Saikatsaha1996** [comment]
> Do you know where the "main" include directory is located in android?
> What happens actually is it tries to find dnnl libs there.

I don't know where is android include directory
I know only android vendor , system, lib, lib64 directory
