### ISSUE TITLE
calc error on ubuntu20.04

### ISSUE THREAD

**Issue by zhangpy** [LeelaChessZero/lc0#1606]
![e1](https://user-images.githubusercontent.com/52045/126100876-74aa1502-a4d8-43ca-a056-125f87e5588a.png)

I build v0.27 or master branch on ubuntu 20.04, the calc result seems wrong. (the max value should be 55)
But on ubuntu 16.04, it is correct. 
The networks file is from https://www.comp.nus.edu.sg/~sergio-v/t40/256x20/
If you need more info, please let me know it.

**Comment by AndrewTCEC** [comment]
I don't see any anomalies. Maybe you need to switch the lines of moves in GUI to show  "Win %" instead of "Nodes %"? This is done internally though GUI and has nothing to do with Lc0 engine itself.

**Comment by zhangpy** [comment]
Oh, yes. I remove previous config folder and restart. It is correct now. 
Thanks @AndrewTCEC
