### ISSUE TITLE
Crash in 0.28-rc1

### ISSUE THREAD

**Issue by rooklift** [LeelaChessZero/lc0#1619]
This seems to crash 0.28 (tested with cuda and dx12)

```
position fen rnbqkb1r/ppp2ppp/3p1n2/4p3/4P3/2P2N2/PP1P1PPP/RNBQKB1R w KQkq - 1 4
go infinite searchmoves f3e5
```

Can anyone confirm please?

**Comment by Virenz123** [comment]
Also crashes for me:

https://i.imgur.com/vlHujGu.png and https://i.imgur.com/yRX68NA.png are the event logs

**Comment by dje-dev** [comment]
Also crashes for me both on Windows (CUDA 11.4) and Linux (CUDA 11.2)

**Comment by OfekShochat** [comment]
#1595 I think this is the same thing. can you confirm this is happening with #1617 ?

**Comment by rooklift** [comment]
Could be the same thing, yeah.

**Comment by dje-dev** [comment]
It seems like the #1595 happens only with filtering triggered by tablebases, but this position is far out of tablebase.

**Comment by OfekShochat** [comment]
nope, see borg's comment there @dje-dev

**Comment by rooklift** [comment]
OK it's already fixed I guess.

**Comment by OfekShochat** [comment]
um did you check tho?

**Comment by rooklift** [comment]
Yes.
