### ISSUE TITLE
Constante deimal - porcentaje decimal de la constante.

### ISSUE THREAD

**Issue by adrian1acoran** [LeelaChessZero/lc0#1621]
0.0.0.0.0.( 0% pi)= black))=(0% decimals pi)=0) 0=0%)))           0.0.0.0.1.(33,3%pi)=green))=(33.3 billions decimals pi)=+1) 33,3=-33%))))    1.1.0.0.0.(66,6%pi)=red))=(66.6 billions decimals pi)=+2) 66.6=66.6%)))1.1.1.0.0.(99,9%pi)=blue))=(99.9 billions decimals pi)=+3)99.9=+99.9%)))1.1.1.1.0.(100%pi)=white))=(100 billions decimals pi)=+4)100=100%)))    1.1.1.1.1.          Dimensiones= (+-)x.y.z.))

**Comment by cn4750** [comment]
Closed as spam.
