### ISSUE TITLE
CUDNN works on RTX 2080, but not on RTX 3080

### ISSUE THREAD

**Issue by Rechenschieber** [LeelaChessZero/lc0#1632]
cudnn-fp 16 works for me fine on RTX 2080, 2080 Ti, 2080 super, GTX 1650 (Laptop)
But on RTX 3080 and 3090 it stops after "GPU compute capability..."
p.s.
The log file gives no additional info:

============= Log started. =============
0829 08:16:54.269597 1220 c:\projects\lc0\src\main.cc:42] Lc0 started.
0829 08:16:54.269643 1220 c:\projects\lc0\src\main.cc:43] [1m[31m       _
0829 08:16:54.270158 1220 c:\projects\lc0\src\main.cc:44] |   _ | |
0829 08:16:54.270542 1220 c:\projects\lc0\src\main.cc:45] |_ |_ |_|[0m v0.28.0 built Aug 25 2021
0829 08:16:54.664427 1220 c:\projects\lc0\src\utils\numa.cc:56] Detected 8 core(s) and 8 thread(s) in 1 group(s).
0829 08:16:54.665262 1220 c:\projects\lc0\src\utils\numa.cc:61] Group 0 has 8 core(s) and 8 thread(s).
0829 08:16:54.667652 1220 c:\projects\lc0\src\utils\commandline.cc:56] Command line: C:\Extras\lc0-v0.28.0-windows-gpu-nvidia-cudnn\lc0.exe
0829 08:17:18.608883 1220 c:\projects\lc0\src\chess\uciloop.cc:136] >> setoption name logfile value log0.txt
0829 08:17:30.264963 1220 c:\projects\lc0\src\chess\uciloop.cc:136] >> go depth 10
0829 08:17:31.984950 1220 c:\projects\lc0\src\neural\loader.cc:238] Found pb network file: C:\Extras\lc0-v0.28.0-windows-gpu-nvidia-cudnn/752187.pb.gz
0829 08:17:32.098756 1220 c:\projects\lc0\src\neural\factory.cc:91] Creating backend [cudnn-auto]...
0829 08:17:32.132978 1220 c:\projects\lc0\src\neural\cuda\network_cudnn.cc:1051] Switching to [cudnn-fp16]...
0829 08:17:32.149386 1220 c:\projects\lc0\src\neural\cuda\network_cudnn.cc:925] CUDA Runtime version: 10.0.0
0829 08:17:32.151033 1220 c:\projects\lc0\src\neural\cuda\network_cudnn.cc:938] Cudnn version: 7.4.2
0829 08:17:32.152308 1220 c:\projects\lc0\src\neural\cuda\network_cudnn.cc:948] Latest version of CUDA supported by the driver: 11.1.0
0829 08:17:32.155541 1220 c:\projects\lc0\src\neural\cuda\network_cudnn.cc:956] GPU: GeForce RTX 3080
0829 08:17:32.156821 1220 c:\projects\lc0\src\neural\cuda\network_cudnn.cc:957] GPU memory: 10 GiB
0829 08:17:32.157436 1220 c:\projects\lc0\src\neural\cuda\network_cudnn.cc:959] GPU clock frequency: 1800 MHz
0829 08:17:32.157856 1220 c:\projects\lc0\src\neural\cuda\network_cudnn.cc:960] GPU compute capability: 8.6

Has anyone cudnn-fp16 running on any RTX 30x0 ?

**Comment by borg323** [comment]
The cudnn package we distribute is built with older versions of cuda/cudnn for compatibility with previous gpu generations. You should get the cuda package instead.

**Comment by Rechenschieber** [comment]
CUDA works well. I just was curious if CUDNN might do better. Btw. the new version 28.0 works much better when memory gets low. Thank you for your great work :)
