### ISSUE TITLE
Leela v0.28.0 and v0.27.0 doesn't start with Nibbler but v0.26.0 does

### ISSUE THREAD

**Issue by Vukica14** [LeelaChessZero/lc0#1655]
Hi to all,
I downloaded Leela v0.28.0 and v0.27.0 and it doesn't wanna to  start with Nibbler but v0.26.0 does. I am using Win7 x64. Leela start and do the benchmark independently but called from Nibbler it seams there is a difference in comaprison with previous versions. Its the same with Fritz16, cant create UCI enginee of 26 and 27 version and 26 can.

Could anyone help about this issue?

Many thanks!

**Comment by Vukica14** [comment]
![2021-11-01 17_09_34-Nibbler](https://user-images.githubusercontent.com/93468705/139703469-7e99c0f9-2514-49a6-8d98-330e636e1a8e.jpg)

**Comment by mooskagh** [comment]
Hi,

It's expected that Nibbler would work also with the latest versions of Lc0.
I suggest to join our Discord chat at lc0.org/chat and ask in #help channel there, it will be much easier to debug the issue there.

**Comment by Naphthalin** [comment]
@Vukica14 can you try reproducing your issue with v0.28.2 and the most recent Nibbler version? if not, this issue can be closed, as it refers to an unreproducable issue with outdated versions.
