### ISSUE TITLE
Client v33 : Unhandled exception: Invalid weight file: lc0 version >= 0.29.0 required.

### ISSUE THREAD

**Issue by YouriAndropov** [LeelaChessZero/lc0#1721]
Hello there,

Unable to run the client, it downloads a weight file for 0.29, but only 0.28.2 engine available ...

Error message is : Unhandled exception: Invalid weight file: lc0 version >= 0.29.0 required.

**Comment by Naphthalin** [comment]
That's because the current runs all require Lc0 version v0.29.0, which is released as rc0 and is safe for use in training.
