### ISSUE TITLE
NPS slowdown issue in TCEC bonus games

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#173]
Here is a log for TCEC of bonus games: http://paste.ubuntu.com/p/srK8KS7rq7/

The following section shows very low NPS (time 11s, nps 0 and time 14s, nps 18). In the end, g2g4 is picked with only 5822 visits after around 14s of thinking.

```
>position startpos moves d2d4 d7d5 c2c4 e7e6 b1c3 g8f6 c4d5 e6d5 c1g5 c7c6 e2e3 f8e7 f1d3 e8g8 d1c2 b8d7 g1e2 f8e8 e1c1 b7b5 h2h4 h7h6 g5f4 d8a5 c1b1 d7b6 e2c1 b6c4 d1g1 a5d8 f2f3 e7d6
>isready
<readyok
>go wtime 1328256 btime 1239809 winc 16000 binc 16000
<info depth 3 seldepth 16 time 11091 nodes 6719 score cp 23 hashfull 1000 nps 0 pv g2g4 d6f4 e3f4 d8d6 f4f5 a7a5 g4g5 f6h5 f5f6 a5a4 f6g7 a4a3 b2b3 c4e3 c2d2 a8a7
<info depth 3 seldepth 16 time 13975 nodes 6975 score cp 23 hashfull 1000 nps 18 pv g2g4 d6f4 e3f4 d8d6 f4f5 a7a5 g4g5 f6h5 f5f6 a5a4 f6g7 a4a3 b2b3 c4e3 c2d2 c8f5
<info string c2a4  (262 ) N:       1 (+ 0) (P:  0.64%) (Q: -0.90750) (U: 0.90263) (Q+U: -0.00487) (V:  -.----)
<info string h1h3  (183 ) N:       2 (+ 0) (P:  0.57%) (Q: -0.55255) (U: 0.54340) (Q+U: -0.00915) (V:  -.----)
<info string c2b3  (258 ) N:       3 (+ 0) (P:  0.75%) (Q: -0.69535) (U: 0.52919) (Q+U: -0.16616) (V:  -.----)
--- cut ---
<info string c3d1  (469 ) N:     220 (+ 0) (P:  7.46%) (Q: -0.04061) (U: 0.09580) (Q+U:  0.05519) (V:  -.----)
<info string f4d6  (833 ) N:     253 (+ 0) (P: 15.38%) (Q: -0.11310) (U: 0.17194) (Q+U:  0.05884) (V:  -.----)
<info string g2g4  (378 ) N:    5822 (+91) (P:  7.93%) (Q:  0.05293) (U: 0.00381) (Q+U:  0.05674) (V:  -.----)
<bestmove g2g4
```

Maybe similar/related to #157?

**Comment by jjoshua2** [comment]
Network weights were 483 and default clop tune

**Comment by apleasantillusion** [comment]
I know this has been happening occasionally throughout the games, but it happened again in the first game between Leela and the 1600 core SF cluster: [screenshot](https://media.discordapp.net/attachments/425419999096733706/467756465340284935/unknown.png?width=542&height=617)

147 seconds of thinking, 8,600 nodes total.

**Comment by mooskagh** [comment]
I think that may cause #170
With low nps, predicted number of nodes for remaining move time is very low, and it immediately realizes that what was inherited from tree reuse is unbeatable.

**Comment by RedDenver** [comment]
I wonder if the garbage collector is causing the slowdown once there's a lot of nodes to gc. Inside the gc loop there's a mutex getting locked and unlocked repeatedly and the search threads also lock and unlock that mutex periodically. After an opponent plays a move that's not the PV is when the search threads would hit the gc the hardest, I think. The actual release of memory happens outside the lock, but maybe the overhead of locking and unlocking is adding up. Maybe a spin lock would cause less overhead?

**Comment by RedDenver** [comment]
I meant to only put this code in my own github, but I accidentally created PR for main lc0:
https://github.com/LeelaChessZero/lc0/pull/175
Can someone who can recreate the issue test this and see if it has any effect?

**Comment by mooskagh** [comment]
@RedDenver 
The problem is not with passing subtrees into gc. (There are ~30 of those to pass on every move, that's done even when thinking is not started, they are surely not a problem).

The problem is when subtree actually is deallocated, every single node is deleted by unique_ptr's destructor. We don't have any mutex on our side, but there's probably a mutex inside malloc().
Replacing malloc with tcmalloc would address that, or if we have our node pool, we'd also had control over it.

**Comment by RedDenver** [comment]
You're right. I was thinking the subnodes were passed separately into the gc which then deleted each one of them, but it's just moving the root of each subtree which the `unique_ptr` destructor then must traverse, which occurs outside the mutex lock.

**Comment by Tilps** [comment]
However all of the GC time should happen 'after' the move is complete right? - seems a bit crazy that it would still be running by the time the opponents turn has finished. In the original post it looks like the opponent took at least 10 seconds on the move before the slowdown (maybe even 26 seconds depending when the increment was applied).

**Comment by mooskagh** [comment]
Yes, GC happens every 100ms, and in my tests (5 years old computer), it takes ~100ms to dispose 10 million nodes.
While 100ms would be too much to block main search (hence the need of GC thread), it's not something that takes seconds even in the case of really large trees. Although maybe active parallel allocation slows it down, that I didn't test (although doubt it will be 10 seconds)

**Comment by dubslow** [comment]
Not for 30s it couldn't overlap.

**Comment by RedDenver** [comment]
Cyril and TheAnswer both report that tcmalloc_minimal didn't help with the slowdown.

**Comment by TollerTyp** [comment]
position startpos moves e2e4 c7c5 g1f3 b8c6 d2d4 c5d4 f3d4 g8f6 b1c3 d7d6 c1g5 e7e6 d1d2 a7a6 e1c1 c8d7 f2f4 f8e7 d4f3 b7b5 g5f6 g7f6 c1b1 d8b6 f1d3 e8c8 h1e1 c8b8 a2a4 b5a4 c3a4 b6b7 d3c4 c6b4 a4c3 b8a8 f3d4 d8b8 f4f5 b4c6 c4b3 c6a5 f5e6 f7e6 d2h6 d6d5 d1d3 h8c8 e4d5 e6e5 d4c6 a5b3 c6b8 c8b8 c2b3 b7b3 h6d2 e7a3
go wtime 1125575 btime 916507 winc 16000 binc 16000

This is the position when Leela did one of her blunders: 
The bestmove is c3d1 (q+u: -0.14866) compared to the much better move c3e4 (q+u: -0.16363)

info string c3e4  (487 ) N:   43861 (+ 0) (P:  6.33%) (Q: -0.16665) (U: 0.00301) (Q+U: -0.16363) 
info string c3d1  (469 ) N:  328836 (+213) (P: 25.22%) (Q: -0.15026) (U: 0.00160) (Q+U: -0.14866)

**Comment by roy7** [comment]
In the LZ0 vs DX game today there were some moves reported in the web UI with 6K nps on 2x1080Ti, and LZ0 moved with under 300K total nodes explored. About 3 minutes were left on the clock so it wasn't a severe time crunch. Perhaps this bug is continuing to pop up?

**Comment by RedDenver** [comment]
Weren't the bonus games played on TheAnswer's machine?

**Comment by dubslow** [comment]
Indeed, this issue predates Season 13, indeed even predates the bonus games before S13; this was first noticed by Cyril in the runup to WCCC
