### ISSUE TITLE
Crash when illegal/nonsensical moves are entered after tree reuse

### ISSUE THREAD

**Issue by dubslow** [LeelaChessZero/lc0#178]
Reproduce:

```
go nodes 2
position startpos a1h8
```

This causes `assert(!edges_);` to fail in `CreateSingleChildNode`, because the move already had its legal children constructed.

I confirmed that this *didn't* cause a crash prior to the edge-node separation commit.

It's probably best fixed by outright rejecting illegal moves somewhere up in the Engine code. It would be possible to recreate old behavior (which was to not crash but search the nonsensical position as if it were valid), but it would be ugly as hell, and nontrivial to properly destroy and reconstruct `current_head_`, which I'm far too braindead to figure out currently.

**Comment by mooskagh** [comment]
If you really want that behavior (force add invalid move), I think removing the assert will make it just work.
It doesn't feel right to allow that. But I think I know another similar case, that actually justifies removal of the assert:
```
position startpos moves e2e4 e7e5 d2d4
position startpos moves e2e4 d7d5    # probably hits the same assert
```

Luckily most of people use release build where asserts are compiled out so the are not affected, but I still think we should remove that assert.

**Comment by dubslow** [comment]
Mmm, I see, that's a very valid analysis use case.


Does merely overwriting `Node::edges_` ensure proper cleanup of the former object stored there? It looks like it's not a pointer but an actual entire object, which I believe means the `EdgeList` will be properly destroyed, and in turn its `unique_ptr` to `Edge[]` will be cleaned up as well?

**Comment by mooskagh** [comment]
Yes, unique_ptr will automatically do everything right.
