### ISSUE TITLE
Issue with cblas_sgemm_batch on Ubuntu 18.04

### ISSUE THREAD

**Issue by cbeaume** [LeelaChessZero/lc0#1782]
Hello,

I am trying to install LCZero with OpenBLAS as backend on my Ubuntu 18.04 laptop. Here is some of my setup: 

meson --version: 0.61.5
ninja --version: 1.8.2
libopenblas-dev: 0.2.20+ds-4

I proceed according to the Readme.md file until step 4. I used the command: 
> CC=clang-6.0 CXX=clang++-6.0 INSTALL_PREFIX=~/.local ./build.sh

The installation aborts after the following error message: 
../../src/neural/blas/winograd_convolution3.cc:205:3: error: use of undeclared identifier 'cblas_sgemm_batch'
  cblas_sgemm_batch(CblasColMajor, &transA, &transB, &m_array, &n_array,
  ^
1 error generated.

I have tried using other compilers (g++-8) and several version of LCZero (0.28.2, 0.28.0, 0.22.0) and the same errors pops up and aborts the installation. 

Would anyone have an idea of how to fix this?

Thanks!

**Comment by cbeaume** [comment]
Problem solved. It turns out that the build routine finds some Intel libraries on my laptop:
> Library mkl_rt found: YES
which might force a certain standard or their use.

I went to the meson.build file and forced the build as if mkl_rt was not found by commenting the "if" statement in the below paragraph:
```
  mkl_libdirs = get_option('mkl_libdirs')
  mkl_lib = cc.find_library('mkl_rt', dirs: mkl_libdirs, required: false)
##  if not mkl_lib.found()
    mkl_lib = cc.find_library('mklml', dirs: mkl_libdirs, required: false)
##  endif
```
And it worked. Installation complete!

**Comment by borg323** [comment]
For the next one that comes across this, an alternative is to pass `-Dmkl=false` to build.sh.
