### ISSUE TITLE
Lc0 v0.28.2 impossible to install on Android mobile devices

### ISSUE THREAD

**Issue by ReikJ** [LeelaChessZero/lc0#1793]
### Discussed in https://github.com/LeelaChessZero/lc0/discussions/1669

<div type='discussions-op-text'>

<sup>Originally posted by **borg323** December 13, 2021</sup>
This is what should have been v0.28.1:
* Improved cuda performance for 512 filter networks on Amprere GPUs.
* Several fixes for the onnx backend.
* New lc0 modes to process network files: describenet, leela2onnx and onnx2leela
* Documentation updates.
* Correctness fixes for rescorer support functions.

<hr /><em>This discussion was created from the release <a href='https://github.com/LeelaChessZero/lc0/releases/tag/v0.28.2'>v0.28.2</a>.</em></div>

**Comment by ReikJ** [comment]
Warum diese Gott verdammte IGNORANZ !! 👊🦶☝️

**Comment by borg323** [comment]
For questions like this a better place is the #hep channel in our discord chat, <http://lc0.org/chat>.
