### ISSUE TITLE
lc0: print uci info more often

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#18]
_From @mooskagh on May 27, 2018 5:26_

Currently `lc0` prints updated `uci info` when bestmove/depth/seldepth is changed.
At higher depth it may take a while until something from that list is changed.
It makes sense to print `uci info` also on timer (every 27 seconds, for example).

_Copied from original issue: glinscott/leela-chess#668_

**Comment by mooskagh** [comment]
_From @Videodr0me on May 31, 2018 17:0_

I fixed this in my experimental version. This outputs info approx every second.
Just added this:
((uci_info_.nodes / (uci_info_.nps+1) )!= ((total_playouts_ + initial_visits_) / (uci_info_.nps+1)))||
in

```c++
void Search::MaybeOutputInfo() {
  SharedMutex::Lock lock(nodes_mutex_);
  Mutex::Lock counters_lock(counters_mutex_);
  if (!responded_bestmove_ && best_move_node_ &&
       (best_move_node_ != last_outputted_best_move_node_ ||
       uci_info_.depth != root_node_->GetFullDepth() ||
       ((uci_info_.nodes / (uci_info_.nps+1) )!= ((total_playouts_ + initial_visits_) / (uci_info_.nps+1)))||
       uci_info_.seldepth != root_node_->GetMaxDepth())) {
    SendUciInfo();
  }
}

**Comment by mooskagh** [comment]
I think it makes sense to remember time when uci info was last output, and if >30 seconds are passed, output it again.

**Comment by Videodr0me** [comment]
I would say that 30 seconds is a bit much. Many guis suppress early output (chessbase) and if you wait to long with the next uci output it for example breaks chessbase guis test position feature. Shredder for example outputs uci info every second (and its author invented the uci protocol). But i agree a more "professional" solution is to remember the last time uci output was updated, the above was just a quick fix by be to make chessbase gui work properly - i did this even before i saw this issue, just for my own tests. I just finished my search modifications and will write up those, but after that i can revisit this and provide a "clean" solution.

**Comment by Videodr0me** [comment]
Here is a "clean" solution:

```c++
void Search::MaybeOutputInfo() {
  SharedMutex::Lock lock(nodes_mutex_);
  Mutex::Lock counters_lock(counters_mutex_);
  if (!responded_bestmove_ && best_move_node_ &&
	  (best_move_node_ != last_outputted_best_move_node_ ||
		  uci_info_.depth != root_node_->GetFullDepth() ||
		  (uci_info_.time  + 1000 < GetTimeSinceStart())  ||
       uci_info_.seldepth != root_node_->GetMaxDepth())) {
    SendUciInfo();
  }
}
