### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by gabrielp10031978** [LeelaChessZero/lc0#1813]
Hello,
I tried to use Lc0 v0.29.0 with a weights file from here (http://training.lczero.org/networks/3) but is not working.
It is working only with the the weights file from the package.
Please help me.
Thanks.

**Comment by borg323** [comment]
What backend are you using.

**Comment by gabrielp10031978** [comment]
I have Geforce GTX 1060 6 Gb so, I understand CUDNN version.

**Comment by borg323** [comment]
Unfortunately T78 nets require a lot of memory. Please ask in the #help channel of our discord chat http://lc0.org/chat for possible workarounds.

**Comment by borg323** [comment]
This was solved by adding `custom_winograd=false` to the backend options.
