### ISSUE TITLE
Add permission under GPL v3 section 7 for linking with cuDNN/CUDA.

### ISSUE THREAD

**Issue by borg323** [LeelaChessZero/lc0#184]
In order to be able to distribute a windows cuDNN/CUDA lc0 binary together with the required dlls we need to comply with both GPL and nVidia license terms. In short, GPL requires no proprietary dlls distributed with lc0, while nVidia requires the dlls distributed only with lc0 and not independently. 

There is a way around this by adding an additional permission as allowed by GPL v3 in section 7. An example for such an additional permission for CUDA is found [here](https://gitweb.gentoo.org/repo/gentoo.git/plain/licenses/GPL-3+-with-cuda-exception). 

This can be done for all files currently in lc0 with the agreement of all contributors, except for the leela/lczero derived ones used for BLAS/OpenCL, so that lc0 can be distributed, with the cudnn backend only, together with the required dlls.

The suggested text is the following
```
Additional permission under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or
combining it with NVIDIA Corporation's libraries from the
NVIDIA CUDA Toolkit and the the NVIDIA CUDA Deep Neural
Network library (or a modified version of those libraries),
containing parts covered by the terms of the respective license
agreement, the licensors of this Program grant you additional
permission to convey the resulting work.
```

**Comment by Tilps** [comment]
I have no problems with this exception being added.

**Comment by dubslow** [comment]
I'll hop on board if everyone else does

**Comment by mooskagh** [comment]
I agree.

**Comment by killerducky** [comment]
I agree.

**Comment by borg323** [comment]
To go forward with this, we need the agreement of all contributors to lc0. Please respond even if you only did non-code changes. I'll update the following list when I hear from you:
@mooskagh - OK
@frpays
@dubslow- OK conditional on everyone agreeing
@ankan-ban
@Tilps - OK
@Error323  
@borg323 - OK
@fli 
@students
@jjoshua2 
@blin00 
@GBeauregard 
@rhdunn 
@AlexGreason 
@ddobbelaere 
@jnewlin12345 
@playlaughlovelearn 
@Ghotrix 
@gsobala 
@Aloril 
@killerducky 
@DanielUranga 
@ganeshkrishnan1 
@ppdixit
@ron-wolf 
@dje-dev 
@evalon32 
(list sorted by number of commits)

**Comment by blin00** [comment]
I agree

**Comment by DanielUranga** [comment]
I agree

**Comment by rhdunn** [comment]
I agree

**Comment by evalon32** [comment]
I agree

**Comment by dje-dev** [comment]
I agree

**Comment by ppdixit** [comment]
I agree

**Comment by GBeauregard** [comment]
I agree

**Comment by ganeshkrishnan1** [comment]
No problem, I agree

**Comment by fli** [comment]
I agree

**Comment by AlexGreason** [comment]
I agree

**Comment by Aloril** [comment]
I agree

**Comment by ddobbelaere** [comment]
I agree

**Comment by ankan-ban** [comment]
I agree

**Comment by Ghotrix** [comment]
I agree!

**Comment by jjoshua2** [comment]
Ok

**Comment by Error323** [comment]
I agree

**Comment by playlaughlovelearn** [comment]
Yes, of course. :)

**Comment by gsobala** [comment]
Agree

**Comment by borg323** [comment]
@SashaMN - it seems that your github handle is not correct in the log, but you are mentioned as "students", so you were not copied in the original exchange. Can you take a look here and tell us whether you agree with the additional permission?

**Comment by jnewlin12345** [comment]
I agree

**Comment by frpays** [comment]
I agree

**Comment by SashaMN** [comment]
@borg323 I agree

**Comment by dubslow** [comment]
I guess that leaves me. I agree.

**Comment by ron-wolf** [comment]
Yes, this is fine 😀
