### ISSUE TITLE
Incorrect notation.

### ISSUE THREAD

**Issue by Karavadgoo** [LeelaChessZero/lc0#185]
There is sign of check in the end of training game http://lczero.org/game/20932231. But actually this game ended with mate.
I suppose it should be 41. Rh8# instead of 41. Rh8+.

**Comment by cwbriscoe** [comment]
All of the training data PGN's here: http://lczero.org/training_data have the same issue.

I also opened a sort of related issue here:  https://github.com/LeelaChessZero/lczero-server/issues/6

I am not sure if I opened that one in the right place or not.

**Comment by TollerTyp** [comment]
Hello. I'm interessted to solve this. How can I get this issue fix assigned? Thx. Martin.

**Comment by Error323** [comment]
Hi @TollerTyp you can just work on the issue and create a pull request.

**Comment by TollerTyp** [comment]
Ok. Thx.

**Comment by mooskagh** [comment]
That was an lczero.org old pipeline where it was lczero.exe who provided PGNs.
With new pipeline, PGN generation is done by client, and I believe there's no such problem there.
