### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by supersri811** [LeelaChessZero/lc0#1878]
Hi!
I was earlier trying to build lc0 on Arch linux.
However I get the same error while installing from the AUR or manually building it
`INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /home/supersri/.local/bin/ninja -C /home/supersri/lc1/build/release
ninja: Entering directory `/home/supersri/lc1/build/release'
[0/1] Regenerating build files.
The Meson build system
Version: 1.0.1
Source dir: /home/supersri/lc1
Build dir: /home/supersri/lc1/build/release
Build type: native build
Project name: lc0
Project version: undefined
C++ compiler for the host machine: c++ (gcc 12.2.1 "c++ (GCC) 12.2.1 20230201")
C++ linker for the host machine: c++ ld.bfd 2.40
Host machine cpu family: x86_64
Host machine cpu: x86_64
Has header "optional" : YES (cached)
Has header "string_view" : YES (cached)
Has header "charconv" : YES (cached)
Compiler for C++ supports arguments -march=native: YES (cached)
Program scripts/compile_proto.py found: YES (/home/supersri/lc1/scripts/compile_proto.py)
Program git found: YES (/usr/bin/git)
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
../../meson.build:116: WARNING: Failed to parse short revision. Use git clone instead of downloading the archive from GitHub.
Message: Using build identifier "git.unknown".
Configuring build_id.h using configuration
Dependency threads found: YES unknown (cached)
Library dl found: YES
Found pkg-config: /usr/bin/pkg-config (1.8.1)
Found CMake: /usr/bin/cmake (3.26.3)
Run-time dependency tensorflow_cc found: NO (tried pkgconfig and cmake)
Run-time dependency accelerate found: NO (tried pkgconfig and cmake)
Library mkl_rt found: NO
Library mklml found: NO
Library dnnl found: YES
Library openblas.dll found: NO
Library openblas found: YES
Has header "openblas_config.h" : NO (cached)
Has header "openblas_config.h" : YES (cached)
Dependency eigen3 found: YES 3.4.0 (cached)
Program ispc found: NO
Library OpenCL found: YES
Run-time dependency opencl found: NO 
Has header "CL/opencl.h" : YES (cached)
Library cublas found: YES
Library cudnn found: YES
Library cudart found: YES
Program /opt/cuda/bin/nvcc found: YES (/opt/cuda/bin/nvcc)
Run-time dependency appleframeworks found: NO (tried framework)
Dependency zlib found: YES 1.2.13 (cached)
WARNING: find_library('libatomic') starting in "lib" only works by accident and is not portable
Library libatomic found: YES
Dependency gtest found: YES 1.13.0 (cached)
Build targets in project: 10

lc0 undefined

  User defined options
    buildtype: release
    prefix   : /usr/local
    mkl      : false

Found ninja-1.11.1.git.kitware.jobserver-1 at /home/supersri/.local/bin/ninja
Cleaning... 0 files.
[1/9] Linking target liblc0_lib.so
FAILED: liblc0_lib.so 
c++  -o liblc0_lib.so common_kernels.o fp16_kernels.o liblc0_lib.so.p/src_utils_protomessage.cc.o liblc0_lib.so.p/src_benchmark_backendbench.cc.o liblc0_lib.so.p/src_benchmark_benchmark.cc.o liblc0_lib.so.p/src_chess_bitboard.cc.o liblc0_lib.so.p/src_chess_board.cc.o liblc0_lib.so.p/src_chess_position.cc.o liblc0_lib.so.p/src_chess_uciloop.cc.o liblc0_lib.so.p/src_engine.cc.o liblc0_lib.so.p/src_lc0ctl_describenet.cc.o liblc0_lib.so.p/src_lc0ctl_leela2onnx.cc.o liblc0_lib.so.p/src_lc0ctl_onnx2leela.cc.o liblc0_lib.so.p/src_mcts_node.cc.o liblc0_lib.so.p/src_mcts_params.cc.o liblc0_lib.so.p/src_mcts_search.cc.o liblc0_lib.so.p/src_mcts_stoppers_alphazero.cc.o liblc0_lib.so.p/src_mcts_stoppers_common.cc.o liblc0_lib.so.p/src_mcts_stoppers_factory.cc.o liblc0_lib.so.p/src_mcts_stoppers_legacy.cc.o liblc0_lib.so.p/src_mcts_stoppers_simple.cc.o liblc0_lib.so.p/src_mcts_stoppers_smooth.cc.o liblc0_lib.so.p/src_mcts_stoppers_stoppers.cc.o liblc0_lib.so.p/src_mcts_stoppers_timemgr.cc.o liblc0_lib.so.p/src_neural_cache.cc.o liblc0_lib.so.p/src_neural_decoder.cc.o liblc0_lib.so.p/src_neural_encoder.cc.o liblc0_lib.so.p/src_neural_factory.cc.o liblc0_lib.so.p/src_neural_loader.cc.o liblc0_lib.so.p/src_neural_network_check.cc.o liblc0_lib.so.p/src_neural_network_demux.cc.o liblc0_lib.so.p/src_neural_network_legacy.cc.o liblc0_lib.so.p/src_neural_network_mux.cc.o liblc0_lib.so.p/src_neural_network_random.cc.o liblc0_lib.so.p/src_neural_network_record.cc.o liblc0_lib.so.p/src_neural_network_rr.cc.o liblc0_lib.so.p/src_neural_network_trivial.cc.o liblc0_lib.so.p/src_neural_onnx_adapters.cc.o liblc0_lib.so.p/src_neural_onnx_builder.cc.o liblc0_lib.so.p/src_neural_onnx_converter.cc.o liblc0_lib.so.p/src_selfplay_game.cc.o liblc0_lib.so.p/src_selfplay_loop.cc.o liblc0_lib.so.p/src_selfplay_tournament.cc.o liblc0_lib.so.p/src_syzygy_syzygy.cc.o liblc0_lib.so.p/src_trainingdata_reader.cc.o liblc0_lib.so.p/src_trainingdata_trainingdata.cc.o liblc0_lib.so.p/src_trainingdata_writer.cc.o liblc0_lib.so.p/src_utils_commandline.cc.o liblc0_lib.so.p/src_utils_configfile.cc.o liblc0_lib.so.p/src_utils_esc_codes.cc.o liblc0_lib.so.p/src_utils_files.cc.o liblc0_lib.so.p/src_utils_histogram.cc.o liblc0_lib.so.p/src_utils_logging.cc.o liblc0_lib.so.p/src_utils_numa.cc.o liblc0_lib.so.p/src_utils_optionsdict.cc.o liblc0_lib.so.p/src_utils_optionsparser.cc.o liblc0_lib.so.p/src_utils_random.cc.o liblc0_lib.so.p/src_utils_string.cc.o liblc0_lib.so.p/src_utils_weights_adapter.cc.o liblc0_lib.so.p/src_version.cc.o liblc0_lib.so.p/src_utils_filesystem.posix.cc.o liblc0_lib.so.p/src_neural_blas_convolution1.cc.o liblc0_lib.so.p/src_neural_blas_fully_connected_layer.cc.o liblc0_lib.so.p/src_neural_blas_se_unit.cc.o liblc0_lib.so.p/src_neural_blas_network_blas.cc.o liblc0_lib.so.p/src_neural_blas_winograd_convolution3.cc.o liblc0_lib.so.p/src_neural_opencl_network_opencl.cc.o liblc0_lib.so.p/src_neural_opencl_OpenCL.cc.o liblc0_lib.so.p/src_neural_opencl_OpenCLTuner.cc.o liblc0_lib.so.p/src_neural_opencl_OpenCLBuffers.cc.o liblc0_lib.so.p/src_neural_shared_activation.cc.o liblc0_lib.so.p/src_neural_shared_winograd_filter.cc.o liblc0_lib.so.p/src_neural_cuda_layers.cc.o liblc0_lib.so.p/src_neural_cuda_network_cudnn.cc.o liblc0_lib.so.p/src_neural_cuda_network_cuda.cc.o -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,liblc0_lib.so -Wl,-rpath,/opt/cuda/lib64 -Wl,-rpath-link,/opt/cuda/lib64 -pthread /usr/lib/libopenblas.so /opt/cuda/lib64/libOpenCL.so /opt/cuda/lib64/libcublas.so /opt/cuda/lib64/libcudart.so /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../lib/libcudnn.so /usr/lib/libz.so /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../lib/libatomic.so -Wl,--end-group
/usr/bin/ld: /tmp/ccUkL1mS.ltrans20.ltrans.o: in function `lczero::Convolution1<false>::Forward(unsigned long, unsigned long, unsigned long, float const*, float const*, float*)':
<artificial>:(.text+0x227f): undefined reference to `cblas_sgemm'
/usr/bin/ld: /tmp/ccUkL1mS.ltrans20.ltrans.o: in function `lczero::FullyConnectedLayer<false>::Forward1D(unsigned long, unsigned long, unsigned long, float const*, float const*, float const*, lczero::ActivationFunction, float*)':
<artificial>:(.text+0x4eed): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x4f62): undefined reference to `cblas_sgemv'
/usr/bin/ld: /tmp/ccUkL1mS.ltrans20.ltrans.o: in function `lczero::(anonymous namespace)::BlasComputation<false>::ComputeBlocking()':
<artificial>:(.text+0x6e08): undefined reference to `cblas_sgemm'
/usr/bin/ld: /tmp/ccUkL1mS.ltrans20.ltrans.o: in function `lczero::FullyConnectedLayer<false>::Forward0D(unsigned long, float const*, float const*)':
<artificial>:(.text+0x2d2f): undefined reference to `cblas_sdot'
/usr/bin/ld: /tmp/ccUkL1mS.ltrans21.ltrans.o: in function `lczero::WinogradConvolution3<false>::Sgemm(unsigned long, float const*, unsigned long, unsigned long)':
<artificial>:(.text+0x11b2): undefined reference to `cblas_sgemm'
/usr/bin/ld: /tmp/ccUkL1mS.ltrans21.ltrans.o: in function `lczero::(anonymous namespace)::BlasComputation<false>::MakeEncoderLayer(std::vector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&, unsigned long, lczero::LegacyWeights::EncoderLayer const&, int, int, lczero::ActivationFunction, lczero::ActivationFunction, float) [clone .lto_priv.0]':
<artificial>:(.text+0x45ed): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x47dd): undefined reference to `cblas_sgemm'
collect2: error: ld returned 1 exit status
[2/9] Linking target lc0
FAILED: lc0 
c++  -o lc0 common_kernels.o fp16_kernels.o lc0.p/src_main.cc.o lc0.p/src_utils_protomessage.cc.o lc0.p/src_benchmark_backendbench.cc.o lc0.p/src_benchmark_benchmark.cc.o lc0.p/src_chess_bitboard.cc.o lc0.p/src_chess_board.cc.o lc0.p/src_chess_position.cc.o lc0.p/src_chess_uciloop.cc.o lc0.p/src_engine.cc.o lc0.p/src_lc0ctl_describenet.cc.o lc0.p/src_lc0ctl_leela2onnx.cc.o lc0.p/src_lc0ctl_onnx2leela.cc.o lc0.p/src_mcts_node.cc.o lc0.p/src_mcts_params.cc.o lc0.p/src_mcts_search.cc.o lc0.p/src_mcts_stoppers_alphazero.cc.o lc0.p/src_mcts_stoppers_common.cc.o lc0.p/src_mcts_stoppers_factory.cc.o lc0.p/src_mcts_stoppers_legacy.cc.o lc0.p/src_mcts_stoppers_simple.cc.o lc0.p/src_mcts_stoppers_smooth.cc.o lc0.p/src_mcts_stoppers_stoppers.cc.o lc0.p/src_mcts_stoppers_timemgr.cc.o lc0.p/src_neural_cache.cc.o lc0.p/src_neural_decoder.cc.o lc0.p/src_neural_encoder.cc.o lc0.p/src_neural_factory.cc.o lc0.p/src_neural_loader.cc.o lc0.p/src_neural_network_check.cc.o lc0.p/src_neural_network_demux.cc.o lc0.p/src_neural_network_legacy.cc.o lc0.p/src_neural_network_mux.cc.o lc0.p/src_neural_network_random.cc.o lc0.p/src_neural_network_record.cc.o lc0.p/src_neural_network_rr.cc.o lc0.p/src_neural_network_trivial.cc.o lc0.p/src_neural_onnx_adapters.cc.o lc0.p/src_neural_onnx_builder.cc.o lc0.p/src_neural_onnx_converter.cc.o lc0.p/src_selfplay_game.cc.o lc0.p/src_selfplay_loop.cc.o lc0.p/src_selfplay_tournament.cc.o lc0.p/src_syzygy_syzygy.cc.o lc0.p/src_trainingdata_reader.cc.o lc0.p/src_trainingdata_trainingdata.cc.o lc0.p/src_trainingdata_writer.cc.o lc0.p/src_utils_commandline.cc.o lc0.p/src_utils_configfile.cc.o lc0.p/src_utils_esc_codes.cc.o lc0.p/src_utils_files.cc.o lc0.p/src_utils_histogram.cc.o lc0.p/src_utils_logging.cc.o lc0.p/src_utils_numa.cc.o lc0.p/src_utils_optionsdict.cc.o lc0.p/src_utils_optionsparser.cc.o lc0.p/src_utils_random.cc.o lc0.p/src_utils_string.cc.o lc0.p/src_utils_weights_adapter.cc.o lc0.p/src_version.cc.o lc0.p/src_utils_filesystem.posix.cc.o lc0.p/src_neural_blas_convolution1.cc.o lc0.p/src_neural_blas_fully_connected_layer.cc.o lc0.p/src_neural_blas_se_unit.cc.o lc0.p/src_neural_blas_network_blas.cc.o lc0.p/src_neural_blas_winograd_convolution3.cc.o lc0.p/src_neural_opencl_network_opencl.cc.o lc0.p/src_neural_opencl_OpenCL.cc.o lc0.p/src_neural_opencl_OpenCLTuner.cc.o lc0.p/src_neural_opencl_OpenCLBuffers.cc.o lc0.p/src_neural_shared_activation.cc.o lc0.p/src_neural_shared_winograd_filter.cc.o lc0.p/src_neural_cuda_layers.cc.o lc0.p/src_neural_cuda_network_cudnn.cc.o lc0.p/src_neural_cuda_network_cuda.cc.o -flto -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,/opt/cuda/lib64 -Wl,-rpath-link,/opt/cuda/lib64 -pthread -Wl,--start-group /usr/lib/libopenblas.so /opt/cuda/lib64/libOpenCL.so /opt/cuda/lib64/libcublas.so /opt/cuda/lib64/libcudart.so /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../lib/libcudnn.so /usr/lib/libz.so /usr/lib/gcc/x86_64-pc-linux-gnu/12.2.1/../../../../lib/libatomic.so -Wl,--end-group
/usr/bin/ld: /tmp/ccjDqskH.ltrans20.ltrans.o: in function `lczero::FullyConnectedLayer<false>::Forward1D(unsigned long, unsigned long, unsigned long, float const*, float const*, float const*, lczero::ActivationFunction, float*)':
<artificial>:(.text+0x1f6d): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x1fe2): undefined reference to `cblas_sgemv'
/usr/bin/ld: /tmp/ccjDqskH.ltrans20.ltrans.o: in function `lczero::(anonymous namespace)::BlasComputation<false>::ComputeBlocking()':
<artificial>:(.text+0x5679): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x5737): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x5950): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x5a63): undefined reference to `cblas_sdot'
/usr/bin/ld: <artificial>:(.text+0x5bc8): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x5f24): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x6241): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x68af): undefined reference to `cblas_sgemv'
/usr/bin/ld: <artificial>:(.text+0x6b4e): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x7d67): undefined reference to `cblas_sgemv'
/usr/bin/ld: <artificial>:(.text+0x7e27): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x7eb5): undefined reference to `cblas_sgemv'
/usr/bin/ld: /tmp/ccjDqskH.ltrans21.ltrans.o: in function `lczero::(anonymous namespace)::BlasComputation<false>::MakeEncoderLayer(std::vector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&, std::vector<float, std::allocator<float> >&, unsigned long, lczero::LegacyWeights::EncoderLayer const&, int, int, lczero::ActivationFunction, lczero::ActivationFunction, float) [clone .lto_priv.0]':
<artificial>:(.text+0x3b2e): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x3d61): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x4069): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x42b8): undefined reference to `cblas_sgemv'
/usr/bin/ld: /tmp/ccjDqskH.ltrans21.ltrans.o: in function `lczero::WinogradConvolution3<false>::Forward(unsigned long, unsigned long, unsigned long, float const*, float const*, float*)':
<artificial>:(.text+0x9079): undefined reference to `cblas_sgemm'
/usr/bin/ld: /tmp/ccjDqskH.ltrans29.ltrans.o: in function `lczero::FullyConnectedLayer<false>::Forward1D(unsigned long, unsigned long, unsigned long, float const*, float const*, float const*, lczero::ActivationFunction, float*) [clone .constprop.4]':
<artificial>:(.text+0x7a62): undefined reference to `cblas_sgemm'
/usr/bin/ld: <artificial>:(.text+0x7c47): undefined reference to `cblas_sgemv'
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
`

**Comment by mooskagh** [comment]
It seems that `blas` implementation on the system doesn't have all the function.

However, as you don't need the blas backend (I can see it found cudnn and cuda libraries), you can build without it, by running:

```
$ ./build.sh -Dblas=false
```
(delete the build/ directory before the attempt so that it regenerates the config)

**Comment by supersri811** [comment]
Thanks! Will check it out.

**Comment by supersri811** [comment]
Yup, It worked!
Thanks for the help. 
I hope this will help other users with a similar problem.
