### ISSUE TITLE
WDL in python binding

### ISSUE THREAD

**Issue by SimonBenhamou** [LeelaChessZero/lc0#1900]
Hello,

In the python binding, it seems like the engine's evaluate function can only output the Q score, but not the WDL head results. Here is my code:

```python
from lczero.backends import Weights, Backend, GameState
w = Weights('../../maia_models/maia-1900.pb')
b = Backend(weights=w, backend='eigen')
board_input = GameState(fen='2R5/5kpp/4p3/p4p2/3B4/1K5N/4rNPP/8 b - - 0 29').as_input(b)
board_evaluation = b.evaluate(board_input)[0]
```

Is there any way to expose the WDL attributes to python?

**Comment by SimonBenhamou** [comment]
Found it, I missed the d method...

**Comment by LilacPeregrine** [comment]
Do you have the fixed code for including WDL? I'm looking to do something similar.
