### ISSUE TITLE
No citation file

### ISSUE THREAD

**Issue by dpaleka** [LeelaChessZero/lc0#1923]
If this repo had a [CITATION.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file, the project would be easy to cite in papers, and every paper would cite it in the same way (enabling e.g. Google Scholar accounting). See examples for [PyTorch](https://github.com/pytorch/pytorch/blob/main/CITATION.cff) and [Stockfish](https://github.com/official-stockfish/Stockfish/blob/master/CITATION.cff).

**Comment by AlexisOlson** [comment]
The basic info should be something like:

```
cff-version: 1.2.0
title: LeelaChessZero
type: software
authors:
  - name: The LCZero Authors
repository-code: 'https://github.com/LeelaChessZero/lc0'
url: 'https://lczero.org/'
repository-artifact: 'https://github.com/LeelaChessZero/lc0/releases/'
abstract: >-
  Lc0 is a UCI-compliant chess engine designed to play chess
  via neural network, specifically those of the
  LeelaChessZero project.
keywords:
  - chess
  - neural networks (NN)
  - artificial intelligence (AI)
license: GPL-3.0
```

**Comment by AlexisOlson** [comment]
Created https://github.com/LeelaChessZero/lc0/pull/1934

**Comment by mooskagh** [comment]
Thanks Danial for the suggestion and Alexis for providing the file!
Closing the issue as fixed.
