### ISSUE TITLE
Make lc0 0.31.0 available in the main repository

### ISSUE THREAD

**Issue by dkappe** [LeelaChessZero/lc0#1960]
0.31.0 take quite a bit effort to find. Make it available with instructions for BT3/BT4.

**Comment by Kovax007** [comment]
0.31.0 is not available yet.

**Comment by soisseseben** [comment]
Where can I find 0.31.0 beta?

**Comment by Mr-Twave** [comment]
> Where can I find 0.31.0 beta?

You'll have to learn how to use github to do that. The master branch is technically the current 31.0 beta.

**Comment by VaeterchenFrost** [comment]
Is it closed, looking at https://github.com/LeelaChessZero/lc0/releases ?
