### ISSUE TITLE
Not able to build Lc0 on Mac OS

### ISSUE THREAD

**Issue by GiordanoVicoli** [LeelaChessZero/lc0#2005]
Hi,

I have a Macbook with Sonoma and M1 Pro. I also have installe Xcode 15.3.
I tried to build Lc0 last release following your instructions without success.

I upload a screenshot of the terminal with the error.

Thanks and regards,
Giordano

<img width="1601" alt="Screenshot 2024-03-29 alle 11 37 42" src="https://github.com/LeelaChessZero/lc0/assets/18027781/25f664c8-822a-4dba-93db-04dc42527931">

**Comment by mooskagh** [comment]
You seem to have inconsistent submodule. Your `lczero-common` submodule is the latest version, but the `lc0` itself is older.  Sync lc0 to the master, or update `lczero-common` to the version referenced in the lc0 commit you use.
