### ISSUE TITLE
Obtaining a PJRT plugin through Jax

### ISSUE THREAD

**Issue by puct9** [LeelaChessZero/lc0#2068]
As part of Jax's GPU support, there is a package https://pypi.org/project/jax-cuda12-pjrt/ which essentially contains the PJRT plugin is included as a dependency.

https://github.com/openxla/xla/issues/13733#issuecomment-2168361287

> We only publish a GPU plugin for now: https://pypi.org/project/jax-cuda12-pjrt/ (cuda11 also available)

In a separate project, I found that it was valid to run `pip install jax-cuda12-pjrt` and copy the file found in `venv/lib/python3.10/site-packages/jax_plugins/xla_cuda12/xla_cuda_plugin.so` (you will need to adapt the front part of the path). And then rename or use as required (e.g., rename to `pjrt_c_api_gpu_plugin.so`).

I can call `dlopen` and `dlsym(..., "GetPjrtApi")` against this file, and run computation. This also seems like a substantially more convenient way than building the target in the XLA repo. The filesize is also much more in line with what you would expect from building it yourself:

```sh
~/lc0/build/release$ du -sh * | grep so$
...
579M    libxla_extension.so
227M    pjrt_c_api_gpu_plugin_selfbuild.so
265M    xla_cuda_plugin.so
```

Where the objects shown are the one from https://github.com/elixir-nx/xla/releases, building it manually from XLA, and copying from `jax-cuda12-pjrt` in this order.

Unfortunately I was unable to convert any recent networks for the time being, but if anyone has this set up then it should be quite easy to validate this idea.

**Comment by mooskagh** [comment]
Thanks for the pointer, I'll add it to the wiki (or you can do that yourself).  
If the `GetPjrtApi` function exists in the .so file, it means it's a valid one.

On the other hand, libraries provides by the `elixir-nx` don't seem to contain `GetPjrtApi`.

**Comment by borg323** [comment]
I wonder if <https://pypi.org/project/intel-extension-for-openxla/> will also work.

**Comment by mooskagh** [comment]
`intel-extension-for-openxla` is not a part of XLA, but rather a separate library that implements PjRT plugin.

From the diagram on their [github page](https://github.com/intel/intel-extension-for-openxla), it seems that they only support StableHLO as the input (serialized as a MLIR bytecode) rather than XLA HLO (serialized as protobuf).  I guess we'd need to add a support of StableHLO in Lc0 to make it work.

**Comment by puct9** [comment]
Updated the wiki!
