### ISSUE TITLE
Lc0 doesn't populate repetition planes

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#209]
Example:
```
position fen rnbqkbnr/pp2pppp/2pp4/8/1P6/5N2/P1PPPPPP/RNBQKB1R w KQkq - 0 1 moves c2c4 d8b6 d1b3 a7a5 b4b5 g8f6 b1c3 e7e5 a2a3 c6b5 e2e3 e5e4 f3g5 h7h6 g5e4 f8e7 e4f6 e7f6 d2d4 a5a4 b3b5 b6b5 c3b5 e8g8 b5d6 f6e7 d6c8 f8c8 a1b1 c8c7 c4c5 b8d7 f1b5 g7g6 e1e2 h6h5 b5d7 c7d7 b1b4 f7f5 c1d2 a8a7 h1b1 e7d8 b4b5 g8g7 h2h3 g7f6 e2d3 g6g5 d3c4 f6e6 d2e1 g5g4 e1d2 g4h3 g2h3 e6f7 d2e1 f7f8 f2f4 d7h7 c4d3 h7d7 d3c4

go nodes 0
```

Populated planes:
https://gist.github.com/mooskagh/327e2380056ed41ee917fa5738ca20fd

For comparison, lczero populated planes for the same position:
https://gist.github.com/mooskagh/140e5d59cefc2340f8ce9ba454e11b3b

**Comment by DanielUranga** [comment]
how you get the populated planes?

**Comment by mooskagh** [comment]
You mean how to I dump them?

```cpp
for (auto& x : result) std::cerr << std::bitset<64>(x.bits) << ' ' << x.value << std::endl;
```

**Comment by mooskagh** [comment]
That game on lichess: https://lichess.org/qJ5Dhirq#65

**Comment by DanielUranga** [comment]
I think the issue is here: https://github.com/LeelaChessZero/lc0/blob/2321011913d8a7914d8177e82ceaf34fbe2d6ee8/src/chess/position.cc#L102
the loop should start from `int idx = positions_.size() - 1`, if not is not considering the last position.

**Comment by Tilps** [comment]
'last' is the last position - if you make that loop positions_.size() - 1(i.e. last) it will immediately terminate because last == last and thus return 1 because its repetition count is 0.
(That being said I've not worked out the problem yet.)

**Comment by DanielUranga** [comment]
but it goes from the last position to position 0, so if it uses `-3` is not counting the current position. I'm adding tests and I'm almost 100% sure that fixes the issue. PR in a couple minutes.

**Comment by DanielUranga** [comment]
Also it shouldn't be required to go to position 0, going back `GetNoCapturePly` positions should be enough, just a minor optimization.

**Comment by Tilps** [comment]
last == positions_.back() == positions_[positions_.size() - 1] - if idx == positions_.size()-1 (as proposed in the first loop) then last.GetBoard() == positions_[idx].GetBoard() - thus the if statement is true and it returns 1 + positions_[idx].GetRepetitions().  positions_[idx].GetRepetitions() is 0 as its never been set at this point - and so the function returns 1 unless it has hit the early out that 50 move rule is 0.

**Comment by DanielUranga** [comment]
Ok, I get what is happening, move 31. f4, is a two steps pawn move, so it creates an en-passant, so it's not technically the same position.

**Comment by DanielUranga** [comment]
But it is an en-passant wich can not be captured, so yes, there is a bug, but a minor one at least.

**Comment by Tilps** [comment]
aha that is a tricky case.

**Comment by mooskagh** [comment]
I was pointed to a similar discussion here: https://github.com/niklasf/python-chess/issues/144
