### ISSUE TITLE
What to include with the packaged cudnn windows binary

### ISSUE THREAD

**Issue by borg323** [LeelaChessZero/lc0#214]
Now that the additional permission is added to lc0 we can distribute the cuda/cudnn dlls together with lc0, but we have to add some extra files. The following is based on the [proposal](https://discordapp.com/channels/425419482568196106/425419999096733706/468350744383324161) by @mooskagh : 

1. A README.md file mentioning Nvidia licensed files (see later).
2. The COPYING file with the full GPL text. 
3. CUDA.txt with the CUDA eula.
4. CUDNN.txt with the CUDNN eula.

This seems to be enough. Am I missing anything?

Suggested text for the README.md:

---
# Lc0

Lc0 is a UCI-compliant chess engine designed to play chess via neural network, specifically those of the [LeelaChessZero project](https://lczero.org).

This binary uses CUDA and cuDNN dynamic link libraries copyrighted by [Nvidia corporation](http://www.nvidia.com), and redistributed as permitted by the respective license file (see CUDA.txt section 2.2 and CUDNN.txt section "CUDNN DISTRIBUTION" for details). You are authorized to redistribute these libraries together with this package as a whole but not individually.

## License

Leela Chess is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Leela Chess is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Leela Chess.  If not, see <http://www.gnu.org/licenses/>.

### Additional permission under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or
combining it with NVIDIA Corporation's libraries from the NVIDIA CUDA
Toolkit and the the NVIDIA CUDA Deep Neural Network library (or a
modified version of those libraries), containing parts covered by the
terms of the respective license agreement, the licensors of this
Program grant you additional permission to convey the resulting work.

**Comment by dubslow** [comment]
Perhaps the readme could contain a comment about how the binary and mixed license specifically exclude the blas/opencl backends as well? Is that important?

**Comment by borg323** [comment]
I want to keep README.md to the bare minimum for easy reviewing. We can add more material later.

**Comment by mooskagh** [comment]
Looks good!
But I think we should make it README.txt rather than .md (e.g. expand urls). If it will be just a file lying near .exe, there will be no way to render markdown. (I know .md is easily readable without rendering but still).

**Comment by borg323** [comment]
Simple conversion of README to txt:
```
Lc0

Lc0 is a UCI-compliant chess engine designed to play chess via
neural network, specifically those of the LeelaChessZero project
(https://lczero.org).

This binary uses CUDA and cuDNN dynamic link libraries copyrighted
by Nvidia corporation (http://www.nvidia.com), and redistributed as
permitted by the respective license file (see CUDA.txt section 2.2
and CUDNN.txt section "CUDNN DISTRIBUTION" for details). You are
authorized to redistribute these libraries together with this
package as a whole but not individually.


License

Leela Chess is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Leela Chess is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Leela Chess.  If not, see <http://www.gnu.org/licenses/>.

Additional permission under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or
combining it with NVIDIA Corporation's libraries from the NVIDIA CUDA
Toolkit and the the NVIDIA CUDA Deep Neural Network library (or a
modified version of those libraries), containing parts covered by the
terms of the respective license agreement, the licensors of this
Program grant you additional permission to convey the resulting work.
```
