### ISSUE TITLE
Define a new benchmark position

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#215]
Currently we mostly use `startpos` as a position to measure nps.

However, startpos is not very typical position for the chess. Near startpos there are many reasonable moves with similar evals, which makes search wide, node collisions rarer, batches larger, and `nps`es greater.

We should pick another position for benchmark and declare it a standard.
It may be just a middlegame position from an arbitrary game, or we can look at logs (e.g. from WCCC) and pick position with low nps (to be closer to "lower bound" of nps).

Example:
WCCC R5 had ~40000 nps at startpos, and only ~7k at this position:
```
position startpos moves e2e4 c7c5 g1f3 d7d6 d2d4 g8f6 b1c3 c5d4 f3d4 a7a6 f1e2 e7e5 d4b3 f8e7 e1g1 c8e6 f2f4 e8g8 g1h1 f8e8 f4f5 e6d7 e2f3 b7b5 a2a3 h7h6
```

**Comment by Error323** [comment]
Using my 2x 1080Ti and the following argv I'm getting 14185 nps:

`lc0 -t 4 --minibatch-size=512 --backend=multiplexing "--backend-opts=(backend=cudnn,gpu=0),(backend=cudnn,gpu=1)"`

**Comment by mooskagh** [comment]
What do you have on startpos?

It's possible that that position was slow in WCCC for other reasons (long GC after previous move, running our of RAM and starting to swap etc).

**Comment by Error323** [comment]
17836 nps on startpos with everything else equal.

**Comment by RedDenver** [comment]
There's some interesting positions with high and low number of legal moves at: https://www.chessprogramming.org/Perft_Results

Position 2 has 48 legal moves while position 4 has only 6.

**Comment by jjoshua2** [comment]
I would just use the sf ones...

**Comment by mooskagh** [comment]
Hm, I wonder if our `lc0 benchmark` should have some non-startpos fen as default?
@borg323 what do you think?

**Comment by ankan-ban** [comment]
Maybe add these positions:
https://www.chessprogramming.org/Perft_Results

**Comment by mooskagh** [comment]
I think it's better to add some "typical midgame position" rather than tricky position for movegen.
Also it should be just one.

**Comment by borg323** [comment]
I wasn't very happy using startpos by default, but it was what everybody was doing. So I like this idea, but we have to decide which position to use...

I also like the idea of testing multiple positions. This can be done as a script file, or maybe we can add an option to load a file with positions to run

I also want to add a `--moves` option. I thought there was an issue for that, but I can only find #15.

**Comment by Naphthalin** [comment]
`benchmark` from #1069 behaves now like intended. Issue can be closed.
