### ISSUE TITLE
OpenCL exhaustive tuning is broken.

### ISSUE THREAD

**Issue by frpays** [LeelaChessZero/lc0#216]
The normal search does a brute-force search in the valid configuration among:

```
    opts = {
        {"MWG", {16, 32, 64}},  {"NWG", {16, 32, 64}},  {"KWG", {32}},
        {"MDIMC", {8, 16, 32}}, {"NDIMC", {8, 16, 32}}, {"MDIMA", {8, 16, 32}},
        {"NDIMB", {8, 16, 32}}, {"KWI", {2}},           {"VWM", {1, 2, 4}},
        {"VWN", {1, 2, 4}},     {"STRM", {0}},          {"STRN", {0}},
        {"SA", {0, 1}},         {"SB", {0, 1}},
    };
```

The exhaustive search does the same inside a much larger set:
    opts = {
        {"MWG", {16, 32, 64}},  {"NWG", {16, 32, 64}},  {"KWG", {16, 32}},
        {"MDIMC", {8, 16, 32}}, {"NDIMC", {8, 16, 32}}, {"MDIMA", {8, 16, 32}},
        {"NDIMB", {8, 16, 32}}, {"KWI", {2, 8}},        {"VWM", {1, 2, 4, 8}},
        {"VWN", {1, 2, 4, 8}},  {"STRM", {0, 1}},       {"STRN", {0, 1}},
        {"SA", {0, 1}},         {"SB", {0, 1}},
    };

It's about 144x larger. To cope with it, lczero skipped 1/16 of the set elements.

` 
           if (cfg_sgemm_exhaustive) {
                if (rng.randfix<16>() != 0) {
                    continue;
                }
            }
`

I noticed that GCP's leela is using yet again more exhaustive parameter set:

```
            {"MWG", {16, 32, 64}},
            {"NWG", {16, 32, 64}},
            {"KWG", {16, 32}},
            {"MDIMC", {8, 16, 32}},
            {"NDIMC", {8, 16, 32}},
            {"MDIMA", {8, 16, 32}},
            {"NDIMB", {8, 16, 32}},
            {"KWI", {2, 8}},
            {"VWM", {1, 2, 4, 8}},
            {"VWN", {1, 2, 4, 8}},
            {"STRM", {0, 1}},
            {"STRN", {0, 1}},
            {"SA", {0, 1}},
            {"SB", {0, 1}},
```

Finally I coded a much more efficient stochastic algorithm which is able to cope with the largest parameter set.

I propose:

- To fix the exhaustive search.
- To add the stochastic algorithm as the default. 

Edit. Addressed by https://github.com/LeelaChessZero/lc0/pull/671.

**Comment by frpays** [comment]
MacOS

Normal Tuning:
```
Started OpenCL SGEMM tuner.
Will try 578 valid configurations.
(1/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=16 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 1.6232 ms (11.6 GFLOPS)
(11/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=1 VWN=1 0.9768 ms (19.3 GFLOPS)
(74/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.8254 ms (22.9 GFLOPS)
(75/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=1 0.7429 ms (25.4 GFLOPS)
(119/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=1 0.7219 ms (26.1 GFLOPS)
(194/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=2 VWN=2 0.6579 ms (28.7 GFLOPS)
(227/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=0 SB=0 STRM=0 STRN=0 VWM=4 VWN=2 0.5870 ms (32.2 GFLOPS)
(309/578) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=1 VWN=1 0.5602 ms (33.7 GFLOPS)
(363/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=1 0.5546 ms (34.0 GFLOPS)
(364/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=1 0.3968 ms (47.6 GFLOPS)
(369/578) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=1 0.2910 ms (64.9 GFLOPS)
(483/578) KWG=32 KWI=2 MDIMA=16 MDIMC=16 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2851 ms (66.2 GFLOPS)
(489/578) KWG=32 KWI=2 MDIMA=32 MDIMC=32 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=2 VWN=2 0.2649 ms (71.3 GFLOPS)```

**Comment by borg323** [comment]
Testing on colab with net10180, stochastic found a better result than exhaustive, but got slightly less nps:

 - With `tune_stochastic=true`
`(49/50) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 73.8 us (454.9 GFLOPS)`
go nodes 100000
`info depth 5 seldepth 24 time 142240 nodes 95680 score cp 20 hashfull 309 nps 672 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 f8d6 f1d3 g8e7 e1g1 e8g8 c1g5 c8g4 g5h4 d8d7 h4g3`

 - With default tuning
`(402/578) KWG=32 KWI=2 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=1 80.5 us (416.9 GFLOPS)`
go nodes 100000
`info depth 5 seldepth 24 time 148893 nodes 96738 score cp 20 hashfull 312 nps 649 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 f8d6 f1d3 g8e7 e1g1 e8g8 c1g5 b8c6 c2c3 c8g4 g5h4`

 - With `tune_exhausitve=true`
`(2410/4874) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=0 STRM=1 STRN=1 VWM=4 VWN=2 78.4 us (427.9 GFLOPS)`
go nodes 100000
`info depth 5 seldepth 24 time 141003 nodes 95231 score cp 20 hashfull 308 nps 675 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 f8d6 f1d3 g8e7 e1g1 e8g8 c1g5 c8g4 g5h4 d8d7 h4g3`

 - With cudnn
go nodes 100000
`info depth 5 seldepth 24 time 48950 nodes 95153 score cp 20 hashfull 325 nps 1943 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 f8d6 f1d3 g8e7 e1g1 e8g8 c1g5 c8g4 g5h4 d8d7 h4g3`

**Comment by borg323** [comment]
Also stopping the stochastic tuning early gives good performance, better than default.

**Comment by frpays** [comment]
How do you stop the the stochastic tuning early? Did you change into the
code?
I am wondering if we tune for the right kind of work then.

**Comment by frpays** [comment]
But maybe you found something important. I want to examine the size of the
matrices in tuning and conpare then with the typical one in inference. Also
the exceptions bother me.

**Comment by borg323** [comment]
Single thread, 3 runs `go nodes 50000` this time, net 10100. Results are more consistent.
 - stochastic
`(49/50) KWG=16 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 75.0 us (447.2 GFLOPS)`
`info depth 5 seldepth 20 time 95339 nodes 48190 score cp 24 hashfull 159 nps 505 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
`info depth 5 seldepth 20 time 95145 nodes 48190 score cp 24 hashfull 159 nps 506 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
`info depth 5 seldepth 20 time 95086 nodes 48190 score cp 24 hashfull 159 nps 506 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
 - exhaustive
`(4278/4905) KWG=32 KWI=8 MDIMA=32 MDIMC=16 MWG=64 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=1 STRN=0 VWM=2 VWN=2 77.2 us (434.9 GFLOPS)`
`info depth 5 seldepth 20 time 96967 nodes 48190 score cp 24 hashfull 159 nps 496 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
`info depth 5 seldepth 20 time 97680 nodes 48190 score cp 24 hashfull 159 nps 493 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
`info depth 5 seldepth 20 time 97833 nodes 48190 score cp 24 hashfull 159 nps 492 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`

Second try, same parameters. Here the nps are almost the same between exhaustive and stochastic, even though the expected performance differs. Maybe this gives a clue?
 - stochastic
`(49/50) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=0 STRN=0 VWM=4 VWN=2 75.8 us (442.4 GFLOPS)`
`info depth 5 seldepth 20 time 97284 nodes 48190 score cp 24 hashfull 159 nps 495 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
`info depth 5 seldepth 20 time 97018 nodes 48190 score cp 24 hashfull 159 nps 496 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
`info depth 5 seldepth 20 time 97256 nodes 48190 score cp 24 hashfull 159 nps 495 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
 - exhaustive
`(4752/4815) KWG=32 KWI=8 MDIMA=8 MDIMC=8 MWG=32 NDIMB=8 NDIMC=8 NWG=16 SA=1 SB=1 STRM=1 STRN=1 VWM=4 VWN=2 78.4 us (428.2 GFLOPS)`
`info depth 5 seldepth 20 time 96793 nodes 48190 score cp 24 hashfull 159 nps 497 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
`info depth 5 seldepth 20 time 97150 nodes 48190 score cp 24 hashfull 159 nps 496 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`
`info depth 5 seldepth 20 time 97227 nodes 48190 score cp 24 hashfull 159 nps 495 pv e2e4 e7e6 d2d4 d7d5 e4e5 c7c5 c2c3 c8d7 g1f3 b8c6 f1e2 g8e7 e1g1 c5d4 c3d4 e7f5`

**Comment by frpays** [comment]
Actually, I just realized that I left the middle-sized parameters set for stochastics.
Appologies. I should give you better results (but slower).

**Comment by mooskagh** [comment]
I don't know what's this is about, but is it still an issue?
@frpays ?

**Comment by frpays** [comment]
Sorry for the long answer.

I think this still is an issue: line 247 to 249 of OpenCLTunner are commented-out and the "exhaustive" search probably **never returns** for most users. It's probably hours of useless computations.

In my understanding, the "simple" search should take from 15 sec to 2 min and  the "exhaustive" search should be 10x longer, no more.

A quick fix would be to get back to the original lczero implementation. Find an updated appropriate factor of samples to skip, for the "exhaustive" search to be about 10x larger than the "simple" search. Using a random number generator also makes sense.

But as you understand, "exhaustive" is a misnomer. I developed a new "stochastic" approach to find the optimal settings faster. (https://github.com/frpays/lc0/commits/dev-opencl-tuner-regress). But the tests were not conclusive enough in my opinions. Since this development, some bugs have been found (ttl) that may also explain the discrepancies found during tests.  So this should be worth a new shot.

**Comment by frpays** [comment]
Addressed by https://github.com/LeelaChessZero/lc0/pull/671.
