### ISSUE TITLE
LC0 as an IDeA engine

### ISSUE THREAD

**Issue by CarlBicknell** [LeelaChessZero/lc0#220]
I have been told that for LC0 to work in Aquarium as an IDeA engine (it works fine in Aquarium in Sandbox, but not IDeA) it needs to support "exclude move".

Please could this be developed - it would be fantastic to use the engine this way.

**Comment by cwbriscoe** [comment]
Wouldn't the GUI just use the UCI "searchmoves" parameter for all possible moves except for the ones you want to exclude?  What is the UCI command that the GUI is sending to Leela?

**Comment by CarlBicknell** [comment]
Sorry I don't know the specifics except that in Aquarium LC0 works fine in sandbox as an analysis engine. But in IDeA it can't start. At first I thought it was a timeout issue, but on the talkchess forum someone said that in order for IDeA to build its tree properly, the UCI engine must support "exclude move".

**Comment by jjoshua2** [comment]
Use inbetween.exe to log passthrough an engine that works

**Comment by CarlBicknell** [comment]
Please ignore this thread. LC0 works in IDeA as it is. There was another problem which wasn't the engine's fault.
