### ISSUE TITLE
Store weights as flat binary

### ISSUE THREAD

**Issue by SunnyWar** [LeelaChessZero/lc0#255]
Example:

weights_576.txt.gz    size: 65.5 MB
weights_576.txt        size: 179 MB

all weights converted to 4 bytes segments and written with no delimiters
weights_576.bin       size:  54.3 MB

Advantages:
1. Weights file is smaller (about 17%)
2. Reading file is faster (smaller and not compressed)
3. Writing file is faster (smaller and not compressed)

**Comment by gonzalezjo** [comment]
I believe the protobuf efforts do this.

**Comment by SunnyWar** [comment]
@gonzalezjo  Do the weights at this link not reflect the protobuf work? [http://lczero.org/networks](url)

**Comment by dubslow** [comment]
They do not. The testserver weights, for a 20 block network, are under 50 MB, so significantly better compression than even this "bin" format.

**Comment by SunnyWar** [comment]
@dubslow ah...ok, Thanks.

**Comment by SunnyWar** [comment]
Word is this is unnecessary given protobuf.
