### ISSUE TITLE
Create a PR585 type variant for lc0

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lc0#27]
Either as a configuration parameter, or just as a never-to-submit PR which has it hard coded, implement a search option which gives every root child exactly one visit.
This should be able to be batched very efficiently, which might allow Aloril's spreadsheet to update PR585 columns much faster.

(As a stretch goal, support arbitrary depth alpha-beta search using value head, with policy head suggesting which child to search first to optimize the alpha-beta.  This however requires a different get_best_child implementation and probably doesn't provide a massive increase in value over the simple depth1 case for testing purposes.)

**Comment by dubslow** [comment]
Can this issue be closed with the existence of the PR?
