### ISSUE TITLE
Lets debug the v0.17 nps slowdown

### ISSUE THREAD

**Issue by dubslow** [LeelaChessZero/lc0#278]
Enough different people are reliably producing nps slowdowns with v0.17.0-rc1 compared to v0.16.0, independently of the time management.

Lets use the psuedo standard benchmark of everyone just running `go nodes n` from the start position. For most folks, `100000` or perhaps `10000000` will be good choices; run that from the start position and then copy and paste the final UCI `info` output line to a comment here; repeat that a handful of times with v0.17.0-rc1, and then run it identically the same in v0.16.0, and post the final info line from all trials here for comparison. Be sure to use the same options for both binaries (ignoring TM, this problem seems to be independent of TM), as well as please specify which backend you're using. All the reports I've seen so far have been on cuda, so I'd like to see some folks weigh in with OpenCL. (I'll try to run some CPU comparisons.)

**Comment by mooskagh** [comment]
It's probably not a simple slowdown due to slower code, but rather because of node selection order, which leads e.g. to smaller batches. May be for example because of more aggressive smart pruning or some effect of uint16 policy rounding.
Can someone run a bisect?

**Comment by Mardak** [comment]
Are there recommended options to use? Just plain ./lc0 with go nodes 1000000:
```
v0.17.0-rc1
info depth 11 seldepth 31 time 412936 nodes 815485 score cp 22 hashfull 1000 nps 1974 tbhits 0 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 g8f6 f1d3 f8d6 e1g1 e8g8 c1g5 c8g4 b1d2 c7c5 d4c5 d6c5 c2c3 b8d7 d1c2 h7h6 g5h4 d8c7 h4g3 c5d6 g3d6 c7d6 h2h3 g4e6

v0.16.0
info depth 5 seldepth 31 time 433656 nodes 812426 score cp 22 hashfull 1000 nps 1873 pv e2e4 e7e6 d2d4 d7d5 e4d5 e6d5 g1f3 g8f6 f1d3 f8d6 e1g1 e8g8 c1g5 c8g4 b1d2 c7c5 d4c5 d6c5 c2c3 b8d7 d1c2 h7h6 g5h4 d8c7 h4g3 c5d6 g3d6 c7d6 h2h3 g4e6 f1e1
```

**Comment by TCECfan** [comment]
OMG.  I am still TCECfan here;  I will debug my nick now.

**Comment by dubslow** [comment]
Hmm, perhaps I should specify that these `go nodes` commands should be run with `--no-smart-pruning` == `--futile-search-aversion=0`. Also, please sample each commit multiple times to ensure that the result is consistent.

**Comment by dubslow** [comment]
```git checkout v0.17.0-rc1 ; ninja; ./lc0 --minibatch-size=16 --max-prefetch=0 --backend=multiplexing --backend-opts="blas(threads=8)" -t 8 --verbose-move-stats -w ../../../weights/524-6-8averaged.pb.gz --futile-search-aversion=0
go nodes 100000

info depth 8 seldepth 28 time 1472454 nodes 100009 score cp 24 hashfull 327
```

(to be updated)

**Comment by dubslow** [comment]
Discordite Flavius has some excellent data showing that his cuda backend is unaffected:

```
lc0 --futile-search-aversion=0
       
|    | |
| | |_| v0.17.0-rc1 built Aug 19 2018
go nodes 100000
Found pb network file: ./Test_10_877
Creating backend [cudnn]...

info depth 8 seldepth 32 time 17896 nodes 100058 score cp 27 hashfull 352 nps 5591 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 e8g8 a4a5 b8d7
bestmove e2e4 ponder c7c5

info depth 8 seldepth 33 time 18176 nodes 100038 score cp 27 hashfull 352 nps 5503 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4 e8g8
bestmove e2e4 ponder c7c5

info depth 8 seldepth 32 time 18191 nodes 100121 score cp 27 hashfull 353 nps 5503 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 e8g8 d2c4
bestmove e2e4 ponder c7c5

info depth 8 seldepth 32 time 18303 nodes 100244 score cp 27 hashfull 353 nps 5476 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 e8g8 d2c4 f7f5
bestmove e2e4 ponder c7c5

info depth 8 seldepth 32 time 18032 nodes 100244 score cp 27 hashfull 353 nps 5559 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 e8g8 d2c4 f7f5
bestmove e2e4 ponder c7c5

avg nps=5526.4
```

```
lc0 --no-smart-pruning
       
|    | |
| | |_| v0.16.0 built Jul 20 2018
go nodes 100000
Found pb network file: ./Test_10_877
Creating backend [cudnn]...

info depth 5 seldepth 32 time 18632 nodes 100188 score cp 27 hashfull 367 nps 5377 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4 e8g8
bestmove e2e4

info depth 5 seldepth 32 time 18822 nodes 100127 score cp 27 hashfull 367 nps 5319 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4 e8g8
bestmove e2e4

info depth 5 seldepth 32 time 18657 nodes 100181 score cp 27 hashfull 366 nps 5369 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4 e8g8
bestmove e2e4

info depth 5 seldepth 32 time 18624 nodes 100188 score cp 27 hashfull 367 nps 5379 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4 e8g8
bestmove e2e4

info depth 5 seldepth 32 time 18633 nodes 100188 score cp 27 hashfull 367 nps 5376 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4 e8g8
bestmove e2e4

avg nps=5364.0
```

```
lc0 (withhout options)
       
|    | |
| | |_| v0.17.0-rc1 built Aug 19 2018
go nodes 100000
Found pb network file: ./Test_10_877
Creating backend [cudnn]...

info depth 8 seldepth 32 time 15566 nodes 85368 score cp 27 hashfull 304 nps 5484 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 g8f6 d2d4 c5d4 f3d4 a7a6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5
bestmove e2e4 ponder c7c5

info depth 8 seldepth 32 time 15483 nodes 85151 score cp 27 hashfull 304 nps 5499 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 g8f6 d2d4 c5d4 f3d4 a7a6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4 ponder c7c5

info depth 8 seldepth 32 time 15490 nodes 85151 score cp 27 hashfull 304 nps 5497 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 g8f6 d2d4 c5d4 f3d4 a7a6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4 ponder c7c5

info depth 8 seldepth 32 time 15498 nodes 85151 score cp 27 hashfull 304 nps 5494 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 g8f6 d2d4 c5d4 f3d4 a7a6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4 ponder c7c5

info depth 8 seldepth 32 time 15327 nodes 83726 score cp 28 hashfull 299 nps 5462 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4 ponder c7c5

avg nps=5487.2
```

```
lc0 (without options)
       
|    | |
| | |_| v0.16.0 built Jul 20 2018
go nodes 100000
Found pb network file: ./Test_10_877
Creating backend [cudnn]...

info depth 4 seldepth 32 time 15858 nodes 84086 score cp 27 hashfull 312 nps 5302 pv e2e4 c7c5 g1f3 d7d6 b1c3 g8f6 d2d4 c5d4 f3d4 a7a6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4

info depth 5 seldepth 32 time 15875 nodes 84324 score cp 27 hashfull 312 nps 5311 pv e2e4 c7c5 g1f3 d7d6 b1c3 g8f6 d2d4 c5d4 f3d4 a7a6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4

info depth 5 seldepth 32 time 15621 nodes 82685 score cp 28 hashfull 307 nps 5293 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4

info depth 5 seldepth 32 time 16641 nodes 88135 score cp 27 hashfull 327 nps 5296 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4

info depth 5 seldepth 32 time 15650 nodes 82868 score cp 28 hashfull 307 nps 5295 pv e2e4 c7c5 g1f3 d7d6 b1c3 g8f6 d2d4 c5d4 f3d4 a7a6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5 d2c4
bestmove e2e4

avg nps=5299.4
```

**Comment by Lephidiles** [comment]
980GTX cuda version in all tests.
v0.17.0-rc1 is faster with both default and settings you wanted

v0.17.0-rc1: (--futile-search-aversion=0)
info depth 8 seldepth 30 time 26237 nodes 100201 score cp 25 hashfull 348 nps 3819 tbhits 0 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 b1c3 f8e7 c4d5 e6d5 c1f4 c7c6 d1c2 f6h5 f4d2 h5f6
bestmove d2d4 ponder g8f6

v0.16.0: (--no-smart-pruning)
info depth 5 seldepth 30 time 27265 nodes 100065 score cp 25 hashfull 363 nps 3670 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 b1c3 f8e7 c4d5 e6d5 c1f4 c7c6 d1c2 f6h5 f4d2 h5f6 e2e3
bestmove d2d4

v0.17.0-rc1: (default)
info depth 8 seldepth 29 time 26442 nodes 99933 score cp 26 hashfull 350 nps 3779 tbhits 0 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5
bestmove e2e4 ponder c7c5

v0.16.0: (default)
info depth 5 seldepth 30 time 27476 nodes 100051 score cp 25 hashfull 365 nps 3641 pv e2e4 c7c5 g1f3 d7d6 b1c3 a7a6 d2d4 c5d4 f3d4 g8f6 c1e3 e7e5 d4b3 f8e7 b3d2 b7b5 a2a4 b5b4 c3d5 f6d5 e4d5 b8d7 a4a5 f7f5
bestmove e2e4

**Comment by roy7** [comment]
If relevant, from Discord:

> It turned out that openCl batching is off by default, so no 5x speedup is visible.
> To enable, use command like flag --backend_opts=batch_size=16.
> Due to another issue, it may happen that batch size 16 requires too much VRAM so it doesn't start. In that case, try lower values.

**Comment by mooskagh** [comment]
I think we can conclude that there is no performance drop.
Any objections?

**Comment by borg323** [comment]
As above but with opencl backend:
3982d30... Bump to version 0.16.0 (#199) `--no-smart-pruning`
info depth 5 seldepth 30 time 186777 nodes 100031 score cp 25 hashfull 365 nps 535

0b1e5ce... Batch computation for OpenCL (#191) `--smart-pruning-aggresiveness=0`
info depth 5 seldepth 31 time 180350 nodes 100200 score cp 25 hashfull 350 nps 555

0b1e5ce... Batch computation for OpenCL (#191) `--smart-pruning-aggresiveness=0 --backend-opts=batch_size=2`
info depth 5 seldepth 29 time 149339 nodes 100199 score cp 25 hashfull 350 nps 670

0b1e5ce... Batch computation for OpenCL (#191) `--smart-pruning-aggresiveness=0 --backend-opts=batch_size=4`
info depth 5 seldepth 30 time 139110 nodes 100179 score cp 24 hashfull 348 nps 720

0b1e5ce... Batch computation for OpenCL (#191) `--smart-pruning-aggresiveness=0 --backend-opts=batch_size=8`
info depth 5 seldepth 30 time 139313 nodes 100166 score cp 24 hashfull 348 nps 718

0b1e5ce... Batch computation for OpenCL (#191) `--smart-pruning-aggresiveness=0 --backend-opts=batch_size=16`
info depth 5 seldepth 31 time 140832 nodes 100101 score cp 25 hashfull 350 nps 710

83bf29c... Bump to v0.17.0-rc1 `--futile-search-aversion=0`
info depth 8 seldepth 31 time 179856 nodes 100145 score cp 25 hashfull 348 nps 556

83bf29c... Bump to v0.17.0-rc1 `--futile-search-aversion=0 --backend-opts=batch_size=2`
info depth 8 seldepth 30 time 149566 nodes 100032 score cp 25 hashfull 350 nps 668

83bf29c... Bump to v0.17.0-rc1 `--futile-search-aversion=0 --backend-opts=batch_size=4`
info depth 8 seldepth 30 time 140245 nodes 100224 score cp 25 hashfull 350 nps 714

83bf29c... Bump to v0.17.0-rc1 `--futile-search-aversion=0 --backend-opts=batch_size=8`
info depth 8 seldepth 30 time 139845 nodes 100033 score cp 25 hashfull 348 nps 715

83bf29c... Bump to v0.17.0-rc1 `--futile-search-aversion=0 --backend-opts=batch_size=16`
info depth 8 seldepth 31 time 140640 nodes 100014 score cp 25 hashfull 348 nps 711

**Comment by borg323** [comment]
The only other patch that may be causing a nps difference is #244 (update to cudnn 7.2.1) but this should only affect the appveyor built windows cuda package.
On colab the above results were with cudnn 7.2.1. Redoing the test for "3982d30... Bump to version 0.16.0 (#199) `--no-smart-pruning`"
 * cudnn 7.1.4:
info depth 5 seldepth 30 time 60171 nodes 100228 score cp 25 hashfull 365 nps 1665
 * cudnn 7.2.1 (previous result):
info depth 5 seldepth 30 time 59173 nodes 100073 score cp 25 hashfull 364 nps 1691

Here the latest cudnn version looks like an improvement.

**Comment by dubslow** [comment]
Having collected and viewed much more data, I'm now satisfied that this can be closed as non-existent.
