### ISSUE TITLE
v0.17.0-rc1 losing on time

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#279]
There are many reports on lc0 loosing on time.
Seemingly only happen on openCL, so no need to hurry for CCCC, but has to be fixed for v0.17 release.

Examples:
http://talkchess.com/forum3/viewtopic.php?f=2&t=68259
http://talkchess.com/forum3/viewtopic.php?f=2&t=68255
https://groups.google.com/d/topic/lczero/HgLzOnuWea0/discussion
Multiple complaints on discord.

**Comment by Lephidiles** [comment]
Might be unrelated, but my SF9 also looses a lot on time if the TB is located at a "old" normal HDD (not SSD) but changing to 5 men and putting it on the SSD fixes the issue for SF9. Have not had the issue my self with Lc0

**Comment by Videodr0me** [comment]
The problem is that on a slow HD that might spin down during the early part of the game, and then when TB is needed (for example in SF if DTZ are on a different drive) has to be spun up, which can take 5 - 8 seconds. There are tools that prevent HD spindown.
