### ISSUE TITLE
How to distribute binaries for other cuda versions

### ISSUE THREAD

**Issue by borg323** [LeelaChessZero/lc0#280]
The binaries on the release page are for cuda 9.2. Some people with older cards have asked for cuda 9.0 and 9.1 binaries. I have created branches for them in my tree, that I will be updating after each release tag so that appveyor will create binaries. The following links will always point to the latest version:
* [Cuda 9.0 executable only](https://ci.appveyor.com/api/projects/borg323/lc0/artifacts/build/lc0.exe?branch=cuda90)
* [Cuda 9.0 zip with dlls](https://ci.appveyor.com/api/projects/borg323/lc0/artifacts/lc0-windows-cuda90.zip?branch=cuda90)
* [Cuda 9.1 executable only](https://ci.appveyor.com/api/projects/borg323/lc0/artifacts/build/lc0.exe?branch=cuda91)
* [Cuda 9.1 zip with dlls](https://ci.appveyor.com/api/projects/borg323/lc0/artifacts/lc0-windows-cuda91.zip?branch=cuda91)

While this approach works, it requires human intervention. Any ideas for a better approach?

**Comment by xghostxx** [comment]
Maybe looking into the way SF does things at http://abrok.eu/stockfish/ would be useful?

**Comment by mooskagh** [comment]
Obsolete.
