### ISSUE TITLE
protobuf not compiling/installing on Ubuntu 16.04

### ISSUE THREAD

**Issue by RedDenver** [LeelaChessZero/lc0#283]
I get the following after building from the repo:
`lc0 --weights=code/leela/weights/weights_598.txt.gz
lc0: error while loading shared libraries: libprotobuf-lite.so: cannot open shared object file: No such file or directory`

the compile looks like it builds protobuf but then says it doesn't find it:
```
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library libprotobuf found: NO
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Dependency protobuf found: NO
Program protoc found: NO
Using protobuf from cache.
Using protobuf-3.5.1-2w-wrap.zip from cache.

|
|Executing subproject protobuf.
|
|Project name: protobuf
|Project version: 3.5.1
|Native C++ compiler: clang++-6.0 (clang 6.0.1-svn334776 "clang version 6.0.1-svn334776-1~exp1~20180817181751.91 (branches/release_60)")
|Compiler for C++ supports arguments -DHAVE_PTHREAD: YES
|Compiler for C++ supports arguments -Wno-sign-compare: YES
|Compiler for C++ supports arguments -Wno-unused-parameter: YES
|Compiler for C++ supports arguments -Wno-ignored-qualifiers: YES
|Compiler for C++ supports arguments /wd4146: NO
|Compiler for C++ supports arguments /wd4244: NO
|Compiler for C++ supports arguments /wd4305: NO
|Compiler for C++ supports arguments /wd4506: NO
|Dependency threads found: YES
|Build targets in project: 6
|
|Subproject protobuf finished.
Library pthread found: YES
Library dl found: YES
Library libtensorflow_cc found: NO
Library libprotobuf found: NO
```

I tried installing protobuf in Ubuntu with:
`sudo apt-get install libprotobuf-dev`

Now the compile shows: `Library libprotobuf found: YES`
and I get a different error message:
`lc0 --weights=code/leela/weights/weights_598.txt.gz
lc0: symbol lookup error: lc0: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E`

I then tried installing protobuf compiler with:
`sudo apt-get install libprotoc-dev`

The compile still shows: `Program protoc found: NO`
And the execution still has error: 
`lc0 --weights=code/leela/weights/weights_598.txt.gz
lc0: symbol lookup error: lc0: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E`

**Comment by cwbriscoe** [comment]
When you cloned, did you include ```--recurse-submodules```?  I forgot not too long back and got a similar error.

```git clone -b release --recurse-submodules https://github.com/LeelaChessZero/lc0.git```

**Comment by RedDenver** [comment]
I tried `git submodule update --init --recursive` and `git submodule update --recursive` to no avail. And then I deleted my local repo and tried `git clone -b release --recurse-submodules https://github.com/LeelaChessZero/lc0.git', but that didn't work either.

**Comment by RedDenver** [comment]
I installed protobuf-compiler and libprotobuf-dev, so I have the same installed as cwbriscoe:
```
apt list --installed | grep protobuf
libmirprotobuf3/xenial-updates,xenial-security,now 0.26.3+16.04.20170605-0ubuntu1.1 amd64 [installed]
libprotobuf-dev/xenial,xenial,now 2.6.1-1.3 amd64 [installed]
libprotobuf-lite9v5/xenial,xenial,now 2.6.1-1.3 amd64 [installed]
libprotobuf9v5/xenial,xenial,now 2.6.1-1.3 amd64 [installed]
protobuf-compiler/xenial,xenial,now 2.6.1-1.3 amd64 [installed]
```

But still getting this error: `lc0 --weights=code/leela/weights/weights_598.txt.gz
lc0: symbol lookup error: lc0: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringB5cxx11E`

**Comment by RedDenver** [comment]
Ok, I got it to work. After installing protobuf using apt-get, I was using `./build.sh` to compile, which wasn't working. But when I compiled using: 
```CC=clang-6.0 CXX=clang++-6.0 INSTALL_PREFIX=~/.local ./build.sh```
(which I had been using before installing protobuf), then it worked. I'm not sure why, but hopefully this helps somebody else.

**Comment by dubslow** [comment]
Protobuf has always been whacky with versioning; often the system version is incompatible with whatever version we're using. Some people have found that commenting out a few clauses in `meson.build`, to fake out meson into not finding any pre-installed versions and instead compiling the meson subproject version of pb, which is known to be compatible with our stuff (by construction), works. Perhaps that's worth trying? For you and for future folks.
