### ISSUE TITLE
Alpha test of OpenBench for lc0

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#284]
@DanielUranga aka fersberry has let me setup an Alpha test of OpenBench for lc0. This will allow us to formalize the testing of changes to code and/or parameters. @mooskagh is working on a longer term solution, but until then we can use Andy Grant's OpenBench with some small changes.

Working:
* Auto git clone and build of arbitrary git SHAs from github
* Auto download of network file
* lc0 vs lc0 SPRT tests

Limitations for now:
* Only supports linux, and maybe only Nvidia GPUs
* Only supports lc0 vs lc0 SPRT tests (lc0 vs A/B engine TBD). 
* Does not support scaling yet, so all machines fast or slow use the same time controls.
* Names of tests are the branch or SHA being tested. For branch this isn't too bad but for SHA it's not good. We need an extra field to allow users to give a short title for the test, and maybe a longer description field also.

We need a few Alpha testers with Linux and Nvidia GPU to test. To help, create an account on the server:
* http://ec2-34-217-73-2.us-west-2.compute.amazonaws.com:8000

Next (Note the temporary bug workaround `mkdir Engines`)
```
pip3 install bs4 lxml
git clone -b lc0 https://github.com/killerducky/OpenBench
cd OpenBench/Client
mkdir Engines
python3 OpenBench.py -U username -P password -S http://ec2-34-217-73-2.us-west-2.compute.amazonaws.com:8000 -T 2
```

The client will upload results every 10 games. To stop the client just ctrl-c it.

The first test is of @DanielUranga's minimaxtake2 branch: https://github.com/LeelaChessZero/lc0/pull/243

**Comment by killerducky** [comment]
Setting up a test:
![screenshot from 2018-08-20 19-50-53](https://user-images.githubusercontent.com/64080/44374757-90318380-a4b5-11e8-99cf-ea486c6d28d5.png)

* Dev/Base Branch can be a git branch name, or an arbitrary git SHA.
* Dev/Base Bench is not used yet, just put a fake number 1 there.
* Dev/Base Options
  * threads *must* be first
  * UCI options, not command line.
  * Use "_" instead of " "
  * Network is the number, this network is auto-downloaded from http://testserver.lczero.org

**Comment by DanielUranga** [comment]
Collab OpenBench client script: https://colab.research.google.com/gist/DanielUranga/8396193da473bfa2f1366fe89344335b/lc0-openbench.ipynb

**Comment by Videodr0me** [comment]
Fantastic. This is much needed.

**Comment by killerducky** [comment]
Estimating the cost of SPRT tests:
https://gist.github.com/AndyGrant/fdcb97d8deeb2540d6108741aac3a016
```
usage: estimate.py [-h] [--alpha ALPHA] [--beta BETA] [--lower LOWER]
                   [--upper UPPER]
                   elo_diff draw_rate

python estimate.py 10 .6 --lower=0 --upper=5 --alpha=0.95 --beta=0.95
```

| Elo diff | Games |
| ---:| -----:|
| -15 |  2676 |
| -10 |  3829 |
|  -5 |  6731 |
|   0 | 27767 |
| 2.5 | 49385 |
|   5 | 13064 |
|  10 |  5286 |
|  15 |  3312 |
|  20 |  2411 |
|  25 |  1894 |
|  30 |  1560 |

**Comment by roy7** [comment]
Some extra instructions.

pip install bs4 lxml
mkdir Networks

**Comment by gonzalezjo** [comment]
Instructions should say Client, not client. should exist 


Auto-download of networks file is broken if the Networks folder does not exist in Client.

**Comment by roy7** [comment]
> ./cutechess: error while loading shared libraries: libQtCore.so.4: cannot open shared object file: No such file or directory

Prob since I"m using ssh. Should cutechess-cli be used when there's no terminal? Or doesn't matter if there's no display available?

**Comment by DanielUranga** [comment]
@roy7 run `apt install libqtcore4`, that will work on Debian based systems.

**Comment by killerducky** [comment]
mps19 reports:
* 10583 > 10965 by 60 Elo vs A/B Engines
* 10965 > 10583 by 30 Elo in self play

That's a 90 Elo difference in results of vs A/B Engines compared to self-play. I'd like to replicate this in OpenBench.

```
   # PLAYER            :  RATING  ERROR  POINTS  PLAYED   (%)  CFS(%)
   1 Stockfish 9       :    3446     26   135.0     214  63.1      95
   2 lc0 10583         :    3411     37   114.5     181  63.3      82
   3 Stockfish 8       :    3393     25   123.5     224  55.1      61
   4 lc0_tcec 10520    :    3385     45    57.5      94  61.2      55
   5 lc0 10520         :    3382     35    74.5     124  60.1      55
   6 lc0 10751         :    3379     41    78.0     130  60.0      51
   7 lc0 10663         :    3378     54    55.5     102  54.4      62
   8 lc0 10852         :    3365     54    41.0      70  58.6      66
   9 lc0 10780         :    3353     33   122.5     216  56.7      54
  10 lc0 10965         :    3351     41    79.5     140  56.8      86
  11 lc0 10925         :    3322     40    54.5     104  52.4      83
  12 lc0 594           :    3296     46    50.5     104  48.6      77
  13 Stockfish 5       :    3278     25    76.0     185  41.1      66
  14 Ethereal 10.55    :    3271     30    79.0     208  38.0      55
  15 Ethereal 10.81    :    3268     41    60.0     160  37.5      57
  16 Andscacs 0.94     :    3264     38    73.5     194  37.9      78
  17 lc0 10161         :    3244     47    46.0     104  44.2      98
  18 Laser 1.6         :    3188     35    48.0     184  26.1     ---
```

```
   # PLAYER            :  RATING  ERROR  POINTS  PLAYED   (%)  CFS(%)
   1 lc0 10965         :     163     74    46.0      80  57.5      78
   2 lc0 10751         :     139     70    60.0     112  53.6      59
   3 lc0 10583         :     133     58    97.5     177  55.1      73
   4 lc0 10520         :     118     54    88.0     166  53.0      55
   5 lc0 10663         :     114     65    52.0     102  51.0      59
   6 lc0 10780         :     108     71    49.5      98  50.5      57
   7 lc0 10925         :     101     93    19.5      40  48.8      54
   8 lc0 10852         :      97     81    24.5      50  49.0      62
   9 lc0_tcec 10520    :      82     87    15.0      30  50.0      80
  10 lc0 594           :      45     55    62.5     151  41.4      95
  11 lc0 10161         :       0   ----    29.5      82  36.0     ---
```

**Comment by killerducky** [comment]
Some tests are getting timeouts. It looks like most of them are from google colabs machines (Raincloud and xyzzy), but my machine is also getting some:
http://ec2-34-217-73-2.us-west-2.compute.amazonaws.com:8000/viewTest/8/ - 10/100
http://ec2-34-217-73-2.us-west-2.compute.amazonaws.com:8000/viewTest/7/ - 48/920
http://ec2-34-217-73-2.us-west-2.compute.amazonaws.com:8000/viewTest/4/ - 1/140

These are some related PRs:
https://github.com/LeelaChessZero/lc0/pull/277
https://github.com/LeelaChessZero/lc0/pull/243
https://github.com/LeelaChessZero/lc0/pull/276

**Comment by killerducky** [comment]
See also https://github.com/LeelaChessZero/lc0/issues/105

I couldn't reproduce timeouts on my machine. But I did see it using up to 68ms of the 100ms move-overhead buffer. So there's a good chance it was exceeded in a few games. And maybe google colab machines are more vulnerable.

**Comment by killerducky** [comment]
No near term plans to work on this. Closing for now.
