### ISSUE TITLE
Poor endgame play using TB

### ISSUE THREAD

**Issue by LC0fan** [LeelaChessZero/lc0#288]
I ran 2x130 games of lc0 17.10900 vs Stockfish 8, TC 1min+1sec, default settings, lc0 using GTX960, SF using 4 cores from i7-6700.
Leela scored 45.5/130 without TB.
Leela scored 44.0/130 with access to full (WDL only) Syzygy TB (up to 6-men).
I watched many of "with-TB" games live and noticed some poor endgame play.
For example, TB seemed to cause her to lose this one (Example 1): https://lichess.org/ptBeFuhX#131 
Example 2:   https://lichess.org/OG5jGRG2#170 
Example 3:  https://lichess.org/74aSSX3k#184
I have many more examples...

**Comment by xghostxx** [comment]
This probably has to do with Leela just not having "learned" those particular end games yet. (I know there is a spreadsheet where this was being tracked as well but those tend to be quite hard to find)

Are you sure the "poor endgame play" was not present in both selections of games, including those without tb?

Have you tried playing Leela with and without TB on specific endgame cases against SF and seeing the results of that?

**Comment by LC0fan** [comment]
Example 4: https://lichess.org/DZ3hlVuK#282 
Example 5: https://lichess.org/zKEYbXJZ#163
I skimmed through all 130 games, and I only found these 5 examples, so there were not as many examples as I thought earlier.
@xghostxx  I haven't got that far yet.  It might be worse or as bad with TB off.  I am just highlighting this issue for now.

**Comment by LC0fan** [comment]
I just tried example 1 for leela without TB (starting at move 56), the result was a draw.

**Comment by Tilps** [comment]
Maybe try with #293

**Comment by jjoshua2** [comment]
#293 is merged and fixes this. If there are still issues, open a new ticket
