### ISSUE TITLE
Add noconfig option to be sent by the client.

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lc0#295]
The new config support potentially overrides command line arguments which is not ideal for when lc0 is invoked by the client.
I guess this could be accomplished with --config= with a code change to make that legal, but it might be clearer with a noconfig option.

**Comment by cwbriscoe** [comment]
Is this with selfplay?  If so, config files don't load in selfplay mode.

**Comment by Tilps** [comment]
Match games don't use selfplay.

**Comment by cwbriscoe** [comment]
Oh so they use UCI then?  Then I think your suggestion to override config to nothing would be pretty easy to implement.  I will do it unless you want to.

**Comment by cwbriscoe** [comment]
If you do `./lc0 --config=` it will actually not load a configuration file.  It incorrectly reports that it does.  I will fix it so that it does not give the erroneous message.

**Comment by cwbriscoe** [comment]
@Tilps Does my PR fix your concerns?  Also, command line parameters will always override anything in the configuration file.  Lc0 now parses the command line twice.  Here is the order of operations:
1.  Parse command line to get the --config option
2.  Parse whatever is in --config or lc0.config.
3.  Parse the command line again which will override anything set in the config file if also specified on the command line.

**Comment by mooskagh** [comment]
We are switching to matches using `selfplay`, it won't have this problem anymore!

**Comment by Tilps** [comment]
I think the concerns were already addressed by PR301 anyway :)
