### ISSUE TITLE
UCI options should be case insensitive

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#296]
`The name of the option in  should not be case sensitive and can inludes spaces like also the value.`
http://wbec-ridderkerk.nl/html/UCIProtocol.html

**Comment by mooskagh** [comment]
Currently Uci option name also acts as a help for `./lc0 --help`.
I think we should separate them. That way we can introduce shorter/more standard Uci options, and won't be limited in space for help.

**Comment by oscardssmith** [comment]
This was fixed in v19, right?

**Comment by mooskagh** [comment]
Indeed!
