### ISSUE TITLE
UCI option for limiting memory use

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#298]
We need an option to limit memory use. UCI defines "Hash". Some options:

1) Use Hash to limit size of search tree (nodes/edges allocated)
1) Use Hash to limit size of search tree + nncache + other large structures (are there any?)
1) Make a new option to limit size of search tree + nncache + other large structures (are there any?)

**Comment by karolm2** [comment]
+1 This is what I opt for here: https://github.com/LeelaChessZero/lc0/issues/318  Very important request.

**Comment by oscardssmith** [comment]
Exists in v19. Should be closed.
