### ISSUE TITLE
Avoid temperature moves with only one (or two) visits

### ISSUE THREAD

**Issue by gonzalezjo** [LeelaChessZero/lc0#304]
If this is considered a valid issue, I'm willing to write a PR. 

Leela Zero does not play "temperature moves" that only have one visit. This should prevent some of the more egregious moves from entering training game data.

**Comment by killerducky** [comment]
Some earlier related discussion (OP of this issue suggests we do the opposite of what you suggest)
https://github.com/glinscott/leela-chess/issues/559

**Comment by gonzalezjo** [comment]
That’s... interesting. Definitely makes me rethink things. I’m firmly on the side of increasing exploration at almost all costs, but I’m also on the side that temperature can have some negative side effects. I wish we had more data. It’s hard for me to hold both beliefs.



My prior reasoning for this comes from this issue, where gcp discusses the impact of temperature on Leela Chess: https://github.com/gcp/leela-zero/issues/1355



> I can definitely point at positions where Leela Chess is sometimes doing badly because of high temperature, i.e. where it plays to drawn endings from a better position, only because the resulting positions makes it much more likely for the worse player to blunder. Something similar happens to giving very high evaluation to making some threats around the king, and that sometimes causes lost games.



And also: 



> The reasoning is that by selecting moves with 1 visit, you are actually neglecting the result of the tree search.



You commented on it, which was cool! So now I’m wondering what insights you might have on this, given that you’ve probably had it in your mind for w longer than I have.




We know that the Leelas need exploration. We also know that they benefit from having higher quality games to work work with. Both are *likely* to help raise the learning ceiling, but I guess it’s a tradeoff.

**Comment by jjoshua2** [comment]
I think it is necessary for noise alone to be able to cause a move to be
considered and played in training occasionally.
But it also should not normally happen in the average endgame otherwise it
will expect that you can win merely by not blundering. Yes there is some
chance but it is a very small chance against even a mid level engine.

**Comment by jjoshua2** [comment]
So the way I would balance this is to do enough visits where noise alone
gives something like 1/1000 of two visits which would mean over 50 moves
there is a small chance of a blunder and not allow moves with one or zero
visits. This is what leela go did.

**Comment by gonzalezjo** [comment]
Do you think that’s worth the decrease in game rate? Are there any estimates on the game generation speedup that adaptive resign rate can provide?

**Comment by dubslow** [comment]
I'm in favor of excluding one visit moves from temperature selection. Dealing with First Play Urgency has been a problem, and excluding one visit moves in a way gives a good way to ignore the problems of FPU when it comes to positional variety.

**Comment by oscardssmith** [comment]
Should be closed. Temp offset handles this.
