### ISSUE TITLE
lco v0.17.0 bug

### ISSUE THREAD

**Issue by AlingoAlingo** [LeelaChessZero/lc0#314]
![img_20180827_164704](https://user-images.githubusercontent.com/33194033/44663827-43502e80-aa1a-11e8-9815-8d04ad59ea25.jpg)
 lc0 v0.17.0 opencl crash on chessbase 14 and 13

**Comment by cwbriscoe** [comment]
Why did you open another issue instead of updating your existing issue here: https://github.com/LeelaChessZero/lc0/issues/248

We cannot help unless you give us more info.  See my post in your original issue.
