### ISSUE TITLE
Application Error - v0.17 Crash

### ISSUE THREAD

**Issue by karolm2** [LeelaChessZero/lc0#318]
![crash](https://user-images.githubusercontent.com/42834450/44844633-bb516b00-ac4b-11e8-8f5f-358e72894005.png)

This happend in v.0.17 lc0 CUDA:

The exception unknown software exception (0x40000015) occured in the application at location 0xf3c3eacf.

Hardware: GeForce GTX 1060
GUI: HIARCS Chess Explorer v 1.9.2.
Number of worker threads set to 1.

The error occured around depth 27 while analysing the following position:

r1bq1rk1/pppp1ppp/2n2n2/8/3BP3/2N5/PPP2PPP/R2QKB1R w KQ - 1 8

**Comment by karolm2** [comment]
And now I realised that memory usage keeps growing endlessly during infinite analysis, which is likely to be the cause of this error. Is this memory leak?

**Comment by karolm2** [comment]
OK, so now i understand that the whole tree has to be stored in memory, which is why RAM usage keeps growing while doing infinite analysis (see Task Manager). But this doesn't change the fact that the way Leela utilizes RAM is very bad, because once the whole memory is filled - lc0.exe crashes. So here's what I think shuld be done to improve this:

1) fixed amount of memory for search tree should be allocated while lc0.exe is being launched.
2) this amount of memory could be called 'Hash' - even though it's not hash per se.
3) this amount of memory can be adjusted in UCI protocol by: setoption name Hash value...
4) after "go infinite" - once memory is 100% filled the search stops and the engine gives result: bestmove...

**Comment by oscardssmith** [comment]
How much ram do you have? The main reason this hasn't been done is because it takes a very long time (hours) to fill ram so it doesn't usually come up.

**Comment by karolm2** [comment]
My machine has 8GB RAM. Leela crashes after filling about 5GB (remaining 3GB are used by other system tasks). Chess players use engines to analyze positions for many hours. During infinite analysis I have to keep my Task Manager open to control RAM usage, which is quite uncomfortable.

**Comment by all12** [comment]
I have the same problem and I have ->

16GB RAM
