### ISSUE TITLE
Meson "ValueError: path is on mount 'C:', start on mount 'E:'"

### ISSUE THREAD

**Issue by zeFresk** [LeelaChessZero/lc0#325]
### Problem/Bug

When building the latest release on Windows 10 I get an error if the source files are located on a different drive than meson.

**Logs**

> E:\Users\zeFresk\Documents\Programmation\Contributions\lc0>call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" amd64
> **********************************************************************
> ** Visual Studio 2017 Developer Command Prompt v15.7.6
> ** Copyright (c) 2017 Microsoft Corporation
> **********************************************************************
> [vcvarsall.bat] Environment initialized for: 'x64'
> The Meson build system
> Version: 0.47.2
> Source dir: E:\Users\zeFresk\Documents\Programmation\Contributions\lc0
> Build dir: E:\Users\zeFresk\Documents\Programmation\Contributions\lc0\build
> Build type: native build
> Project name: lc0
> Project version: undefined
> Native C++ compiler: cl (msvc 19.14.26433)
> Build machine cpu family: x86_64
> Build machine cpu: x86_64
> Library libprotobuf found: NO
> Found Pkg-config: NO
> Dependency protobuf found: NO
> Program protoc found: NO
> [...]
> Dependency [1mgtest[0m from subproject [1msubprojects\gtest[0m found: [1;32mYES[0m
> Build targets in project: [1m13[0m
> Traceback (most recent call last):
>   File "c:\users\zefresk\appdata\local\programs\python\python37\lib\site-packages\mesonbuild\mesonmain.py", line 351, in run
>     app.generate()
>   File "c:\users\zefresk\appdata\local\programs\python\python37\lib\site-packages\mesonbuild\mesonmain.py", line 117, in generate
>     self._generate(env)
>   File "c:\users\zefresk\appdata\local\programs\python\python37\lib\site-packages\mesonbuild\mesonmain.py", line 166, in _generate
>     intr.backend.generate(intr)
>   File "c:\users\zefresk\appdata\local\programs\python\python37\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 164, in generate
>     projlist = self.generate_projects()
>   File "c:\users\zefresk\appdata\local\programs\python\python37\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 364, in generate_projects
>     self.gen_vcxproj(target, str(projfile_path), proj_uuid)
>   File "c:\users\zefresk\appdata\local\programs\python\python37\lib\site-packages\mesonbuild\backend\vs2010backend.py", line 833, in gen_vcxproj
>     args.append('-I' + self.relpath(curdir, target.subdir)) # build dir
>   File "c:\users\zefresk\appdata\local\programs\python\python37\lib\site-packages\mesonbuild\backend\backends.py", line 253, in relpath
>     os.path.join('dummyprefixdir', fromdir))
>   File "c:\users\zefresk\appdata\local\programs\python\python37\lib\ntpath.py", line 564, in relpath
>     path_drive, start_drive))
> ValueError: path is on mount 'C:', start on mount 'E:'
> Microsoft (R) Build Engine version 15.7.180.61344 pour .NET Framework
> Copyright (C) Microsoft Corporation. Tous droits réservés.
> 
> MSBUILD : error MSB1009: Le fichier projet n'existe pas.
> Commutateur : lc0.sln

**Quick fix**

Compile on the same drive as meson/cuda/cudnn.

I'm not familiar with meson so I don't know if it can be easily fixed but I think it shouldn't happen.

**Comment by mooskagh** [comment]
Asked in #mesonbuild channel on freenode. Here is the conversation:


`09:30 <crem>` Hi! People complain that they cannot build if meson is located on other drive than project, in windows. https://github.com/LeelaChessZero/lc0/issues/325

`09:31 <crem>` Is it indeed the case?

`09:40 <textshell>` crem: It's possible that there is an regression. I know that some time meson got fixed to allow source and build directory on different drives. Absolute pathes on windows are a bit special when crossing drives and it's not tested in CI.

`09:44 <textshell>` But in that report something seems missing. I don't think vcvars64.bat will start meson...

`09:45 <crem>` I think he ran https://github.com/LeelaChessZero/lc0/blob/master/build-cuda.cmd

`09:47 <textshell>` anyway. It's supposed to work i would say, but someone with windows will need to have a look why this might be failing. Maybe meson needs to wrap relative path calls so they can switch to absolute pathes when needed on windows.

`09:47 <GoaLitiuM>` for the time being if you really need to have the files in different drive, you could use symlinks to get around it

**Comment by cyrenaique** [comment]
@zeFresk i did compile on the same drive (meson/cuda/cudnn) but still got this error.
Did you change anything else?
Best,
Arnaud
