### ISSUE TITLE
Multi-PV pondering

### ISSUE THREAD

**Issue by zz4032** [LeelaChessZero/lc0#331]
Current pondering implentation is "thinking" on the single best possible opponent move from pv.

My guess is that since NN-engines produce instant multi-pv without loss in playing strength as it's the case with AB-engines, a better implementation would be multi-pv pondering.
There are several reasons to switch from the 1st best guessed opponent move to the 2nd (3rd ...) best move:
1) Ponder move can be responded with a mate (actually same as 3.)
2) Ponder move leads to a tablebase position, the 2nd/3rd.. best move doesn't
3) If the engine discovers in the process of calculation that the pv move is indeed worse (fail high) and the 2nd best move would become the "new 1st".

Even if none of the above is the case, dividing resources between several moves might still be beneficial.
The weighting distribution of how many time to spend on which move could be estimated by the evaluations of the moves and any kind of a function, resulting in most of the calculation resources for the 1st pv-move, less for the next and so on.

What is your opinion on this?

**Comment by zz4032** [comment]
One more reason for that is I always wanted the engine I play against not to have the "unnatural" behaviour responding instantly when I play the ponder move of the engine and thinking for the usual time if I play any other move. That's not what humans do (thinking about only one possible opponent move) and that's why I suspect the engine shouldn't.

I know hardly anyone nowadays is playing against engines...
Which is actually a good idea in case of Leela because of it's playing style.

**Comment by zz4032** [comment]
In Leela's blog an article appears today saying:
> Ponder is Leela's ability to think during opponent's time. Unlike most of other engines, which think about one opponent's move, Leela thinks about all of them. Leela thinks more about more likely moves though.
Is it really the case? This would make this issue unnecessary.

**Comment by mooskagh** [comment]
Yes, we never had pondering which only thought on one move.

**Comment by zz4032** [comment]
So my initial statement was wrong.
That's great. Case closed.
