### ISSUE TITLE
What binaries should appveyor build?

### ISSUE THREAD

**Issue by borg323** [LeelaChessZero/lc0#336]
Currently in #315 I propose to also build a nopopcnt binary for the release packages together with the normal binary and package them together. However extensive testing with the random backend using positions that maximize the number of popcnt instructions show that the impact is negligible. Actually the nopopcnt version was consistently a bit faster (probably due to better alignment/caching).

So I'm leaning towards changing #315 to keep the popcnt instruction generation on by default (as is now) but making appveyor build only nopopcnt binaries. Opinions?

**Comment by borg323** [comment]
A related issue is the generation of binaries using mkl - these have a significant speed advantage over openblas for cpu users. Currently we cannot generate mkl binaries automatically, and installation is difficult since getting mkl requires registration. There is an alternative, using the mklml library that is distributed in <https://github.com/intel/mkl-dnn/releases>. This seems to have identical performance with the full mkl library for lc0.

**Comment by oscardssmith** [comment]
Close this?

**Comment by borg323** [comment]
Yes
