### ISSUE TITLE
Support for 32 bit operating systems

### ISSUE THREAD

**Issue by borg323** [LeelaChessZero/lc0#338]
Is there any fundamental reason we don't support 32 bit operating systems? #327 seems like a step in this direction. Is there anything else needed?

**Comment by mooskagh** [comment]
There are no 32 bit cudnn and tensorflow libs.
As for other backends, I don't know.

**Comment by borg323** [comment]
I was able to build win32 versions with [blas](https://ci.appveyor.com/api/buildjobs/6fgpdwfyb1vofxal/artifacts/lc0-win32-blas.zip) and [opencl](https://ci.appveyor.com/api/buildjobs/fqs1763lmca79owr/artifacts/lc0-win32-opencl.zip) backends. However was only able to (lightly) test them on 64 bit windows.

**Comment by mooskagh** [comment]
I think 32-bit binaries are now possible.
