### ISSUE TITLE
android version please

### ISSUE THREAD

**Issue by l1t1** [LeelaChessZero/lc0#363]
just like aqgo(https://github.com/gcp/leela-zero/issues/1679) or gridmaster(https://github.com/gcp/leela-zero/issues/779) for leelazero.

**Comment by l1t1** [comment]
will lc0 support droidfish?

**Comment by tedsummers** [comment]
Now that 'Chess For Android' supports 'DGT Electronic Chessboards', an Android version of Leela (LC0) would be just what I would be looking for.

**Comment by mooskagh** [comment]
There is no android version on our roadmap unless someone volunteers.
I'm inclined to close this issue as it's not very actionable.

**Comment by RafeHaab** [comment]
I'm too late to volunteer?

**Comment by mooskagh** [comment]
No, noone started to work on that so it's not late to volunteer.

**Comment by UA2425** [comment]
I think someone already started work
