### ISSUE TITLE
On Ubuntu 16.04 after following install instructions and running build.sh

### ISSUE THREAD

**Issue by jorditg** [LeelaChessZero/lc0#364]
Run:
`git clone -b release --recurse-submodules https://github.com/LeelaChessZero/lc0.git`
Install required packages following instructions in README.md

After run: 
`./build.sh`

I get error:

Error during basic setup:

[Errno 2] No such file or directory: '/home/jordi/lc0/build/release'

**Comment by vishalkumarchaudhary** [comment]
How did you resolved this??
