### ISSUE TITLE
CLOP MCTS params for v0.18

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#368]
Those were not CLOPped since long ago (cpuct, policy softmax, fpu reduction).
Would be nice to have fresh ones for v0.18!

**Comment by zz4032** [comment]
My tuning results:

Version: LC0 v0.16 Id 11008
2nd engine: asmFish

TC: 45s+0.25s
Average nodes on opnening moves: 3000

Parameters (standard/tuned):
```
Cpuct MCTS option -> 3.4/2.7
First Play Urgency Reduction -> 0.9/1.1
Policy softmax temperature -> 2.2/2.3
```

In discord we observerd that at least Cpuct and FPU are highly TC sensitive (higher with more nodes/move) so tuned values from faster hardware and at longer TC should be used. Posting this just for completeness of known results.

**Comment by mooskagh** [comment]
**ASilver** is running CLOP for that, results expected in 2-3 days.

**Comment by jjoshua2** [comment]
I have tried 2 or 3 CLOPs that failed to gain elo at least by more than 10. They were testing like 30 elo worse with 40 elo error bars...
I plan on testing the ASilver fpur change soon to see if that is also the case for his or not. He used multiple engines and I used only SF, so maybe that makes it work better...

**Comment by mooskagh** [comment]
That's done now, v0.18 is released.
