### ISSUE TITLE
lc0 doesn't manages time well

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#37]
There were reports that lc0 doesn't manage time well.

Solution will be for lc0 to look at it's misevaluations for previous move times and adjust (instead of having static slowmover).

**Comment by dubslow** [comment]
Can we close this with the recent time pr and clop tunings?

**Comment by GBeauregard** [comment]
@dubslow last I checked there was still some trouble on non-incremental time controls (e.g. fixed time per 40 moves) with Leela running out of time completely. When I get around to it I'll get an example game with the time spent on each move.

**Comment by dubslow** [comment]
That can be dealt with in #36 .

I'll close this now on the theory that while there are maybe improvements and elo gains left, it's probably true that we've gone very "bad" to "somewhat good, if not best possible yet".
