### ISSUE TITLE
Training: only make random moves for the side that thinks it is losing?

### ISSUE THREAD

**Issue by habbler** [LeelaChessZero/lc0#372]
Maybe only the side that thinks it is losing should make random moves during training?

This would give variety of moves and positions, without having blunders in the training games.

**Comment by rwbc** [comment]
How would you define 'losing' then? Actually I think your idea makes a lot more sense if reversed.
The side which is 'losing' should make less (no) random moves to have best resistance against the
winning side, which would create a much better learning effect.

**Comment by zz4032** [comment]
I think that's a promising idea to have randomness depend on evaluation.

What I thought about is that both sides should start playing with less variety once 1) evaluation grows for either side or 2) is equal for a period of moves (likely to draw soon). Randomness should produce new, yet unknown moves for the engine to learn but should not influence the outcome decisively. So it should continually decrease if there's a decision emerging in the game.

**Comment by habbler** [comment]
If the random move changes the outcome for the side playing it from a loss or a draw to a win, that is very good. The network needs to learn that there is a better move than it was considering.

i.e. we want to learn moves that decisively change the outcome. But only if they are good moves.

**Comment by zz4032** [comment]
Yes, should have better said "randomness should not influence the game outcome for the winning side".

**Comment by zz4032** [comment]
Can one of the developers please comment on this issue? Is it a valid idea or not for some reason?
In my opinion this is something that could solve Leela's weakness in endgames as well as exaggerated evaluations in drawn positions which are the main visible flaws of the engine.

**Comment by mooskagh** [comment]
We are reducing endgame temperature to very low values now, this will probably help.
Closing this issue for now.
