### ISSUE TITLE
error CUDA error: unknown error (../src/neural/network_cudnn.cu:977)

### ISSUE THREAD

**Issue by Silver-Fang** [LeelaChessZero/lc0#374]
_
|   _ | |
|_ |_ |_| v0.17.0 built Aug 27 2018
go
Found pb network file: C:\Users\zhang\Downloads\lc0-windows-cuda/network.txt
Creating backend [cudnn]...
error CUDA error: unknown error (../src/neural/network_cudnn.cu:977)

**Comment by Silver-Fang** [comment]
Cuda version from https://github.com/LeelaChessZero/lc0/releases/tag/v0.17.0
Newest Cuda Toolkit and cudnn already installed from Nvidia official.

**Comment by ankan-ban** [comment]
from your line no, it seems this call is failing:
    ReportCUDAErrors(cudaGetDeviceCount(&total_gpus));

@Silver-Fang  On which GPU are you running on? Display Driver version?

**Comment by Silver-Fang** [comment]
@ankan-ban 
NVIDIA GeForce GTX 965M
Well, it's probably a bug between Win10 OS and NVIDIA driver. I did some investigation. It was reported that Win10 is incompatible with the newest driver, which lacks a valid digital signature. After rolling back to an older driver I got an "insufficient version" error in Lc0. In all, I simply can't have a proper driver compatible between Win10 and Lc0. Any workaround, please?

**Comment by borg323** [comment]
You can get v0.18rc1 for cuda 9.0 from <https://ci.appveyor.com/api/buildjobs/739qjpj6kv0gyc5d/artifacts/lc0-windows-cuda90.zip>. This will work with older drivers.

**Comment by Silver-Fang** [comment]
@borg323 Thanks. This is proven to be an OS bug, not Lc0, as the newest Win10 18247 announced today has it fixed. Close.
