### ISSUE TITLE
Possible way to fix initial slow nps

### ISSUE THREAD

**Issue by oscardssmith** [LeelaChessZero/lc0#378]
One consistent thorn in the side of dynamic time management PR's is that Leela takes almost 60s to ramp up to full nps on powerful hardware. This is largely because we add to the tree in batches to efficiently use the gpu, but early in tree construction there are very few explored lines to take batches from. I think we could fix this by adding a command line argument of `full-explore-depth` that would default to 0 (current behaviour), but if given a higher value, would add a step at the beginning of search where all moves of `depth` or less would get evaluated immediately. This would help a ton in tournament conditions where by the end of search we have fully explored up to depth 6 or so just through mcts. With this change, these nodes would get immediate eval preventing all bad tactical of a smaller depth and giving all moves initial consideration before we start building the rest of the tree.

**Comment by jjoshua2** [comment]
This sounds like a great plan. How does it compare to just increasing node
collisions and prefetch at first? It seems it might have same effect?

**Comment by mooskagh** [comment]
Closed due to issue bankruptcy.
