### ISSUE TITLE
Blas Lc0 v18rc1 using 11250 does not see a perpetual check.  Looks like a threading issue.

### ISSUE THREAD

**Issue by jeffwadsworth** [LeelaChessZero/lc0#389]
The position:
3q4/5p1k/6p1/4N3/2Q1P2p/PR3PnP/3r2PK/8 b - - 6 81 

v17 correctly sees the following moves.  v18rc1 does not.  Blas version in Win 10 64bit.
The correct move is Rxg2+, KxR, Q-d2+ followed by perpetual check.  Lc0 with history and without history never sees it and loses the game.  Full PGN below.  Move 81 is where the blunder takes place for black.

[BlunderCheckGame.txt](https://github.com/LeelaChessZero/lc0/files/2421584/BlunderCheckGame.txt)

**Comment by jeffwadsworth** [comment]
I changed my threads from 2 to 1 and it now sees Q-e7 and Rxg2 moves.

**Comment by borg323** [comment]
Can you recheck with rc2?
