### ISSUE TITLE
Percentage options

### ISSUE THREAD

**Issue by Synthetica9** [LeelaChessZero/lc0#391]
Options that represent percentage (`immediate-time-use`, `resign-percentage`, `resign-playthrough`) don't use a consistent scale. `immediate-time-use` uses 0-1, `resign-...` use 0-100. 

My proposal is to add another `Option` subclass to deal with this, `PercentageOption`. This would be a subclass of `FloatOption`, where the parse function parses `0.1` as `0.1`, `70` as `0.7`, and `70%` as `0.7` as well. It would also have a fixed min and max. Thoughts?

**Comment by gonzalezjo** [comment]
Figuring out how to do percentages for a PR was really confusing for me. This would help a lot.

**Comment by mooskagh** [comment]
Probably not going to happen, so closing for now.
Changing parameter format turned out to be more painful than expected.
