### ISSUE TITLE
MSVCP140.dll not found

### ISSUE THREAD

**Issue by jonbrock** [LeelaChessZero/lc0#399]
Hi there,

I'm trying to run lc0 (lc0-v0.18.0-rc2-windows-cuda) with an nvidia card (gtx 750 ti) on a Windows 10 PC and I get "The code execution cannot proceed because MSVCP140.dll was not found. Reinstalling the program may fix this problem."

I installed Visual C++ Redistributable for Visual Studio 2015 and that fixed the issue. However, this step is not listed on the getting started page. I think this may be a difficult barrier for people who want to contribute but don't recognize the dll name.

Also, the initial symptom when running client.exe was simply that lc0.exe exited without producing any games. No error message. It wasn't until I ran lc0.exe directly that I found this error.

One solution is to create an installer for the project that can detect the missing dependencies and install them. Perhaps it could also suggest/select the correct back-end to install. Another solution is to bundle the required dlls as described in the "Local Deployment" section at https://msdn.microsoft.com/en-us/library/dd293574.aspx

Please let me know if I can help.

**Comment by mooskagh** [comment]
For questions like this, it's better to ask in discord chat (http://lc0.org/chat, channel #help) or in forum http://lc0.org/forum
