### ISSUE TITLE
LCZero 0.18.0 - which windows package is recommended?

### ISSUE THREAD

**Issue by yellow-panther** [LeelaChessZero/lc0#406]
hardware: Intel i5 Quad - 4 CPU´s, 4 GB RAM, AVX, POPCNT and SSE4.2 is supported, but not BMI2, 4 GB RAM, Windows 7 64 bit SP1; Cuda, Blas. OpenCL or anything else? GUIs: WinBoard Interface, Arena etc.

**Comment by borg323** [comment]
The main question is whether you have a gpu, and if so which one.

**Comment by yellow-panther** [comment]
Is the current LCZero 0.18.0 only running on modern GPUs or on older CPUs
too?

CPU
Intel Core i5 3470
Cores 4
Threads 4
Name Intel Core i5 3470
Code Name Ivy Bridge
Package Socket 1155 LGA
Technology 22nm
Specification Intel Core i5-3470 CPU @ 3.20GHz
Family 6
Extended Family 6
Model A
Extended Model 3A
Stepping 9
Revision N0
Instructions MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, Intel 64, NX,
VMX, AES, AVX
Virtualization Supported, Enabled
Hyperthreading Not supported
Fan Speed 1599 RPM
Bus Speed 99.8 MHz
Stock Core Speed 3200 MHz
Stock Bus Speed 100 MHz
Average Temperature 34 °C
Caches
L1 Data Cache Size 4 x 32 KBytes
L1 Instructions Cache Size 4 x 32 KBytes
L2 Unified Cache Size 4 x 256 KBytes
L3 Unified Cache Size 6144 KBytes
Cores
Core Speed Multiplier Bus Speed Temperature Threads
Core 0 1596.2 MHz x 16.0 99.8 MHz 38 °C APIC ID: 0
Core 1 1596.2 MHz x 16.0 99.8 MHz 33 °C APIC ID: 2
Core 2 1596.2 MHz x 16.0 99.8 MHz 34 °C APIC ID: 4
Core 3 1596.2 MHz x 16.0 99.8 MHz 31 °C APIC ID: 6


Further Leela versions are running under CB-GUI like the following
procedure:  that I gound on a forum:


LC Zero with ChessBase GUI
Since v0.7 no adapter is needed (inBetween, polyglot) for running leela in
Fritz.
Just do this:
1) Create a Leela-folder somewhere on your PC in a folder, which is not
write-protected
(normally C:\ProgramFiles\ChessBase\Engines is write-protected!) - I
created it in my documents-folder.
2) download the Windows GPU Leela files here:
https://github.com/glinscott/leela-chess/releases -
https://github.com/LeelaChessZero/lc0/releases
3) Unzip all files in your leela-folder
4) Download the Network-file here (but NOT the first on top of the list
(the newest)):
http://162.217.248.187/networks
5) unpack the network-file, you get a folder. In it a file. Rename it to
weights.txt
6) Copy the weights.txt file in your leela-folder
7) start the lczero.exe -file one time with mouse-double-click. That
creates a file called "leelaz_opencl_tuning", which is needed! (If you want
to run Leela faster, create a small .bat file with one line in it
"lczero.exe -w weights.txt --full-tuner" and start that .bat file with
double-click. Then you have to wait around 20-30 minutes, while Leela tries
around 5000 GPU-configurations in order to find the fastest.)
8) Start Fritz and create UCI-engine with lczero.exe. It is recommended, to
set the number of Threads to the number of CPUs of your system, that makes
Leela a little bit faster, although she uses the GPU for main calculations.
(Thread is 2 by default)

Am Mo., 1. Okt. 2018 um 16:17 Uhr schrieb borg323 <notifications@github.com

**Comment by borg323** [comment]
If you don't have a gpu you need the blas version: https://github.com/LeelaChessZero/lc0/releases/download/v0.18.0/lc0-v0.18.0-windows-blas.zip
Note that this is a lot slower than the gpu versions.
You will also need a weights file, 11248 is our choice for the upcoming competitions: http://lczero.org/get_network?sha=994de36c13ddf2540bf588817fcca0cb4e279e61c7d118c3bccc9c74419caecd
Just copy it in the same folder with lc0.exe, no need to unpack or rename. Also lc0 will *not* create `leelaz_opencl_tuning`, so go from step 4 to step 8 in the above procedure.

**Comment by yellow-panther** [comment]
thank you very much borg323! but in my opinion these additional infos belong into the folder "releases" to avoid misunderstandings

**Comment by mooskagh** [comment]
That doesn't look like an appropriate use of github issues, but glad it's resolved. :)
