### ISSUE TITLE
Have a different default minibatch size for slow (CPU) backends

### ISSUE THREAD

**Issue by ghost** [LeelaChessZero/lc0#415]
I have used Xboard latest version and started a game (Stockfish vs lc0).
For example, it cannot do first move in 3+2 blitz.

**Comment by borg323** [comment]
Is this with the blas backend (i.e. cpu only)?

**Comment by stas730** [comment]
@borg323, yes.

**Comment by mooskagh** [comment]
Per-backend minibatch defaults is still on todo list.
Meanwhile, `--minibatch-size=16` should help for blas backend

**Comment by mooskagh** [comment]
Blocked by #432

**Comment by mooskagh** [comment]
Actually the minibatch size issue is still relevant, I've renamed the issue.

**Comment by Naphthalin** [comment]
Solved by #1294.
