### ISSUE TITLE
Website best Network download

### ISSUE THREAD

**Issue by maelic13** [LeelaChessZero/lc0#419]
Hi,
I am sorry for writing here as it probably does not belong - but I thought it would be nice to include a button on the website to download the (at the time) strongest network for leela. It is not really convenient to look it up in the netwrork section and some of the downloads there are not working anyway - downloads some weird file but it is most definitively not the network.
It would also be nice if the download link to the strongest network was fixed so it was possible to write a script that would download new one e.g. every two days or so - once the nets are gonna get stronger again, it would be very useful.
Thank you! And sorry for probably wrong place to write, I had no idea where else..

**Comment by jjoshua2** [comment]
That is a big problem but I'm fine with a nber of solutions like the net
that got sent to the last tournament tcec or cccc  etc.
Or top of alorils 100 node list...

**Comment by borg323** [comment]
I think the best solution for this is to add an FAQ entry with a brief explanation and links to a few nets.

**Comment by MaurizioDeLeo** [comment]
I'll try to add it to the wiki

**Comment by maelic13** [comment]
Thank you for kind responses!
The new nets are evaluated with elo strength though - isn't that enough? I know it probably is not tested with exceptional depth but still. In theory you could take some top nets and test them against each other properly. Although that probably sinks on decision when new nets are ready to "challenge" the reigning best net - everytime a net surpasses the "champion net" in elo rating in testing? Too many tests slowing down developement. Once a week a tournament with "champion net" and like 4-5 top rated nets that surpasses the reigning champion in tests? Sounds like arbitrary choice of period and week might be too long..

**Comment by MaurizioDeLeo** [comment]
Added to the https://github.com/LeelaChessZero/lc0/wiki/FAQ

**Comment by mooskagh** [comment]
Probably won't be added before C++ supports sockets (C++23, so around year 2026)
