### ISSUE TITLE
Fixing Tensorflow compile on macos

### ISSUE THREAD

**Issue by gsobala** [LeelaChessZero/lc0#437]
I have finally worked out why the default meson.build script fails to find `libtensorflow_cc.so` on macos. I realise this is somewhat low on any list of priorities, but it has been bugging me for a while. 

Basically if given a specific directory to search in, meson appends what it thinks are suitable suffixes for dynamic libraries, and looks for a filematch by name. `.so` is fine for Linux but it tries `.dylib` for darwin. The problem can be solved prior to the compile by the user symlinking `libtensorflow_cc.so` to `libtensorflow_cc.dylib` in `/usr/local/lib/tensorflow_cc`, but does anyone know of a way of fixing this in meson.build to allow it to work with the default tensorflow install?

I can nearly get there by adding to meson.build some darwin specific code to search for `tensorflow_cc` *without* giving a directory to search in, as in that case meson tries a test compile / link using `-ltensorflow_cc` and this does find the library if it is in `/usr/local/lib`, but not in `/usr/local/lib/tensorflow_cc`.

Maybe the best solution is just some extra instructions in the README?

**Comment by gsobala** [comment]
I've put in a PR on the meson github to have it recognise `.so` as well as `.dylib` when `find_library()` is invoked, but if that does not fly then I will add some code to `build.sh` to make a symlink if running on Darwin and if the tensorflow_cc library exists.

**Comment by gsobala** [comment]
The meson PR has been accepted so the next version of meson should "just work" with lc0 on macos.

**Comment by oscardssmith** [comment]
@gsobala should this be closed then?

**Comment by gsobala** [comment]
The PR is in meson master but they have not bumped release past 0.48 yet. So this remains an outstanding issue.

**Comment by oscardssmith** [comment]
ok. Thanks

**Comment by gsobala** [comment]
Meson release 0.49 now includes the pr to fix this so the tensorflow libraries are detected correctly on macos when -Dtensorflow=true is set
