### ISSUE TITLE
Additional software for Lc0 to work

### ISSUE THREAD

**Issue by gpaunica** [LeelaChessZero/lc0#451]
Hello,
I want to ask you what additional software must be installed for Lc0 to work.
I tried to installed in any GUI, but didn't work.
Please help me.
Thanks.

**Comment by oscardssmith** [comment]
please only use GitHub for hi bos bugs and feature request. questions should be asked in the help channel of the discord. https://discord.gg/M9BPGa

**Comment by JamieO53** [comment]
This link has expired. Go here instead: [https://discord.gg/EA6r5rG](https://discord.gg/EA6r5rG)

**Comment by mooskagh** [comment]
Please come to our chat, channel #help, with questions like this.
https://discord.gg/pKujYxD <- discord invite
