### ISSUE TITLE
async processing instead of batch

### ISSUE THREAD

**Issue by techagon** [LeelaChessZero/lc0#456]
LC0 NPS is bottlenecked on GPU _latency_ (per @crem discussion on discord).  This suggestion has two parts, that are somewhat independent of each other:

- Use an asynchronous command and completion paradigm instead of "batch size", to drive higher GPU utilization.
- Use a heuristic that runs on CPU to "optimistically" anticipate next node to expand, so that required degree of parallelism can be achieved in MCTS to keep the GPUs saturated.

### Asynchronous Eval instead of Batch

Currently, MCTS collects a batch of evals, submits them to the GPU(s), and waits for the batch to complete.  This has a few of issues.

- Imagine the GPU pipeline.  At the start of every batch, the pipeline takes some time to fill up, and at the end of every batch, time to drain.  This causes suboptimal utilization of the GPU.  The larger the batch-size, the less this matters, because we can amortize the fill and drain cost across a large number of evals.  However,

- Larger batch sizes mean that there is will be more delay (latency) between when a node was gather into the eval batch, and when its evaluated result is made available to the CPU to update the tree.

- MCTS is inherently sequential, and we have trouble collecting large enough batches.  The higher the result-latency, the more this leads to MCTS getting "ahead of itself" -- we are adding work into the batch, _hoping it would be useful work_, while we wait for the batch to complete.

Ideally, you'd want:
- each eval to be completed by the GPU and its result incorporated into MCTS by the CPU, as soon as possible, and without having to wait for the remaining commands of hte batch to complete.
- the GPU pipeline to be full of work at all times, and not have the bubbles introduced by fill-drain of batching. thereby maximizing the GPU utilization.

**Solution**
This can be achieved using multiple CudaStreams and CudaEvents to determine when a GPU job is completed.  Ideally, there would be one "dispatch" thread that dispatches eval commands to the card, and returns command "completions" back to the workers.  Each MCTS worker would maintain a lockless producer-consumer queue-pair with the Dispatch thread.  Using CudaEvents instead of barrier synchronization (CudaStreamSynchronize), ensures that we don't introduce bubbles into the pipeline.

### Intelligent Optimistic Node Expansion
Even with the evals returning with the lowest possible latency, this latency could be on the order of several milliseconds.  This latency needs to be masked.  i.e. the CPU should do useful work while we wait for the GPU to eval.

At the same time we need an anticipatory heuristic to add nodes to expands -- so that we can keep the GPU's pipeline full of work.  

**Solution**
The idea is the use knowledge distillation, to create a small enough network, to predict the next node to expand, such that this network can be synchronously computed on the CPU(s) at the rate required to feed the GPU(s).  This has the benefit that:

- the CPU(s) now do useful work -- selecting the right set of nodes to expand.  They use an approximate version of the real-thing, so expect a lot less 'wasted work'.
- the GPU pipeline can be kept full, driving the GPU at full utilization.

**Comment by jjoshua2** [comment]
This sounds like a good approach. Maybe @ankan-ban can weigh in on cuda details if that is actually so...

**Comment by oscardssmith** [comment]
I suspect this might work even without the small net. I would be very interested in seeing an implementation. one possible improvement: a way to send a "eval 1 node beyond this node" I suspect it would reduce latency on favorite parts is the tree.

**Comment by DanielUranga** [comment]
I really like this being captured as an issue, thanks @techagon.
The first step required to be able to make any progress would be to **measure how things are right now**, ideally we need a branch that reports how many batches per second are being completed, how long it takes to gather a batch, how long it takes to wait for it to be evaluated, how long it takes for the results to be backpropagated so new nodes can be picked.
That is crucial to be able to understand better where the bottlenecks are, and get better understanding of the issue.

In a previous version of my lockless branch I was sending random child nodes of nodes that where still waiting for a GPU eval, but probably sending random nodes is a bad idea.

Also this might not be exactly the focus of this task, but I think it is interesting to include:
This is a profile result with the random backend:
![imagen](https://user-images.githubusercontent.com/1651950/47184329-c302c700-d300-11e8-96c8-ee051b32278e.png)

And this is using 6x1060 GPUs and a weak CPU:
![imagen](https://user-images.githubusercontent.com/1651950/47184384-e88fd080-d300-11e8-9401-23a564ce0b24.png)

**Comment by hans-ekbrand** [comment]
GPU-utilisation is indeed the problem on the high end systems (V100), see https://github.com/LeelaChessZero/lc0/pull/455.

Whatever works to increase GPU-utilisation is welcome, and perhaps your suggestion will do so. However, I wonder if it is radical enough. My worry is that the current mode of MCTS, based on having a centralised core (CPU) sequentially delegate evaluation tasks to dumb workers (GPUs) might turn out not being possible to speed up very much. Perhaps we need to question the model more, and try a more decentralised logic? One idea is to have N independent "processes" (not necessarily threads in the technical sense) that make their own decisions on which nodes to expand, always busy doing evalutations and picking nodes to expand, and continously (or in small batches) telling some central agent the evaluation of nodes. The central agent collects stats about nodes, does time management and decides on which move to send, and informs the evalutor-processes about moves made in the game. If MCTS would have been deterministic, then N independent processes would do exactly the same thing, and we would end up with N identical copies of the search-tree. AFAIK, the particular implementation of MCTS used by lc0, UCT, is actually deterministic. But adding randomness to UCT would be easy, you could treat the evaluation of a position as random variable, ie something which is inherently noisy, and only has some probability of being a correct evaluation, or you could make CPUCT a random variable, ie sample the value to use for CPUCT (Perhaps you don't want to sample a new value of CPUCT for each node expansion, and perhaps the central agent should decide over the value and when to change it).

Root parallelisation is shown to be the most effective way of parallelising MCTS. http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.159.4373&rep=rep1&type=pdf It requires some randomness in the search algoritm (easy) and a more decentralised logic (more work).

![foo](https://user-images.githubusercontent.com/551014/47185887-112ebf00-d32f-11e8-8d0d-159f00aa944e.png)

That being said, I'm looking forward to _any_ work that could help lc0 gain GPU-utilisation, and your suggestion sound very interesting. I like the idea of having small nets being evaluated by CPUs! The current hardware situation means that there is normally tons of CPU:s floating around in the high-end machines with 4 V100:s, it sound great to use them. However, a single V100 can easily be run by 1-2 CPU:s with the current batching regime, so the batching regime _also_ works, when it doesn't have to wait/syncronise.

**Comment by hans-ekbrand** [comment]
@DanielUranga I fully support your idea of gathering more data about how thing actually work now. Have you seen https://github.com/LeelaChessZero/lc0/pull/455 ? As you can see there, GTX 1060 actually scales pretty well, unlike the V100. Admitttedly, I don't know the underlying cause of the difference between them, it might be that the GTX 1060 is just so slow that we never face really queue problems, rather than a problem with the V100 - but my point is that we should focus on how things actually work now on the V100.

**Comment by ankan-ban** [comment]
The idea of using multiple CudaStreams sounds good, but I am not very optimistic that it will help cudnn convolution kernels much. As far I know, those kernels are optimized to hog the entire GPU (even when they are processing small batches), so even if you have another cudaStream ready to be scheduled, the GPU might not be actually able to start on that. 

Right now we process batches serially (due to lock_) even when multiple CPU threads gather multiple batches in parallel, see: https://github.com/LeelaChessZero/lc0/blob/master/src/neural/network_cudnn.cu#L1155
I had previously tried getting rid of this lock_ and scheduling GPU work on multiple cudaStreams - one for each CPU thread but I didn't get any speedup (got a very slight slowdown).

There may be cases where it can help so it would be good to test this out. Maybe just try small standalone test running convolutions with small batch sizes (that we care about) asynchronously on different CudaStreams and compare its performance with one single convolution running with big batch size.

**Comment by gonzalezjo** [comment]
My proposal for finding nodes to expand was to allocate a buffer equal to the current batch size, and fill it with extra nodes which can be explored. The buffer can be filled using something like SF’s move ordering heuristics, SEE, and other nice search extensions. Andrew Grant’s thing is search, and Daniel Shawul has written both A/B and NN engines. Perhaps they would be good people to ask.

**Comment by ankan-ban** [comment]
Actually looks like I was wrong about multiple parallel async batches. With a small directed test (random data, no synchronization), I am actually seeing pretty good gains:
`On RTX 2080Ti for single 256x256 channel 3x3 convolution of 8x8 chessboard

Test code:
https://gist.github.com/ankan-ban/39d765fb789a9807c1e633157a13a54d

NumStreams Time (for NumStreams batches)  Throughput (convs/second)
===================================================================
batch size of 1:
1          0.0760956                      13141.4
2          0.0896062                      22319.9
4          0.100309                       39877
8          0.146538                       54593.5
16         0.348064                       45968.6
32         0.645461                       49576.9

batch size of 8:
1          0.0796517                      100437
2          0.0920328                      173851
4          0.107219                       298455
8          0.15796                        405166
16         0.291378                       439292
32         0.63973                        400169

batch size of 32:
1          0.0778488                      411053
2          0.094298                       678700
4          0.176221                       726360
8          0.343232                       745850
16         0.628379                       814795
32         1.15336                        887841

batch size of 64:
1          0.0837136                      764512
2          0.174065                       735360
4          0.320887                       797787
8          0.582076                       879611
16         1.11767                        916191
32         2.04753                        1.00023e+06


batch size of 256:
1           0.280713                      911965
2           0.527                         971537
4           0.939439                      1.09001e+06
8           2.00638                       1.02074e+06`

**Comment by Videodr0me** [comment]
Just discovered this issue, this is one thing i wondered myself about some time ago, but set aside as i was under the impression it would maybe require some low level gpu programming. 

I also had simpler solutions in mind, for example breaking the computation of the full NN into smaller parts or stages, so that one batch would at least comprise different stages of computation so that some positions are already in a later stage or finished while others are in their first or intermediate stages.

If that now can be handled without much hassle with cudastreams and if the computation results can also be fetched aynchronously (no use computing asynchronously if the results can still only be fetched at the same time) then this would probably shift the sequentiality vs. nps tradeoff.  @ankan: Is it possible to get similar data with actual leela computations?

**Comment by mooskagh** [comment]
As investigated by @ankan-ban, streaming GPU computation turned out not to be as good as it was expected. For other backends it's probably even harder to implement. I'm closing this issue for now, but it can be reopened or referenced if we have another revival of this idea.
