### ISSUE TITLE
Protobuf doesn't support large networks

### ISSUE THREAD

**Issue by Ttl** [LeelaChessZero/lc0#458]
Loading 256x40 network in https://github.com/Cyanogenoid/lczero-training/releases gives error message:

```
[libprotobuf ERROR google/protobuf/io/coded_stream.cc:207] A protocol message was rejected because it was too big (more than 67108864 bytes).  To increase the limit (or to disable these warnings), see CodedInputStream::SetTotalBytesLimit() in google/protobuf/io/coded_stream.h.
error Invalid weight file: parse error.
```

**Comment by oscardssmith** [comment]
Good news is it looks like it might only be a 1 line fix

**Comment by mooskagh** [comment]
Yeah that's known problem to everyone who used protobufs. The fix is indeed just one line.

**Comment by mooskagh** [comment]
That's known problem to everyone who used protobufs. The fix is indeed just
one line.
