### ISSUE TITLE
UCI 'go' command is flawed

### ISSUE THREAD

**Issue by karolm2** [LeelaChessZero/lc0#482]
Possible bug: Lc0 v0.18.1 stops searching long before reaching given number of nodes or given amount of time. For example:

position startpos
go nodes 10000000

..and it stops after reaching about 5.2M nodes:

info depth 18 seldepth 48 time 1706091 **nodes 5203077** score cp 24 hashfull 1000 nps 3049 tbhits 0 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 b1c3 c7c6 c1g5 h7h6 g5f6 d8f6 e2e3 b8d7 d1c2 g7g6 c4d5 e6d5 f1d3 f8g7 e1g1 e8g8 b2b4 d7b6 a2a4 a7a5 b4a5 a8a5 f1b1 b6c4 d3c4 d5c4 f3d2 c8f5 c3e4 f6e7
bestmove d2d4 ponder g8f6

The same happens with 'go movetime':

position startpos
go movetime 3600000

..and it hasn't even reach half of given time:

info depth 18 seldepth 48 **time 1618940** nodes 4955601 score cp 24 hashfull 1000 nps 3061 tbhits 0 pv d2d4 g8f6 c2c4 e7e6 g1f3 d7d5 b1c3 c7c6 c1g5 h7h6 g5f6 d8f6 e2e3 b8d7 d1c2 g7g6 c4d5 e6d5 f1d3 f8g7 b2b4 e8g8 e1g1 d7b6 a2a4 a7a5 b4a5 a8a5 f1b1 b6c4 d3c4 d5c4 f3d2
bestmove d2d4 ponder g8f6

**Comment by hans-ekbrand** [comment]
Try https://github.com/LeelaChessZero/lc0/pull/455

**Comment by mooskagh** [comment]
That's expected. It stops then search when it's guaranteed that best move won't be changed during the remaining part of the search. With --futile-move-aversion=0 it should use all the quota.

**Comment by hans-ekbrand** [comment]
--futile-move-aversion=0 is a workaround, but wouldn't it be logical if `go nodes X` really produced X nodes by default?

**Comment by mooskagh** [comment]
I don't think there is a reason to waste visits just to get total nodes exactly equal to number of requested nodes. If bestmove is known in advance, why not return it.
Also there's really no way to reproduce exact node distribution in search.
E.g. if you do `go wtime 1000`, it estimated total number of nodes as `10000` and stopped after, say,
6000 nodes for move A
1000 nodes for move B
100 nodes for move C.

then to reproduce the same distribution, only way to do that (approximately at least) is to run `go nodes 10000` with the same settings.

No patch will make `go nodes 7100` have the same distribution.
