### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by reikdas** [LeelaChessZero/lc0#488]
I am having some troubles getting it working with a chess GUI on Ubuntu 18.04.

I installed the dependencies. (Also the dependencies suggested specifically for Ubuntu 18.04)
I built it successfully. (Using the specific build command for Ubuntu 18.04)
I added ~/.local/bin to my path. 
I downloaded the network weight 22115 and put it both in ~/.local/bin as well as lc0/build/release

Chess GUI I am using = Cutechess
Followed the instructions for cutechess here - http://blog.lczero.org/2018/09/guide-setting-up-leela-on-chess-gui.html (Tried setting command to both lc0 --weights=22115 and lc0 --weights=~/.local/bin/weights_run1_22115.pb.gz)
Error - No response to ping.

**Comment by andreaspaulick** [comment]
Same here: adding the "--uci" parameter solves the "no response to ping" issue but still the engine won't start

**Comment by reikdas** [comment]
> Same here: adding the "--uci" parameter solves the "no response to ping" issue but still the engine won't start.
> 
> I think it's a GUI issue.

Try this - https://www.youtube.com/watch?v=xOcPPNTHOZs&t=568s

**Comment by mooskagh** [comment]
It's faster to get help with such questions in discord chat https://discord.gg/pKujYxD (channel #help), or in forum: https://groups.google.com/forum/#!forum/lczero
