### ISSUE TITLE
lc0 for Mac: after compiling, issue "Missing tuner parameters" since version 0.19 and up

### ISSUE THREAD

**Issue by ArminHHJ** [LeelaChessZero/lc0#498]
For MAC-lc0

I use this workflow to create lc0

Preperation
1. Install brew as per the instructions at https://brew.sh/
2. Install python3: `brew install python3`
3. Install meson: `brew install meson`
4. Install ninja: `brew install ninja`

Lc0 Creation
5. cd /Users/armin/
6. git clone -b release --recurse-submodules https://github.com/LeelaChessZero/lc0.git
7. cd /Users/armin/lc0
8. ./build.sh

Works for lc0 Version up to v0.18.1, only can use blas and opencl, no cuda (Intel Grafic)

Since version v0.19.x and v0.20.x (master) there is the following error after compiling and starting the lc0:

Selected device: Intel(R) Iris(TM) Graphics 6100
with OpenCL 1.2 capability.
Missing tuner parameters
MWG
NWG
KWG
MDIMC
NDIMC
VWM
VWN

logout

What is missing since v0.19?

**Comment by Ttl** [comment]
This should be fixed in the latest commit (PR #491).

**Comment by mooskagh** [comment]
...Which is already integrated into v0.19.0-rc3

**Comment by MichaelB7** [comment]
I can confirm v0.19.0-rc3 complies for the macOS.
