### ISSUE TITLE
Continuing integration

### ISSUE THREAD

**Issue by dubslow** [LeelaChessZero/lc0#50]
Enable some sort of continuing integration, both testing PRs and generating new builds as needed.

**Comment by Ghotrix** [comment]
should it be client and engine for win/linux/mac? server also? anything else? what automation tool it should be? where it will be hosted?

**Comment by dubslow** [comment]
lczero uses Travis-CI for linux, and appveyor for winblows

**Comment by DanielUranga** [comment]
Ubuntu 18.04 CircleCI build PR: https://github.com/LeelaChessZero/lc0/pull/101

**Comment by DanielUranga** [comment]
So Linux (CircleCI) and Windows (Appveyor) are ready, now only Mac is missing right?
Also we need to create the official CircleCI and Appveyor accounts for Leela and link them to this repo.

**Comment by DanielUranga** [comment]
What is missing to consider this task closed?

**Comment by dubslow** [comment]
We need to ensure that tags/releases get builds autouploaded to GitHub.
