### ISSUE TITLE
Huge nps reported by engine

### ISSUE THREAD

**Issue by frpays** [LeelaChessZero/lc0#503]
I was analysing the Carlsen Caruana first game on the cloud with 2 v100 (fp16) through ssh with Deep Shredder 12 mac.

Here are the normal FPS.

https://pasteboard.co/HMwMqVp.png

I went to analyse the line Bxh5 and hxg5. Then went back because Carlsen opted for another move (Nxf8). Then the problem showed up.

https://pasteboard.co/HMwNQax.png

The nps kept climbing while doing the infinite analysis.

https://pasteboard.co/HMwOkMj.png

https://pasteboard.co/HMwOvwz.png

Then the next move, all was ok.

https://pasteboard.co/HMwOY9h.png

Engine version: 19 dev.

Game: 

[Event ""]
[Site ""]
[Date "2018.11.09"]
[Round ""]
[White "Player N.N."]
[Black "Shredder"]
[ECO "B31"]
[Result "*"]

1.e4 c5 2.Nf3 Nc6 3.Bb5 g6 4.Bxc6 dxc6 5.d3 Bg7 6.h3 Nf6 7.Nc3 
Nd7 8.Be3 e5 9.O-O b6 10.Nh2 Nf8 11.f4 exf4 12.Rxf4 Be6 13.Rf2 
h6 14.Qd2 g5 15.Raf1 Qd6 16.Ng4 O-O-O 17.Nf6 Nd7 18.Nh5 Be5 19.g4 
f6 20.b3 Bf7 21.Nd1 Nf8 22.Nxf6 Ne6 23.Nh5 Bxh5 24.gxh5 Nf4 25.Bxf4 
gxf4 26.Rg2 Rhg8 27.Qe2 Rxg2+ 28.Qxg2 Qe6 29.Nf2 Rg8 30.Ng4 Qe8 
31.Qf3 Qxh5 32.Kf2 Bc7 33.Ke2 Qg5 34.Nh2 h5 35.Rf2 Qg1 36.Nf1 
h4 37.Kd2 Kb7 38.c3 Be5 39.Kc2 Qg7 40.Nh2 Bxc3 41.Qxf4 *

**Comment by kirill57** [comment]
Same here, nps at 8900 kn/s on 2080 in game analysis.

**Comment by mooskagh** [comment]
Probably we should only report first visit to a terminal nodes as node visit..
It may make search seemingly stall though.

**Comment by killerducky** [comment]
There's no perfect solution, but the current method makes `go nodes 1000` work neatly. If you don't count terminals the search will never terminate when it finds short mates.

Another option is to output an `info string` that breaks down the playouts by type (Tree reused, NN lookup, NNCache hit, terminal hit).

**Comment by Naphthalin** [comment]
Recent efforts on smoothing the reported nps #1243, waiting for a minimum number of batches #1113 etc should have solved this issue.
