### ISSUE TITLE
Engine UCI interface should ignore 'position' while in infinite search.

### ISSUE THREAD

**Issue by frpays** [LeelaChessZero/lc0#506]
If you type:

```
position startpos
go infinite
(... pv output)
position startpos e2e4
```

It *stops* the search. (you can restart the search with `go ...`). I believe that the command `position startpos e2e4` should be ignored until `stop` is received. 

```
position startpos
go infinite
(... pv output)
stop
(... bestmove output)
position startpos e2e4
```

Here is the protocol specification.

http://wbec-ridderkerk.nl/html/UCIProtocol.html

**Comment by mooskagh** [comment]
I cannot find anything in protocol description suggesting that stopping the search is wrong.
It's not that straightforward with tree reuse and also it's not clear why this behavior may be needed.

So for me it doesn't look like a bug at all.

**Comment by mooskagh** [comment]
Closing as not an issue.

**Comment by mooskagh** [comment]
I don't understand what inconvenience causes current behavior (for which I'm not even convinced that it's incorrect).
Attempts to fix it will introduce bugs which will be distracting (for devs who would otherwise do other things) to fix.

E.g. fix in #530 is wrong:

```bash
position startpos moves e2e4
go infinite
  # (search goes on)
stop # and then if the next command comes immediately before the search really stops, ...
position startpos moves d2d4
go infinite # ... continues search of from e2e4, not from d2d4 that GUI expects.
```

**Comment by frpays** [comment]
This is arguably minor, but time will come when we will want to fix this bugs.
So I think it's better to keep track of them, even if you don't fix them now.
At least, you know them and you can't keep an eye on them.

We should regroup all the UCI issues in one, remove the bug label that catches the eyes and maybe add a label tagging as non-blocking, long term issues to fix one day.

**Comment by frpays** [comment]
Also, the finite-state machine associated with the UCI is fairy simple, to say the least (2 states!).
I would say that aiming at full compliance is not a too high objective, considering the level of technology displayed in the rest of the project.

**Comment by mooskagh** [comment]
I still don't think it's a bug. (E.g. I think that the current behavior is correct).
I'm inclined to close it, but let it gather comments for one more month or so..

**Comment by Naphthalin** [comment]
Issue was closed by a dev, reopened by the author and decided to be not an issue relevant for Lc0, as it doesn't fit the UCI standard. Can be closed.
