### ISSUE TITLE
v0.19.0-rc4 caused an exception(games stopped), loses on time, freezes gui = bugs

### ISSUE THREAD

**Issue by all12** [LeelaChessZero/lc0#507]
It **freezes** the **Aquarium 2018 gui**, when playing matches or tournaments with ponder **on**.
At 1 minute per game + **1 second per move** time control.
[Aquarium 2018, ponder on, 1+1 LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2579604/Aquarium.2018.ponder.on.1%2B1.LogFile.txt)

It **loses sometimes on time** with ponder **off**, at 1 minute per game + **1 second per move** time control.
But it **doesn't freezes** the gui.
[Aquarium 2018, ponder off, 1+1 LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2579611/Aquarium.2018.ponder.off.1%2B1.LogFile.txt)

**Works fine:)**
It **doesn't freezes** the gui.
It **doesn't loses on time** with ponder **off**, at 1 minute per game + **60 seconds per move** time control.
[Aquarium 2018, ponder off, 1+60 LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2579618/Aquarium.2018.ponder.off.1%2B60.LogFile.txt)

When using the **Fritz 16 gui**, it **caused an exception** in every game.
With ponder **on** and 1 minute per game + **1 second per move** time control.
[Fritz 16, ponder on, 1+1 LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2579628/Fritz.16.ponder.on.1%2B1.LogFile.txt)

It also works fine when using the ChessBase 15 gui:)

Infinite analysis runs fine in every gui.

Help wanted
I don't like release blocker
Let us kill the bugs:)

**Comment by all12** [comment]
@borg323,

it doesn't freezes the gui but it loses on time.
[LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2580619/LogFile.txt)

**Comment by borg323** [comment]
Running out of time with 1 second increment is somewhat likely with the current search overhead, so I haven't looked at the logs yet. Changing `HistoryFill` fixes the symptom, but not the problem - only confirms what was overwritten.

**Comment by borg323** [comment]
@all12 can you try a few of the following lc0 versions and see tell us whether they work or not? You don't need to do all of them. 
[v0.19-rc1](https://ci.appveyor.com/api/buildjobs/9oalbrjdwe6w2prs/artifacts/build%2Flc0.exe)
[d6441723](https://ci.appveyor.com/api/buildjobs/uky9xfi1gwr6va8y/artifacts/build%2Flc0.exe)
[a2d710eb](https://ci.appveyor.com/api/buildjobs/9g6aji5qknv22pad/artifacts/build%2Flc0.exe)
[e63b6f4f](https://ci.appveyor.com/api/buildjobs/cka7nkghi7yoneha/artifacts/build%2Flc0.exe)
[daa4ef83](https://ci.appveyor.com/api/buildjobs/gick888c4mkp8dqi/artifacts/build%2Flc0.exe)
[aaf4b0df](https://ci.appveyor.com/api/buildjobs/31lpgg33wscg1quh/artifacts/build%2Flc0.exe)
[v0.18.1](https://ci.appveyor.com/api/buildjobs/2rb20v955mum9am2/artifacts/build%2Flc0.exe)

**Comment by mooskagh** [comment]
Startpos fen takes pretty long route
kStartposFen -> EngineLoop::CmdPosition -> EngineController::SetPosition -> current_position_ -> SetupPosition -> NodeTree:ResetToPosition -> ChessBoard::SetFromFen

Would be nice to know where along the route it's corrupted.
It's unlikely kStartposFen itself, as string literals are usually located in read-only segment.

**Comment by borg323** [comment]
I got a report about the same corruption on linux with nvidia GT 710 using the opencl backend and ponder on. Unfortunately there is no log file available.

**Comment by borg323** [comment]
@all12 the patch by @frpays seems related, so can you try this executable to see if it fixes the crashes?
<https://ci.appveyor.com/api/buildjobs/7nm84cg0sqqqhmwk/artifacts/build%2Flc0.exe>

**Comment by all12** [comment]
@borg323,

it's a great improvement:)
It fixed the crash bug. 
It fixed the freezed gui bug. 
It fixed the caused an exception bug.
But still loses on time.
[LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2591188/LogFile.txt)

**Comment by borg323** [comment]
Went through the latest log and didn't see any time losses at all. It came close a few times so `MoveOverheadMs` should be at least 500 to be safe. Maybe something else is confusing the gui. @mooskagh any ideas?

**Comment by borg323** [comment]
Further analysis of the log shows that the search sometimes takes too long to be destroyed:
```
1116 22:57:44.307649 3152 ..\src/chess/uciloop.cc:131] >> go ponder wtime 1136 winc 1000
...
1116 22:57:45.039570 3152 ..\src/chess/uciloop.cc:131] >> ponderhit
...
1116 22:57:45.975861 7740 ..\src/mcts/search.cc:325] Stopped search: Ran out of time.
...
1116 22:57:45.977126 7740 ..\src/chess/uciloop.cc:218] << bestmove h4h3 ponder e6e7
...
1116 22:57:45.978214 3152 ..\src/chess/uciloop.cc:131] >> position startpos moves a2a3 e7e5 e2e4 g8f6 b1c3 f8c5 g1f3 d7d6 f1c4 e8g8 d2d3 a7a5 h2h3 h7h6 g2g4 f6h7 g4g5 h6g5 h1g1 c8e6 f3g5 e6c4 d3c4 b8d7 d1e2 h7f6 c1d2 c5d4 e1c1 f8e8 g1g2 d4c3 d2c3 d8e7 f2f4 e5f4 d1f1 d7e5 f1f4 c7c6 c4c5 d6d5 e2f1 d5e4 f4f6 e7f6 f1f6 g7f6 g5e4 e5g6 e4f6 g8f8 f6e8 a8e8 c3a5 e8e3 g2h2 f8g7 a5c3 f7f6 h2d2 e3e1 d2d1 e1d1 c1d1 g6f4 h3h4 g7g6 a3a4 f4d5 c3e1 g6f5 b2b4 d5c7 c2c4 c7a6 d1c2 f5g4 c2d3 g4f4 d3d4 f4f5 b4b5 a6c7 d4c3 c7e6 e1f2 f5g4 a4a5 g4f4 b5c6 b7c6 a5a6 e6c7 a6a7 f4f5 c3b4 f5f4 b4a5 c7a8 a5a6 f4f3 a6b7 f3f2 b7a8 f6f5 a8b7 f5f4 a7a8q f4f3 h4h5 f2e1 a8a1 e1e2 a1f6 f3f2 f6f2 e2f2 b7c6 f2f3 c6d5 f3e2 d5e5 e2e1 e5e4 e1f1 e4d4 f1f2 d4d5 f2e1 d5e5 e1d1 e5f5 d1c2 f5f4 c2c1 f4f3 c1b2 f3f2 b2c3 f2f3 c3b3 f3f2 b3b4 f2e2 b4c5 e2d2 c5c4 d2e2 c4d5 h5h6 d5d6 e2d2 d6d7 d2d1 d7e6 h6h7 e6d5 d1d2 d5c5 d2d1 c5c6 h7h8q c6d6 h8h2 d6e6 h2h6 e6e7 h6h4 e7e6 h4h3 e6e7
1116 22:57:45.978355 3152 ..\src/mcts/search.cc:635] Aborting search, if it is still active.
1116 22:57:46.501679 3152 ..\src/mcts/search.cc:649] Search destroyed.
1116 22:57:46.501742 3152 ..\src/chess/uciloop.cc:131] >> go ponder wtime 1151 winc 1000
```

**Comment by all12** [comment]
@borg323,

with MoveOverheadMs = 200, 
2 of 8 games were time loses.

Now I tried it with MoveOverheadMs = 500

1 of 10 games was a time loss, (game 9)
[Aquarium 2018, ponder on, 1+1, LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2591678/Aquarium.2018.ponder.on.1%2B1.LogFile.txt)

and 1 of 20 games was a time loss, (game 4)
[Fritz 16, ponder on, 1+1, LogFile.txt](https://github.com/LeelaChessZero/lc0/files/2591679/Fritz.16.ponder.on.1%2B1.LogFile.txt)

**Comment by borg323** [comment]
Continuing with the previous log, I see something else that looks strange (but this may be due to Aquarium):
```
1116 22:57:57.154785 9540 ..\src/mcts/search.cc:616] End a watchdog thread.
1116 22:57:57.678059 3152 ..\src/chess/uciloop.cc:131] >> setoption name UCI_Chess960 value false
```
