### ISSUE TITLE
Feature request - Xeus notebook?

### ISSUE THREAD

**Issue by reikdas** [LeelaChessZero/lc0#509]
https://github.com/QuantStack/xeus

Has anyone given creating a Xeus notebook showing how it works a thought?

**Comment by mooskagh** [comment]
No idea what's that about.

**Comment by oscardssmith** [comment]
Bad reason for closing, but I agree that Jupyter support for lc0 seems not very useful.

**Comment by reikdas** [comment]
> Bad reason for closing, but I agree that Jupyter support for lc0 seems not very useful.

Maybe demonstrating how it works.
