### ISSUE TITLE
go movetime 30000 - Leela doesn't use all her time

### ISSUE THREAD

**Issue by sunkisser** [LeelaChessZero/lc0#531]
If the UCI command to Leela is "go movetime 30000" (think for 30 seconds then make a move), she should not move faster than that because in that tournament format, it wont reserve extra time for future moves.  I am running an arena tournament where the time is set to 30 seconds per move.  Arena issues the command "go movetime 30000" to the engines, but Leela only uses a few seconds per move because she thinks she is saving that time for the future. Stockfish does it correctly and thinks 20-29 seconds per move.

**Comment by gsobala** [comment]
Search stops when it is calculated that it is impossible for the best move to be overtaken in number of visits. It may surprise you just how skewed the visit distribution can become, the leading move may have eg 10x more visits than the next, and in such a case even if all subsequent visits were to go to the next best move there is not enough time left for it to become the best.

**Comment by MelleKoning** [comment]
Thanks for explaining @gsobala 
Sounds like the best move can take up 10x the number of visits in only 3 seconds thereby making any second best move search totally obsolete; that is, spending another 27 seconds won't change the end result anyway. Is that what you are saying?
Question: suppose we want to use up to 30 seconds just to investigate second best moves a bit more, how can we use this information to prevent the leading move eating up 10x the visits?
I'm curious to what part of engine.cc is deciding the cut-off as well.

**Comment by hans-ekbrand** [comment]
There is a parameter that forces lc0 not to move early, in version 19 and later this parameter is called  `--smart-pruning-factor` while in earlier versions it was called `--futile-search-aversion`. Set it to zero to achieve the effect you want.
