### ISSUE TITLE
Update BLAS release packages from upstream

### ISSUE THREAD

**Issue by gcp** [LeelaChessZero/lc0#544]
The bundled OpenBLAS in the release package dates back to 2015. It will not recognize many new CPUs and run slow.

The release packages on https://github.com/gcp/leela-zero/releases contain updated OpenBLAS DLL builds based on OpenBLAS 0.3.3.

Just picking the DLL from there and replacing the one in the lc0 release speeds up the program by a factor >2 on my Zen 2 machine.

**Comment by gcp** [comment]
...and it also removes the need to bundle all those other DLLs.

**Comment by borg323** [comment]
Where do you get this OpenBLAS version? Is a precompiled package (with headers) available somewhere? As far as I can see, the leela-zero appbeyor builds use the same OpenBLAS version we do.

**Comment by gcp** [comment]
It's compiled from the source with mingw. I can upload a release package for you, but you can also just drop in the DLL as the header and link stub are (apparently) compatible so you really only need the DLL. 

Compiling it from source is slightly tricky because it needs mingw, a bunch of configure options and some fiddling. That's also the reason Leela Zero's CI just uses the older Nuget packages. But the release zips are updated with the newer OpenBLAS.

**Comment by gcp** [comment]
https://sjeng.org/ftp/OpenBLAS-0.3.3-win-oldthread.zip

Making a Nuget package out of this would also be handy, I guess.

**Comment by borg323** [comment]
Thanks for this, I'll integrate it in our build. Alternatively, Appveyor has mingw installed in their images, so we can build from source (and cache the result) if you would like this for Leela Zero as well.

**Comment by borg323** [comment]
I'll make my offer explicit: If you give me build instructions, I'll set-up an appveyor build for openblas.
