### ISSUE TITLE
Cutechess fails to fetch UCI params when there is no network file

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#547]
Steps to reproduce:
1. Start cutechess
2. Ensure that there's no network next to ./lc0 file
3. Add ./lc0 as a new engine
4. Go to the parameters tab
5. Note that it is empty.

The reason for that is that cutechess sends `isready` but never receives `readyok`.

**Comment by borg323** [comment]
Simple test:
```
       _
|   _ | |
|_ |_ |_| v0.20.0-dev built Dec  2 2018
isready
error Network weights file not found.

```
There are two issues here:
1. The reply `error Network weights file not found.` is not a valid uci reply. Probably should be prefaced by `info string`.
2. There is no `readyok` reply as mentioned. 

I'll prepare a patch.

**Comment by mooskagh** [comment]
For the `error` part I think it's fine, as UCI protocol says to ignore unknown strings, so I decided to have something consistent.
Other chess engines usually just output text without prepending `error`.

**Comment by mooskagh** [comment]
And the problem is that it tries to load network, not that it doesn't return `readyok`. It should not attempt to load network before configuration is set. (and cutechess sends `isready` before it sets configuration or before it queries params).

**Comment by borg323** [comment]
I think trying to autodetect a network after 'isready' is fine. But the `isready` reply should be sent even if there is an error. The following works, but I'm looking for something better:
```
  // Network.
  auto network_configuration = NetworkFactory::BackendConfiguration(options_);
  if (network_configuration_ != network_configuration) {
    try {
      network_ = NetworkFactory::LoadNetwork(options_);
      network_configuration_ = network_configuration;
    } catch (Exception& ex) {
      if (std::strcmp(ex.what(), "Network weights file not found.") != 0) {
        throw ex;
      }
    }  
  }
```

**Comment by mooskagh** [comment]
I think it should not load the network before it knows that the game starts.
First, it may load wrong network (e.g. user has some networks lying around the binary, but he configures proper network through UCI parameter.
Second, if a user wants just to configure engine (e.g. open parameters window in cutechess engine options), it should not give him a 5 second delay like it does now.

Also, if error happened, it should not return `readyok` because it is not ready. It's more convenient to see engine hanging with last message on a screen reporting what's wrong.
Also, I still think that `isready` should not trigger any actions, it should wait for actions to finish instead. We had some exceptions where it seemed to be the only workaround (although why don't we do that on `position` command?), but in cases like that where obviously no workaround is needed, we should not trigger work on `isready`.

**Comment by borg323** [comment]
A simple solution is to remove the call to `UpdateFromUciOptions()` from `EnsureReady()`. The only other calls to `UpdateFromUciOptions()` are in `NewGame()` and `SetupPosition()`, i.e. after `ucinewgame` and `go` commands respectively. Unfortunately, not every gui is sending `ucinewgame` at the start as suggested in the uci spec, so in this case the network autodetection and loading will happen after `go`, eating into the move time. 

The uci spec implies that loading should be done after `setoption` and be finished before `readyok` is returned, so my preferred solution (for now) is to leave `UpdateFromUciOptions()` in `EnsureReady()` but conditional on having received `setoption` since the last call.

**Comment by borg323** [comment]
Thinking about it some more, this may still throw an exception before replying `readyok`, which will also cause trouble (and is a violation of the spec form our side).
