### ISSUE TITLE
win_percentage and q should not be passed to the uci_gui as cp uci_info score

### ISSUE THREAD

**Issue by drbas** [LeelaChessZero/lc0#551]
The uci interface specifies the evaluation / sendinfo as a value in centipawns.
Sending win_percentage and q as a sendinfo score causes misbehavior of various UIs. (Chessbase family, Arena) For win% and q a UCI extention should be used, and the sendinfo only used for evaluation values in cp.

**Comment by borg323** [comment]
Sending the win% score using standard uci `info string` was tried and didn't work well with Arena. So we had to chose one non-standard extension over another, and since the cp calculation is an arbitrary transformation of the win% this seemed safe, and was tested to work with Arena and Fritz.

Can you give more details of what kind of misbehavior you are seeing?

**Comment by drbas** [comment]
Example: Chessbase "Fritz 16" gui with lc0, uci param. scoring type as win%

The ui takes the eval. score and uses this for functions like text-commentary, evaluation profile  etc. But more seriously, it passes this value on to the Chessbase online "Let's check" database. Which means, amongst other things, the reference and comparison with other engines fails. 

I mailed back and forth with Chessbase, and they confirm this behavior. They expect cp-values from uci engines.

**Comment by gsobala** [comment]
Yes, corrupting Chessbases painstakingly gathered database would not go down well. Lerla would probably be banned.

**Comment by mooskagh** [comment]
Lc0 outputs centipawns by default. When people change that option, they probably understand what they are doing.

**Comment by drbas** [comment]
Does anyone know why the uci-standard way of sending info from engine-to-gui supposedly didn't work with Arena? [info score cp 0.00 string win% 50.00] should work normally?

For an NN ai it makes sense to have win% as evaluation default. When analyzing in CB I myself use a case-tuned non-ai engine as "primary" engine on the cpus (so it has the "Let's Check" reference attached), and Leela as secondary on the gpus displaying the win%.
The online Let's check database with evaluations by other users\engines is used as an important control reference for validation. (Never trust a single engine or parameter set.)
But one has to be careful here not to swap the engines, or win% is uploaded from Leela instead of cp from Komodo.

**Comment by borg323** [comment]
This was the original approach. However, the `string` part of the `info` output is displayed after the pv and Arena truncates the lines, so after a few moves it was not shown any more.
