### ISSUE TITLE
meson.build:66:0: ERROR

### ISSUE THREAD

**Issue by NicolaiHartmann** [LeelaChessZero/lc0#554]
Just after running build.sh I got this Error:

_Build started at 2018-12-04T21:36:05.267526
Main binary: /usr/bin/python3
Python system: Linux
The Meson build system
Version: 0.45.1
Source dir: /home/bamdad/Schreibtisch/lc0-master
Build dir: /home/bamdad/Schreibtisch/lc0-master/build/release
Build type: native build
Project name: lc0
Sanity testing C++ compiler: c++
Is cross compiler: False.
Sanity check compiler command line: c++ /home/bamdad/Schreibtisch/lc0-master/build/release/meson-private/sanitycheckcpp.cc -o /home/bamdad/Schreibtisch/lc0-master/build/release/meson-private/sanitycheckcpp.exe
Sanity check compile stdout:

-----
Sanity check compile stderr:

-----
Running test binary command: /home/bamdad/Schreibtisch/lc0-master/build/release/meson-private/sanitycheckcpp.exe
Native C++ compiler: c++ (gcc 7.3.0 "c++ (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library libprotobuf found: YES
Program protoc found: YES (/usr/bin/protoc)

meson.build:66:0: ERROR: File libs/lczero-common/proto/net.proto does not exist._

As I am a total programming noob, I would really apreciate your help ! thx in advance

**Comment by mooskagh** [comment]
I never remember what exactly you have to type, but it's something like:
```
git submodule update --init --recursive --remote
```

If it's possible to make meson suggest typing that if submodule is not fetched, that would be nice.

**Comment by JushBJJ** [comment]
Im also getting this too, running Ubuntu 18.10
