### ISSUE TITLE
will the alphazero paper patent prohibit devloping lc0 and other opensource projects

### ISSUE THREAD

**Issue by l1t1** [LeelaChessZero/lc0#569]
https://patentscope2.wipo.int/search/en/detail.jsf?docId=WO2018215665

**Comment by oscardssmith** [comment]
Probably won't effect us, we pre-exist the patent, and google tends not to sue open source projects.

**Comment by mooskagh** [comment]
That's fine, Google patents lots of stuff for defensive reasons, but doesn't use patents for to prevent other development.
