### ISSUE TITLE
cannot git clone? (newbie question sorry)

### ISSUE THREAD

**Issue by kwccoin** [LeelaChessZero/lc0#570]
git clone -b release --recurse-submodules https://github.com/LeelaChessZero/lc0.git
Cloning into 'lc0'...
fatal: Remote branch release not found in upstream origin

**Comment by mooskagh** [comment]
We have a separate branch per minor release now, so instead of `release` use `release/0.19`.

**Comment by oscardssmith** [comment]
Also for future reference, this type of question should go to the help channel on discord
