### ISSUE TITLE
Ensure shortest wins (or: stop trolling)

### ISSUE THREAD

**Issue by MelleKoning** [LeelaChessZero/lc0#572]
When a mate is in sight, we want lc0 te execute on the mate without prolonging the game.

Currently, in node.cc the values are set at game end to:

```
void Node::MakeTerminal(GameResult result) {
  is_terminal_ = true;
  if (result == GameResult::DRAW) {
    q_ = 0.0f;
  } else if (result == GameResult::WHITE_WON) {
    q_ = 1.0f;
  } else if (result == GameResult::BLACK_WON) {
    q_ = -1.0f;
  }
}

```
What we see here is that at game end the number of moves, or movedepth, is not taken into account.

Suppose leela finds a winning game-end at a searchdepth of three and also one at five, what would influence leela to take the shorter route? **Currently nothing.**

We should pass in the search-depth from root into MakeTerminal to influence the outcome.

For example:

```
void Node::MakeTerminal(int _depth_from_root, GameResult result) {
  is_terminal_ = true;
  if (result == GameResult::DRAW) {
    q_ = 0.0f;
  } else if (result == GameResult::WHITE_WON) {
    q_ = 1.0f - (_depth_from_root * 0.01f);
  } else if (result == GameResult::BLACK_WON) {
    q_ = -1.0f + (_depth_from_root * 0.01f);
  }
}
```

In the above case when leela plays white and found a win in five moves the score becomes not 1.0f, but 1.0f - (5 * 0.01) is 0.95f, while a win at three depth gets 0.97f so lc0 will prefer the win with shortest path to get there.

The goal is to slightly influence towards shorter wins.

**Comment by hans-ekbrand** [comment]
I think Certainty Propagation will make sure that if there is a _forced_ mate in sight, then lc0 will execute mate (some mate, I'm not sure if necessarily picks the shortest one). And that is good enough for me.

**Comment by oscardssmith** [comment]
This proposal would break everything (at least with these parameters). The problem is that at medium to long time controls depth gets to ~50. Since the net correctly evaluates a position up a queen as .9 or higher (except in unusual cases but you get the point), this would mean that deep in the tree, the net would actively try to avoid mates.

**Comment by MelleKoning** [comment]
@oscardssmith No, this won't break everything, that is just too strong a judgement. 

The idea of altering the score at the end of the game by taking into account the distance to that end, by looking at how many number of moves away the end is, is nothing new at all.

For example see the adjustment in the calculation taken in part-2 in this paper:
https://medium.com/oracledevs/lessons-from-alphazero-connect-four-e4a0ae82af68

> The fastest Connect Four win is 7 total moves, and the longest is 42 (using up the whole board). Some quick algebra shows that if n is the actual game length, then the expression 1.18–(9*n/350) will yield a value in [0.1, 1] for a win. This makes MCTS prefer quick wins (and slow losses).

As you say the suggested alternation of 0.01 for depth would indeed make the score 50 moves away to go from 1 to 0.5 which might indeed be too extreme. I'm not against a different number at all. Even a lower number of 0.001 would make leela go for the shortest mate when a mate is in sight. It would prefer the mate in 4 moves over the mate in 10 which is the goal here.

**Comment by oscardssmith** [comment]
the problem with this is that as long as the NN rates guaranteed wining positions very close to 1, at high depth, the search will try to avoid mate as the non mate lines will have higher eval than the mate lines. The only way to avoid this is to make the penalty small enough that it doesn't do anything (this was tried for test30).

**Comment by MelleKoning** [comment]
That's the current problem already; leela prefers to promote a pawn to a queen to increase her winning chances instead going for the closer Mate. 
And that is because the net thinks getting a queen by promoting a pawn gives a high winning percentage; it has learned that because the current game-end formula does not take the depth of win into account. 
I'm not saying the formula must be implemented as suggested here; maybe increasing beyond 1 is much better; the net does not know what a queen is worth so there is nothing but this MakeTerminal that lets the net learn to go for closer wins; it needs to know about depth.

**Comment by jhellis3** [comment]
Decrementing score with ply is correct, but the range has to be outside what the nn can output. So you either need to limit non terminal node scores to something like .99 or have mates above 1 and use special score reporting in that case.

**Comment by oscardssmith** [comment]
the problem with using values outside [-1,1] is that they behave badly with averaging.

**Comment by jhellis3** [comment]
I don't see much problem with something in the range of say (1, 1.1] for example or even (1, 1.01].  You can get as precise as your fp format allows here.  Once the value exceeds a certain threshold say 0.95 for example, you check the PV for mate and report if found, clamp to 1 for output otherwise.

There are many ways to resolve the issue correctly.  But decreasing score by ply and special score handling is pretty standard practice.

**Comment by jhellis3** [comment]
Unrelated issue but, mate distance pruning is another search optimization that could be used.  If the PV results in mate in x, no expansion should be happening in nonPV nodes beyond that ply count (since any value found will be worse than mate in x ply).

**Comment by oscardssmith** [comment]
mate distance pruning makes a lot of sense. I don't disagree with the goal of this issue, I just want to make sure that the approach we use doesn't lose elo.

**Comment by MelleKoning** [comment]
We never want to loose elo by adjusting scoring of the end of the game.

If the goal is to only slightly favour shorter wins over longer ones, it is all about including the search-depth in the evaluation. There are different ways to do this and the original pseudo-code that I posted probably diverts too far away because it is always substracting the depth.

If values for a win between [1, 1.1] are preferred, just to give a slight preference to the shorter win, the formula could be adjusted to something like max(1, (1.1- (move_depth/500) )

That is, if the win is close-by (0 moves) the value becomes 1.1, if the win is depth 50 or farther away, the value will be 1. 
Not assuming lc0 will soon reach those depths, but just to have a cap to prevent going lower than 1, we use the max around the formula.

```
void Node::MakeTerminal(int _depth_from_root, GameResult result) {
  is_terminal_ = true;
  if (result == GameResult::DRAW) {
    q_ = 0.0f;
  } else if (result == GameResult::WHITE_WON) {
    q_ = max( 1.0f, 1.10f - (_depth_from_root / 500.0f);
  } else if (result == GameResult::BLACK_WON) {
    q_ = -  max( 1.0f, 1.10f - (_depth_from_root / 500.0f);
  }
}
```

**Comment by Tilps** [comment]
The proposal breaks tree reuse - what you want to do is have the back propagation of q up the tree decay absolutes away from 1 as it gets further up the tree.  You could apply this logic generally even multiply q application for back propagation by (1.0-distance_from_leaf/k)  for some constant k that probably should be at least 600 - maybe 1000.

**Comment by MelleKoning** [comment]
Yeah, after seeing and reporting issue #627 I see why certainty propagation would be the preferred solution.  #487

**Comment by MelleKoning** [comment]
Closing.
