### ISSUE TITLE
OpenBLAS Build requirements - Need clarification

### ISSUE THREAD

**Issue by putztzu** [LeelaChessZero/lc0#578]
Building on openSUSE LEAP 15, perhaps Tumbleweed
1. Distro provides choice OpenBLASMP and OpenBLAS Serial. I'm guessing the first is multi-threaded and the second is single threaded. Aside from that guess, your documentation provides no guidance which should be chosen, and from what I've read selection should be based on whether Lc0 feeds multiple parallel or single threaded data to OpenBLAS (Selection should be opposite what is fed)

2. Aside from the OpenBLAS development headers, I don't see that development headers seem to be required for anything else. Just hoping to verify that is true?

**Comment by putztzu** [comment]
Still no response!
I would have thought this question would be so basic that an answer would be forthcoming by anyone who had already installed using OpenBLAS! So, still waiting for an answer, otherwise eventually I may just have to start experimenting...

In any case, for anyone who finds this posting, I have better info correcting my guesses specifically for the pre-compiled openSUSE packages... All packages provided by openSUSE are likely multi-threaded enabled by default, so if single-threaded is desired, needs to be set by command line. More than likelyt the pthreads package should be selected, subject to discovering possible undocumented features may be required in other packages.

**Comment by mooskagh** [comment]
I'd suggest asking help on #help channel in our discord server https://discord.gg/pKujYxD.

If you found something that you think is worth adding to wiki or README, could you please update wiki or send a PR to the repo?
