### ISSUE TITLE
not using Intel graphics

### ISSUE THREAD

**Issue by Chessie-K** [LeelaChessZero/lc0#579]
The opencl Version installed in a GUI does not use Intel graphics. Blas is Default and there is no way to change to opencl. You can choose only blas, check, random, multiplexing.
It only works inside command prompt.

**Comment by hans-ekbrand** [comment]
Hi Chessie-K

My guess is that your problems do not indicate bugs in lc0, but please ask for help on https://discordapp.com/channels/425419482568196106/427066771627966466
to solve the issues you brought up.
