### ISSUE TITLE
Tuner isn't working on AMD Opencl

### ISSUE THREAD

**Issue by firekuv** [LeelaChessZero/lc0#588]
reverting to before #521 fixed it

Selected platform: AMD Accelerated Parallel Processing
Selected device: Pitcairn
with OpenCL 2.1 capability.
Started OpenCL SGEMM tuner with batch size 16.
Will try 578 valid configurations.
Failed to find a working configuration.
Check your OpenCL drivers.

**Comment by borg323** [comment]
Additional testing reported on discord #help indicates that using an existing `leelaz_opencl_tuning` latest master works fine. Also latest master was able to tune using a test30, while the above report was with a test35 series network.

**Comment by borg323** [comment]
@firekuv test executable for #589: https://ci.appveyor.com/api/buildjobs/pg9747xr71n2cohj/artifacts/build%2Flc0.exe
