### ISSUE TITLE
selfplay not work

### ISSUE THREAD

**Issue by abdulbadii** [LeelaChessZero/lc0#600]
I tried typing on Windows or mingw console:

lc0 selfplay -b blas -t 2 --games=35

but only show,
|   _ | |
|_ |_ |_| v0.19.1 built Dec 11 2018
id name Lc0 v0.19.1
id author The LCZero Authors.
Found pb network file: ./weights_run1_35273.pb.gz

Then a second next get back to console prompt

How to solve this??

**Comment by mooskagh** [comment]
Please come to our chat, channel #help, with questions like this.
https://discord.gg/pKujYxD <- discord invite
