### ISSUE TITLE
Black moves pieces towards h1 corner

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#61]
http://testserver.lczero.org/match/28
http://testserver.lczero.org/match_game/27988 (white is test31, black is test27).
This match was probably played with the T=1 bug, which is why it lasted so long in the first place. But another question is why does black tend to move its pieces towards h1? It's probably because moves towards h1 for black (h8 for white) have the largest encoded values. So possibly something is overflowing, and all results are tied, and the final tie-break is the size of the move encoding.

So far though I'm not able to reproduce that, search looks normal, it wants to play 150.Bb7.
```
position startpos moves g2g3 e7e5 h2h4 b8c6 d2d3 f8c5 c1h6 g8h6 e1d2 h6g4 d1c1 g4f2 c2c4 d7d5 b2b3 f2h1 c1a3 c5d4 b3b4 d4a1 c4d5 d8d5 e2e4 d5d6 h4h5 d6b4 a3b4 c6b4 d3d4 h1g3 b1a3 e5d4 h5h6 g7h6 g1e2 g3f1 d2c1 d4d3 c1d1 d3e2 d1e2 f7f5 e4f5 c8f5 e2f1 e8c8 a3c4 b4a2 c4e3 f5h3 f1e2 h6h5 e3f5 h3f5 e2e3 h5h4 e3f4 h4h3 f4f5 h3h2 f5e6 h2h1q e6f7 h7h5 f7g6 h5h4 g6f7 h4h3 f7g6 h3h2 g6f5 b7b6 f5e6 a7a5 e6f5 h1g1 f5f4 b6b5 f4f3 a2c3 f3f4 h2h1q f4f5 b5b4 f5f4 b4b3 f4f5 b3b2 f5f4 b2b1q f4e5 c3e4 e5f4 a1b2 f4f5 a5a4 f5e6 a4a3 e6f5 a3a2 f5f4 a2a1q f4f5 d8d1 f5f4 b2c1 f4f5 c1d2 f5e6 d2e1 e6e7 e1d2 e7e6 d2e1 e6e7 e1g3 e7e6 g3f4 e6f7 h1g2 f7e6 f4e5 e6f5 g2h1 f5e6 h1g2 e6e7 e4f2 e7e6 d1f1 e6f7 g2h1 f7e6 e5h2 e6e7 c8b8 e7d7 h1g2 d7e6 g2h1 e6d7 f2g4 d7e6 h8h6 e6d7 g1f2 d7d8 h6h5 d8e8 h5h4 e8d8 f2g3 d8e8 f1f2 e8d7 b1g1 d7d8 a1f1 d8e8 f1g2 e8d7 f2f1 d7d8 g3f3 d8d7 g4f2 d7d8 h4h3 d8e7 f1e1 e7d7 e1f1 d7d8 f1e1 d8d7 e1f1 d7d8 b8a7 d8d7 a7a6 d7c8 f1e1 c8d8 e1f1 d8e8 f1e1 e8d7 e1f1 d7d8 c7c6 d8c8 c6c5 c8d8 a6b7 d8e8 c5c4 e8d8 c4c3 d8e8 c3c2 e8d8 c2c1q d8e7 c1b2 e7e6 b2c1 e6e7 b7a8 e7e8 c1b2 e8d7 b2c1 d7d8 c1b2 d8c8 f1e1 c8d8 b2c1 d8d7 e1f1 d7d8 c1g5 d8d7 g5h6 d7c8 h6h5 c8d8 h5h6 d8e8 h6h5 e8d7 h5h4 d7c8 h4g3 c8d8 f1e1 d8d7 e1f1 d7d8 a8b7 d8e8 b7a6 e8d8 f1e1 d8d7 e1f1 d7d8 a6b5 d8d7 b5c4 d7d8 f1e1 d8d7 g1f1 d7d8 f2g4 d8d7 g4f2 d7d8 e1a1 d8c8 g2g1 c8d7 g3g2 d7d8 a1a2 d8d7 a2c2 d7c8 c4c5 c8d8 c5d4 d8e8 d4d3 e8d7 c2e2 d7d8 e2e1 d8d7 d3e2 d7d8 e2d1 d8d7 d1d2 d7d8 f1e2 d8d7 g1f1 d7d8 h2g1 d8d7 h3h2 d7d8 f2d1 d8d7 g1f2 d7d8 g2g1 d8c8 
go nodes 800
```
```
info string d1b2  (1683) N:      22 (+ 0) (V:  99.95%) (P:  6.97%) (Q:  0.22714) (U: 0.26501) (Q+U:  0.49215)
info string d1e3  (1681) N:      30 (+ 0) (V:  99.96%) (P:  8.88%) (Q:  0.23324) (U: 0.25028) (Q+U:  0.48353)
info string f3b7  (1295) N:     293 (+ 0) (V:  99.97%) (P:  0.48%) (Q:  0.85665) (U: 0.00141) (Q+U:  0.85807)

```

**Comment by killerducky** [comment]
@mooskagh I haven't been able to hit the condition, but lczero has some extra code to protect against some weird cases:
https://github.com/LeelaChessZero/lczero/blob/release/src/UCTNode.cpp#L108

That case was being hit when we used a random net. After softmax, policy would put a 1.0 on one move, and 0.0 on all others. Typically the 1.0 move was illegal, so after filtering, total policy was zero. If this is happening it could cause the behavior we see (moving pieces to h1/h8).

lc0 doesn't have the same:
https://github.com/LeelaChessZero/lc0/blob/master/src/mcts/search.cc#L798

Maybe we should add similar guard code?

**Comment by Tilps** [comment]
Actual testing of PR69 found that all policy elements being 0 doesn't happen much if ever, even in only slightly trained networks. So that explanation seems out.

**Comment by mooskagh** [comment]
I think I saw similar behaviour recently (QQQQK vs KPP), but QQQQ managed to checkmate in the end.
Closing for now as not really causing troubles.
