### ISSUE TITLE
Build lc0 - "No usable computation backends found" - Advice req

### ISSUE THREAD

**Issue by putztzu** [LeelaChessZero/lc0#611]
openSUSE 15 (fully updated)
gcc 8.2.1 (Interesting that the log shows is not respecting the update-alternatives switch and still using 7.3.1)
meson 0.46.0
ninja 1.8.2
OpenBLAS package and version openblas-pthreads_0_2_20-gnu-hpc-devel-static .rpm
OpenBLAS development headers packages for the above also installed

lc0 cloned from github repo 12/24/2018

**Advice Needed:**
As can be seen by the log below, the build fails when it cannot find a Tensorflow backend.
Need advice:
openSUSE provides tensorflow packages which I know nothing about today but can study. The log suggests that lc0 can run without a compute backend, but what does "random only backend" mean?, and is this option passed in a meson configuration file, passing the parameter to meson in build.sh or some other way?

Also, I suppose I should investigate why openblas was not detected, initial appearance from the log is that the build script is looking for "openblas.dll" which would be found on a Windows machine, I wonder if the build script only looks for openblas on Windows and does not test for openblas on Linux.

TIA.

**STDOUT and Meson log**
 ./build.sh 
The Meson build system
Version: 0.46.0
Source dir: /home/tony/github/lc0
Build dir: /home/tony/github/lc0/build/release
Build type: native build
Project name: lc0
Native C++ compiler: c++ (gcc 7.3.1 "c++ (SUSE Linux) 7.3.1 20180323 [gcc-7-branch revision 258812]")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library libprotobuf found: NO
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Dependency protobuf found: NO
Program protoc found: NO
Downloading protobuf from https://github.com/google/protobuf/releases/download/v3.5.1/protobuf-all-3.5.1.tar.gz
Download size: 6662844
Downloading: ..........
Downloading patch from https://github.com/borg323/protobuf/releases/download/3.5.1-2w/protobuf-3.5.1-2w-wrap.zip
Download size: 2905
Downloading: ..........

|
|Executing subproject protobuf.
|
|Project name: protobuf
|Native C++ compiler: c++ (gcc 7.3.1 "c++ (SUSE Linux) 7.3.1 20180323 [gcc-7-branch revision 258812]")
|Compiler for C++ supports arguments -DHAVE_PTHREAD: YES
|Compiler for C++ supports arguments -Wno-sign-compare -Wsign-compare: YES
|Compiler for C++ supports arguments -Wno-unused-parameter -Wunused-parameter: YES
|Compiler for C++ supports arguments -Wno-ignored-qualifiers -Wignored-qualifiers: YES
|Compiler for C++ supports arguments /wd4146: NO
|Compiler for C++ supports arguments /wd4244: NO
|Compiler for C++ supports arguments /wd4305: NO
|Compiler for C++ supports arguments /wd4506: NO
|Dependency threads found: YES
|Build targets in project: 6
|
|Subproject protobuf finished.
Message: updating git submodule libs/lczero-common
Library pthread found: YES
Library dl found: YES
Library libtensorflow_cc found: NO
Dependency Accelerate found: NO
Library mkl_rt found: NO
Library openblas.dll found: NO
Library openblas found: NO
Program ispc found: NO
Library OpenCL found: NO
Dependency OpenCL found: NO
Library cublas found: NO
Library cudnn found: NO
Library cudart found: NO
Program /usr/local/cuda/bin/nvcc found: NO
Program /opt/cuda/bin/nvcc found: NO
Program nvcc found: NO

meson.build:397:2: ERROR:  Problem encountered: 

        No usable computation backends (cudnn/tensorflow/etc) are found.
        If you want to build it with random only backend, pass
        -D build_backends=false to a meson build.

A full log can be found at /home/tony/github/lc0/build/release/meson-logs/meson-log.txt

**Comment by borg323** [comment]
As you correctly state, the issue is that OpenBLAS is not detected. (There is a second check right after the dll one). Can you find where the OpenBLAS library is installed? The include files are also needed, specifically `openblas_config.h`. You need to set the build.sh options  `-Dopenblas_libdirs=` and `-Dopenblas_include` to the correct paths.

The tensorflow backend is a pain to build, I would avoid it for now. I'll reword the above error message to avoid confusion in the future.

**Comment by putztzu** [comment]
Hi,

The full path to  openblas_config.h is the following

`/usr/lib/hpc/gnu7/openblas-pthreads/0.3.4/include/openblas_config.h`

After not finding those statements in build.sh, I started looking at the other files and believe I found them in meson_options.txt. Am speculating perhaps that I should modify **this** file as follows? Or, alternatively would it be better to symlink from the locations described in this file to the location above?
Thx.

```
option('openblas_libdirs',
       type: 'array',
       value: ['/usr/lib/hpc/gnu7/openblas-pthreads/0.3.4/'],
       description: 'Paths to OpenBLAS libraries')

option('openblas_include',
       type: 'array',
       value: ['//usr/lib/hpc/gnu7/openblas-pthreads/0.3.4/include/'],
       description: 'Paths to openblas include directories')
```

**Comment by borg323** [comment]
You can do it like that, but the `openblas_libdirs` should point to the directory with the `libopenblas.so` library, probably `/usr/lib/hpc/gnu7/openblas-pthreads/0.3.4/lib` or similar. You can override the paths from `meson_options.txt` by using the command line options I mentioned earlier when building, `-Dopenblas_include=/usr/lib/hpc/gnu7/openblas-pthreads/0.3.4/include/` and `-Dopenblas_libdirs=/usr/lib/hpc/gnu7/openblas-pthreads/0.3.4/lib` (or whatever the correct library path is).

**Comment by putztzu** [comment]
No joy.. Error is exactly as posted above, no change.

Tried entering the following commands in build.sh, near the end of(just before pushd) and just before the BUILDDIR code block. When that failed, I tried making the modifications to meson_options.txt as described in the above post, except that the opbenblas_libdirs value was modified to point to /usr/lib64 (instead of the default /usr/lib)

build.sh
`Dopenblas_libdirs=/usr/lib64/
Dopenblas_include=/usr/lib/hpc/gnu7/openblas-pthreads/0.3.4/include/`

**Comment by borg323** [comment]
My apologies if my description was not very clear. What I was trying to say is to cal `build.sh` like this:
```
./build.sh -Dopenblas_libdirs=/usr/lib64/ -Dopenblas_include=/usr/lib/hpc/gnu7/openblas-pthreads/0.3.4/include/
```
However, changing the paths in `meson_options.txt` should have worked, so this is strange. What openblas libraries are available in `/usr/lib64/`? Can you also check the permission bits on them?

**Comment by putztzu** [comment]
I don't know if permissions should be an issue, I've been building in a root console.

ls -l /usr/lib64/libopenblas*
```
-rwxr-xr-x 1 root root 36943480 May 12  2018 /usr/lib64/libopenblas_pthreads.so.0
lrwxrwxrwx 1 root root       43 Aug  9 11:47 /usr/lib64/libopenblas.so.0 -> /etc/alternatives/libopenblas_pthreads.so.0
```

**Comment by putztzu** [comment]
For kicks, as described I ran build.sh specifying the openblas library and include directories as command arguments and to no surprise, there is no change, same error.

**Comment by borg323** [comment]
Typically there is a link named `libopenblas.so` pointing to the actual shared library. I just tried this on my system and if it isn't there the build system looks for a static library (`libopenblas.a`). 
It seems you should have installed `libopenblas_pthreads-devel-0.3.4-lp150.56.1.x86_64.rpm` (and the dependencies).

**Comment by putztzu** [comment]
Yes, thank you for spending so much time on this.
Your solution is exactly right and fixes the problem for me (although there still seems to be a gtest error which I'll post in a new thread).

A full explanation of what happened follows...
In the immediately following code block you can see I installed the development headers package specific to the installed openblas, I didn't install the more generalized package. I don't know why sometimes both header packages need to be installed and in others only one or the other, but it's good practice to install both when they're available(which i didn't do). I've run into this once before involving building kernel modules.

The following is what was installed
zypper se openblas*
```
S  | Name                                          | Summary                            | Type      
---+-----------------------------------------------+------------------------------------+-----------
   | openblas-devel                                | Development headers and librarie-> | package   
   | openblas-devel-headers                        | Development headers for OpenBLAS   | package   
i+ | openblas-pthreads_0_2_20-gnu-hpc-devel-static | Static version of OpenBLAS         | package   
   | openblas-pthreads_0_3_4-gnu-hpc               | An optimized BLAS library based -> | srcpackage
i+ | openblas-pthreads_0_3_4-gnu-hpc-debugsource   | Debug sources for package openbl-> | package   
i+ | openblas-pthreads_0_3_4-gnu-hpc-devel-static  | Static version of OpenBLAS         | package 
   | openblas_0_2_20-gnu-hpc-devel-static          | Static version of OpenBLAS         | package   
   | openblas_0_3_4-gnu-hpc                        | An optimized BLAS library based -> | srcpackage
   | openblas_0_3_4-gnu-hpc-debugsource            | Debug sources for package openbl-> | package   
   | openblas_0_3_4-gnu-hpc-devel-static           | Static version of OpenBLAS         | package   
   | openblas_openmp                               | An optimized BLAS library based -> | srcpackage
   | openblas_openmp-debugsource                   | Debug sources for package openbl-> | package   
   | openblas_openmp-devel-static                  | Static version of OpenBLAS         | package   
   | openblas_pthreads                             | An optimized BLAS library based -> | srcpackage
   | openblas_pthreads-debugsource                 | Debug sources for package openbl-> | package   
   | openblas_pthreads-devel-static                | Static version of OpenBLAS         | package   
   | openblas_serial                               | An optimized BLAS library based -> | srcpackage
   | openblas_serial-debugsource                   | Debug sources for package openbl-> | package   
   | openblas_serial-devel-static                  | Static version of OpenBLAS         | package 
```

The install command which fixed the problem is

`zypper in openblas_pthreads-devel-static `

The result is

zypper se -i openblas*
```
S  | Name                                          | Summary                               | Type   
---+-----------------------------------------------+---------------------------------------+--------
i  | openblas-devel                                | Development headers and libraries f-> | package
i  | openblas-devel-headers                        | Development headers for OpenBLAS      | package
i+ | openblas-pthreads_0_2_20-gnu-hpc-devel-static | Static version of OpenBLAS            | package
i+ | openblas-pthreads_0_3_4-gnu-hpc-debugsource   | Debug sources for package openblas--> | package
i+ | openblas-pthreads_0_3_4-gnu-hpc-devel-static  | Static version of OpenBLAS            | package
i+ | openblas_pthreads-devel-static                | Static version of OpenBLAS            | package
```
Now it looks like the main part of build.sh runs to conclusion successfully, but has run into a new error related to gtest, but IIRC in the documentation gtest was optional.

Since I'll be posting the new error in a new thread, this issue has been resolved.
