### ISSUE TITLE
Nvidia CUDA error

### ISSUE THREAD

**Issue by PangolinGiLA** [LeelaChessZero/lc0#615]
Hi, 
I am using Windows 10 and i downloaded the lastest version of Leela (but not pre-release) and when I try ti run it, I see error : "error CUDA error: CUDA driver version is insufficient for CUDA runtime version (../src/neural/network_cudnn.cu:976)". What should I doto fix it?

**Comment by PangolinGiLA** [comment]
Thank you! I will try it (my driver is being downloaded now). Maybe you should update common problems at https://github.com/LeelaChessZero/lc0/wiki/Getting-Started#debug because there is written that 397.44 is needed and because of that I didn't try to update my driver before

**Comment by cn4750** [comment]
Thank you for pointing out the issue with the wiki. It is quite out of date, but I have updated it somewhat to hopefully help prevent this issue in the future.
