### ISSUE TITLE
Newly Built lc0 on an RPM machine - final steps

### ISSUE THREAD

**Issue by putztzu** [LeelaChessZero/lc0#623]
Comparing this new build on an openSUSE 15 to the install instructions for Ubuntu,
It looks like on  Ubuntu machines, the lc0 binary is supposed to be copied to

`~/.local/bin/`

This didn't happen on this openSUSE.
I found the newly built binary in the build/release subfolder of the development tree, and it appears to work.

I assume that this binary has no dependencies and can be copied to anywhere I wish?

When I've completed putting lc0 through a few paces, I'll review what I did and  create a pull request for installing on openSUSE, and although I won't be checking should be very close if not exactly what would be required to install on Fedora... only diff would be repositories and the package management utility.

**Comment by simlu** [comment]
Have you considered making it reproducible using docker? I find docker scripts highly instructive and very easy to validate.

**Comment by putztzu** [comment]
The install scripts I create are very flexible, fully commented and automated, I hope to be able to publish soon.

I am a very big fan of docker, but have mixed feelings about using it... The big plus of course is the portable package that can be deployed everywhere, the downside is that to achieve that universality, you have to include a stub of the distro it was built on in every instance plus any other dependencies.

**Comment by putztzu** [comment]
@simlu 
If you're interested, I've posted my current build script at
https://gist.github.com/putztzu/17efbba3a9b04d12781f41bb4298b314

You'll find the script should be generously commented, and if you want to turn it into a Docker file, over 95% of what you need is right there.

The script should support every current version and release of openSUSE including both the ultra stable LEAP and rolling release Tumbleweed. I didn't test, but believe it should also work on the openSUSE release of RPi and possibly other mobile devices running ARM architectures.... As for versions, support should go back several to LEAP 42.1 and should also support the coming LEAP 15.1 when those repositories and builds become available. 

The script supports only the openBLAS backend because it's the most generic that can be installed on all hardware, it does not support the GPU processing backends.

So, what's lacking that's preventing me from submitting a Pull Request now?
- Detecting whether a repository already exists so that the script can be run to fix or update an existing install. Am undecided if this is best done by code or simply providing a separate script without the conflicting code.
- Final verification the compiled binary is valid. I see nothing wrong with it when I run the binary directly but am having problems hooking it up to a graphical frontend.
- Some possible package selection optimization, although plenty has been done up to this point.
- Am hoping for some visibility and possible support for future versions of gcc,  current package selection is locked into gcc7 because although some gcc8 packages are already available, not all supporting libraries and components are available as of yet.

**Comment by putztzu** [comment]
Have created a Pull Request.
Anyone who wants to take a look at this before it's finally approved can view on my github lco site

https://github.com/putztzu/lc0/blob/putztzu-patch-1/openSUSE_install.md

**Comment by putztzu** [comment]
This issue can be considered superceded by 
Pull Request
https://github.com/LeelaChessZero/lc0/pull/675

**Comment by Naphthalin** [comment]
#675 has been merged, so this issue can be closed.

**Comment by mooskagh** [comment]
We still have to resolve what is listed in #976 to make it really packageable in linux distros.
But closing this as we have a separate issue for that.
