### ISSUE TITLE
undefined sanitizer issues

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lc0#639]
I did a quick test of a random backend benchmark with undefined sanitizer applied and got a couple of errors.

1) loader.cc tries to read 4 bytes of magic using a 32 bit pointer cast at a 1 byte offset into data.  But that results in a pointer with alignment which is invalid so there is undefined behavior.
2) fastmath.h performs a left shift of a negative number if the power being calculated is negative.  This is also undefined behavior.

**Comment by borg323** [comment]
Number2 is addressed in #643.

**Comment by borg323** [comment]
Number 1 also assumes little endian order.
