### ISSUE TITLE
Lc0 massive blunder second move out of book at tcec bonus.

### ISSUE THREAD

**Issue by Tilps** [LeelaChessZero/lc0#644]
position startpos moves e2e4 e7e5 b1c3 g8f6 f1c4 f6e4 d1h5 e4d6 c4b3 b8c6 c3b5 g7g6 h5f3 f7f5 f3d5 d8f6 b5c7 e8d8 c7a8 b7b6 d2d3 c8b7
At this position tcec bonus (apparently using v20rc2 net 32329 - with 2 x2070 gpus 4 threads 160 mini batch size and 64 collision events in 20 minute and 2 second increment) h2h4 was played, leading leela, which after c6e7 from sf leela immediately switched evals from almost +2 to  -17 or worse.  SF agrees h4 is a bad move, expecting nf3.

Jesse tested the position https://termbin.com/4bz3 (possibly with a different net... With master on 4 gpus both with demux and roundrobin) and h2h4 is only considered relatively briefly at lowish nodes.

Might be worth some further investigation.

**Comment by jkormu** [comment]
Net 32329 seems to be just blind to c6e7 response that has prior 0.0135.
To eliminate possibility that blunder is caused by minibatch size or collisions, I ran this position with --minibatch-size=1 and --threads=1. Blunder move h2h4 is the selected move from 725 nodes onwards at least up to 2 million nodes when I stopped the search.  

```
info depth 17 seldepth 42 time 2022134 nodes 681968 score cp 182 hashfull 1000 nps 337 tbhits 0 pv h2h4 f5f4 d5f3 f8h6 c1d2 c6d4 f3h3 h8e8 g1f3 b7a8 e1c1 d4f3 g2f3 a8c6 c2c3 a7a5 b3c2 f6f7 c2b3 f7f6 c1b1 a5a4 b3c2 a4a3 b2a3 h6f8 a3a4 d8c7
```
However, on this position and on low nodes the search tree shape varies a lot from run to run when 160 minibatch size, 64 collision events and 2 threads are used as seen in [plot](https://script.google.com/macros/s/AKfycbzA7OyZd_j_ZZ98HWDpkbTRmFMiivnbDrPIvJEKk47SgMQPI574/exec?file_name=issue644_blunder.html).
The four runs with minibatch=160  vary a lot and are quite far from minibatch=1 search. But the minibatch size is not the cause for the blunder here.

**Comment by jkormu** [comment]
With
```--minibatch-size=1 --threads=1 --max-collision-visits=1```
h2h4 is the best move up to 2873533 nodes, when g1f3 over takes it and stays as best move until 6 million nodes.

Did also one run with
``` --minibatch-size=160 --threads=2 --max-collision-events=64 ```
and the story is the same, g1f3 is found only at 2970400 nodes.

It just takes a lot of nodes for 32329 to avoid the blunder.

**Comment by Videodr0me** [comment]
Try this version with Certainty Propagation enabled (and threads = 4): https://ci.appveyor.com/project/LeelaChessZero/lc0/builds/21916156/job/851awkkkw5etj92n/artifacts

With this and net 32329 it takes only 307k nodes to avoid h2h4 and switch to Nf3:
Neue Partie Line
N2k1b1r/pb1p3p/1pnn1qp1/3Qpp2/8/1B1P4/PPP2PPP/R1B1K1NR w KQ - 0 1

Analysis by Lc0 v0.21.0-dev:
  +- (1.65)  Tiefe: 15/42   00:01:07  284kN
12.h2-h4 h7-h6 13.Dd5-f3 Lf8-g7 14.Sa8xb6 a7xb6 15.Df3-h3 Th8-e8 16.Lc1-e3 e5-e4 17.Sg1-e2 e4xd3 18.c2xd3 Df6xb2 19.Ta1-d1 Sc6-d4 20.Se2xd4 f5-f4 21.0-0 f4xe3 22.f2xe3 Te8xe3 23.Sd4-f3 Sd6-f5 24.Dh3-g4 Lb7xf3 25.Tf1xf3 
  +- (1.65)  Tiefe: 15/42   00:01:12  307kN
12.Sg1-f3 f5-f4 13.Ke1-f1 Kd8-c8 14.d3-d4 e5-e4 15.Dd5-g5 Df6-g7 16.Sf3-e5 Lf8-e7 17.Dg5-g4 Sc6xe5 18.d4xe5 Sd6-f5 19.Lc1xf4 h7-h5 20.Dg4-e2 g6-g5 21.Lf4-e3 Dg7xe5 22.c2-c3 Lb7xa8 23.Kf1-e1 La8-c6 24.Ke1-d2 Lc6-b5 25.Lb3-c4 Lb5-c6 26.Kd2-c2 b6-b5 27.Lc4-b3 a7-a5 28.a2-a4 b5-b4 
  +- (1.70)  Tiefe: 15/42   00:01:15  321kN
12.Sg1-f3 f5-f4 13.Ke1-f1 Kd8-c8 14.d3-d4 e5-e4 15.Dd5-g5 Df6-g7 16.Sf3-e5 Lf8-e7 17.Dg5-g4 Sc6xe5 18.d4xe5 Sd6-f5 19.Lc1xf4 h7-h5 20.Dg4-e2 g6-g5 21.Lf4-e3 Dg7xe5 22.c2-c3 Lb7xa8 23.Kf1-e1 La8-c6 24.Ke1-d2 Lc6-b5 25.Lb3-c4 Lb5-c6 26.Kd2-c2 b6-b5 27.Lc4-b3 a7-a5 28.a2-a4 b5-b4

**Comment by TesseractA** [comment]
@Tilps still applicable? Which game was this?

**Comment by Mardak** [comment]
> after c6e7 from sf leela immediately switched evals from almost +2 to -17 or worse

Yeah looks like t30 and t40 are blind to that move while t60 finds it within a few thousand visits. Here's various runs and networks:
```
expect c6e7 from…
position startpos moves e2e4 e7e5 b1c3 g8f6 f1c4 f6e4 d1h5 e4d6 c4b3 b8c6 c3b5 g7g6 h5f3 f7f5 f3d5 d8f6 b5c7 e8d8 c7a8 b7b6 d2d3 c8b7 h2h4

32000 P:  0.46% V:  0.2915
32050 P:  0.21% V:  0.2736
32100 P:  0.26% V:  0.3260
32150 P:  0.17% V:  0.2101
32200 P:  0.13% V:  0.2679
32250 P:  0.14% V:  0.2549
32300 P:  0.15% V:  0.3066
32350 P:  0.08% V:  0.3456
32400 P:  0.08% V:  0.2563
32450 P:  0.10% V:  0.2674
32500 P:  0.08% V:  0.2344
32550 P:  0.07% V:  0.0933
32600 P:  0.06% V:  0.2873
32650 P:  0.10% V:  0.2191
32700 P:  0.09% V:  0.2924
32750 P:  0.08% V:  0.2893
32800 P:  0.11% V:  0.2702
32850 P:  0.08% V:  0.3232
32900 P:  0.09% V:  0.3108
32950 P:  0.09% V:  0.2732
33000 P:  0.08% V:  0.3669

41850 P:  0.08% V: -0.0125
41900 P:  0.10% V: -0.1410
41950 P:  0.08% V: -0.1535
42000 P:  0.07% V: -0.1971
42050 P:  0.15% V:  0.1219
42100 P:  0.12% V: -0.0615
42150 P:  0.06% V:  0.2293
42200 P:  0.04% V: -0.0283
42250 P:  0.06% V: -0.1405
42300 P:  0.04% V: -0.2004
42350 P:  0.04% V: -0.0259
42400 P:  0.04% V: -0.1520
42450 P:  0.04% V: -0.0919
42500 P:  0.03% V: -0.3952
42550 P:  0.03% V: -0.2794
42600 P:  0.02% V: -0.1197
42650 P:  0.03% V: -0.0011
42700 P:  0.02% V: -0.1752
42750 P:  0.01% V: -0.0939
42800 P:  0.01% V: -0.1291
42850 P:  0.01% V: -0.1131

62150 P:  1.99% V:  0.3069
62200 P:  1.90% V:  0.1982
62250 P:  1.39% V:  0.1065
62300 P:  1.18% V:  0.2095
62350 P:  1.92% V:  0.2683
62400 P:  1.39% V:  0.4177
62450 P:  1.62% V:  0.0036
62500 P:  2.09% V:  0.1592
62550 P:  3.58% V:  0.1094
62600 P:  2.92% V:  0.2456
62650 P:  2.20% V:  0.2112
62700 P:  3.44% V:  0.0781
62750 P:  3.04% V:  0.1785
62800 P:  2.95% V:  0.2226
62850 P:  2.48% V:  0.1756
62900 P:  2.35% V:  0.1988
62950 P:  2.18% V:  0.2266
63000 P:  2.17% V:  0.1857
63050 P:  2.87% V:  0.1107
63100 P:  2.46% V: -0.0005
63150 P:  1.93% V:  0.2957
```
