### ISSUE TITLE
Lc0 responds with `bestmove` if it reaches limit during ponder.

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#651]
Reported on discord.
It seems that during ponder, when Lc0 decides to suspend progress, it sends `bestmove` and confuses Arena.

Video where this issue is reproduced:
https://cdn.discordapp.com/attachments/427066771627966466/530507183432138753/arena-lc0-bug-002.mp4
https://cdn.discordapp.com/attachments/427066771627966466/530502146848849930/arena-lc0-bug-WARNING-search-limit.mp4

Arena log:
https://cdn.discordapp.com/attachments/427066771627966466/530509246777917453/arena-protocol.txt

Lc0 log:
https://cdn.discordapp.com/attachments/427066771627966466/530513736964767744/lc0log.txt

**Comment by mooskagh** [comment]
Arena sends:
```
go ponder movetime 15000
```
Those 15000 mean that that timer should start on `ponderhit`. But we start it immediately.
When the timer runs out before `ponderhit`, it hangs.
If timer runs out after `ponderhit`, it's still wrong, as timer should not have counted time before `ponderhit`.

**Comment by borg323** [comment]
There are two issues here:
1. `go ponder` with any additional constraint (except `wtime` and `btime`) honors the constraint. This is correct for `searchmoves` and certainly wrong for `movetime` which should only be honored after `ponderhit` (as mentioned above by @mooskagh). Whether it should be honored in the other cases like `depth` or `nodes` is arguable, although the nodes limit is also used internally to constrain memory usage. 
2. When a limit is used while pondering, lc0 stops responding to uci commands.

The `Bestmove was from pondersearch, ignoring` message from Arena is just indicating that the required `bestmove` after a `stop` was received, this is not a problem.

**Comment by borg323** [comment]
Point 2 above is probably due to <https://github.com/LeelaChessZero/lc0/pull/539> (from reading the code).
