### ISSUE TITLE
Isn't there any instruction on how to build on Mingw/Msys2 ?

### ISSUE THREAD

**Issue by abdulbadii** [LeelaChessZero/lc0#656]
How can we build lc0 on Mingw/Msys2 ?
there're some package in pacman,
```
   mingw-w64-x86_64-liblas
   ASPRS LiDAR data translation toolset 

   mingw-w64-x86_64-ninja
    Ninja is a small build system with a focus on speed

   mingw-w64-x86_64-meson
   High-productivity build system
```
could be very likely to succeed in build ?
 Instructions will bring in fine gratitudes

**Comment by borg323** [comment]
Should be possible but only with the opencl and blas backends. 
 - The first package you list seems unrelated, you will need libopeneblas, not liblas.
 - You will also need python (v3) but meson will probably bring it in. 
 - You will most probably also need git installed.

After that try to run meson and then ninja and hopefully it will work. If not ask here or on discord for help.

**Comment by Naphthalin** [comment]
@abdulbadii did you have any success with that build? Either way, it would be nice if you could document that in this issue.
