### ISSUE TITLE
Suggestion: GPL--> LGPL license for an engine

### ISSUE THREAD

**Issue by Technologov** [LeelaChessZero/lc0#664]
Else this engine would be forced out from commercial GUIs, like Chessmaster 9k, which is sad.
I think engine can stay free, but not force GUIs.

NOTE: it may be possible to merely 'invoke' the engine from commercial GUI (via UCI; preventing GPL), but this is possible only on the PC, while mobile platforms may need better integration for a single package to be installed and run as a single executable.

I suggest to change license of the chess engine from GPL to LGPL or BSD.

case-in-point: Stockfish was rejected from upcoming Geekbench 5 candidate list, due to GPL:
http://support.primatelabs.com/discussions/geekbench/16079-please-add-stockfish-chess-engine-as-a-new-benchmark-test

**Comment by Naphthalin** [comment]
I think this issue is resolved by releasing Android binaries #1095 per default, and doesn't need any license change.

**Comment by Technologov** [comment]
I Think a more liberal license is better (BSD or LGPL)

чт, 30 квіт. 2020, 17:19 користувач Naphthalin <notifications@github.com>
пише:

**Comment by mooskagh** [comment]
Changing license at this point is technically very hard (we need agreement of all contributors).
And I'm sure that many of them won't agree to relax the license (I heard suggestions to make it even stricter, aGPL, but it's similarly hard)

I'm closing this issue as not really actionable.
