### ISSUE TITLE
Make Lc0 a valuable sparring partner for human players.

### ISSUE THREAD

**Issue by Harumpel** [LeelaChessZero/lc0#666]
Lc0 extracts knowledge from games of self-play. After watching some games, this knowledge seems slightly different to classic human chess knowledge at times. Thus, Lc0 chess knowledge would be of great value for humans training chess. At least a great alternative to alpha-beta engines. 

Humans need a motivating way to play against Lc0. Some will be OK with playing sparring games against a full-strength-Lc0 engine. But some would like to play against a weakened version. The possibilities to weaken Lc0 would be as follows:

1. adjust temperature / temp value cutoff to randomize moves (UCI settings)
2. limit max nodes computed for one move, instant reply
3. slow down Lc0 engine execution speed so that some very low number of nodes per move is computed
4. use some older networks with diffused knowledge, but still full speed computation, high nodes count.

Please share your ideas about this, I will add and edit this issue.

**Comment by oscardssmith** [comment]
a 10b net at 1 or 2 nodes is a pretty good sparring partner for me. There also has been a patch to make leela aim for even positions which makes her blunder when up.

**Comment by borg323** [comment]
I have made a branch adding an extra option, `--move-delay-ratio` to specify a portion of the move time that lc0 will wait before starting the search. Setting this to 1 makes lc0 process only a single node, and 0.5 wastes half the search time. Test cuda binary: <https://ci.appveyor.com/api/buildjobs/hm1a1q0t6n9mu0eh/artifacts/build%2Flc0.exe>

Suggestions for better option names are welcome.

**Comment by Naphthalin** [comment]
This can probably be closed once #685 is merged.

**Comment by mooskagh** [comment]
Closing as #685 is there, and otherwise it's more like a vague idea rather than concrete feature.
