### ISSUE TITLE
Enforce standard ELO test for new releases

### ISSUE THREAD

**Issue by FinalCut64** [LeelaChessZero/lc0#667]
We should from now on include in every release script at least 2 tests (STC and LTC) against the previous version and only accept new releases that pass or have proven no regression. Even if the changes are only features or at first sight not performance related.
Given our current release rate (about 1 per month) this should be easy to accomplish.
This tests should be standarised in some way and give a good confidence on the results.
This way we can keep track of progress over time and also helps with the morale of the contributors, like every other top chess engine already does in each new release.

**Comment by Naphthalin** [comment]
These tests are actually done for each version, results can be viewed in #test-results on the discord [redirect.lczero.org/chat](redirect.lczero.org/chat). This issue can be closed.
