### ISSUE TITLE
Syzygy usage is unreliable

### ISSUE THREAD

**Issue by mbabigian** [LeelaChessZero/lc0#668]
My attempt to get Syzygy tablebases working seems to point to a bug.  Using lc0-v0.20.1-windows-cuda.zip  I configured lc0 with the following command line in Arena 3.5.1

-t 4 --syzygy-paths=S:\Syzygy\5All-6ManWDL;S:\Syzygy\7-Man-WDL;J:\Syzygy7WDL;J:\SyzygyDTZ --logfile=log.txt

During my first attempt analyzing, only 6 piece tablebases from the first path were being used.  Someone suggested that lc0 may be ignoring the rest of the locations, so I tried moving one of the 7 piece locations to the front and then no tablebase access occurred.  After many experiments, I configured just the 5/6man location "only" figuring it would resume accessing them; however, it will not.  I've completely closed the gui and restarted, but no tablebase access occurs with the following command line:

-t 4 --syzygy-paths=S:\Syzygy\5All-6ManWDL --logfile=log.txt

I have attached the log-single.txt file which shows it detecting the files before analysis begins.  In addition, I have attached log-multi.txt which shows lc0 detecting all the files when multiple locations are specified, and the file counts are correct in the log for all locations.  However, no tablebase file access occurs.  All tablebase files have been hashed and verified good.  The intermittent use of the files during analysis looks like a bug to me.

FYI
[log-single.txt](https://github.com/LeelaChessZero/lc0/files/2738898/log-single.txt)
[log-multi.txt](https://github.com/LeelaChessZero/lc0/files/2738902/log-multi.txt)

**Comment by Tilps** [comment]
Both of those logs show tablebases being used - you'll need to provide more details as to what you think the problem is.

**Comment by mbabigian** [comment]
Using resource manager I can see file use per program.  Setting up 8 piece positions with easy exchanges available will cause every program that I have including lc0 to start accessing the syzygy files.  The difference is, lc0 fails to access any 7 piece files more often than not and often even the 5/6 piece files do not show as being accessed.   I expect access to show every time I test such a position and that isn't happening.  At 6 to 20k nps, I'd expect to see constant file access.  Many times no access is detected whatsoever.  Resource manager shows no such behavior with other syzygy aware programs.  Since I've tested the syzygy setup this way for other programs, the behavior does not look correct.  Each position I've tested, simplifies into a 7 piece ending for which I have the files.  I tested SF on the same positions with consistent results (5,6 and 7 piece all get accessed). Perhaps it is just a display issue with Resource manager, but no such behavior has been noted with SF.

**Comment by Tilps** [comment]
If you are getting tbhits in the stats, the tablebase is being used.  If its not showing up in your resource manager, you probably have it misconfigured somehow - or something has cached everything magically and resource manager is only tracking fall through to disk.

**Comment by mbabigian** [comment]
The behavior is suspicious, but I'm not here to beg you to look into it. Only report it. I won't post further.

**Comment by oscardssmith** [comment]
Since this was never confirmed to be a bug, close?
