### ISSUE TITLE
OpenCL; mcts search freeze on AMD

### ISSUE THREAD

**Issue by TesseractA** [LeelaChessZero/lc0#669]
--Summary--
Hardware; AMD Radeon HD 6670 , Running on Windows 10 , Intel(R) Xeon(R) CPU, X5365 @ 3.00 GHz 2.99 GHz, installed memory 20.0 GB RAM 64-bit operating system x64-bit processor
Download; lc0-v0.20.1-windows-opencl
Problem; Lc0 never starts the search, or gets stuck before analyzing a position.
Independent variable; Lc0 test run number
Dependent variable in experimentation; Search working/not working past a certain point in the startup,
Procedure; 
1. I ran lc0 with test40 weights, and waited a while. 
2. Seeing it took far longer than I expected at a certain point, so I stopped it.
3. cd to the lc0 directory, ran lc0 with the option --logfile=log.txt
4. I downloaded all the networks one by one, renamed their files to their respective runs, and ran each.
5. Ran with T37, T30, T40, and T35. If one of them froze, I would wait a while to see whether it did anything.
6. I quit out of the ones that didn't run over the period of wait time.

Results; T30, T35 ran fine and searched for me the number of nodes I asked the program to give me.
T37 and T40 didn't run past a certain point, and that point happened to be the same for the both of them.

Here's a little bit of the logs that represents when the problem happened.
0108 18:31:13.435461 9996 c:\projects\lc0\src\neural\opencl\opencltuner.cc:466] Loaded existing SGEMM tuning for batch size 16.
0108 18:31:14.146079 9996 c:\projects\lc0\src\neural\opencl\opencl.cc:359] Wavefront/Warp size: 64

0108 18:31:14.146994 9996 c:\projects\lc0\src\neural\opencl\opencl.cc:364] Max workgroup size: 256
0108 18:31:14.148654 9996 c:\projects\lc0\src\neural\opencl\opencl.cc:367] Max workgroup dimensions: 256 256 256
0108 18:31:14.617273 9996 c:\projects\lc0\src\engine.cc:371] Limits: visits:10000 playouts:-1 depth:-1 infinite:0
0108 18:31:14.617896 280 c:\projects\lc0\src\mcts\search.cc:617] Start a watchdog thread.
0108 18:31:14.618239 2056 c:\projects\lc0\src\mcts\search.h:200] Started search thread.
0108 18:31:14.618485 1380 c:\projects\lc0\src\mcts\search.h:200] Started search thread.
0108 19:48:17.629239 9996 c:\projects\lc0\src\chess\uciloop.cc:131] >> quit
0108 19:48:17.629564 9996 c:\projects\lc0\src\mcts\search.cc:667] Aborting search, if it is still active.
0108 19:48:17.629608 280 c:\projects\lc0\src\mcts\search.cc:646] End a watchdog thread.

Possible causes; SE network architecture discontinuous with other code, OpenCL encoding issues, hardware incompatibilities, no exceptions for SE in the OpenCL architecture.

Attached are the tuning and the logs of the things I tried.
[leelaz_opencl_tuning.zip](https://github.com/LeelaChessZero/lc0/files/2739156/leelaz_opencl_tuning.zip)

[log.txt](https://github.com/LeelaChessZero/lc0/files/2739152/log.txt)

Thank you for your time.

**Comment by SunnyWar** [comment]
I believe AMD declared support for OpenCL 2.1 and we're currently using OpenCL 2.0. Not sure it's an issue put it makes me wonder if #655 would fix this.

**Comment by TesseractA** [comment]
Update; My lc0 is working and running just fine. I don't know whether my issue was fixed deliberately, but I am now able to run test40 networks. Thank you.

**Comment by TesseractA** [comment]
I've been too hasty. I downloaded the windows-blas version and test40 networks work (slowly, of course) on it. The OpenCL version does not start the search, which I need to run my GPU on. This is not as urgent an issue as it originally was since I am still able to run a network for low-node testing.
Nonetheless, I am reopening this issue.
Sorry for the confusion.

**Comment by TesseractA** [comment]
There's more unknowns here than is necessary to diagnose this issue. Leela runs fine on my CPU and I'm happy with that for now. I'll probably be getting a new graphics card by the time I actually need GPU time, so I'll close this issue.
