### ISSUE TITLE
Would like to submit files for openSUSE install

### ISSUE THREAD

**Issue by putztzu** [LeelaChessZero/lc0#670]
Looks like lc0 is blocking any Pull Requests from unauthorized users, so am not able to make a Pull Request directly.

Would like to submit the following files
https://github.com/putztzu/lc0/blob/master/openSUSE_install.md
https://github.com/putztzu/lc0/blob/master/install_openSUSE_lc0.sh

And,
Similar to the existing sections in the lc0 README.md providing instructions for installing on Ubuntu,
Recommend creating a link in the existing lc0 README.md to point to openSUSE_install.md

FYI - a RPM has also been created and is currently being tested for possible inclusion as an openSUSE package in an openSUSE repository.

**Comment by putztzu** [comment]
For those who are interested in trying the RPM, it is being built only for LEAP 15.0 and Tumbleweed on x64,

https://software.opensuse.org//download.html?project=home%3Amalcolmlewis%3ATESTING&package=lc0

All the RPM should do is provide the lc0 binary, 
You'll still need to add the networks file and do whatever is necessary to connect to a chessboard.

If interested, I'm sure if people want packages built for other distros (like Ubuntu, Fedora, etc), Malcolm can do that easily if asked... It's one of the benefits of packaging using the Open Build Service platform.

**Comment by borg323** [comment]
Since you could open this issue you should be able to make a new PR, so this seems a bit strange. Please try again, we prefer a PR for every contribution as it is easier for us and you get credited for your work. In the meantime, this looks like a perfect fit for the wiki.

**Comment by putztzu** [comment]
I figured it out. Typically when I do a Pull Request, I upload the files to my branch on a project which won't work for lc0. 

I see now that a Pull Request can compare a branch on a remote repository instead.
I'll make some additional changes to files before submitting a Pull Request for this in a day or two.
