### ISSUE TITLE
Lc0 : why play for a Mate if i can get a extra 50moves?!

### ISSUE THREAD

**Issue by Ipmanchess** [LeelaChessZero/lc0#688]
Lc0 will get more strenght when this issue is fixed!
Like many other people see that Lc0 can shuffle around with her pieces for nothing.

In a clearly winning game even with a eval from above +50 can ends in a draw..why?
- She knows how to Mate a opponent but choose first for the extra 50moves she get (50-moves rule)
- No setting change this behavor
- No Time Control change this.. long,short..TC with or without increments doesn't help..
- Tablebase adjudication doesn't change it..it just replace the issue before this adjudiction.
- It shows clearly when you test with Sudden Death games!

What Lc0 do now:

When she overplay her opponent with clearly advantage in eval..even when Stockfish 10 already see a mate score she will Not play for a Mate position but wants to move a pawn,exchange a piece when 50moves rule reached..the pawns wait on 7th row till she has to promote them..can also happen by exchange a piece before the 50move rule.. when a pawn or pawns get promoted she will shuffle around with them.. have seen 3 queens..shuffle around and then to give them away one by one..till one left..again shuffle around till she see ,ohh i'm almost on the end off my last 50moves ,i need my Kings help to Mate opponent.. this can be with a rook or knight promote with same behavor.

What do people see..ohh it ends in a draw ,or even lost the game by a blunder.. why..she has gives to many pieces away and miss a needed piece to win the game and has too less time left.

The winning games who ends draw are just because she shuffle around with a piece..thinks i have 50moves..i have still pawns to promote so why hurry..till she see i have too less time left ,no time anymore to promote a other pawn and make repetition moves to draw a winning game?

I have suggest a few times on Discord.. make a compile with a 50-moves setting true/false ,is a very easy way to check my findings!

Play sudden death games..so that she has no extra time left and has to finish the game..follow these games and you will see what i mean!

When this behaver (condition/rule) is fixed then she will handle any Time Control and will play out the game in the right way!

Lc0 will get more points = more strenght and Elo!!

Till then i can't enter Lc0 into my lists.. i run a Championship with Lc0 v20.1 cuda ID32579 -t 3 on a RTX2080 vs Stockfish 10 18cores @4.2Ghz on a i9 7980XE with TC: 5m+5s ,100games and she won with : 51 -49 !

So means i have a new Champion.. No as she can't handle other TC's because this behavor..it's when she get enough increments like this +5s she has time enough to finish these games even with the extra 50 shuffle moves she get!

With Stockfish ,Houdini & Komodo i has also been busy to tune Time Managements and these engines can handle almost any TC and the number 1 wins on any cpu with any TC i'm using..i see Stockfish 10 on a i3 ,i7 & i9 with using different cores ,using TC's 10s+1 ,1m+5s ,3m+3s ,4m+0s and 5m+5s as best engine (now ofcourse new dev's) so it doesn't matter..

Lc0 will do this when issue above is fixed!!

You can train 100 or 1000 nets as long this behavor/condition/rule is not fixed she's losing strenght! even she get stronger..

So in real when fixed ,Lco is stronger then most people thinks!

Hope programmers will look into it! Good luck further with this fantastic project!!

My tests can be followed via my spreadsheet : https://docs.google.com/spreadsheets/d/11vXZe4Dm7nIXWIYD9EoZguR4xOuRWUQHpzSfQW2HaMo/edit#gid=1168769812

Kind regards,
Ipman.

**Comment by Videodr0me** [comment]
Try this version with Certainty Propagation enabled: https://ci.appveyor.com/project/LeelaChessZero/lc0/builds/21908253/job/92pkh2tvbq9ffihg/artifacts

Or the stronger version with look-ahead here, but you might need to increase threads to ( 2 * no. of gpus) +1: https://ci.appveyor.com/project/LeelaChessZero/lc0/builds/21916156/job/851awkkkw5etj92n/artifacts

both are the cuda versions, but others are available too. CP should greatly help to fix this.

**Comment by Ipmanchess** [comment]
Thank you very much!

I will try them out and let you know..

Okay i had yesterday already tried PR700 but i didn't see any Mate value..but this was with 6men syzygy tablebase adjudication..maybe have to try without it..

With my RTX 2080 i use -t 3

**Comment by Ipmanchess** [comment]
About 1 month later i still get same behavior as above..
Tried different PR's last one i'm using PR487 with CP from videodr0me
After many tests i know it cover up these problems when using enough time increments +5sec.
It prevent losing points..but it's ofcourse not the way it should work as it can't play any TC yet!

So i'm using 1m+5s and can show again a nice example how Lc0 act in endgames!

https://lichess.org/i0Cxcq3y
and pgn notition: https://pastebin.com/DAtYU5dR

This really needs a fix!
I know you do all fantastic work on Lc0 ,have a lot idea's to try out..but this is Basic..Lc0 need first to know how to end a game right!

Ipman.

**Comment by MelleKoning** [comment]
You can now try reducing the 50 move rule with #861 which enables shortening the draw-rule from 100 ply. Having the sticky-endgames in the engine ensures the search will go for less trolling -given it sees a more advantage line-

**Comment by Naphthalin** [comment]
#961, #1110 and #1175 are merged; MLH should solve this issue, so it can be closed.
