### ISSUE TITLE
Leela will draw some easy won endgames on slow hardware despite using TB

### ISSUE THREAD

**Issue by gsobala** [LeelaChessZero/lc0#695]
Apologies for yet another very similar endgame issue, as this is related to trolling but more serious. On slow hardware, Leela's search horizon can be very short and it does not extend to the 50-move draw limit. In an endgame defined by tablebases, she will choose between winning moves, but without regard to the time to mate. Specifically the syzygy DTZ tablebases are not used. Usually she will sort things out when the 50 move draw limit approaches and enters her horizon, but on slow hardware she may already have committed to a winning line that takes too long and without a shorter alternative. Outcome = draw. She can even throw KQvK endgames like this.

**Comment by killerducky** [comment]
Can you post a logfile with an example? Or at least a pgn file?

**Comment by gsobala** [comment]
I withdraw this. It seems the example I was shown was due to a GUI bug rather than Leela. In fact, testing shows that a tablebase-equipped Leela can consistently find long mates within the 50-move rule even with nodes=1 and backend=random.
