### ISSUE TITLE
Uncaught exceptions on Windows aren't printed to stderr

### ISSUE THREAD

**Issue by cn4750** [LeelaChessZero/lc0#704]
It appears that the expected behavior for uncaught exceptions on Linux of printing to stderr does not happen on Windows without [additional configuration](https://docs.microsoft.com/en-us/cpp/cpp/unhandled-cpp-exceptions?view=vs-2017).

**Comment by borg323** [comment]
Fixing this will also allows us to remove some messy code in the client (used in the cudnn-fp16 backend detection).
