### ISSUE TITLE
Uses of exit instead of Exception

### ISSUE THREAD

**Issue by cn4750** [LeelaChessZero/lc0#706]
The following code uses `exit` instead of the more flexible [Exception](https://github.com/LeelaChessZero/lc0/blob/407be4d0bd480cb1a56e8bd86dcc3d5d8d58c6e7/src/utils/exception.h#L36):

1. [syzygy.cc#L1049](https://github.com/LeelaChessZero/lc0/blob/master/src/syzygy/syzygy.cc#L1049)
2. [syzygy.cc#L1063](https://github.com/LeelaChessZero/lc0/blob/master/src/syzygy/syzygy.cc#L1063)
3. [syzygy.cc#L1070](https://github.com/LeelaChessZero/lc0/blob/master/src/syzygy/syzygy.cc#L1070)

**Comment by Naphthalin** [comment]
This still applies, right? If yes, a PR should be created, if not, we can close this issue.

**Comment by mooskagh** [comment]
Fixed by #1343
