### ISSUE TITLE
Problems in startup-script of  the Google Cloud guide wiki page

### ISSUE THREAD

**Issue by Vorsokratiker** [LeelaChessZero/lc0#715]
Hi,

when trying to use the script from the Google Cloud howto wiki as is I faced following problems:

1. The script tries to install nvidia drivers and xorg, and asks interactively for a keyboard layout setting => if you run the script the first time on a VM instance the script stucks at this point.
2. The script tries to compile lc0 using clang, however only g++ is installed as a prerequisite using apt-get => fails to compile lc0
3. The script uses git to clone and check-out lc0 from github, however git is not installed before hand => script fails to checkout.

Now I was not sure if I should just change the wiki and correct the script, or just post an issue (maybe I missed something).

Any ideas on this?

Thanks,
Steve

**Comment by careless25** [comment]
Hey, sorry that no one got back to you.
I think you selected the wrong image on Google cloud. You need to select the tensorflow image and then run the script. 

Also I have an updated version of this script: 
```
echo "Install Driver if needed"
[ -f /opt/deeplearning/install-driver.sh ] && sudo /opt/deeplearning/install-driver.sh

echo "Installing dependencies"
apt-get install -y ninja-build libprotobuf-dev protobuf-compiler python3-pip clang-6.0
rm -rf lc0 

echo "Installing lc0"
git clone --recurse-submodules https://github.com/LeelaChessZero/lc0.git
cd lc0 && git checkout $(git tag --list |grep -v rc |tail -1)
pip3 install meson
CC=clang-6.0 CXX=clang++-6.0 ./build.sh
mv ./build/release/lc0 lc0

echo "Downloading lczero client"
curl -s -L https://github.com/LeelaChessZero/lczero-client/releases/latest | egrep -o '/LeelaChessZero/lczero-client/releases/download/.*/client_linux' | head -n 1 | wget --base=https://github.com/ -i - -O client_linux && chmod +x client_linux

echo "Running Leela Chess Zero"
./client_linux --user googlecloud --password googlecloud
```

**Comment by Naphthalin** [comment]
As this issue seems to simply have been caused by using an outdated script, this can probably be closed.
