### ISSUE TITLE
T50 should have a bigger net 40 x 512

### ISSUE THREAD

**Issue by superbnet** [LeelaChessZero/lc0#723]
Then it will see much more 1-10 moves tactics.

**Comment by TesseractA** [comment]
Not sure this is the appropriate place to discuss this. I do agree that we should be trying slightly larger networks, but far from point. Leela discord is an appropriate place to communicate concerns like this.

**Comment by mooskagh** [comment]
Yeah, ideas of having larger networks are kept in mind, but for now there are still ideas to try with the current network size.
Closing that for now.
