### ISSUE TITLE
Compilation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by navdeeprana** [LeelaChessZero/lc0#726]
`CC=clang-6.0 CXX=clang++-6.0 ./build.sh`
fails on Ubuntu-18.04 with the following error:
`c++: error: unrecognized command line option ‘-std=c++14’`

Also native c++ compiler is getting picked up for some reasons.
`Native C++ compiler: c++ (gcc 4.8.5 "c++ (Ubuntu 4.8.5-4ubuntu8) 4.8.5")`

Does anyone knows a workaround?

**Comment by ddobbelaere** [comment]
I'm guessing you have to remove the build directory first, it's probably using cached compiler options. So just try `rm -rf build` before `CC=clang-6.0 CXX=clang++-6.0 ./build.sh`.

**Comment by navdeeprana** [comment]
> I'm guessing you have to remove the build directory first, it's probably using cached configure options. So just try `rm -rf build` before `CC=clang-6.0 CXX=clang++-6.0 ./build.sh`

This works, but then the compiling stops at nvcc with the error
`nvcc fatal   : Value 'compute_70' is not defined for option 'gpu-architecture'`
Any ideas?

**Comment by navdeeprana** [comment]
Update:
The errors were due to older Cuda versions. Compiles without issues with Cuda 10 and clang-6.0 with latest nvidia drivers.
