### ISSUE TITLE
Bootstraps or building NNs: gradual feeding or all at once?

### ISSUE THREAD

**Issue by ASilver** [LeelaChessZero/lc0#73]
I had a test to suggest, which I think might be very important for any future bootstraps and increase in net size. My question is this:

Suppose I have 1 million games. Is it better to feed the NN  with all 1 million at once and then just adjust LR when needed? 

OR

Is it better to split those million into 10 blocks of increasing strength, and train the NN on each block exclusively and successively?

Leela Zero works with gradual increases, we know. And all bootstraps, as far as I know, work by feeding all the games at once. I have not seen anyone tell me, or even know, whether this might not make a profound difference.

**Consider this after all:** The games are not of uniform strength. There are the near random ones from the beginning, and the advanced ones much much later. **By mixing them all the entire way, you are feeding the NN, even when it is mature, with near random games still.** To my mind there is just no way that can be ideal.

Therefore my test is this: take that second test run that has already started at 10x128, and all the games that led to it, but rebuild the 10x128 bootstrap by feeding the games gradually, not all at once. See if the end result is the same strength (or similar) or it is stronger.

If feeding gradually has a strong impact on strength in a positive sense, this might be an important guide towards bootstraps in general.

**Comment by killerducky** [comment]
Here is how @bjiyxo did his LZGo bootstrap. https://github.com/gcp/leela-zero/issues/1113#issuecomment-376587776

You can see from the table "Training Weight Files Number" that he shifted the window not smoothly but in large steps (I guess just a practical decision). You have to cross reference http://zero.sjeng.org/ to see how many games each ID played. e.g. he started with ID78-82. ID78 played 84K games. Add them to find total games in his window.

In the MSE graph you can see it goes up when he did a large window shift, then continues going down slowly. Also looks like the test/train separating for MSE is large and noisy when LR is large. And the gap narrows when LR is dropped.

**Comment by mooskagh** [comment]
Doesn't seem that that issue describes bug or enhancement, closing.
