### ISSUE TITLE
File is not compatible with the version of Windows you're running

### ISSUE THREAD

**Issue by HolgerCB** [LeelaChessZero/lc0#732]
When trying to run lc0.exe for the first time, I get:
File is not compatible with the version of Windows you're running.
Die Version dieser Datei ist nicht mit der ausgeführten Windows-Version kompatibel.

Usually, I get this when I try to run a 64bit-Programm on my 32bit-System. But there is no information anywhere that lc0.exe is 64bit.
What it the problem?

**Comment by oscardssmith** [comment]
question: how do you have a 32 bit system? Also lc0 comes in both 32 and 64 bit versions.

**Comment by HolgerCB** [comment]
32 bit system: I am programming with an old 16 bit environment. Yes, sometime I will change to the 32 bit successor, but 10.000 lines are a lot to convert. And yes, my system is running smoothly on nearly everything (Win7 32 Q9550), but starting a virtual pc on this system takes to much time for me. On a new powerhouse PC with 16 GB RAM and a SSD this will be no problem (5-10 seconds?), but that will be in the future.

On the Leela releases side (https://github.com/LeelaChessZero/lc0/releases), I did not found any information about the download being for 64 or 32 bit, so I did of course not found any 32 bit files. In any of the zip-files, there is only one lc0.

**Comment by borg323** [comment]
There is no official 32 bit release, but the code supports it. I make 32 bit windows binaries now and then, here is the 32 bit blas version (for cpu only): https://ci.appveyor.com/api/buildjobs/s2dgcounvahri0ef/artifacts/lc0-win32-blas.zip
There is also an opencl version for gpu, but you'll probably need to replace the packaged dlls to make it work.

**Comment by HolgerCB** [comment]
Thank you for the 32bit-version. It works.

**Comment by mooskagh** [comment]
I'm closing this issue as it seems to be resolved. Feel free to reopen if you think it needs further attention.
