### ISSUE TITLE
Leela just exits when running out of virtual memory.

### ISSUE THREAD

**Issue by Videodr0me** [LeelaChessZero/lc0#740]
If leela (on windows) runs out of memory (including virtual memory) it just exits (might also raise an exception, did not check). To reproduce set page-file size in windows to fixed and analyze a position with "go infinite".

Leela generally handles searching on virtual memory (if ram is exhausted) on SSD pretty well. With a GPU like a 1080ti speed decreases but only by about 30% (depending on position, speed of SSD etc.). 

One can limit memory leela is allowed to use, but that might be subject to other processes running and might flucutate. Maybe its better for leela to instead just play the best move if (normal + virtual) memory  is exhausted or stop infinite mode.

**Comment by mooskagh** [comment]
There's no way to check remaining available memory in modern OSes.
When memory is exhausted, `new` operator will throw an exception. This can happen anywhere (e.g. outputting string, creating vector to build PV for output etc all allocate memory).

It's very hard to fail gracefully in this case (and most of software just ignores this case).

And it's next to impossible to actually recover "correctly" from this situation. [ Search tree may be in inconsistent state (e.g. if it's memory failure when allocating new node/edge, exception is thrown, but the tree is itself already altered, e.g. `n_in_flight_` is incremented).]
But even if we could stop if gracefully, without available memory we won't be able to allocate temporary buffers for outputting `uci` response etc.

Furthermore, modern OSes do memory overcommiting. As it's known that software usually uses only ~70% of memory it allocates, usually OS allows to allocate more memory than it's available (but keeps memory pages unused). When software finally starts to use that memory (and there's no free pages in physical memory+swap), usually OS just terminates the process.
For C++ code it means that `new` won't even throw an exception, it will succeed, but the process will be killed when it tries to use it.

So this feature is very far from being feasible to implement.

**Comment by Videodr0me** [comment]
It doesn't have to be exact. In windows something like GlobalMemoryStatusEx could be used (maybe sysconf in Linux) to get a rough ballpark figure. I agree that its messy, and this issue serves more to document this behaviour than to motivate a quick-fix.  It just came up when I noticed it in a long analysis (the position where leela failed to convert a winning ending in TCEC). Some sort of  failsafe to prevent losses in TCEC or CCCC due to memory overlow would be nice, but i agree its not easy to do accurately.

**Comment by killerducky** [comment]
See also similar issue #801 were we aim to have the user tell Lc0 how much RAM to use (instead of Lc0 asking OS how much RAM is available).

**Comment by Naphthalin** [comment]
Is this still an issue, or does the search simply stop now when reaching the RAM limit?
