### ISSUE TITLE
Move count plane

### ISSUE THREAD

**Issue by bojosos** [LeelaChessZero/lc0#751]
Why is the move count plane empty? There is only this comment there and there has never been any code added that actually populates the 6th pane.

` // Plane kAuxPlaneBase + 6 used to be movecount plane, now it's all zeros.`

**Comment by mooskagh** [comment]
It was tested in ~May that it doesn't improve strength so it was removed back then.
(and also it had some bugs back then, e.g. for move 256 it was populated as 0 or something like that, so it was easier to stop populating it).

I'm closing this issue. Feel free to reopen if you think it needs further attention.
