### ISSUE TITLE
Take reused nodes into account when budgeting time.

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#753]
Currently we budget move time for Leela to think.
However, (I think) we really want to aim for particular number of nodes at the moment of making the move. 
Particularly, if tree was mostly reused, we need to think less, and if no tree was reused, we need to think more.

A particualr case of this issue is first move (where no tree is usually reused). There is a PR which tries to solve this for the first move https://github.com/LeelaChessZero/lc0/pull/645, but I really think it should be solved in more generic way.

Particualry, totally unexpected move (no tree reuse) should trigger the same behaviour as first move, and partially unexpected move should also increase thinking time.

**Comment by mooskagh** [comment]
Actually, probably idea of "budgeting nodes not time" is not entierly correct.
It can be either nodes or time, but it should take reused nodes (or reused time, e.g. reused nodes from last move converted back to seconds) into account.

**Comment by Naphthalin** [comment]
Sounds like this was implemented with #1195, so issue can probably be closed.
