### ISSUE TITLE
[Compiling Problem] Lc0 Build Fails on vast.ai Cloud Computer

### ISSUE THREAD

**Issue by Technologov** [LeelaChessZero/lc0#770]
vastai/tensorflow image.

echo "Install Driver if needed"
[ -f /opt/deeplearning/install-driver.sh ] && sudo /opt/deeplearning/install-driver.sh

echo "Installing dependencies"
apt-get install -y ninja-build libprotobuf-dev protobuf-compiler python3-pip clang-6.0
rm -rf lc0 
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
dpkg-reconfigure locales

echo "Installing lc0"
git clone --recurse-submodules https://github.com/LeelaChessZero/lc0.git
cd lc0 && git checkout $(git tag --list |grep -v rc |tail -1)
pip3 install meson
CC=clang-6.0 CXX=clang++-6.0 ./build.sh
mv ./build/release/lc0 lc0

echo "Downloading lczero client"
curl -s -L https://github.com/LeelaChessZero/lczero-client/releases/latest | egrep -o '/LeelaChessZero/lczero-client/releases/download/.*/client_linux' | head -n 1 | wget --base=https://github.com/ -i - -O client_linux && chmod +x client_linux

echo "Running Leela Chess Zero"
./client_linux --user googlecloud --password googlecloud

=================================================================
But compilation Fails !!!

root@C.232543:~/lc0$ ./build.sh
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = "en_US.UTF-8",
        LC_CTYPE = "en_US.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Error during basic setup:

[Errno 2] No such file or directory: '/root/lc0/build/release'

Then I did:
export LC_ALL="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
dpkg-reconfigure locales

root@C.232555:~/lc0$ ./build.sh 
Error during basic setup:

[Errno 2] No such file or directory: '/root/lc0/build/release'
root@C.232555:~/lc0$ mkdir -p /root/lc0/build/release
root@C.232555:~/lc0$ ./build.sh 
The Meson build system
Version: 0.29.0
Source dir: /root/lc0
Build dir: /root/lc0/build/release
Build type: native build

Meson encountered an error in file meson_options.txt, line 1, column 0:
Unknown type array.

....
That's it.
Any ideas ?

https://vast.ai/

**Comment by careless25** [comment]
This happens because the default python is python2.7 and not python3 which has an old version of meson.

**Comment by Technologov** [comment]
The build script must detect version of Meson and version of Python and fail gracefully, explaining which versions were expected. Instead of throwing random messages like 
"Error during basic setup" or "Unknown type array." which doesn't help user.

**Comment by Technologov** [comment]
Two more commands are required to force Leela to use python 3 on Vast.AI docker images:
#
echo
pip3 install --upgrade pip
echo
pip3 install --upgrade meson

**Comment by careless25** [comment]
^^ The above comment only applies when you install python2.7 on the instance. Otherwise it will work.

**Comment by InnovativeInventor** [comment]
This fix works for me!

**Comment by mooskagh** [comment]
Not sure if something else is still needed, feel free to reopen if it does.

**Comment by Technologov** [comment]
it is needed. How to reopen ?

**Comment by mooskagh** [comment]
Where did you get that script from?
I'm not sure who maintains it, it's not part of the Lc0 repo.

**Comment by careless25** [comment]
That script is from me and its pinned in the general channel on Discord

**Comment by TesseractA** [comment]
Has this been fixed?

**Comment by ShailChoksi** [comment]
```echo "Install Driver if needed"
[ -f /opt/deeplearning/install-driver.sh ] && sudo /opt/deeplearning/install-driver.sh

echo "Installing dependencies"
apt-get update
apt-get install -y python3-pip clang-6.0
rm -rf lc0 

echo "Installing lc0"
git clone --recurse-submodules https://github.com/LeelaChessZero/lc0.git
cd lc0 && git checkout $(git tag --list |grep -v rc |tail -1)
pip3 install --upgrade pip
pip3 install meson ninja
CC=clang-6.0 CXX=clang++-6.0 ./build.sh
mv ./build/release/lc0 lc0

echo "Downloading lczero client"
curl -s -L https://github.com/LeelaChessZero/lczero-client/releases/latest | egrep -o '/LeelaChessZero/lczero-client/releases/download/.*/client_linux' | head -n 1 | wget --base=https://github.com/ -i - -O client_linux && chmod +x client_linux

echo "Running Leela Chess Zero"
nohup ./client_linux --gpu 0 --user blah --password blah > lc0_1.log &
```

This is what I use now @TesseractA

**Comment by Naphthalin** [comment]
@Technologov if possible can you check whether this works for you?

**Comment by Technologov** [comment]
I had a lot of problems building on Vast.AI, because by default it uses
Ubuntu 16.04 docker. (but it's much easier with Ubuntu 18.04 docker images
- so now I use those images ; additional pain is that dockers environment
is just different from a physical Ubuntu server and I had to put a lot of
customization and jump through hoops to make it compile...). Definitely not
a simple build.

чт, 30 квіт. 2020, 18:04 користувач Naphthalin <notifications@github.com>
пише:

**Comment by ShailChoksi** [comment]
@Technologov I use the 
vastai/tensorflow docker image on vast.ai and the script i posted above works with it. 

I have setup both Ubuntu 16 and 18 before so if you have a specific error with those - can you post it here?

**Comment by mooskagh** [comment]
I believe the intended way to "fix" this is to wait when vast.ai has modern enough setups so that meson version there is fresh enough.

Given that nothing is expected from our side, closing this issue.
