### ISSUE TITLE
Noise doesn't work with tree reuse

### ISSUE THREAD

**Issue by Ttl** [LeelaChessZero/lc0#775]
Originally reported by aart on discord a while ago. It seems that when root node is made from tree reuse dirichlet noise is not applied.

Works if  `TrimTreeAtHead` is called. Self-play calls it so this doesn't apply to training.

Logs: https://pastebin.com/hC7KBc7u

The first move has noised policy as it's not generated by tree-reuse, but the second move has identical policy with and without noise.

**Comment by Mardak** [comment]
If this issue becomes more general to fix up tree-reuse issues, a separate thing to address is from https://github.com/LeelaChessZero/lc0/pull/822#issuecomment-484213160 where a move reusing trees with a terminal child could make the new head terminal and prevent its children from getting visits.

**Comment by Naphthalin** [comment]
The question probably is whether there is any use case for tree reuse + dirichlet noise at the same time where NN cache can't replace the tree reuse; as we use noise only in training afaik, this doesn't seem to be the case (?)

**Comment by mooskagh** [comment]
Probably it's a good idea to throw and error in this case (dirichlet noise + tree reuse), but it's not clear whether it's actually a good idea.
In any case, I think it makes sense to close this issue as unfeasible.
