### ISSUE TITLE
Class Boardsquare wrong squarenumbers in comment  / Fen parser accepts illegal moves

### ISSUE THREAD

**Issue by Videodr0me** [LeelaChessZero/lc0#78]
Hi, when debugging some search mods and looking at the node structures and the moves, I noticed that this comment below is plain wrong: 

```c++
class BoardSquare {
 public:
  constexpr BoardSquare() {}
  // As a single number, 0 to 63, bottom to top, left to right.
// 0 is a1, 8 is b1, 63 is h7.
```
actually 1 is b1 and 63 is h8. 55 would be h7 

Also the fen parser does accept illegal moves:
```
position fen 6Q1/8/8/7k/8/8/3p1pp1/3Kbrrb w - - 0 1 g8g7 h5h4 g7g6 h5h3
````
but maybe its normal as stockfish also accepts this.

**Comment by mooskagh** [comment]
Comment is fixed, illegal moves in fen is not really a problem (sf accepts those too).
Closing!
