### ISSUE TITLE
Leela can't find a better move EDIT : You forgot a dot in default cpuctbase

### ISSUE THREAD

**Issue by zeFresk** [LeelaChessZero/lc0#789]
Hello.

**EDIT :** **_I found the reason of the bug !
The new default cpuct in v0.21 is way too high ! I think someone forgot a dot there.
By reversing it to a more normal value (1.9xxx) Leela finds the move instantly !
This the latest version, downloaded today, I just reset the parameters to their default values in Arena._**

I was studying the Smith-Morra gambit and ended up with this position [2rq1b1r/1b1pkp2/p1n1pN1p/1p2Pn2/6p1/1B4B1/PP2QPPP/3RR1K1 b - - 5 18]
![position_smith_morra](https://user-images.githubusercontent.com/8807862/54053577-f5e22480-41e7-11e9-872b-41f4e90270c7.PNG)
Where Leela thinks h5 is the only best move by far, with a little -2 at first, going up to -7 at 1M+ nodes.

I was watching this position and thought "But what about Bg7 ?", I played it seeing no obvious tactics and BOOOM, -5.6 (at 1k node) ! I beat Leela and she agreed with me !

Strangely SF finds it in less than 5 seconds whereas it doesn't appear on top 8 best moves from Leela, even after 2M nodes.

Maybe h5 is indeed the best move, but I think it is strange for Leela to miss such a simple move.

Here is my config : 
![lc0_config_bug](https://user-images.githubusercontent.com/8807862/54053937-28d8e800-41e9-11e9-8b82-9c83c49ba372.PNG)
Net is 32930.

**_EDIT :_** 
![cpuct_bug](https://user-images.githubusercontent.com/8807862/54054777-69d1fc00-41eb-11e9-8295-44630a29dd26.png)
_I have to restart everything from scratch :'(_

**Comment by mooskagh** [comment]
19652 is correct value for CPuctBase.
What you usually want to adjust is CPuct.

**Comment by zeFresk** [comment]
Yes someone told me in Discord later, that's why I closed this issue.
I'm sorry for bothering you :(

But isn't it kind of strange for Leela to be 100% oblivious to a move, even if she acknowledges it as better when it is shown to her ?
