### ISSUE TITLE
"Exact-Win Strategy for Overcoming AlphaZero" 

### ISSUE THREAD

**Issue by xcombelle** [LeelaChessZero/lc0#799]
I would like to point the paper quoted in this leela go zero issue https://github.com/leela-zero/leela-zero/issues/2276 

https://www.researchgate.net/publication/331216459_Exact-Win_Strategy_for_Overcoming_AlphaZero

The improvement consist in using proven values which appears during exploration of tree search instead of estimation given by ucb formula.

It shows significant improvements in the playing of three games tested (tic tac toe, connect 4 and go) comparing to the mcts version. Especially it outperforms leela go zero by +61-39=0.

I believe it should give even better in leela chess zero than in the go version.

First the game tree is smaller in chess than in go leading to the fact that proven position are more frequent.

Second it could make direct use of endgame table bases instead of the "hack" actually done to use them. The fact that there is endgame database is also a reason why the chess result should be better than go one by reducing size of tree search.

The author conclude the paper by saying they expect the training phase to be improved too by giving more accurates values as evaluation of the result of the games to the neural networks but they could not test it because of lack of hardpower of deepmind or leelas. I believe this guess can be trust to some extend.

I'm a programmer myself, but my c++ skills are not that good, I did just few tries to make go or chess engine, I don't know the lc0 code base. As such I propose that someone else implement the paper idea. If nobody does it, I will probably try but with a greater expected probability to fail because of my lack of skill.

**Comment by oscardssmith** [comment]
@xcombelle do you have a copy of the source? From the abstract, this looks very similar to certainty propagation. https://github.com/LeelaChessZero/lc0/pull/700 Are there differences?

**Comment by xcombelle** [comment]
As far as I understand it is exactly same idea. I am not 100% sure though because after reading the pull request I have not a cristal clear vision of what does certainty propagation. One can, to double check my opinion, look either on the leela go zero github issue which has some of the relevant parts of the paper or into sci-hub to have full paper.

**Comment by xcombelle** [comment]
After reading 

https://github.com/LeelaChessZero/lc0/issues/263

And

https://github.com/Videodr0me/leela-chess-experimental/wiki/MCTS-Solver---Certainty-Propagation-and-Autoextending

I can confirm it is exactly same idea.

**Comment by mooskagh** [comment]
If someone is looking for a full version of the paper, and not aware of sci-hub,
sci-hub.tw is DOI to PDF converter. :)
