### ISSUE TITLE
Improve RAM limit

### ISSUE THREAD

**Issue by killerducky** [LeelaChessZero/lc0#801]
We need a solution for this before TCEC sufi. Previous sufi we had some problems with several insta-moves in a row due to using up all RAM and swapping. Right now RAM limit estimates based on nodes, which is really all playout types including terminals etc that do not actually increase RAM usage. 

Choices:
1) Count real nodes/edges before you start to think: https://github.com/LeelaChessZero/lc0/pull/776 -- But this takes ~2.6s for ~16M nodes.
2) Increment/decrement a counter when constructing/destructing edges/nodes. But nodes are not destructed until 100ms after we start to think. Maybe we could special case when we are out of RAM to not wait 100ms? 
3) Stick with estimate and accept we will stop early in cases with many terminals? Some weird hybrid that adjusts the estimate live based on how many terminals we are hitting?

Right now I'm thinking 2) with some special case code to wait for garbage collection to make progress when search begins already out of RAM.

**Comment by mooskagh** [comment]
For me just option 3 sounds fine.
Are there examples when we have lots of terminal hits, but it's still useful to think further?
I think it's usually clear which move is the best in such situations..

**Comment by killerducky** [comment]
I did a little more testing. I set: RamLimit 500 -- estimated 2.188M nodes

I tested startpos, and an endgame position:
```
startpos + random backend: 2.4M nodes
7man endgame position from TCEC (that we could not win) + 32930: 3.47M
Same but with 6man TBs: 3.48M
```

For pure node+edge calculation we are conservative by 10%. For endgame position we are conservative by 60%. These seem reasonable to me.

But a problem is the actual memory used according to Ubuntu system monitor: is 1.3GB larger than whatever RamLimit you set. For short term we can just know this and account for 1.3GB overhead. Long term we can try to find if that is constant or depends on something like backend and account for it in RamLimit calculations.

**Comment by killerducky** [comment]
For TCEC, they have 16GB of RAM - 1.3GB overhead = RamLimit 14700
`RAM limit 14700MB. Cache takes 6240MB. Remaining memory is enough for approximately 42300000 nodes.` 
42.3M nodes, a little on the low side.

If Allie makes it to DivP, we will have to lower NNCache because otherwise: 8GB of RAM - 1.3GB overhead = RamLimit 6700:
`RAM limit 6700MB. Cache takes 6240MB. Remaining memory is enough for approximately 2300000 nodes.`
2.3M nodes, far too low.

**Comment by mooskagh** [comment]
Did you look into virtual memory usage or resident?

Note that amount of virtual memory allocated for a process is usually larger than a process actually uses (there are pages which are not ever accessed and for them neither physical nor swap memory is allocated).

It's a question whether we should include shared memory there (cudnn libraries will go there for example), but I'd say we should not include entire virtual image size as it's not the memory that we actually use.

**Comment by killerducky** [comment]
I switched to using Top. Looks like resident memory usage is higher than what I reported before with Resource Manager GUI I was using.

Top after running just 1 node search:
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                              
11445 aolsen    20   0 8103556 1.782g 288836 S   0.0 11.4   0:02.04 lc0                                                                                                                  
```

After hitting RamLimit 6700 (-NNCache 6240MB = 480MB = 2.3M nodes, actual search 2.13M nodes)
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                              
11445 aolsen    20   0 9021060 2.698g 298684 S   0.0 17.3   1:49.53 lc0                                                                                                                  
```

**Comment by killerducky** [comment]
I switched to random backend so I can test faster, set NNCacheSize=0 since random doesn't use it, and set RamLimit=6700 = ~33.5M nodes. I ran two lc0 copies, let one search until it hit RamLimit. Then let the other start searching. Since I have some other programs open, I ran out of RAM when the second search reached ~33M nodes. System slowed, swap started getting used. NPS went from 284K to 192K. I stopped it before it got worse and crashed my machine.

**Comment by killerducky** [comment]
Bonus game Allie vs Lc0: https://cd.tcecbeta.club/archive.html?season=15&div=bonus_div4vsdivp&game=251

Suspicious sequence for Lc0, maybe ran out of ram at move 19 and spent the next several moves swapping.
```
 move      speed   movetime  nodes
19...Bxe3  55knps    0:48   18.4M
           35knps    0:00   18.0M
           11knps    0:00   17.3M
            6knps    0:00   17.2M
            0knps    0:11   13.3M
            1knps    0:02    2.6M
           50knps    8:57   26.9M
```

**Comment by mooskagh** [comment]
Yes, this pattern is really similar to what we saw after long thoughts at TCEC.
Anothough there it happened at ~60Mnodes, not at 18M.

**Comment by killerducky** [comment]
I chatted with Aloril on TCEC. He is aware of the RAM issue and noticed the problems in the Allie vs Lc0 test match. He says if they cannot upgrade GPU server RAM they can run Lc0 vs Allie games with different settings than Lc0 vs CPU server engine games.

**Comment by killerducky** [comment]
I ran a test on my Windows box where I measured the actual RAM used (instead of what the code calculates it should be based on nodes/edges):

nodes | Commit | WS
-- | -- | --
1 | 2.4 | 1.4
100,000 | 2.5 | 1.4
1,000,000 | 2.8 | 1.7
5,000,000 | 3.8 | 2.6
10,000,000 | 5.0 | 3.9
20,000,000 | 7.7 | 6.4

Roughly 250MB of memory per 1M nodes. But the code assumes we only need 200MB of memory per 1M nodes. So we will use ~25% more memory than intended.

**Comment by oscardssmith** [comment]
Do we have any idea where the discrepancy is?

**Comment by mooskagh** [comment]
The estimation just sums up structure sizes for tree and cache, assuming all nodes have 30 possible moves.
It was intended as raw estimation, and I'm surprised it's so precise. :)

I think we can just muptiply it by some factor, but possibly we should also test cache size estimation and tree size estimation separately.

**Comment by davidsoncolin** [comment]
I know this is an old thread, I just wanted to suggest a way forward. a solution is to use two processes with a communications channel. when the second process runs out of memory and crashes it needn't bring down the main process, which can then recover gracefully and start a new process. FWIW, before the second process crashes it may become unresponsive and this could be used as a trigger to kill the second process.

**Comment by mooskagh** [comment]
That approach won't work. When any process in the system fails to allocate memory, it's already catastrofic for the system.
There's no way to make this particular process to fail and not another.
Plus usually there is swap file, and it's better to stop much earlier than when swap runs out.
Plus there's usually memory overcommitment, which means app can allocate memory but crashes when attempts to use it.

**Comment by mooskagh** [comment]
Yeah let's close.
