### ISSUE TITLE
Pathological case for TB re-scoring vs MCTS/policy values clash?

### ISSUE THREAD

**Issue by manyoso** [LeelaChessZero/lc0#803]
Hello,

In implementing Allie's TB for WDL, I came across the following fen that may be a pathological case for Lc0 as well: 2K5/8/2P3q1/8/P4k2/7Q/8/8 w - - 3 110

![path_fen](https://user-images.githubusercontent.com/10168/54606395-1d27c580-4a22-11e9-9ac1-96e413e0da6a.png)

It is white to move and AllieStein with TB WDL enabled selects Qh7 which instantly goes from White completely winning to a draw. The context here is important. Allie is using a **5-man tablebase**. So why does this happen?

The reason is because the stein network selects Qxc6 for Black as the highest policy value for a reply to Qh7. Allie then queries the TB for this Black Qxc6 move and discovers that it is completely losing for Black and turns it into a TB terminal with -1.0f as the score. Needless to say, this _seems_ very good for White and so the MCTS algorithm then takes over and amplifies and re-visits Qh7 over and over thereby increasing the visits and thus Qh7 is selected. However, the _actual_ best reply by Black is not Qxc6, but Qxh7 and with this White goes from completely winning to completely drawn.

The solution to me seems to be to that TB needs to modify the policy values in some way...

I haven't figured out how to do that, but **then it occurred to me that lc0's TB rescoring might run into similar pathological cases unless it already does modify the policy values as well??!!** If so, might this be an extremely well hidden case for Lc0 draws in completely winning positions? I will update the PR when I've had a chance to test Lc0 binary with t30 and t40 nets.

**Comment by Mardak** [comment]
MCTS for black's response will favor the non-loss move even without DTZ:
```
g6c6  (608 ) N:     256 (+ 0) (P: 15.84%) (Q: -1.00000) (D:  0.000) (U: 0.04252) (Q+U: -0.95748) (V: -1.0000) (T) 
g6h7  (605 ) N:     256 (+ 0) (P: 25.71%) (Q:  0.00000) (D:  1.000) (U: 0.06900) (Q+U:  0.06900) (V:  0.0000) (T) 
```
Yes potentially if g6c6 had extremely high prior and g6h7 had very low prior, search could take longer to find a move other than g6c6, but after 1 visit to the TB loss move, even with first play urgency of loss, all other unvisited moves look no worse than the known loss move so MCTS then picks the next move based on the Uncertainty portion.

**Comment by manyoso** [comment]
Closing as I think this is invalid. I am sorry for wasting time.
