### ISSUE TITLE
Backpropagating game-theoretical values

### ISSUE THREAD

**Issue by TFiFiE** [LeelaChessZero/lc0#81]
Has it been considered to (recursively) determine whether nodes have been "solved" (as a natural by-product of the search as is)? See http://www.ru.is/~yngvi/pdf/WinandsB10a.pdf for an example.

**Comment by gonzalezjo** [comment]
I believe that is what [this](https://github.com/Videodr0me/leela-chess-experimental/wiki#single-legal-move-positions---auto-extend1) does.

**Comment by mooskagh** [comment]
Certainty propagation addresses that. There's a separate issue and PR for it.
