### ISSUE TITLE
Reason Behind the sharp drop of ELO every period of time

### ISSUE THREAD

**Issue by gerrysonx** [LeelaChessZero/lc0#827]
When checking the elo rating graph in the main page, I found network with id:20070, 35002, 37001, their elo drops sharply from around 3000 to nearly zero. Wonder what happened to the network.Is the self-play 
 trained model reset to initial state every period of time?

**Comment by oscardssmith** [comment]
In general, questions should go to discord, and GitHub used for bugs or code changes. The answer to your question is is of. We have had several resets when we have found bugs or started using new neutral net architectures.

**Comment by gerrysonx** [comment]
Thanks for ur kind reply.

**Comment by oscardssmith** [comment]
np. Please close the issue though so it's clearly resolved.
