### ISSUE TITLE
v21.1 Memory Leak

### ISSUE THREAD

**Issue by brianprichardson** [LeelaChessZero/lc0#829]
v21.1 there is still a slow leak on Win7 cuda.
Can see it if you run some match games with and without the cutechess-cli restart=on option

**Comment by brianprichardson** [comment]
`H:\Lc0-v0.21.1>lc0
       _
|   _ | |
|_ |_ |_| v0.21.1 built Mar 23 2019
go nodes 1
Found pb network file: ./128x10-pgns-run2-12-01.txt
Creating backend [cudnn]...
GPU: GeForce GTX 1070
GPU memory: 8 Gb
GPU clock frequency: 1784.5 MHz
GPU compute capability: 6.1
CUDA Runtime version: 10.0.0
Cudnn version: 7.3.1
Latest version of CUDA supported by the driver: 10.0.0
info depth 1 seldepth 1 time 36 nodes 1 score cp 0 hashfull 0 nps 27 tbhits 0 pv e2e4
bestmove e2e4
`

**Comment by brianprichardson** [comment]
H:\Lc0-v0.21.1>lc0
       _
|   _ | |
|_ |_ |_| v0.21.1 built Mar 23 2019
go nodes 1
Found pb network file: ./128x10-pgns-run2-12-01.txt
Creating backend [cudnn]...
GPU: GeForce GTX 1070
GPU memory: 8 Gb
GPU clock frequency: 1784.5 MHz
GPU compute capability: 6.1
CUDA Runtime version: 10.0.0
Cudnn version: 7.3.1
Latest version of CUDA supported by the driver: 10.0.0
info depth 1 seldepth 1 time 36 nodes 1 score cp 0 hashfull 0 nps 27 tbhits 0 pv e2e4
bestmove e2e4

**Comment by brianprichardson** [comment]
Also changes match results:
Score of Leak-A vs Leak-B: 31 - 18 - 51  [0.565] 100
Elo difference: 45.42 +/- 47.89

Dead even within one game with restart=on

**Comment by mooskagh** [comment]
For memory leak alone I think there's not enough evidence that there is a leak. It is expected that a process doesn't release unneeded memory to OS immediately.

For the weakening the engine after reusing it, would be nice if someone tested that independently.

**Comment by oscardssmith** [comment]
Has anyone run with Valgrind?

**Comment by Rechenschieber** [comment]
I'm running some tests using a 64 GB PC with 2x RTX 2080Ti. When analyzing one position, it really looks like a memory leak. Memory usage can get above 60 GB. But that memory is being released as soon as the position changes. NNCacheSize has no impact on this.

**Comment by mooskagh** [comment]
It is expected that during thinking the memory consumption grows. Unlike traditional engines, Lc0 stores entire search tree in memory.

What this issue says is that after if you play many games using the same engine without restarting the engine, it will slowly increase memory usage during every game.

**Comment by Rechenschieber** [comment]
But there should be some limit to memory usage. When a PC has no page file, Lc0 crashes when there's no more memory left. Also kn/s drop when memory usage is high.

**Comment by Rechenschieber** [comment]
I made a test which lasted ~21 hours playing an engines match Lc0 21.1 on RTX 2080 vs Stockfish 120319 on 10 cores.
At the beginning of the second game Lc0 had a memory usage of 2844 MB. At the beginning of one the last games memory usage was 3060 MB. These values varied quite a lot from game to game,  So I think there is no real memory leak. Performance didn't drop. Lc0 won +8 =85 -6 Timing was 4 min + 2 sec increment. Ponder on.

**Comment by brianprichardson** [comment]
@Rechenschieber Agreed, it may be just the way Leela uses memory.  However, I am still finding it quite strange that the two runs with Leak-A and B, which are identical, would vary by so much, although within margins of error.  Can you also try something similar?  Just copy a directory with Leela and run a sanity match A v B.  They should stay even give or take a game.  If not, they will be even with restart=on.

**Comment by HartmutHering** [comment]
I have the same Problem. Not with tournaments but with long analysis in correspondence chess. After a few hours (Sometimes 4, sometimes 6 hours, depends on board position) lc0 crashes without any message. My Machine has 16 GB of Memory. GPU is a GeForce GTX 970

**Comment by mooskagh** [comment]
Unlike MiniMax algorithm that traditional engines use, Monte-Carlo tree search requires that entire search tree is kept in memory. Therefore memory growth as thinking goes is expected.

There is a command line parameter and UCI option to stop search when memory usage reaches some threshold. Those are `--ramlimit-mb` and  `RamLimitMb`.
Set it tp `--ramlimit-mb=16000` and it will stop when it reaches 16GB.
