### ISSUE TITLE
OpenCLTuner.cc should call store_sgemm intermittently

### ISSUE THREAD

**Issue by croc54** [LeelaChessZero/lc0#834]
With tune_exhaustive=true, lc0 hangs midway and all the effort is lost.. To prevent this leelaz_opencl_tuning should be written to everytime it finds a better configuration

**Comment by Naphthalin** [comment]
this is related to some problematic configurations apparently; @borg323 can you comment on that (and decide what to do with the issue)?

**Comment by borg323** [comment]
Personally, I wouldn't trust one that didn't finish the tuning process: There are many buggy opencl drivers out there.
