### ISSUE TITLE
Make it possible to specify directory for training data, make it CWD (or $HOME/something) by default.

### ISSUE THREAD

**Issue by madformuse** [LeelaChessZero/lc0#839]
I need to add the ability to the client to specify the path to lc0 binary and it's been suggested that similar treatment of networks and data would be beneficial for packaging the application on Linux.  Unfortunately It looks like the data writer is currently using the exe directory to create the temporary data folder in and it's not configurable. 

It would be better if it either used the current working directory or allowed a temp / data parameter which could be used to specify path.  If this was added I could hook into it from the client.

What does everyone else think?

**Comment by mooskagh** [comment]
It's a good point. I think it's mostly work on client side than lc0 side, so I created an issue there: https://github.com/LeelaChessZero/lczero-client/issues/92

Everyone feel free to add ideas or implement some parts of it. :)

I'm closing this issue as it (I think) is fully covered by https://github.com/LeelaChessZero/lczero-client/issues/92.

**Comment by madformuse** [comment]
I'm not sure it is covered as lc0 is hard coded to use path same directory as binary for temp data.

**Comment by mooskagh** [comment]
I meant that PR to cover everything, but it indeed probably makes sense to have Lc0-related issue in Lc0 repo. I'll repurpose this issue then.

**Comment by mooskagh** [comment]
Fixed in #1338.
