### ISSUE TITLE
LC0 doesn't work with two RTX 2080 Ti gpus

### ISSUE THREAD

**Issue by superbnet** [LeelaChessZero/lc0#840]
kN/s are 32.
What needs to be changed, when I use Fritz 16 gui or ChessOk Aquarium gui or ChessBase 15 gui?

**Comment by oscardssmith** [comment]
Try asking in the help channel of our [https://discord.gg/gapYnE](discord). Github should be used only for bug reports/feature requests.

**Comment by superbnet** [comment]
No it must be a bug. 

What I mean is that I had no memory problems with only 1 RTX 2080 Ti but now I have 2x RTX 2080 Ti and the memory is full within some minutes, 5-10.
In every gui.

I have 16 gb.

**Comment by mooskagh** [comment]
It is not a bug, many people use it without problems.
To get help seting it up, go to #help channel at https://discord.gg/pKujYxD, or you can also try asking at our forum, https://groups.google.com/forum/#!forum/lczero (but chat is better).
