### ISSUE TITLE
Improve opening diversity for training

### ISSUE THREAD

**Issue by jhorthos** [LeelaChessZero/lc0#845]
I am implementing a test for opening diversity during training games, and plan to use the test to define engine parameters that achieve high opening diversity without sacrificing game quality. Using diversity measures common in ecology tests for species diversity, I now can measure diversity of game positions at any fixed ply. The measure rewards even position distribution and penalizes strong opening preferences. You can read about the method in Species Diversity on Wikipedia.

Example from a recent set of T40 PGN training games:
```pgn file: run1-20190504-1254.pgn
test ply: 12
total games: 109858
12-ply games: 107824
median game ply: 103
median short-game ply: 19
ECO hits: 1435 (1.3%)
FEN diversity sample: 4000
FEN diversity (q=2): 137.96
FEN diversity (q=3): 61.35
FEN diversity (q=4): 43.23
```

and the full output (which also includes counts of known ECO opening positions):
[run1-20190504-1254_diversity.txt](https://github.com/LeelaChessZero/lc0/files/3150093/run1-20190504-1254_diversity.txt)

The main diversity measure is across all 12-ply game positions, but in addition the ECO output confirms that, for known opening positions, recent networks produce extremely skewed position coverage (not part of the summary above). For example, for the PGN games above, 58% of all ECO openings are accounted for by just 4 12-ply positions. Opening coverage does vary over training progress (so the sum of learning is across more opening diversity), but I think it is **likely that Leela plays the large majority of common openings almost purely by generalizing** from her favored openings, rather than directly learning them. 

My hypothesis is that the difference between generalizing and knowing an opening by direct test is what accounts for Leela's improved performance without a book. When good parameters are found, I will test this hypothesis by doing training tests with games generated with the best parameters.

I will be adding diversity summaries for other game parameters soon. So far I am using only current lc0 parameters, such as temperature, temp decay, visit offset, and policy temperature.

**Comment by jhorthos** [comment]
I will add directions for self-play game generation soon for anyone who wants to contribute. The same process can be used to first test for diversity and later to generate training-format game data.

**Comment by AlexisOlson** [comment]
You may also want to monitor the percent of distinct FEN at N ply over the total number of games as well as the percent of N ply ECO positions hit out of all N ply ECO positions.

I assume there's nothing special about 12 ply and that you'll monitor the diversity indices for multiple N?

**Comment by jhorthos** [comment]
Yes, the test can be directed to any ply. I think the diversity stats are the best measure for what you suggest above, but I should definitely allow an output that just counts each FEN and how often it was found.

**Comment by jhorthos** [comment]
Just to get you all excited in a geeky sort of way, here is the diversity measure for T40 training params (t0.pgn) and temp=3.0 visit-offset=-6 tempdecay=24, all other params the same:
```pgn file: t0.pgn
test ply: 8
total games: 281
8-ply games: 281
median game ply: 145
median short-game ply: 53
ECO hits: 32 (11.4%)
FEN div sample (all): 281
FEN diversity (q=2): 30.76
FEN diversity (q=3): 18.61
FEN diversity (q=4): 14.87

pgn file: t13.pgn
test ply: 8
total games: 281
8-ply games: 281
median game ply: 140
median short-game ply: 51
ECO hits: 20 (7.1%)
FEN div sample (all): 281
FEN diversity (q=2): 253.89
FEN diversity (q=3): 235.23
FEN diversity (q=4): 207.78```

**Comment by jhorthos** [comment]
Will replace that with good data sets and lots of param combinations when I have the data.

**Comment by AlexisOlson** [comment]
See attached for comparison of some T40 training game openings versus ICCF game openings:

[Opening Comparison.xlsx](https://github.com/LeelaChessZero/lc0/files/3155156/Opening.Comparison.xlsx)

**Comment by jhorthos** [comment]
:-)

**Comment by jhorthos** [comment]
After testing many combinations of opening temperature, value offset, visit offset, and opening decay I have settled on first good set of parameters for zero-yet-diverse opening play. They are ``--temperature=3.0 --tempdecay-moves=20 --temp-value-cutoff=5``. This combination provides vastly improved opening diversity, with openings that intersect ECO just as much as the current training parameters (i.e. the openings are generally fairly sane) and actually has a slightly higher Elo than current training parameters.

**Comment by jhorthos** [comment]
Here is a brief summary of the behavior of those parameters relative to current standard training parameters:
```params	div	%ECO	Elo
T40	46	13.0	0	
new	322	14.5	30```

**Comment by AlexisOlson** [comment]
Is that Elo the difference for 800 node matches?

**Comment by jhorthos** [comment]
Yes.

**Comment by mooskagh** [comment]
Seems to be obsolete. Feel free to reopen if not so.
