### ISSUE TITLE
Nvidia gv100

### ISSUE THREAD

**Issue by ik4u** [LeelaChessZero/lc0#847]
lc0 is using only 6% of my Quadro gv100 performance. how can I utilize 100% of my gpu performance.
![image](https://user-images.githubusercontent.com/5150233/57495473-4efd3000-72df-11e9-8569-697941435511.png)

**Comment by oscardssmith** [comment]
Windows does not do a good job reporting gpu load. You should try a 3rd party gpu monitoring program. Also please ask questions like this in the discord (https://www.youtube.com/watch?v=5i0_SGV4J3w) as GitHub should be used for bug reports and feature requests. Thanks. Also good luck getting everything working.

**Comment by Naphthalin** [comment]
Non-issue, as the Win10 task manager correctly reports "Compute" separately, and software like GPU-Z can help further. Can be closed.
