### ISSUE TITLE
Bug, running client with 2x RTX 2080 Ti GPUs, black screen after some minutes

### ISSUE THREAD

**Issue by Chess321** [LeelaChessZero/lc0#870]
I must restart my computer every time:(
That never happens with one gpu.

**Comment by oscardssmith** [comment]
What Power Supply do you have? It sounds like you might be triggering over current protection or something. Have you tried running a dual gpu and cpu stress test?

**Comment by all12** [comment]
All done all fine. 
Only the client with two rtx gpus has this problem.
LC0 analysis doesn't show black screen.

I'm using a Corsair AX1600i.

**Comment by oscardssmith** [comment]
when you say black screen,do you mean your entire computer or just leela?

**Comment by all12** [comment]
Only the monitor.
I mean it isn't off it's black.

**Comment by oscardssmith** [comment]
This really doesn't seem like a leela issue. I'm really not sure what it is though

**Comment by all12** [comment]
Every other programm and game and stress test works fine.
Even LC0 analysis for **some hours** works fine.

But donating training games does not work, when the client does not work correctly.
When I start the client, after **5 to 30 minutes**, the screen becomes black, but fans are still running.

**Comment by hocheung20** [comment]
Leela uses tensor cores, which almost no other benchmark/stress test use. I find it is very picky and maybe revealing weakness in the hardware even at stock clock. I had to replace my sole RTX2080Ti 3 times because lc0 would crash the entire system on overnight runs.

**Comment by Naphthalin** [comment]
As GPUs (especially with high batch sizes) have rather extreme power draw oscillations, this isn't a Leela issue. Can be closed.
