### ISSUE TITLE
Is it possible to set up a match between different LC0s and split my two RTX 2080 Ti GPUs into using one per engine?

### ISSUE THREAD

**Issue by all12** [LeelaChessZero/lc0#871]
Somehow it doesn't work.
I've tried it with ChessBase 15 and ChessOK Aquarium 2018.

**Comment by mooskagh** [comment]
It is possible, but I recommend asking in #help channel of our Discord chat (http://lc0.org/chat) or in forum (http://lc0.org/forum, although it may take longer to get answer there than in chat) for more details.

GitHub issues are generally not for questions like this but rather to report bugs when something doesn't work.
