### ISSUE TITLE
Often, LogLiveStats has V: -.----

### ISSUE THREAD

**Issue by fohristiwhirl** [LeelaChessZero/lc0#874]
Hi -

I'm making a [Lc0 GUI / visualiser](https://github.com/fohristiwhirl/nibbler) and it would be nice to display expected values or winrates, which I believe I can get from the LogLiveStats "V" value, however quite often this seems to be "-.----" (I think possibly more in extreme positions).

As an example:

`info string g8f6  (159 ) N:  554159 (+168) (P: 40.99%) (Q: -0.53568) (D:  0.000) (U: 0.00546) (Q+U: -0.53022) (V:  -.----) `

I can't reliably reproduce this (i.e. give an exact series of moves that always triggers it).

**Comment by mooskagh** [comment]
V is not stored in tree, but is taken from cache. When those nodes are evicted from cache, V cannot be shown anymore.
That's how it works now.
If V is needs to be shown, correct approach would be to re-query NN, but this is not implemented.
(also entire debug API would be nice to have as gRPC service, but it's also only in stage of dreaming now).

**Comment by fohristiwhirl** [comment]
The centipawn scores returned in the normal info is based on winrate, right? So are the winrate values not available somehow?

**Comment by mooskagh** [comment]
V is output of the NN for a given node.
Q is average of NN outputs for entire subtree (with root in this node). Q is stored in the tree, while V is only kept in cache.

**Comment by mooskagh** [comment]
Winrate is Q indeed, but V is sometime curious to see too (mostly for debugging, not for game understanding though).

**Comment by fohristiwhirl** [comment]
Thanks. I'll use Q.
