### ISSUE TITLE
Technical ponder question

### ISSUE THREAD

**Issue by Nordlandia** [LeelaChessZero/lc0#877]
Couple of questions. 

1.

Is it good idea to use ponder when lz0 use gpu while sf use cpu.  Assuming the psu is strong enough.
In my case with i7-5960X i allocate 6-cores for sf and let the remaining 2-cores for lz0 and the os. 

2. 

Do lz0 fully utilize the cpu threads to 100% or just partially.  This is for cuda (nvidia) version.

**Comment by oscardssmith** [comment]
For questions like this, in the future, please use the Lc0 discord. However, lc0 ponder has no issues. It should basically just play like it has 2x as much time. Lc0 can fully use 2 cpu cores, although it depends on your GPU.

**Comment by Nordlandia** [comment]
GPU is GTX 1070 Ti.
