### ISSUE TITLE
Piece move input planes

### ISSUE THREAD

**Issue by TesseractA** [LeelaChessZero/lc0#882]
Edited with another idea and for proper terminology:
The idea is to give the neural network separate binary masks representing each possible move by each piece. The theory is that it will improve tactical recognition and improve pin/skewer detection. The problem is, there are several different implementations of the same idea and I'm having trouble determining which ideas are best:

-32-64 for each piece/pawn on the board. (When there are extra pieces/pawns on the board for variants, that could potentially run into issues with only 32 pieces.)

-18 rook, 18 bishop, 18 queen attack planes (forgoing the king, knight, and pawn attack planes for simplicity) _And maybe ignore putting in extra attack planes for bishops, queens, rooks, and/or knights? We may never reach a real position with 8 queens on both sides anyway. For any such cases, we build in exceptions that say to use a neural network that is either compatible with that many pieces or we forgo putting in some of the pieces._

-Randomly putting pieces into different attack planes of the same or different types (rooks could be on the same planes as bishops are, this would reduce the amount of planes needed to 28 or less.)

-Fixed attack planes for each piece. (Could possibly cause some board symmetry problems)

-Do we preserve and reserve attack masks for a single side or allow attack masks to be used from both sides on the same input plane?

I'd also like other thoughts, regardless of whether they are about this being 'zero' or not.

The attack binary mask board generation should be easy and any necessary infrastructure could be borrowed from Stockfish.

**Comment by oscardssmith** [comment]
Don't bitboards only work with integers? Do you mean binary masks?

**Comment by Naphthalin** [comment]
Any evidence on this possibly helping Lc0? I think other engines are using something like this, but it seems a pretty complicated change for something leela likely calculates automatically, so this might only help small nets.

**Comment by TesseractA** [comment]
Closing because of the more general issue #1258
