### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by SaintRoge** [LeelaChessZero/lc0#883]
I have this problem when i run lc0

`c:\projects\lc0\src\utils\exception.h:39] Exception: CUDA error: CUDA driver version is insufficient for CUDA runtime version (c:\projects\lc0\src\neural\cuda\network_cudnn.cc:202`) 

 but when i type `nvcc --version` it shows
`nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Apr_24_19:11:20_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.168`

It shows that I have the right version. What should I do ?

**Comment by Rechenschieber** [comment]
This is not a Leela problem, you should ask things like this in the forum.

Get GeForce Experience, download the driver using that tool.

**Comment by Naphthalin** [comment]
Cuda version isn't the same as the nvidia driver version. Not a Lc0 issue, can be closed.
