### ISSUE TITLE
lc0 backends scale unfavourably at low movetimes compared to lczero 

### ISSUE THREAD

**Issue by gsobala** [LeelaChessZero/lc0#89]
I have performed a [preliminary analysis](https://docs.google.com/spreadsheets/d/1Qati5nU18QIue-4xpsnNEz0_jAfPSGyTKaK38zfh074/edit#gid=717807427) of how various Leela backends perform with different NN sizes and at different movetimes. 

None of the lc0 backends tested perform well at very short movetimes such as those which might be used for rapid comparative engine testing (i.e. fractions of a second per move). The original opencl backend for lczero does far better in this regard even though it is running on an AMD rather than an nVidia GPU. 

One exception to poor performance at short movetimes with lc0 backends is the tensorflow-cpu lc0 backend which is exceptionally fast with 64x6 networks, but deteriorates very rapidly with increasing network size.

The lc0 opencl backend is slower at short movetimes than the lczero opencl backend although it ultimately overtakes it at longer movetimes.

The opencl backends (both lczero and lc0), are much  slower than cudnn but scale much better with  increasing network size.

It is possible that some of the observed effects are specific to Mac drivers, but the results suggest that there may be considerable room for optimisation of early search speed.

**Comment by dubslow** [comment]
"scale much better with increasing network size" could be turned around to be interpreted as "very inefficient silicon utilization at low network sizes"

**Comment by gsobala** [comment]
Just to summarise speed-drops with each successive network size:

Divisor 3:
lczero/mkl, lc0 tensorflow-cpu, K80 cudnn, blas

Divisor sqrt(2):
lczero/opencl and lc0/opencl
