### ISSUE TITLE
Matefinder Rescoring

### ISSUE THREAD

**Issue by TesseractA** [LeelaChessZero/lc0#894]
Suppose I program an entity that finds mates in 5 or less. Now suppose I use that entity to look at every position in a game to detect whether there is a mate in that position. Then suppose that I rescore both Q and policy on that position within the game replacing the result, and then create a game-split branch much like https://github.com/LeelaChessZero/lc0/pull/720 .

Isn't this a very useful way of getting the net to recognize mating patterns, also just as 'zero' as tablebases?

EDIT: I now recognize the splitting branches may be a completely unnecessary addition. MLH might just 'fix' this issue, so I'll close it in time to reduce clutter.

**Comment by gonzalezjo** [comment]
I’m under the impression that Leela’s issues with quick mates is less to do with Leela improperly assessing the value of a short mating sequence, Q, and more to do with the fact that P is essentially what is picking moves in positions where there are likely to be mates-in-five.

**Comment by oscardssmith** [comment]
If we retrain p as well, it should help.

**Comment by TesseractA** [comment]
By the way, there doesn't seem to be any issues with DarkQueen which was trained off lichess games, and it also seems to be very efficient at mates.

**Comment by TesseractA** [comment]
Should I refashion this thread to include the newer MLH, or close it? I figure this idea is useful, but perhaps outdated.

**Comment by TesseractA** [comment]
Closing, not because the idea is bad, but to reduce issue clutter.
