### ISSUE TITLE
Make training games deterministically reproducible

### ISSUE THREAD

**Issue by dubslow** [LeelaChessZero/lc0#90]
Probably best done by printing and/or storing the `Random` seed used to generate that game.

**Comment by mooskagh** [comment]
Closing this as a part of an issue cleanup, as it's not a pressing issue.

**Comment by oscardssmith** [comment]
I'd leave this open. It's not pressing, but still would be good to have.

**Comment by mooskagh** [comment]
I'd prefer to keep it closed.
There was never a need for that so far, it's pretty complicated to implement and very complicated to maintain.
Just to reduce noise while reviewing list of PRs/issues, I think it's better to keep issues which are not actionable in near future closed.
