### ISSUE TITLE
The DeepMind PUCT formula (probably) causes the lack of opening diversity

### ISSUE THREAD

**Issue by Naphthalin** [LeelaChessZero/lc0#913]
This is supposed to be more or less a summary of a few posts on Discord about the topic.

EatNow (Leela Zero discord) suggested a small change in the PUCT formula which would be in line with the standard UCB, see [here](https://colab.research.google.com/drive/14v45o1xbfrBz0sG3mHbqFtYz_IrQHLTg#scrollTo=1VeRCpCSaHe3 are EatNow's initial considerations), and as it turned out Tilps already realized that there are differences between the DeepMind pseudocode and the formulas, see [https://github.com/LeelaChessZero/lc0/pull/699](https://github.com/LeelaChessZero/lc0/pull/699)

This means:
A) when comparing the DM PUCT formula to their UCB1 origin, one would have to replace a 1/sqrt(parent_visits) by a 1/sqrt(child_visits + 1) to actually match them
B) this means while the formula apparently intends to estimate lower bounds of child nodes, it uses sqrt(parent_visits) to estimate this lower bound
C) one would like to increase the certainty over time which is done by scaling puct by some log(parent_visits) stuff --> this is the same scaling we already do
**D) when using the modified formula, there are actually equilibria for the policies**, so e.g. during the opening the policies don't tend to focus on single moves/lines but on the best moves
especially D) might be very interesting: **while the DeepMind formula promises to have the child_visit ratio as a training target for policies, because of the PUCT formula this training target shifts**, since
`Q_1 + p(s,a_1)*N/(N_1 + 1) * puct/sqrt(N) = P_1 == P_2 = Q_2 + p(s,a_2)*N/(N_2 + 1) * puct/sqrt(N)`
with `p(s,a_1) = N_1/N` and `p(s,a_2) = N_2/N` (assuming we are in a stable equilibrium) can only be true if `Q_1 = Q_2`or the worse moves gets no visits and zero policy.

So whenever Q_1 and Q_2 are different even by the slighest bit, this difference will be amplified by the policies and we get our usual extremely sharp policies.

For Leela Zero Go, the best opening moves 4-4 and 4-3 have evals of 43.76% and 43.67% but policies of 17.6% and 2.6% (which means 70% and 20% including symmetries). the 2 next best moves at 43.54% and 43.28% are at 0.2% and 0.25%

However, the full consequences of this modification/oversight/intended deviation by DeepMind won't be seen without an actual RF run, lightvector (the author of KataGo) will try this in an actual reinforcement run **and i guess it would be very interesting to try this in a lc0 test run as well, since at least the missing opening diversity is a problem we didn't solve yet**

As already stated, one consequence of changing the formula would be the emergence of stable equilibrium policies despite slightly different Q values for different moves. If we take the starting position, the latest T40 net gives these evaluations after 100k node search:
in our case i get after 100k node search the CP and Q values

```
Move  CP     Q
e4  +0.35 +0.079
d4  +0.32 +0.072
c4  +0.20 +0.046
Nf3 +0.28 +0.064
e3  +0.18 +0.041
Nc3 +0.00 +0.000
```

If we plug this into the modified PUCT formula, for given puct and parent_visits values we get a unique stable equilibrium solution of the RL process where `child_visits = p(s,a) * parent_visits` for all moves.
with these Q values and at 800 nodes per move, one would get these equilibrium policies:

```
Move    p (puct=0.5)    p (puct = 0.2)    p (puct = 1.0)
c4        7.86%            2.85%            9.82%
d4       22.76%           19.86%           16.58%
e4       34.60%           63.60%           19.62%
Nf3      15.39%            8.78%           13.90%
e3        6.75%            2.28%            9.00%
Nc3       2.63%            0.65%            4.96%
rest      0.72%            0.14%            1.87%
```

(assuming the remaining moves having evals of -0.1 and lower)

**This means that under the assumption that the evals of the top moves are somehow consistent between different runs, we get diverse openings for free just from temperature without any further need for forced openings, first moves etc** while for the old/current formula these equilibrium policies don't really exist, they are only a product of noise, FPU and the small subtleties with the child_visits + 1.

This means that the story "since the training target for p(s,a) is  the visit ratio, it condenses the 800 node search into 1 node" when there was no equilibrium solution outside "winner takes it all" isn't really true, but instead every run with decided enough evals will have these very sharp policy values, no matter the choice of cpuct (R.I.P. T20...)

These equilibria are stable, as one can see from these simple consideration:

Take the modified PUCT formula
`P = Q + p(s,a) * N / (N_a + 1) * puct / sqrt(N_a + 1)`
in a stable situation, the first factor `p(s,a) * N / (N_a + 1)` is approximately 1.

If after search for N moves it turns out to be < 1 this means N_a was higher than expected, this means the second factor is also smaller than anticipated, that means the Q had to be better than expected. If Q is better than anticipated, N_a will be higher than expected, so the training target for p(s,a) increases.

Since the same holds for the factor being > 1, p(s,a) will always be pushed towards the equilibrium given by Q_a so at least around that fixed point the dynamics is stable.

**Comment by Naphthalin** [comment]
To add to this, the calculation of these equilibrium policies is quite easy, e.g. in Mathematica

`c4 = 0.046
d4 = 0.072
e4 = 0.079
Nf3 = 0.064
e3 = 0.041
Nc3 = 0.0
rest = -0.1
Ntotal = 800
cpuct = 0.2
Solve[{(pc4 + pd4 + pe4 + pNf3 + pe3 + pNc3) + 14*prest == 1,
  P == c4 + cpuct/Sqrt[pc4*Ntotal],
  P == d4 + cpuct/Sqrt[pd4*Ntotal],
  P == e4 + cpuct/Sqrt[pe4*Ntotal],
  P == Nf3 + cpuct/Sqrt[pNf3*Ntotal],
  P == e3 + cpuct/Sqrt[pe3*Ntotal],
  P == Nc3 + cpuct/Sqrt[pNc3*Ntotal],
  P == rest + cpuct/Sqrt[prest*Ntotal]}, {pc4, pd4, pe4, pNf3, pe3, 
  pNc3, prest, P}]`
gives
`{pc4 -> 0.0285257, pd4 -> 0.198612, pe4 -> 0.636009, 
 pNf3 -> 0.0877792, pe3 -> 0.0227638, pNc3 -> 0.00647624, 
 prest -> 0.00141668, P -> 0.0878665}`

**Comment by kiudee** [comment]
To clarify, this change is different from #699.
To implement the modified PUCT formula we would need to change
https://github.com/LeelaChessZero/lc0/blob/78baefee5f51c18a71fef7f52b693d98f011fc0c/src/mcts/node.h#L361-L363
to
```c++
  float GetU(float numerator) const {
    return numerator * GetP() / pow(1.0 + GetNStarted(), 1.5);
  }
```
and
https://github.com/LeelaChessZero/lc0/blob/78baefee5f51c18a71fef7f52b693d98f011fc0c/src/mcts/search.cc#L933-L934
to
```c++
    const float puct_mult =
        cpuct * std::max(node->GetChildrenVisits(), 1u);
```

Of course the simplification of #699 can be applied in addition.

**Comment by Tilps** [comment]
okay I see that the discussion has really nothing to do with PR699
PR699 probably is just as meaningless as I expected then.
Deepmind formula (per papers) is what we have implemented - PR699 switches it to match their pseudoocode instead - they very tiny difference seems insignificant compared to the level of change in this proposal.

**Comment by Tilps** [comment]
Also given deepmind graphs show decent opening diversity in their run - it seems the original assumption that the formula causes our lack of opening diversity seems on shaky ground.

**Comment by kiudee** [comment]
In addition it turns out that the modified PUCT formula might slow down convergence to the best moves (see EatNow’s excellent bandit simulations [here](https://colab.research.google.com/drive/1kwcP_jPT5az7oJj4_3lb3jxXRvxQv2Ov)).
Thus, the question is, whether we can find a PUCT formula which is stable *and* able to converge quickly.

**Comment by Naphthalin** [comment]
@kiudee I looked at the bandit simulations by EatNow you linked, and I don't see where your concerns about the PUCT formula converging too slowly come from. I tried to guess the top 3 child evals from the currently displayed run as 0.758, 0.751 and 0.744 and by using the above analysis I get equilibrium policies of 51%, 17% and 9% for the top 3 moves with the choice of c1 and c2, and the policy of the top move is already ~40% at epoch 35.

**Comment by jkormu** [comment]
Tuning run with 1064 nodes, minibatch-size=32 and net42850 over parameters _cpuct_ and _policy-softmax-temp_ converged in values ~0.38 and ~1.59, respectively. Seems to be about equal or slightly better versus new-u disabled. 

Interestingly the visit distribution from the start position for new-u with these parameters is almost equal to vanilla with standard parameters. Tree shapes and visit distributions below.

new-u enabled with tuned parameters:
![image](https://user-images.githubusercontent.com/13436074/62651267-3f829700-b961-11e9-8a19-dca23ec3dae0.png)

new-u disabled with default parameters:
![image](https://user-images.githubusercontent.com/13436074/62651332-65a83700-b961-11e9-941f-f39b6cf45e80.png)

**Comment by Naphthalin** [comment]
Just a small addition: Using ``policy-softmax-temp`` during the training also introduces equilibrium policies if a temperature > 1 is used, from >1.1 the policies start to be reasonable. The new UCB formula #918 effectively acts as having temp 2.0 apart from not suffering from a varying cpuct factor introduced by the softmax normalization step.

**Comment by Naphthalin** [comment]
The analysis in this issue is still correct; however using `--policy-softmax-temp=1.2` since T58/T60 midrun (resp. 1.4 for T70) solved the issue without any known downsides nor code changes. 

The UCB formula suggested here likely gives low visit nodes too much weight (at least it did for Go), and still suffers from the policy effect not disappearing at higher node counts, as #1173 and others do, and the implementation #918 was closed.

Discussion about PUCT matching the originial formula better should continue in #1231, this issue has served its purpose. Closing now.
