### ISSUE TITLE
lc0 doesn't compile in termux

### ISSUE THREAD

**Issue by outeh** [LeelaChessZero/lc0#914]
lc0 doesn't compile in termux (on android)
using the normal build.sh,
because "/usr/local/include/" is used explicitly.(in termux this directory is located at "/data/data/com.termux/files/usr/include")
The error is : "meson.build:62:4: ERROR: Include dir /usr/local/include/ does not exist."

**Comment by lealgo** [comment]
Please take a look at this:

https://github.com/LeelaChessZero/lc0/wiki/Building-lc0-on-Android,-with-Termux

**Comment by outeh** [comment]
thanks a lot
