### ISSUE TITLE
[build.sh] Error to run build.sh 

### ISSUE THREAD

**Issue by spizzirri** [LeelaChessZero/lc0#919]
Hi, I downloaded the code and followed the steps but I have an error.

Can Anybody help me?

I have Ubuntu 18.04 x64

![imagen](https://user-images.githubusercontent.com/49996301/62587789-d6841c00-b899-11e9-9b45-b737cc2bcacc.png)

This error was produced when I executed CC=clang-6.0 CXX=clang++-6.0 INSTALL_PREFIX=~/.local ./build.sh

**Comment by borg323** [comment]
You probably need to do `sudo apt-get install opencl-headers`

**Comment by mooskagh** [comment]
Ideally meson would detect that and disable opencl backend.
