### ISSUE TITLE
Occasional low GPU load

### ISSUE THREAD

**Issue by koedem** [LeelaChessZero/lc0#937]
Most of the time Leela uses my RTX2060 fully, when using 2 threads, this looks something like that:
http://gpuz.techpowerup.com/19/08/26/b5s.png
As one can see Power consumption is pretty high, the PerfCapReason is power, naturally GPU temperature is high too etc.

However sometimes (not sure yet how to reproduce this consistently) it looks like this: http://gpuz.techpowerup.com/19/08/23/9ce.png
GPU load still is up very high (the small drops are when Leela gets a new position to run on) however all the other values drop a lot, namely Power Consumption, PerfCapReason being idle, temperature etc. as well as Nodes per second being much lower.

Any idea what could be the cause of this, and even better, how to prevent it if possible? I especially don't understand why the GPU load value still is up but everything else isn't.

**Comment by koedem** [comment]
Now I could observe the switch from the first to the second.
Seems to have happened when I was closing a bunch of programs, among them firefox and some others. Still no idea why that would cause anything but at least now there's a theory of how one might trigger it.

**Comment by oscardssmith** [comment]
This is truly bizarre. I would completely buy that slack was slowing lc0 down, but the reverse is very strange. Are you on a laptop? If so, it may be that slack is giving it a baseline load that keeps fans and voltage high or something horrible like that.

**Comment by koedem** [comment]
Someone theorized that Slack might be treated as 3D program thereby activating whatever boost.
FWIW some sample searches on the start position,
1. with Slack closed: https://pastebin.com/3q8UvuAd
2. with Slack open and in background: https://pastebin.com/t7vbCtHS

Peaking at 20 and 24 kN/s respectively, i.e. extra 20% speed. (though extra 90% power consumption)

**Comment by Naphthalin** [comment]
Can you reproduce this with current versions?

**Comment by mooskagh** [comment]
I'm closing as the issue was not updated for long, but feel free to reopen if there's something new on this topic.
