### ISSUE TITLE
Using lc0 

### ISSUE THREAD

**Issue by patzer081** [LeelaChessZero/lc0#938]
Ok so how do I use lc0 in a GUI? First Off I’m trying lc0 on a 1070ti with an i5 2500 16 gigs of ram and windows 10 64 on an ssd.I opened the client and it downloads a network file and this file is found in a sub folder created in lc0. Next I downloaded a weights file and I stuck it in the lc0 folder. I’d like to know does the network file need to be moved from the sub folder that was automatically created and put in the main lc0 folder or just leave it alone? I’m asking because lc0 setting has “auto detect” in the options. So far just running lc0 the way it is without changing anything around I’m watching stockfish 10 absolutely demolish lc0 almost every single game. Lc0 has yet to win even one single time at best shell draw.....sometimes....What is wrong with my setup? Is lc0 really that weak? I feel like on that gpu that stockfish should get smoked like a cheap cigar but it’s the other way around.

**Comment by patzer081** [comment]
Well , after using that weights you linked me it’s a hellova lot of improvement. During 5+5 blitz with a neutral opening book for both sides vs stock fish lc0 doesn’t fumble a draw into a loss nearly as much but she lacks that tactical prowess that ab engines possess. When a position is won vs stock fish she does fuck it up and end up drawing and when it’s a draw she still fucks that up lol. Just not as much. More training needed maybe?

**Comment by oscardssmith** [comment]
It's a very well trained net. How many nps are you getting? There might be issues with how you have it configured

**Comment by patzer081** [comment]
Arena GUi. From the start position about 24k nps after 1 minute to give you a number

**Comment by oscardssmith** [comment]
Hmm, that's about right. Based on your hardware, I'd expect SF and lc0 to be about equal. How close is it?

**Comment by patzer081** [comment]
They’re close but not by a lot. Maybe stock fish is about 5% better in respect to the time controls I’m using 5+5 and a generic drawish home made 8 moves opening book. Though that small gap in differences is huge when I see how lc0 is handling won positions and turns them into a draws occasionally.And draws into losses here and there. That’s not every game but it happens from time to time. I think maybe there’s an untraced bug in lc0?

**Comment by oscardssmith** [comment]
You might want to check out or 925. It improves play at moderate to high Q values. Party if it though is just that SF is very good, and consistently out playing it is hard.

**Comment by patzer081** [comment]
So I’ve been running a new test using perfect 2017 for both stock fish and lc0. I feel that book is still one of the best for testing on a slightly sharper scale than just a neutral book. Anyways , lc0 has actually taken the lead in a 50 games match I started with same time controls 5+5. I have to admit I’m shocked so far lol. Currently it’s on game 29 with the score being lc0 15.5 and stockfish 13.5.

**Comment by mooskagh** [comment]
It's not really the best place to get support, github issues are primarily for reporting bugs.

There're more chances that you'll find your answers to your questions in #help channel of our chat https://discord.gg/pKujYxD (recommended) or our forum: https://groups.google.com/forum/#!forum/lczero.
