### ISSUE TITLE
How to install Linux ?

### ISSUE THREAD

**Issue by GCPBigData** [LeelaChessZero/lc0#939]
I can't run local on linux on a notebook, simple! after I get it I want to put it in GCP. what I want and actually train with her online! or local!

nibbler-1.1.1-linux OK
lc0-0.22.0-rc1 FALL

TANKS !!

uname -a
Linux jr-pc 5.2.0-8-generic #9-Ubuntu SMP Mon Jul 8 13:07:27 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

The Meson build system
Version: 0.51.1
Source dir: /home/jr/nibbler-1.1.1-linux/engine/lc0-0.22.0-rc1
Build dir: /home/jr/nibbler-1.1.1-linux/engine/lc0-0.22.0-rc1/build/release
Build type: native build
DEPRECATION: Option uses prefix "build_", which is reserved for Meson. This will become an error in the future.
Project name: lc0
Project version: undefined
C++ compiler for the build machine: c++ (gcc 9.2.1 "c++ (Ubuntu 9.2.1-4ubuntu1) 9.2.1 20190821")
C++ compiler for the host machine: c++ (gcc 9.2.1 "c++ (Ubuntu 9.2.1-4ubuntu1) 9.2.1 20190821")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Library libprotobuf found: YES
Program protoc found: YES (/usr/bin/protoc)
Library pthread found: YES
Library dl found: YES
Library libtensorflow_cc found: NO
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Did not find CMake 'cmake'
Found CMake: NO
Run-time dependency accelerate found: NO (tried pkgconfig and cmake)
Library mkl_rt found: NO
Library mklml found: NO
Library openblas.dll found: NO
Library openblas found: NO
Program ispc found: NO
Library OpenCL found: NO
Run-time dependency opencl found: NO (tried pkgconfig and cmake)
Library cublas found: NO
Library cudnn found: NO
Library cudart found: NO
Program nvcc found: NO
Program /usr/local/cuda/bin/nvcc found: NO
Program /opt/cuda/bin/nvcc found: NO

meson.build:411:2: ERROR: Problem encountered: 

        No usable computation backends (cudnn/opencl/blas/etc) enabled.
        If you want to build with the random backend only, add
        -Dbuild_backends=false to the build command line.

A full log can be found at /home/jr/nibbler-1.1.1-linux/engine/lc0-0.22.0-rc1/build/release/meson-logs/meson-log.txt
jr@jr-pc:~/nibbler-1.1.1-linux/engine/lc0-0.22.0-rc1$

**Comment by ddobbelaere** [comment]
Please join Discord via https://discord.gg/pKujYxD, ask in #help and close this issue. Thanks!
