### ISSUE TITLE
Crash when creating backend

### ISSUE THREAD

**Issue by Silver-Fang** [LeelaChessZero/lc0#941]
```
PS C:\Users\vhtmf\Downloads\lc0-v0.22.0-windows-cuda> ./lc0
       _
|   _ | |
|_ |_ |_| v0.22.0 built Aug  5 2019
go
Found pb network file: C:\Users\vhtmf\Downloads\lc0-v0.22.0-windows-cuda/weights
Creating backend [cudnn]...
```
Lc0 crashes here without other outputs. GTX 1060. Win10 1903. Binary from https://github.com/LeelaChessZero/lc0/releases v0.22.0 and network from https://lczero.org/networks/, ID 42850.

**Comment by oscardssmith** [comment]
have you tried updating your graphics drivers?

**Comment by Silver-Fang** [comment]
> have you tried updating your graphics drivers?

Isn't 23.21.13.9140 the newest version?

**Comment by borg323** [comment]
This doesn't look like an nvidia driver number - if you got the driver from windows update, try to get one from <https://www.nvidia.com/Download/index.aspx>.

**Comment by borg323** [comment]
@Silver-Fang, if you still have this problem, can you replace lc0.exe with <https://ci.appveyor.com/api/buildjobs/cue9tlx2qpxqcmoh/artifacts/build%2Flc0.exe> and try again? It should give a bit more information regarding what fails.

**Comment by Naphthalin** [comment]
This is definitely a problem with Windows nvidia driver not being up to date; GTX 1060 shouldn't produce this problem. @Silver-Fang can you please report back after updating your drivers?

**Comment by mooskagh** [comment]
Feel free to reopen if you have new data.
