### ISSUE TITLE
Idea: Remove Queen Planes from Gamestate

### ISSUE THREAD

**Issue by JamesLear92** [LeelaChessZero/lc0#942]
Hi all, I was thinking that we might be able make an optimization by removing the queen channels from the game state, and instead consider a queen to be a rook and a bishop on the same square.

This would have two effects:

- Reducing the number of channels considerably (16 fewer)
- Speed up move generation as there would not be a need for the queen bitboards (although it was pointed to me on Discord that move generation isn't a current bottleneck)

**Comment by JamesLear92** [comment]
To expand on this, I've had a look at encoder.cc and mapped out the current game state format, along side the proposed change, and AlphaZero Chess.

![Game States](https://user-images.githubusercontent.com/16664707/64549320-63eade00-d328-11e9-9633-2dfdc32076d6.png)

This would reduce the number of channels from 112 to 96.

**Comment by mooskagh** [comment]
It only affects the very first tensor multiplication, reducing it will not have any noticeable effect.
Also this encoding is only used to call NN eval, movegen uses different encoding (and there actually queens are indeed encoded as bits in both rook and queen planes).

**Comment by Naphthalin** [comment]
I think this is related to what we changed from T30 to T40, which successfully solved the multiple queens problem of T30. @mooskagh can you confirm that?

**Comment by mooskagh** [comment]
It's not something that we changed, but there's no issue that this proposal will be going to save anyway.
As I said, number of input planes doesn't affect the performance of NN at all, it's a really tiny fraction of all computation cost.

So I'm closing the issue.
