### ISSUE TITLE
Lc0 hangs when there is `stop` during ponder.

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#944]
Reported in discord.
[logfile.txt](https://github.com/LeelaChessZero/lc0/files/3596772/logfile.txt)

What seems to cause the hang is:
1. Ponder starts.
2. GUI stops ponder with `stop` uci command (most GUIs don't do that, they send new position without `stop`, but InfinityChess does)
3. We respond with `bestmove`, although I'm not sure whether we should do that after ponder, probably not. It confuses GUI I guess.
4. GUI sends `position` and `go` (possibly before Lc0 manages to cleanup after `stop`?)
5. Lc0 hangs.

Relevant excerpt from the log:
```diff
+12:15:47.379950 6052] << bestmove g7g5 ponder d2e4
-12:15:47.412483 3440] >> position startpos moves g1f3 d7d5 b2b3 e7e6 e2e3 g8f6 c1b2 f8e7 c2c4 e8g8 d2d4 c7c5 b1d2 c5d4 e3d4 b7b6 f1d3 c8b7 e1g1 b8d7 d1e2 d5c4 b3c4 d8c7 a1c1 f8e8 f1e1 a8d8 b2c3 h7h6 d3c2 f6h5 a2a3 e7a3 c1a1 a3d6 a1a7 b7f3 a7c7 f3e2 c7c6 d7b8 c6b6 h5f4 g2g3 e2d3 c2a4 e8e7 g3f4 d6f4 a4b3 e7c7 c4c5 b8d7 b6b4 d7f6 h2h4 f6d5 b3d5 d8d5 g1g2 g8h7 f2f3 d5h5 e1h1 g7g5 d2e4
-12:15:47.412670 3440] >> go ponder wtime 184000 btime 142000
+12:15:47.486948 7712] << info depth 17 seldepth 30 time 43 nodes 242633 score cp 38 hashfull 854 nps 19906 tbhits 0 pv h7g6 e4f2 d3f5 h4g5 h5h1 g2h1 h6g5 b4b2 c7a7 c3d2 f4c7 h1g2 a7a4 d2e3 a4a3 e3d2 f7f6 b2b7 a3a2 b7c7 a2d2 c7d7 d2c2 g2g3 c2c3 d7d6 g6f7 g3g2 f7e7
...
+12:15:48.736113 14192] << info depth 17 seldepth 40 time 1292 nodes 264245 score cp 37 hashfull 862 nps 17390 tbhits 0 pv h7g6 e4f2 d3f5 h4g5 h5h1 g2h1 h6g5 b4b2 c7a7 c3d2 f4c7 h1g2 a7a4 d2e3 a4a3 e3d2 f7f6 b2b7 a3a2 b7c7 a2d2 c7d7 d2c2 d7d6 g6f7 g2g3 c2c3 g3g2 f7e7 d6a6
-12:15:52.137615 3440] >> stop
+12:15:52.137796 6408] << info depth 17 seldepth 40 time 4694 nodes 333965 score cp 36 hashfull 884 nps 19639 tbhits 0 pv h7g6 e4f2 d3f5 h4g5 h5h1 g2h1 h6g5 b4b2 c7a7 c3d2 f4c7 h1g2 a7a4 d2e3 a4a3 e3d2 f7f6 b2b7 a3a2 d2e3 c7a5 b7a7 a2e2 a7a5 e2e3 c5c6 e3c3
+12:15:52.140202 6408] << bestmove d2e4 ponder h7g6
-12:15:52.164333 3440] >> position startpos moves g1f3 d7d5 b2b3 e7e6 e2e3 g8f6 c1b2 f8e7 c2c4 e8g8 d2d4 c7c5 b1d2 c5d4 e3d4 b7b6 f1d3 c8b7 e1g1 b8d7 d1e2 d5c4 b3c4 d8c7 a1c1 f8e8 f1e1 a8d8 b2c3 h7h6 d3c2 f6h5 a2a3 e7a3 c1a1 a3d6 a1a7 b7f3 a7c7 f3e2 c7c6 d7b8 c6b6 h5f4 g2g3 e2d3 c2a4 e8e7 g3f4 d6f4 a4b3 e7c7 c4c5 b8d7 b6b4 d7f6 h2h4 f6d5 b3d5 d8d5 g1g2 g8h7 f2f3 d5h5 e1h1 g7g5 h4g5
-12:15:52.212566 3440] >> go wtime 184000 btime 142000
(and then we hang)
```

**Comment by Rechenschieber** [comment]
Has this been fixed in the new version?

**Comment by mooskagh** [comment]
We forgot about this issue. :)
But in v0.23 time management code was rewritten, so it may happen that it's resolved.

Help with testing/reproducing would be appreciated.

**Comment by mooskagh** [comment]
brinan on Discord reported similar problem with ucinewgame.
```
References to 'ucinewgame' refer to game 4
==========================================

11th Jan T60 log

0111 20:51:12.204636 9908 c:\projects\lc0\src\mcts\search.cc:646] Aborting search, if it is still active.
0111 20:51:12.204674 9908 c:\projects\lc0\src\mcts\search.cc:660] Search destroyed.
0111 20:51:12.211449 9908 c:\projects\lc0\src\chess\uciloop.cc:132] >> isready
0111 20:51:12.211544 9908 c:\projects\lc0\src\chess\uciloop.cc:219] << readyok
0111 20:51:15.242511 9908 c:\projects\lc0\src\chess\uciloop.cc:132] >> ucinewgame


============= Log started. =============
0111 20:51:30.943394 6672 c:\projects\lc0\src\main.cc:40] Lc0 started.
0111 20:51:30.943526 6672 c:\projects\lc0\src\main.cc:41]        _

---------------------------------------------------------------------------------------------------------

18th Jan T60 log

0118 21:51:29.789466 9372 c:\projects\lc0\src\mcts\search.cc:296] --- Opponent moves after: d2c3
0118 21:51:29.789501 9372 c:\projects\lc0\src\chess\uciloop.cc:219] << bestmove d2c3
0118 21:51:29.789610 3828 c:\projects\lc0\src\mcts\search.cc:624] End a watchdog thread.
0118 21:51:29.797194 2552 c:\projects\lc0\src\chess\uciloop.cc:132] >> isready
0118 21:51:29.797319 2552 c:\projects\lc0\src\chess\uciloop.cc:219] << readyok
0118 21:51:44.840614 2552 c:\projects\lc0\src\chess\uciloop.cc:132] >> ucinewgame


============= Log started. =============
0118 21:52:00.761432 1036 c:\projects\lc0\src\main.cc:40] Lc0 started.
```

**Comment by mooskagh** [comment]
Cannot reproduce, full log is needed.

**Comment by mooskagh** [comment]
I looked at log files posted here: https://discordapp.com/channels/425419482568196106/425419999096733706/675499427833577512
And don't see anything wrong from Lc0 side. Also it doesn't seem that ponder was used in all in those games.

**Comment by Rechenschieber** [comment]
To me it looks like Lc0 gets blocked in situations when lots of memory is used. I programmed a little interface (derived from a server / client tool I made for the old Rybka cluster) which writes log files and sends ucinewgame commands to Lc0 to release memory when it's idle. In case a new command comes when LC0 is still releasing memory - it gets blocked. In the attached logs it gets interesting at 06:24:22
You can also see it takes an awful lot of time to release memory.
[logs.zip](https://github.com/LeelaChessZero/lc0/files/4179329/logs.zip)

**Comment by mooskagh** [comment]
It may be slow to release memory for the existing tree, but that is non-blocking (at least is supposed to be so).
Lc0 has a GC thread which slowly releases memory in background while the rest of the engine continues to play.

Although one can argue that in the case of `ucinewgame` it has to be blocking, as that's what it for, GUI should wait.

**Comment by Naphthalin** [comment]
Was this solved with the last release by any chance?

**Comment by mooskagh** [comment]
It's likely not solved but we cannot reproduce it either.

So if someone can reproduce the bug, please update this issue.

Otherwise, in a few weeks it's ok to close it as not reproducible.
