### ISSUE TITLE
Idea: detect all weights/network files and add to option WeightsFile

### ISSUE THREAD

**Issue by nguyenpham** [LeelaChessZero/lc0#948]
I know Lc0 can auto-detect network files when starting. However, the option WeightsFile has a type of string and users have to enter manually their selected networks if they don't want Lc0 choices itself.

I think it is better if we change WeightsFile to combo type and add as its values all network files which Lc0 can detect when starting. Users can select easily networks they want from the dropdown on chess GUIs.

**Comment by mooskagh** [comment]
Non-default WeightsFile is mainly aimed for the use case when weights file is located in a different directory, and with selection box it won't be possible to specify that.

**Comment by nguyenpham** [comment]
We can if we want, right? Say, add subfolders to the names before adding to the selection box.

BTW, we may make some limitations, say, request copying weight files into a specific folder name and tell that to users thus we all will have easier lives.

The purpose is simple: users can control totally Lc0 without searching for file names then typing/copying them.

**Comment by nguyenpham** [comment]
If none of the weight files don't have the same names, it is so simple too. Just list their names only and Lc0 knows exactly the file. In case of similar names, just take the first one

**Comment by mooskagh** [comment]
Most of modern chess GUI show file selection dialog when UCI option contains string "file"
![image](https://user-images.githubusercontent.com/11266455/65042898-299dc400-d95a-11e9-9b22-0b59276b8baf.png)

Command line users also prefer to rely on command line completion to type file name.

Some people keep many versions of Lc0 side by side, and weights file separately, they want to be able to specify path.

All those actions are simple, standard and give freedom in file location.


What you propose to replace that with, is taking the freedom away, forcing people to copy files into specific location, and making it non-standard both for UCI users and command line users.

**Comment by nguyenpham** [comment]
I guess the average users don't like that freedom since it is freedom of programmers. On Lc0's guide, the network files will be downloaded into the same Lc0's folder (as well as some subfolders - I  have just known that recently) thus it can auto-detect. That is! Why do we expect something more complex than that? From my experience, allowing more flexible/storing anything outside that folder just make more messy than gain.

Having more freedom does not always win. If we count freedom in computer chess, playing in console should be better than using engines+chess GUIs, Winboard protocol should win UCI one, Winboard must win all other chess GUIs. However, normal people don't choose that.

I know that is not a big deal. Just 5 cent. Just think about users in the long term.

**Comment by ASilver** [comment]
I'd be very careful about assuming you speak in the name of the average user. It might be what you prefer, but that does not mean everyone. I think the average user has no interest in a bunch of weights files, and just wants one: the best. Those who do want to use a bunch of weights files will prefer the freedom.

**Comment by mooskagh** [comment]
Closing after discussing in chat.
If you still think it's a good idea, feel free to join our Discord chat at http://lc0.org/chat and discuss it.
