### ISSUE TITLE
Violation of GPL license

### ISSUE THREAD

**Issue by ileile** [LeelaChessZero/lc0#960]
Hi,

I have found that there is a project on github may have a violation of GPL license.

https://github.com/leedavid/leela-chess-to-Chinese-Chess

They have made a modified version of LC0 for Chinese chess, and They distributes the binary to users for playing and training. but they never distribute/disclose the source code, but just put the original lc0's source code there.

After I found it, I have searched their name 'GGZero' on the web. They even use it in tournaments to win prize. They tell local news it is a AlphaZero-like engine but they almost never mention LC0. Everyone could use Google Translate to confirm these things.

I don't like that, but I'm not familiar with these license issues. Is GPL serious? Or we are just just saying about opensource,  actually, one could disobey it without any punishment?

Whatever, I think that I shall report this situation to you. there is a license but someone just ignore it made me confused. 

Do we/you/the community acquiesce to these behaviors ?

**Comment by mooskagh** [comment]
Violation of license by other programs is not anything that should be fixed in Lc0, so closing that.
