### ISSUE TITLE
Cannot compile for macOS Catalina 10.15

### ISSUE THREAD

**Issue by nguyenpham** [LeelaChessZero/lc0#984]
I compiled Lc0 well with Mojave, just followed the guide in the readme. However, after upgrading my os into Catalina 10.15, I cannot compile anymore.

I have tried to redo all steps but been stuck to install header files via command `install SDK headers: installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /`
(the system prints error: `install: SDK: No such file or directory`)

I have tried a few things to fix, for example, all solutions from https://stackoverflow.com/questions/58278260/cant-compile-a-c-program-on-a-mac-after-upgrading-to-catalina-10-15 but none works for me.

Bellow is the log:

```
$ ./build.sh 
~/workspace/chess/lc0 ~/workspace/chess/lc0
The Meson build system
Version: 0.52.0
Source dir: /Users/nguyenpham/workspace/chess/lc0
Build dir: /Users/nguyenpham/workspace/chess/lc0/build/release
Build type: native build
Project name: lc0
Project version: undefined
C++ compiler for the host machine: c++ (clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.8)")
C++ linker for the host machine: APPLE ld 512.4
Host machine cpu family: x86_64
Host machine cpu: x86_64
WARNING: Consider using the builtin warning_level option instead of adding warning flags by hand.
Library libprotobuf found: NO
Did not find pkg-config by name 'pkg-config'
Found Pkg-config: NO
Found CMake: /usr/local/bin/cmake (3.15.0-rc4)
Run-time dependency protobuf found: NO (tried pkgconfig, cmake and framework)
Program protoc found: NO

|Executing subproject protobuf method meson 
|
|Project name: protobuf
|Project version: 3.5.1
|C++ compiler for the host machine: c++ (clang 11.0.0 "Apple clang version 11.0.0 (clang-1100.0.33.8)")
|C++ linker for the host machine: APPLE ld 512.4
|Compiler for C++ supports arguments -DHAVE_PTHREAD: YES 
|Compiler for C++ supports arguments -Wno-sign-compare: YES 
|Compiler for C++ supports arguments -Wno-unused-parameter: YES 
|Compiler for C++ supports arguments -Wno-ignored-qualifiers: YES 
|Compiler for C++ supports arguments /wd4146: NO 
|Compiler for C++ supports arguments /wd4244: NO 
|Compiler for C++ supports arguments /wd4305: NO 
|Compiler for C++ supports arguments /wd4506: NO 
|Run-time dependency threads found: YES 
|Build targets in project: 6
|Subproject protobuf finished.

Library pthread found: YES
Library dl found: YES
Library libtensorflow_cc found: NO
Run-time dependency accelerate found: YES (/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/Accelerate.framework)
Library mkl_rt found: NO
Library mklml found: NO
Library openblas.dll found: NO
Library openblas found: NO

meson.build:210:6: ERROR: Include dir /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Headers does not exist.
```

**Comment by borg323** [comment]
This is already fixed in master, and there will be a candidate for the next release soon. In the meantime, you can edit meson.build as in <https://github.com/LeelaChessZero/lc0/commit/ec1acac569d14afd2efc90c44cea8dd45f62f62c#diff-969b60ad3d206fd45c208e266ccfed38>.

**Comment by nguyenpham** [comment]
Thank you! Look like the build has some progress, but I was stuck with strange errors such as:

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:314:9: error: no member named 'signbit' in the global namespace
using ::signbit;`
 
My system (OS, XCode) is always up to date. I also tried to update and upgrade brew, uninstall then reinstall ninja, meson, re-clone lc0 (master branch) but errors are still the same.

Full log:

[lc0log.rtf.zip](https://github.com/LeelaChessZero/lc0/files/3856416/lc0log.rtf.zip)

**Comment by borg323** [comment]
This fails in the protobuf subproject. Can you try with `./build.sh -Dprotobuf-3-6-0=true`? The alternative is to find how to install protobuf (and maybe protoc if it is packaged separately).

**Comment by nguyenpham** [comment]
All failed:
1) I run ./build.sh -Dprotobuf-3-6-0=true => same error messages
2) then I tried to install protobuf via brew (brew install protobuf), checked version (protoc --version) => got 'libprotoc 3.10.0', then run both ./build.sh and  ./build.sh -Dprotobuf-3-6-0=true => same error messages

**Comment by nguyenpham** [comment]
I have tried with both './build.sh -Dprotobuf-3-10-0=true' and './build.sh -Dprotobuf-3-10-0=false' but no hope

**Comment by borg323** [comment]
After installing protobuf, it seems meson is not finding it. You need to add the paths to the build script so that the following lines from your log change:
```
Library libprotobuf found: NO
...
Run-time dependency protobuf found: NO (tried pkgconfig, cmake and framework)
Program protoc found: NO
```
You need one YES in the first two lines and also a YES in the last line in the above.
The options for `build.sh` to do this are `-Dprotobuf_include=` and `-Dprotobuf_libdir=`, while `protoc` should be on the path.

PS. For supported command line options see the `meson-options.txt` file.

**Comment by nguyenpham** [comment]
**Bad news:**  I have tried all your suggestions, as well as some I could find from the Internet. None worked. Thus I decided to give up. Look like I messed up seriously when trying to fix this issue days before.

**Good news:** I borrowed a MacBook pro from my daughter and tried all steps to set up and compile lc0. Successful and simple without any issue. Your fix works well! Thanks!

Just remind you to update Readme (we don't need step 5 for Mac).

**Comment by borg323** [comment]
Don't give up yet - delete the `build` directory and try again. If it fails a log may help to figure it out.

**Comment by nguyenpham** [comment]
OK, if you won't give up (to work with me to solve this problem) I won't give up either. I will come back a bit later (since being busy at the moment) :)

**Comment by cmwetherell** [comment]
Thanks for your support on this so far, still not able to get it to work for me. Hope it's an easy solution!

I am on Catalina 10.15.2 (19C57).

I cloned the repo like this: `git clone -b release/0.23 --recurse-submodules https://github.com/LeelaChessZero/lc0.git`

Tried following the compile steps and after executing ./build.sh I ran into: 

`meson.build:494:2: ERROR: WrapDB connection failed to https://wrapdb.mesonbuild.com/v1/projects/gtest/1.8.1/1/get_zip with error <urlopen error [Errno 51] Network is unreachable>
`

Then I cloned master, as you indicated above, via `git clone --recurse-submodules https://github.com/LeelaChessZero/lc0.git`


Then I tried to execute `./build.sh -Dprotobuf-3-6-0=true` and ended up with a new error:

`meson.build:494:2: ERROR: Subproject exists but has no meson.build file`

Full log attached below.

[meson-log.txt](https://github.com/LeelaChessZero/lc0/files/4050515/meson-log.txt)

Thanks!

**Comment by cmwetherell** [comment]
Borg helped me in Discord, thank you!

`/build.sh -Dgtest=false`

worked like a charm.

**Comment by borg323** [comment]
For future reference the issue was a meson wrapdb outage (https://github.com/mesonbuild/meson/issues/6446) and `/build.sh -Dgtest=false` worked because all subproject files were already available from an earlier build except gtest that was recently updated (https://github.com/LeelaChessZero/lc0/pull/986).

**Comment by Naphthalin** [comment]
@nguyenpham did the suggested solution work for you, especially deleting `build` before trying again?

**Comment by nguyenpham** [comment]
Look like my system got messy seriously when trying to fix compiling Lc0 before. It could not compile with gcc/g++ even some simple C++ programs (but Xcode, Qt still work). After trying to fix a few times, I gave up, reinstalled my macOS Catalina, and now everything becomes OK, Lc0 can be compiled well.

I will close this issue within a few days. Thanks all.
