### ISSUE TITLE
Style Plane

### ISSUE THREAD

**Issue by Toby-Scantlebury** [LeelaChessZero/lc0#993]
### Aim
Get the benefits of training a league of agents with substantially less cost

### Proposal
1. During training, randomly choose reward functions for the net
2. Add a "style plane" as input to the net, to specify which reward functions are active
3. In this way, the net learns to tailor its play style based on the style plane

### Outcomes
1. The style plane can be used to influence the net's playstyle
2. The net may be stronger due to a wider variety of opponents and more exploration

### Concrete Example
The following is a simple sketch of how a small style plane may be implemented and how it could work.

#### Representation
Each reward function (aka "style") is represented by 3 bits. The bits are used to set the intensity of the reward function.
`000`: No weighting
`100`: Small weighting
`110`: Medium weighting
`111`: Large weighting
All other bit patterns are illegal

The advantages of this setup are:
1. Fine control of the net's behaviour (not just on/off)
2. The layout helps the net learn what the small weighting is, even though the reward signal is weak. This is because the small weighting is associated with the large weighting which has a strong signal

As an example, consider a 2x3 style plane where each row is a reward function. The first row rewards shorter games. The second row rewards aggressive play:
```
000 (Short games)
000 (Aggressiveness)
```
#### Training
In training, the style plane is set to random weightings for each style, with a strong bias to "no style".
There may also be some bias towards simpler style planes (with only 1 or 2 styles active).

Example style planes during training:
50% of matches (current reward function):
```
000
000
```
25% of matches (simple styles):
```
100 110 111 000 000 000
000 000 000 100 110 111
```
25% of matches (mixed styles):
```
100 100 100 110 110 110 111 111 111
100 110 111 100 110 111 100 110 111
```

#### Running
After training, the style plane can be used to produce various play styles:

Play shortest games possible:
```
111
000
```

More direct endgame play, less shuffling:
```
100
000
```

Quite aggressive:
```
000
110
```

Punishment for weak engines:
```
111
111
```

Pure win/loss. Strongest play (current Leela):
```
000
000
```

### Conclusion
Hopefully the concept I'm presenting is clear. I'd love to hear from an ML expert if it has any merit.
I'm happy to tune the idea with contributors and do the implementation, as long as there's interest enough to run a test with a smaller net as with the T5x runs.

**Comment by Naphthalin** [comment]
These suggestions don't seem to fit the Lc0 training, and you didn't propose any way of giving rewards or other training signals so it could be learned from self-play.

We now have `--draw-score` #1066 which can be used to weight draws differently in search, and MLH to reward shorter wins/longer losses in search. Punishment for weak engines might be possible by doing the PDA suggested in https://github.com/LeelaChessZero/lc0/issues/345#issuecomment-622218665; but the suggested input planes don't make any sense to me.

**Comment by mooskagh** [comment]
Closing this as not really actionable.
