### ISSUE TITLE
Fix running out of time

### ISSUE THREAD

**Issue by mooskagh** [LeelaChessZero/lc0#996]
There are quite many reports that Lc0 fails on time in tight time conditions (and sometimes not very tight) on slow backend (and sometimes not very slow).

We need to address that, e.g.:
- If engine sees that it cannot respond immediately when sudden `stop` event comes, only gather batch of size 1. (that will be only the very first batch while thinking, and only if tree was not reused).
- Make sure that bestmove is responded immediately even if batch computation is currently in progress (it should work like that already but worth checking).
- Make sure that when time budget is over, the code that outputs bestmove is run immediately.

It would be helpful to have logs of cases when this happens. (**Note: it should be Lc0 logs, not UCI logs from chess GUI!**).
To record Lc0 logs, either pass `--logfile=filename.txt` or set UCI option `LogFile` to some file name. Then Lc0 will start to write logs there.

**Comment by borg323** [comment]
This is related to #869.

**Comment by mooskagh** [comment]
Indeed, but here it's mostly about minimizing time to response when engine has 0 seconds left, while there it's about distributing time budget amond moves wisely.

**Comment by Naphthalin** [comment]
Is this fixed by any of the new time management variants?

**Comment by mooskagh** [comment]
That's partially fixed.
Not instamoving even when there is reused tree was a real bug, and it was fixed by #1123.

I believe that "stop gathering batch when run out of time" is not fixed... Hmm although the first batch always has size of 1.
Ok, closing this for now.
